# -*- coding: utf-8 -*-
"""生成 CH12 作用域与变量 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH12"
TITLE = "作用域与变量"
OUT_DIR = "CH12_Scope"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "函数内定义局部变量并输出。", "def show():\n    x = 5\n    print(x)\n\nshow()", "填空局部变量。", "def show():\n    x = 5\n    print(x)\n\nshow()"),
    (2, "函数内读取全局变量。", "x = 10\ndef show():\n    print(x)\n\nshow()", "填空读取全局。", "x = 10\ndef show():\n    print(x)\n\nshow()"),
    (3, "函数外定义变量函数内使用。", "name = \"Tom\"\ndef greet():\n    print(\"Hello\", name)\n\ngreet()", "填空全局使用。", "name = \"Tom\"\ndef greet():\n    print(\"Hello\", name)\n\ngreet()"),
    (4, "用 global 声明修改全局变量。", "count = 0\ndef inc():\n    global count\n    count += 1\n\ninc()\nprint(count)", "填空 global。", "count = 0\ndef inc():\n    global count\n    count += 1\n\ninc()\nprint(count)"),
    (5, "局部变量遮蔽全局变量。", "x = 10\ndef show():\n    x = 20\n    print(x)\n\nshow()\nprint(x)", "填空遮蔽现象。", "x = 10\ndef show():\n    x = 20\n    print(x)\n\nshow()\nprint(x)"),
    (6, "函数内赋值不影响全局。", "x = 9\ndef change():\n    x = 50\n\nchange()\nprint(x)", "填空局部赋值。", "x = 9\ndef change():\n    x = 50\n\nchange()\nprint(x)"),
    (7, "函数返回局部变量值。", "def get():\n    x = 7\n    return x\n\nprint(get())", "填空返回局部。", "def get():\n    x = 7\n    return x\n\nprint(get())"),
    (8, "全局变量可被多次读取。", "total = 3\ndef add_one():\n    print(total + 1)\n\nadd_one()\nadd_one()", "填空多次读取。", "total = 3\ndef add_one():\n    print(total + 1)\n\nadd_one()\nadd_one()"),
    (9, "global 修改后全局生效。", "value = 1\ndef update():\n    global value\n    value = 100\n\nupdate()\nprint(value)", "填空 global 修改。", "value = 1\ndef update():\n    global value\n    value = 100\n\nupdate()\nprint(value)"),
    (10, "函数参数是局部变量。", "def double(n):\n    n = n * 2\n    print(n)\n\nx = 5\ndouble(x)\nprint(x)", "填空参数局部。", "def double(n):\n    n = n * 2\n    print(n)\n\nx = 5\ndouble(x)\nprint(x)"),
    (11, "嵌套函数内层访问外层变量。", "def outer():\n    x = 20\n    def inner():\n        print(x)\n    inner()\n\nouter()", "填空闭包访问。", "def outer():\n    x = 20\n    def inner():\n        print(x)\n    inner()\n\nouter()"),
    (12, "内层函数读取外层并输出。", "def outer():\n    msg = \"hi\"\n    def inner():\n        print(msg)\n    inner()\n\nouter()", "填空内层读取。", "def outer():\n    msg = \"hi\"\n    def inner():\n        print(msg)\n    inner()\n\nouter()"),
    (13, "全局变量在循环后输出。", "i = 0\nfor i in range(3):\n    pass\nprint(i)", "填空循环后全局。", "i = 0\nfor i in range(3):\n    pass\nprint(i)"),
    (14, "同名变量不同作用域。", "x = 1\ndef f():\n    x = 2\n    return x\n\nprint(f())\nprint(x)", "填空作用域隔离。", "x = 1\ndef f():\n    x = 2\n    return x\n\nprint(f())\nprint(x)"),
    (15, "函数修改全局列表。", "items = [1, 2]\ndef add():\n    items.append(3)\n\nadd()\nprint(items)", "填空全局列表修改。", "items = [1, 2]\ndef add():\n    items.append(3)\n\nadd()\nprint(items)"),
    (16, "全局变量与局部变量相加。", "x = 10\ndef f():\n    y = 5\n    print(x + y)\n\nf()", "填空相加。", "x = 10\ndef f():\n    y = 5\n    print(x + y)\n\nf()"),
    (17, "函数返回后局部变量消失。", "def create():\n    temp = 99\n    return temp\n\nresult = create()\nprint(result)", "填空返回携带。", "def create():\n    temp = 99\n    return temp\n\nresult = create()\nprint(result)"),
    (18, "全局变量在多个函数中使用。", "pi = 3.14\ndef area(r):\n    return pi * r * r\n\nprint(area(1))", "填空全局 pi。", "pi = 3.14\ndef area(r):\n    return pi * r * r\n\nprint(area(1))"),
    (19, "局部变量优先于全局。", "x = 100\ndef f():\n    x = 11\n    print(x)\n\nf()", "填空局部优先。", "x = 100\ndef f():\n    x = 11\n    print(x)\n\nf()"),
    (20, "global 声明后再赋值。", "score = 0\ndef set_score():\n    global score\n    score = 95\n\nset_score()\nprint(score)", "填空 global 赋值。", "score = 0\ndef set_score():\n    global score\n    score = 95\n\nset_score()\nprint(score)"),
    (21, "函数内定义常量风格变量。", "def f():\n    MAX = 30\n    print(MAX)\n\nf()", "填空局部常量。", "def f():\n    MAX = 30\n    print(MAX)\n\nf()"),
    (22, "全局变量被函数引用。", "greeting = \"Hello\"\ndef say():\n    print(greeting)\n\nsay()", "填空全局引用。", "greeting = \"Hello\"\ndef say():\n    print(greeting)\n\nsay()"),
    (23, "global 变量在循环中累加。", "total = 0\ndef add(n):\n    global total\n    total += n\n\nadd(4)\nadd(6)\nprint(\"Total:\", total)", "填空 global 累加。", "total = 0\ndef add(n):\n    global total\n    total += n\n\nadd(4)\nadd(6)\nprint(\"Total:\", total)"),
    (24, "函数返回多个局部变量。", "def pair():\n    a = 1\n    b = 2\n    return a, b\n\nx, y = pair()\nprint(x, y)", "填空返回局部对。", "def pair():\n    a = 1\n    b = 2\n    return a, b\n\nx, y = pair()\nprint(x, y)"),
    (25, "全局变量在嵌套函数中读取。", "g = 12\ndef outer():\n    def inner():\n        print(g)\n    inner()\n\nouter()", "填空嵌套读全局。", "g = 12\ndef outer():\n    def inner():\n        print(g)\n    inner()\n\nouter()"),
    (26, "函数内变量不污染全局。", "count = 10\ndef f():\n    count = 1\n    count += 1\n    print(count)\n\nf()\nprint(count)", "填空不污染。", "count = 10\ndef f():\n    count = 1\n    count += 1\n    print(count)\n\nf()\nprint(count)"),
    (27, "global 声明读取全局。", "limit = 8\ndef check():\n    global limit\n    print(limit)\n\ncheck()", "填空 global 读取。", "limit = 8\ndef check():\n    global limit\n    print(limit)\n\ncheck()"),
    (28, "函数参数与全局同名。", "x = 5\ndef f(x):\n    print(x)\n\nf(40)", "填空参数优先。", "x = 5\ndef f(x):\n    print(x)\n\nf(40)"),
    (29, "全局变量先定义后使用。", "def f():\n    print(x)\n\nx = 13\nf()", "填空后定义全局。", "def f():\n    print(x)\n\nx = 13\nf()"),
    (30, "综合：作用域演示。", "x = 1\ndef outer():\n    x = 2\n    def inner():\n        nonlocal x\n        x = 3\n        return x\n    return inner()\n\nprint(outer())\nprint(x)", "填空作用域链。", "x = 1\ndef outer():\n    x = 2\n    def inner():\n        nonlocal x\n        x = 3\n        return x\n    return inner()\n\nprint(outer())\nprint(x)"),
]

SIMPLE = [
    (1, "用 global 实现计数器。", "count = 0\ndef increment():\n    global count\n    count += 1\n\nincrement()\nincrement()\nincrement()\nprint(f\"Count: {count}\")", "填空 global 计数。", "count = 0\ndef increment():\n    global count\n    count += 1\n\nincrement()\nincrement()\nincrement()\nprint(f\"Count: {count}\")"),
    (2, "全局列表在函数内修改。", "nums = [1, 2, 3]\ndef add_item(n):\n    nums.append(n)\n\nadd_item(4)\nadd_item(5)\nprint(nums)", "填空全局列表修改。", "nums = [1, 2, 3]\ndef add_item(n):\n    nums.append(n)\n\nadd_item(4)\nadd_item(5)\nprint(nums)"),
    (3, "全局字典在函数内更新。", "config = {\"theme\": \"light\"}\ndef set_dark():\n    config[\"theme\"] = \"dark\"\n\nset_dark()\nprint(config)", "填空全局字典更新。", "config = {\"theme\": \"light\"}\ndef set_dark():\n    config[\"theme\"] = \"dark\"\n\nset_dark()\nprint(config)"),
    (4, "global 声明多个变量。", "a = 1\nb = 2\ndef swap():\n    global a, b\n    a, b = b, a\n\nswap()\nprint(a, b)", "填空 global 交换。", "a = 1\nb = 2\ndef swap():\n    global a, b\n    a, b = b, a\n\nswap()\nprint(a, b)"),
    (5, "函数内读写全局变量。", "total = 10\ndef adjust(n):\n    global total\n    total = total + n\n\nadjust(5)\nprint(f\"Total: {total}\")", "填空全局读写。", "total = 10\ndef adjust(n):\n    global total\n    total = total + n\n\nadjust(5)\nprint(f\"Total: {total}\")"),
    (6, "局部变量遮蔽与恢复。", "x = 1\ndef f():\n    x = 10\n    print(f\"Inner: {x}\")\n\nf()\nprint(f\"Outer: {x}\")", "填空遮蔽恢复。", "x = 1\ndef f():\n    x = 10\n    print(f\"Inner: {x}\")\n\nf()\nprint(f\"Outer: {x}\")"),
    (7, "嵌套函数修改外层（nonlocal）。", "def outer():\n    x = 1\n    def inner():\n        nonlocal x\n        x = 2\n    inner()\n    print('X:', x)\n\nouter()", "填空 nonlocal。", "def outer():\n    x = 1\n    def inner():\n        nonlocal x\n        x = 2\n    inner()\n    print('X:', x)\n\nouter()"),
    (8, "nonlocal 实现内层计数。", "def outer():\n    count = 0\n    def inner():\n        nonlocal count\n        count += 1\n    inner()\n    inner()\n    print('Count:', count)\n\nouter()", "填空 nonlocal 计数。", "def outer():\n    count = 0\n    def inner():\n        nonlocal count\n        count += 1\n    inner()\n    inner()\n    print('Count:', count)\n\nouter()"),
    (9, "全局变量与函数参数对比。", "x = 5\ndef f(y):\n    return x + y\n\nprint(f(100))", "填空全局加参数。", "x = 5\ndef f(y):\n    return x + y\n\nprint(f(100))"),
    (10, "函数返回值修改全局变量。", "value = 0\ndef get_value():\n    return 42\n\nvalue = get_value()\nprint(value)", "填空返回赋值。", "value = 0\ndef get_value():\n    return 42\n\nvalue = get_value()\nprint(value)"),
    (11, "闭包访问外层变量。", "def make_multiplier(n):\n    def multiplier(x):\n        return x * n\n    return multiplier\n\ntimes3 = make_multiplier(3)\nprint(times3(8))", "填空闭包。", "def make_multiplier(n):\n    def multiplier(x):\n        return x * n\n    return multiplier\n\ntimes3 = make_multiplier(3)\nprint(times3(8))"),
    (12, "全局字符串在函数内读取。", "title = \"PyQuest\"\ndef show():\n    print(title.upper())\n\nshow()", "填空全局字符串。", "title = \"PyQuest\"\ndef show():\n    print(title.upper())\n\nshow()"),
    (13, "函数内建局部列表。", "def make_list():\n    data = [4, 5, 6]\n    return data\n\nprint(make_list())", "填空局部列表返回。", "def make_list():\n    data = [4, 5, 6]\n    return data\n\nprint(make_list())"),
    (14, "global 变量参与运算。", "base = 100\ndef add_tax():\n    global base\n    base = base * 1.1\n\nadd_tax()\nprint(f\"Base: {base}\")", "填空 global 运算。", "base = 100\ndef add_tax():\n    global base\n    base = base * 1.1\n\nadd_tax()\nprint(f\"Base: {base}\")"),
    (15, "局部变量在循环中更新。", "def f():\n    total = 0\n    for i in range(1, 4):\n        total += i\n    return total\n\nprint(f\"Sum: {f()}\")", "填空局部累加。", "def f():\n    total = 0\n    for i in range(1, 4):\n        total += i\n    return total\n\nprint(f\"Sum: {f()}\")"),
    (16, "作用域内变量数量统计。", "g = 1\ndef f():\n    a = 2\n    b = 3\n    return a + b\n\nprint('Total:', f() + g)", "填空混合作用域。", "g = 1\ndef f():\n    a = 2\n    b = 3\n    return a + b\n\nprint('Total:', f() + g)"),
    (17, "全局列表重新赋值需 global。", "items = []\ndef reset():\n    global items\n    items = [9]\n\nreset()\nprint(items)", "填空 global 重赋值。", "items = []\ndef reset():\n    global items\n    items = [9]\n\nreset()\nprint(items)"),
    (18, "函数参数默认值引用全局。", "rate = 0.1\ndef cost(price, tax=rate):\n    return price * (1 + tax)\n\nprint(f\"Cost: {cost(100)}\")", "填空默认引用。", "rate = 0.1\ndef cost(price, tax=rate):\n    return price * (1 + tax)\n\nprint(f\"Cost: {cost(100)}\")"),
    (19, "内层函数读取外层与全局。", "g = 11\ndef outer():\n    x = 5\n    def inner():\n        return x + g\n    return inner()\n\nprint(outer())", "填空作用域链相加。", "g = 11\ndef outer():\n    x = 5\n    def inner():\n        return x + g\n    return inner()\n\nprint(outer())"),
    (20, "全局变量被局部覆盖后恢复。", "level = 1\ndef play():\n    level = 2\n    print(f\"Level {level}\")\n\nplay()\nprint(f\"Level {level}\")", "填空覆盖恢复。", "level = 1\ndef play():\n    level = 2\n    print(f\"Level {level}\")\n\nplay()\nprint(f\"Level {level}\")"),
    (21, "函数修改全局字符串需 global。", "msg = \"old\"\ndef change():\n    global msg\n    msg = \"new\"\n\nchange()\nprint(msg)", "填空 global 字符串。", "msg = \"old\"\ndef change():\n    global msg\n    msg = \"new\"\n\nchange()\nprint(msg)"),
    (22, "闭包多次调用保持状态。", "def counter():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        return count\n    return inc\n\nc = counter()\nprint(c())\nprint(c())\nprint(c())", "填空闭包状态。", "def counter():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        return count\n    return inc\n\nc = counter()\nprint(c())\nprint(c())\nprint(c())"),
    (23, "全局与局部变量同名时优先局部。", "name = \"Global\"\ndef show():\n    name = \"Local\"\n    print(name)\n\nshow()", "填空局部优先。", "name = \"Global\"\ndef show():\n    name = \"Local\"\n    print(name)\n\nshow()"),
    (24, "函数内定义并返回字典。", "def make_config():\n    settings = {\"debug\": True}\n    return settings\n\nprint(make_config())", "填空局部字典返回。", "def make_config():\n    settings = {\"debug\": True}\n    return settings\n\nprint(make_config())"),
    (25, "global 变量多次累加。", "score = 0\ndef add(points):\n    global score\n    score += points\n\nadd(10)\nadd(20)\nprint(f\"Score: {score}\")", "填空多次累加。", "score = 0\ndef add(points):\n    global score\n    score += points\n\nadd(10)\nadd(20)\nprint(f\"Score: {score}\")"),
    (26, "全局变量在推导式中读取。", "factor = 2\ndef squares():\n    return [n * factor for n in range(1, 4)]\n\nprint(squares())", "填空推导读全局。", "factor = 2\ndef squares():\n    return [n * factor for n in range(1, 4)]\n\nprint(squares())"),
    (27, "函数内局部变量生命周期。", "def f():\n    x = 1\n    return x\n\ndef g():\n    x = 2\n    return x\n\nprint(f())\nprint(g())", "填空局部独立。", "def f():\n    x = 1\n    return x\n\ndef g():\n    x = 2\n    return x\n\nprint(f())\nprint(g())"),
    (28, "global 与参数组合。", "base = 10\ndef apply(n):\n    global base\n    base = base + n\n    return base\n\nprint(apply(7))", "填空组合。", "base = 10\ndef apply(n):\n    global base\n    base = base + n\n    return base\n\nprint(apply(7))"),
    (29, "嵌套作用域变量遮蔽。", "def outer():\n    x = \"outer\"\n    def inner():\n        x = \"inner\"\n        return x\n    return inner()\n\nprint(outer())", "填空嵌套遮蔽。", "def outer():\n    x = \"outer\"\n    def inner():\n        x = \"inner\"\n        return x\n    return inner()\n\nprint(outer())"),
    (30, "综合：作用域链完整演示。", "x = 1\ndef outer():\n    x = 2\n    def inner():\n        nonlocal x\n        x = 4\n        return x\n    return inner()\n\nprint(outer())\nprint(x)", "填空作用域链修改。", "x = 1\ndef outer():\n    x = 2\n    def inner():\n        nonlocal x\n        x = 4\n        return x\n    return inner()\n\nprint(outer())\nprint(x)")
]

MEDIUM = [
    (1, "闭包实现计数器并演示。", "def make_counter():\n    count = 0\n    def counter():\n        nonlocal count\n        count += 1\n        return count\n    return counter\n\nc1 = make_counter()\nprint(c1())\nprint(c1())\nc2 = make_counter()\nprint(c2())", "填空闭包计数器。", "def make_counter():\n    count = 0\n    def counter():\n        nonlocal count\n        count += 1\n        return count\n    return counter\n\nc1 = make_counter()\nprint(c1())\nprint(c1())\nc2 = make_counter()\nprint(c2())"),
    (2, "闭包实现记忆化阶乘。", "def make_fact():\n    cache = {}\n    def fact(n):\n        if n in cache:\n            return cache[n]\n        if n <= 1:\n            cache[n] = 1\n        else:\n            cache[n] = n * fact(n - 1)\n        return cache[n]\n    return fact\n\nf = make_fact()\nprint(f(5))\nprint(f(6))", "填空闭包缓存。", "def make_fact():\n    cache = {}\n    def fact(n):\n        if n in cache:\n            return cache[n]\n        if n <= 1:\n            cache[n] = 1\n        else:\n            cache[n] = n * fact(n - 1)\n        return cache[n]\n    return fact\n\nf = make_fact()\nprint(f(5))\nprint(f(6))"),
    (3, "global 实现银行账户余额。", "balance = 1000\ndef deposit(n):\n    global balance\n    balance += n\n\ndef withdraw(n):\n    global balance\n    if n <= balance:\n        balance -= n\n\ndeposit(500)\nwithdraw(200)\nprint(f\"Balance: {balance}\")", "填空账户操作。", "balance = 1000\ndef deposit(n):\n    global balance\n    balance += n\n\ndef withdraw(n):\n    global balance\n    if n <= balance:\n        balance -= n\n\ndeposit(500)\nwithdraw(200)\nprint(f\"Balance: {balance}\")"),
    (4, "nonlocal 实现累加器。", "def make_accumulator():\n    total = 0\n    def add(n):\n        nonlocal total\n        total += n\n        return total\n    return add\n\nacc = make_accumulator()\nprint(acc(5))\nprint(acc(3))\nprint(acc(2))", "填空累加器。", "def make_accumulator():\n    total = 0\n    def add(n):\n        nonlocal total\n        total += n\n        return total\n    return add\n\nacc = make_accumulator()\nprint(acc(5))\nprint(acc(3))\nprint(acc(2))"),
    (5, "全局变量在函数间共享。", "shared = []\ndef add_to_shared(x):\n    shared.append(x)\n\ndef show_shared():\n    print(shared)\n\nadd_to_shared(1)\nadd_to_shared(2)\nshow_shared()", "填空共享列表。", "shared = []\ndef add_to_shared(x):\n    shared.append(x)\n\ndef show_shared():\n    print(shared)\n\nadd_to_shared(1)\nadd_to_shared(2)\nshow_shared()"),
    (6, "闭包保存配置。", "def make_config():\n    settings = {\"theme\": \"light\"}\n    def set(key, value):\n        settings[key] = value\n    def get(key):\n        return settings[key]\n    return set, get\n\nset_cfg, get_cfg = make_config()\nset_cfg(\"theme\", \"dark\")\nprint(get_cfg(\"theme\"))", "填空闭包配置。", "def make_config():\n    settings = {\"theme\": \"light\"}\n    def set(key, value):\n        settings[key] = value\n    def get(key):\n        return settings[key]\n    return set, get\n\nset_cfg, get_cfg = make_config()\nset_cfg(\"theme\", \"dark\")\nprint(get_cfg(\"theme\"))"),
    (7, "全局与局部变量比较。", "x = 1\ndef f():\n    x = 2\n    y = 3\n    return x + y\n\nprint(f())\nprint(x)", "填空作用域比较。", "x = 1\ndef f():\n    x = 2\n    y = 3\n    return x + y\n\nprint(f())\nprint(x)"),
    (8, "nonlocal 修改外层并返回。", "def outer():\n    value = 1\n    def inner():\n        nonlocal value\n        value *= 2\n        return value\n    inner()\n    inner()\n    return value\n\nprint('Value:', outer())", "填空 nonlocal 加倍。", "def outer():\n    value = 1\n    def inner():\n        nonlocal value\n        value *= 2\n        return value\n    inner()\n    inner()\n    return value\n\nprint('Value:', outer())"),
    (9, "全局变量动态更新。", "steps = 0\ndef move():\n    global steps\n    steps += 1\n\nfor _ in range(5):\n    move()\nprint(f\"Steps: {steps}\")", "填空循环 global。", "steps = 0\ndef move():\n    global steps\n    steps += 1\n\nfor _ in range(5):\n    move()\nprint(f\"Steps: {steps}\")"),
    (10, "闭包返回两个操作函数。", "def make_ops():\n    x = 10\n    def add(n):\n        return x + n\n    def sub(n):\n        return x - n\n    return add, sub\n\nadd_op, sub_op = make_ops()\nprint(add_op(5))\nprint(sub_op(3))", "填空双操作闭包。", "def make_ops():\n    x = 10\n    def add(n):\n        return x + n\n    def sub(n):\n        return x - n\n    return add, sub\n\nadd_op, sub_op = make_ops()\nprint(add_op(5))\nprint(sub_op(3))"),
    (11, "全局变量与函数调用计数。", "calls = 0\ndef f():\n    global calls\n    calls += 1\n    return \"called\"\n\nf()\nf()\nprint(f\"Calls: {calls}\")", "填空调用计数。", "calls = 0\ndef f():\n    global calls\n    calls += 1\n    return \"called\"\n\nf()\nf()\nprint(f\"Calls: {calls}\")"),
    (12, "嵌套作用域三层读取。", "def level1():\n    a = 1\n    def level2():\n        b = 2\n        def level3():\n            return a + b\n        return level3()\n    return level2()\n\nprint('Sum:', level1())", "填空三层作用域。", "def level1():\n    a = 1\n    def level2():\n        b = 2\n        def level3():\n            return a + b\n        return level3()\n    return level2()\n\nprint('Sum:', level1())"),
    (13, "global 修改变量类型。", "data = \"text\"\ndef to_list():\n    global data\n    data = [7, 8]\n\nto_list()\nprint(data)", "填空类型修改。", "data = \"text\"\ndef to_list():\n    global data\n    data = [7, 8]\n\nto_list()\nprint(data)"),
    (14, "闭包实现幂函数工厂。", "def power_factory(exp):\n    def power(base):\n        return base ** exp\n    return power\n\nsquare = power_factory(2)\ncube = power_factory(3)\nprint(square(4))\nprint(cube(2))", "填空幂工厂。", "def power_factory(exp):\n    def power(base):\n        return base ** exp\n    return power\n\nsquare = power_factory(2)\ncube = power_factory(3)\nprint(square(4))\nprint(cube(2))"),
    (15, "全局变量在异常后保持。", "value = 5\ndef safe(n):\n    try:\n        return 10 / n\n    except ZeroDivisionError:\n        return -1\n\nprint(safe(2))\nprint(value)", "填空异常与全局。", "value = 5\ndef safe(n):\n    try:\n        return 10 / n\n    except ZeroDivisionError:\n        return -1\n\nprint(safe(2))\nprint(value)"),
    (16, "nonlocal 多层修改。", "def outer():\n    x = 0\n    def middle():\n        def inner():\n            nonlocal x\n            x += 1\n        inner()\n        inner()\n    middle()\n    return x\n\nprint('Value:', outer())", "填空 nonlocal 多层。", "def outer():\n    x = 0\n    def middle():\n        def inner():\n            nonlocal x\n            x += 1\n        inner()\n        inner()\n    middle()\n    return x\n\nprint('Value:', outer())"),
    (17, "全局变量作为默认参数。", "limit = 10\ndef check(n, max_limit=limit):\n    return n <= max_limit\n\nprint(check(5), check(15))", "填空默认全局。", "limit = 10\ndef check(n, max_limit=limit):\n    return n <= max_limit\n\nprint(check(5), check(15))"),
    (18, "闭包延迟绑定陷阱演示。", "def make_funcs():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda: i)\n    return funcs\n\nfuncs = make_funcs()\nprint([f() for f in funcs])", "填空延迟绑定。", "def make_funcs():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda: i)\n    return funcs\n\nfuncs = make_funcs()\nprint([f() for f in funcs])"),
    (19, "global 变量在多函数中读写。", "state = \"idle\"\ndef start():\n    global state\n    state = \"running\"\n\ndef stop():\n    global state\n    state = \"stopped\"\n\nstart()\nstop()\nprint(state)", "填空状态机。", "state = \"idle\"\ndef start():\n    global state\n    state = \"running\"\n\ndef stop():\n    global state\n    state = \"stopped\"\n\nstart()\nstop()\nprint(state)"),
    (20, "闭包累加多个值。", "def make_stats():\n    values = []\n    def add(v):\n        values.append(v)\n        return sum(values)\n    return add\n\nadder = make_stats()\nprint(adder(10))\nprint(adder(20))\nprint(adder(30))", "填空累加闭包。", "def make_stats():\n    values = []\n    def add(v):\n        values.append(v)\n        return sum(values)\n    return add\n\nadder = make_stats()\nprint(adder(10))\nprint(adder(20))\nprint(adder(30))"),
    (21, "作用域中变量查找顺序。", "x = \"global\"\ndef outer():\n    x = \"outer\"\n    def inner():\n        return x\n    return inner()\n\nprint(outer())", "填空查找顺序。", "x = \"global\"\ndef outer():\n    x = \"outer\"\n    def inner():\n        return x\n    return inner()\n\nprint(outer())"),
    (22, "global 变量被函数返回修改。", "points = 0\ndef score(n):\n    global points\n    points += n\n    return points\n\nprint(score(3))\nprint(score(4))", "填空返回更新。", "points = 0\ndef score(n):\n    global points\n    points += n\n    return points\n\nprint(score(3))\nprint(score(4))"),
    (23, "嵌套闭包访问多层变量。", "def a():\n    x = 1\n    def b():\n        y = 2\n        def c():\n            return x * y\n        return c()\n    return b()\n\nprint('Result:', a())", "填空多层闭包。", "def a():\n    x = 1\n    def b():\n        y = 2\n        def c():\n            return x * y\n        return c()\n    return b()\n\nprint('Result:', a())"),
    (24, "全局变量在循环函数中累加。", "total = 0\ndef add_range(n):\n    global total\n    for i in range(1, n + 1):\n        total += i\n\nadd_range(7)\nprint(f\"Total: {total}\")", "填空循环累加全局。", "total = 0\ndef add_range(n):\n    global total\n    for i in range(1, n + 1):\n        total += i\n\nadd_range(7)\nprint(f\"Total: {total}\")"),
    (25, "闭包实现字符串构建器。", "def make_builder():\n    parts = []\n    def build(s):\n        parts.append(s)\n        return \" \".join(parts)\n    return build\n\nb = make_builder()\nprint(b(\"Hello\"))\nprint(b(\"World\"))", "填空构建器。", "def make_builder():\n    parts = []\n    def build(s):\n        parts.append(s)\n        return \" \".join(parts)\n    return build\n\nb = make_builder()\nprint(b(\"Hello\"))\nprint(b(\"World\"))"),
    (26, "全局变量被局部列表遮蔽。", "data = [1]\ndef f():\n    data = [2]\n    return data\n\nprint(f())\nprint(data)", "填空局部遮蔽。", "data = [1]\ndef f():\n    data = [2]\n    return data\n\nprint(f())\nprint(data)"),
    (27, "nonlocal 与外层交互。", "def outer():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        if count < 3:\n            inc()\n        return count\n    return inc()\n\nprint('Total:', outer())", "填空递归 nonlocal。", "def outer():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        if count < 3:\n            inc()\n        return count\n    return inc()\n\nprint('Total:', outer())"),
    (28, "全局变量类型保持。", "item = 5\ndef f():\n    item = \"changed\"\n    return item\n\nprint(f())\nprint(item)", "填空类型保持。", "item = 5\ndef f():\n    item = \"changed\"\n    return item\n\nprint(f())\nprint(item)"),
    (29, "闭包缓存计算结果。", "def make_cache():\n    cache = {}\n    def compute(n):\n        if n not in cache:\n            cache[n] = n * n\n        return cache[n]\n    return compute\n\nc = make_cache()\nprint(c(4))\nprint(c(4))\nprint(c(5))", "填空缓存闭包。", "def make_cache():\n    cache = {}\n    def compute(n):\n        if n not in cache:\n            cache[n] = n * n\n        return cache[n]\n    return compute\n\nc = make_cache()\nprint(c(4))\nprint(c(4))\nprint(c(5))"),
    (30, "综合：作用域完整应用。", "counter = 0\ndef make_ops():\n    x = 10\n    def add(n):\n        return x + n\n    def double():\n        global counter\n        counter += 1\n        return counter\n    return add, double\n\nadd_op, double_op = make_ops()\nprint(add_op(5))\nprint(double_op())\nprint(double_op())", "填空综合作用域。", "counter = 0\ndef make_ops():\n    x = 10\n    def add(n):\n        return x + n\n    def double():\n        global counter\n        counter += 1\n        return counter\n    return add, double\n\nadd_op, double_op = make_ops()\nprint(add_op(5))\nprint(double_op())\nprint(double_op())"),
]

HARD = [
    (1, "闭包陷阱：延迟绑定与修复。", "def make_funcs():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda i=i: i)\n    return funcs\n\nfuncs = make_funcs()\nprint([f() for f in funcs])", "填空修复延迟绑定。", "def make_funcs():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda i=i: i)\n    return funcs\n\nfuncs = make_funcs()\nprint([f() for f in funcs])"),
    (2, "装饰器雏形：日志包装。", "def logger(func):\n    def wrapper(*args):\n        print(\"Calling\")\n        return func(*args)\n    return wrapper\n\n@logger\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))", "填空装饰器。", "def logger(func):\n    def wrapper(*args):\n        print(\"Calling\")\n        return func(*args)\n    return wrapper\n\n@logger\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))"),
    (3, "装饰器：计时包装。", "def timer(func):\n    def wrapper(n):\n        return func(n) * 2\n    return wrapper\n\n@timer\ndef square(n):\n    return n * n\n\nprint('Result:', square(3))", "填空计时包装。", "def timer(func):\n    def wrapper(n):\n        return func(n) * 2\n    return wrapper\n\n@timer\ndef square(n):\n    return n * n\n\nprint('Result:', square(3))"),
    (4, "闭包实现函数记忆化。", "def memoize(func):\n    cache = {}\n    def wrapper(n):\n        if n not in cache:\n            cache[n] = func(n)\n        return cache[n]\n    return wrapper\n\n@memoize\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))", "填空记忆化。", "def memoize(func):\n    cache = {}\n    def wrapper(n):\n        if n not in cache:\n            cache[n] = func(n)\n        return cache[n]\n    return wrapper\n\n@memoize\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))"),
    (5, "nonlocal 实现状态机。", "def make_state():\n    state = {\"count\": 0}\n    def transition(action):\n        nonlocal state\n        if action == \"inc\":\n            state[\"count\"] += 1\n        elif action == \"reset\":\n            state[\"count\"] = 0\n        return state[\"count\"]\n    return transition\n\nsm = make_state()\nprint(sm(\"inc\"))\nprint(sm(\"inc\"))\nprint(sm(\"reset\"))", "填空状态机。", "def make_state():\n    state = {\"count\": 0}\n    def transition(action):\n        nonlocal state\n        if action == \"inc\":\n            state[\"count\"] += 1\n        elif action == \"reset\":\n            state[\"count\"] = 0\n        return state[\"count\"]\n    return transition\n\nsm = make_state()\nprint(sm(\"inc\"))\nprint(sm(\"inc\"))\nprint(sm(\"reset\"))"),
    (6, "闭包实现多态计算器。", "def make_calculator():\n    result = 0\n    def operate(op, n):\n        nonlocal result\n        if op == \"+\":\n            result += n\n        elif op == \"*\":\n            result *= n\n        return result\n    return operate\n\ncalc = make_calculator()\nprint(calc(\"+\", 5))\nprint(calc(\"*\", 2))", "填空计算器闭包。", "def make_calculator():\n    result = 0\n    def operate(op, n):\n        nonlocal result\n        if op == \"+\":\n            result += n\n        elif op == \"*\":\n            result *= n\n        return result\n    return operate\n\ncalc = make_calculator()\nprint(calc(\"+\", 5))\nprint(calc(\"*\", 2))"),
    (7, "装饰器带参数。", "def repeat(times):\n    def decorator(func):\n        def wrapper(*args):\n            results = []\n            for _ in range(times):\n                results.append(func(*args))\n            return results\n        return wrapper\n    return decorator\n\n@repeat(2)\ndef double(n):\n    return n * 2\n\nprint(double(3))", "填空参数装饰器。", "def repeat(times):\n    def decorator(func):\n        def wrapper(*args):\n            results = []\n            for _ in range(times):\n                results.append(func(*args))\n            return results\n        return wrapper\n    return decorator\n\n@repeat(2)\ndef double(n):\n    return n * 2\n\nprint(double(3))"),
    (8, "闭包保存历史记录。", "def make_history():\n    history = []\n    def record(x):\n        history.append(x)\n        return history\n    return record\n\nrec = make_history()\nprint(rec(1))\nprint(rec(2))\nprint(rec(3))", "填空历史记录。", "def make_history():\n    history = []\n    def record(x):\n        history.append(x)\n        return history\n    return record\n\nrec = make_history()\nprint(rec(1))\nprint(rec(2))\nprint(rec(3))"),
    (9, "global 与闭包混合。", "g = 1\ndef outer():\n    x = 2\n    def inner():\n        global g\n        g += 1\n        return x + g\n    return inner\n\nf = outer()\nprint(f())\nprint(f())", "填空混合作用域。", "g = 1\ndef outer():\n    x = 2\n    def inner():\n        global g\n        g += 1\n        return x + g\n    return inner\n\nf = outer()\nprint(f())\nprint(f())"),
    (10, "装饰器实现权限检查。", "def require_admin(func):\n    def wrapper(user):\n        if user == \"admin\":\n            return func(user)\n        return \"Access denied\"\n    return wrapper\n\n@require_admin\ndef dashboard(user):\n    return \"Dashboard for \" + user\n\nprint(dashboard(\"admin\"))\nprint(dashboard(\"guest\"))", "填空权限装饰器。", "def require_admin(func):\n    def wrapper(user):\n        if user == \"admin\":\n            return func(user)\n        return \"Access denied\"\n    return wrapper\n\n@require_admin\ndef dashboard(user):\n    return \"Dashboard for \" + user\n\nprint(dashboard(\"admin\"))\nprint(dashboard(\"guest\"))"),
    (11, "闭包实现运行计数。", "def make_counter():\n    counts = {}\n    def count(key):\n        counts[key] = counts.get(key, 0) + 1\n        return counts[key]\n    return count\n\nc = make_counter()\nprint(c(\"a\"))\nprint(c(\"b\"))\nprint(c(\"a\"))", "填空多键计数。", "def make_counter():\n    counts = {}\n    def count(key):\n        counts[key] = counts.get(key, 0) + 1\n        return counts[key]\n    return count\n\nc = make_counter()\nprint(c(\"a\"))\nprint(c(\"b\"))\nprint(c(\"a\"))"),
    (12, "非局部变量在递归闭包中。", "def make_fib():\n    cache = {0: 0, 1: 1}\n    def fib(n):\n        if n not in cache:\n            cache[n] = fib(n - 1) + fib(n - 2)\n        return cache[n]\n    return fib\n\nf = make_fib()\nprint(f(8))", "填空递归闭包。", "def make_fib():\n    cache = {0: 0, 1: 1}\n    def fib(n):\n        if n not in cache:\n            cache[n] = fib(n - 1) + fib(n - 2)\n        return cache[n]\n    return fib\n\nf = make_fib()\nprint(f(8))"),
    (13, "装饰器叠加。", "def upper(func):\n    def wrapper(*args):\n        return func(*args).upper()\n    return wrapper\n\ndef exclaim(func):\n    def wrapper(*args):\n        return func(*args) + \"!\"\n    return wrapper\n\n@upper\n@exclaim\ndef greet(name):\n    return \"Hello \" + name\n\nprint(greet(\"Tom\"))", "填空叠加装饰器。", "def upper(func):\n    def wrapper(*args):\n        return func(*args).upper()\n    return wrapper\n\ndef exclaim(func):\n    def wrapper(*args):\n        return func(*args) + \"!\"\n    return wrapper\n\n@upper\n@exclaim\ndef greet(name):\n    return \"Hello \" + name\n\nprint(greet(\"Tom\"))"),
    (14, "闭包实现函数式累加。", "def make_adder():\n    total = 0\n    def add(n):\n        nonlocal total\n        total += n\n        return total\n    return add\n\na = make_adder()\nresult = [a(i) for i in [1, 2, 3, 4]]\nprint(result)", "填空函数式累加。", "def make_adder():\n    total = 0\n    def add(n):\n        nonlocal total\n        total += n\n        return total\n    return add\n\na = make_adder()\nresult = [a(i) for i in [1, 2, 3, 4]]\nprint(result)"),
    (15, "global 变量在类方法中（雏形）。", "counter = 0\nclass Counter:\n    def inc(self):\n        global counter\n        counter += 1\n\nc = Counter()\nc.inc()\nc.inc()\nprint('Counter:', counter)", "填空类方法 global。", "counter = 0\nclass Counter:\n    def inc(self):\n        global counter\n        counter += 1\n\nc = Counter()\nc.inc()\nc.inc()\nprint('Counter:', counter)"),
    (16, "闭包实现取平均值。", "def make_avg():\n    nums = []\n    def avg(n):\n        nums.append(n)\n        return sum(nums) / len(nums)\n    return avg\n\na = make_avg()\nprint(a(10))\nprint(a(20))\nprint(a(30))", "填空平均闭包。", "def make_avg():\n    nums = []\n    def avg(n):\n        nums.append(n)\n        return sum(nums) / len(nums)\n    return avg\n\na = make_avg()\nprint(a(10))\nprint(a(20))\nprint(a(30))"),
    (17, "装饰器处理异常。", "def safe(func):\n    def wrapper(a, b):\n        try:\n            return func(a, b)\n        except ZeroDivisionError:\n            return \"Error\"\n    return wrapper\n\n@safe\ndef divide(a, b):\n    return a / b\n\nprint(divide(10, 2))\nprint(divide(10, 0))", "填空异常装饰器。", "def safe(func):\n    def wrapper(a, b):\n        try:\n            return func(a, b)\n        except ZeroDivisionError:\n            return \"Error\"\n    return wrapper\n\n@safe\ndef divide(a, b):\n    return a / b\n\nprint(divide(10, 2))\nprint(divide(10, 0))"),
    (18, "闭包链式记录。", "def make_tracker():\n    events = []\n    def track(e):\n        events.append(e)\n        return events[-3:]\n    return track\n\nt = make_tracker()\nprint(t(\"a\"))\nprint(t(\"b\"))\nprint(t(\"c\"))\nprint(t(\"d\"))", "填空最近记录。", "def make_tracker():\n    events = []\n    def track(e):\n        events.append(e)\n        return events[-3:]\n    return track\n\nt = make_tracker()\nprint(t(\"a\"))\nprint(t(\"b\"))\nprint(t(\"c\"))\nprint(t(\"d\"))"),
    (19, "global 变量做共享状态。", "mode = \"read\"\ndef set_mode(m):\n    global mode\n    mode = m\n\ndef get_mode():\n    return mode\n\nset_mode(\"write\")\nprint(get_mode())", "填空共享状态。", "mode = \"read\"\ndef set_mode(m):\n    global mode\n    mode = m\n\ndef get_mode():\n    return mode\n\nset_mode(\"write\")\nprint(get_mode())"),
    (20, "闭包与生成器雏形。", "def make_sequence():\n    data = [1, 3, 5]\n    index = 0\n    def next_item():\n        nonlocal index\n        if index >= len(data):\n            return None\n        item = data[index]\n        index += 1\n        return item\n    return next_item\n\nn = make_sequence()\nprint(n())\nprint(n())\nprint(n())\nprint(n())", "填空序列闭包。", "def make_sequence():\n    data = [1, 3, 5]\n    index = 0\n    def next_item():\n        nonlocal index\n        if index >= len(data):\n            return None\n        item = data[index]\n        index += 1\n        return item\n    return next_item\n\nn = make_sequence()\nprint(n())\nprint(n())\nprint(n())\nprint(n())"),
    (21, "作用域隔离的工厂函数。", "def factory(initial):\n    value = initial\n    def get():\n        return value\n    def set(v):\n        nonlocal value\n        value = v\n    return get, set\n\ng1, s1 = factory(1)\ng2, s2 = factory(100)\ns1(2)\nprint(g1())\nprint(g2())", "填空隔离工厂。", "def factory(initial):\n    value = initial\n    def get():\n        return value\n    def set(v):\n        nonlocal value\n        value = v\n    return get, set\n\ng1, s1 = factory(1)\ng2, s2 = factory(100)\ns1(2)\nprint(g1())\nprint(g2())"),
    (22, "装饰器保留元数据（雏形）。", "def log(func):\n    def wrapper(*args):\n        print(func.__name__)\n        return func(*args)\n    return wrapper\n\n@log\ndef add(a, b):\n    return a + b\n\nprint(add(1, 2))", "填空元数据装饰器。", "def log(func):\n    def wrapper(*args):\n        print(func.__name__)\n        return func(*args)\n    return wrapper\n\n@log\ndef add(a, b):\n    return a + b\n\nprint(add(1, 2))"),
    (23, "闭包实现银行账户（含余额查询）。", "def account(initial):\n    balance = initial\n    def deposit(n):\n        nonlocal balance\n        balance += n\n        return balance\n    def get_balance():\n        return balance\n    return deposit, get_balance\n\ndep, bal = account(100)\ndep(50)\nprint(bal())", "填空账户闭包。", "def account(initial):\n    balance = initial\n    def deposit(n):\n        nonlocal balance\n        balance += n\n        return balance\n    def get_balance():\n        return balance\n    return deposit, get_balance\n\ndep, bal = account(100)\ndep(50)\nprint(bal())"),
    (24, "全局变量用于配置开关。", "debug = False\ndef set_debug(v):\n    global debug\n    debug = v\n\ndef log_msg(msg):\n    if debug:\n        return \"[DEBUG] \" + msg\n    return msg\n\nset_debug(True)\nprint(log_msg(\"hi\"))", "填空调试开关。", "debug = False\ndef set_debug(v):\n    global debug\n    debug = v\n\ndef log_msg(msg):\n    if debug:\n        return \"[DEBUG] \" + msg\n    return msg\n\nset_debug(True)\nprint(log_msg(\"hi\"))"),
    (25, "闭包实现平均值与计数。", "def make_stats():\n    total = 0\n    count = 0\n    def add(n):\n        nonlocal total, count\n        total += n\n        count += 1\n        return total / count\n    return add\n\ns = make_stats()\nprint(s(2))\nprint(s(4))\nprint(s(6))", "填空统计闭包。", "def make_stats():\n    total = 0\n    count = 0\n    def add(n):\n        nonlocal total, count\n        total += n\n        count += 1\n        return total / count\n    return add\n\ns = make_stats()\nprint(s(2))\nprint(s(4))\nprint(s(6))"),
    (26, "嵌套装饰器组合。", "def wrap(tag):\n    def decorator(func):\n        def wrapper(*args):\n            return f\"<{tag}>{func(*args)}</{tag}>\"\n        return wrapper\n    return decorator\n\n@wrap(\"b\")\ndef text():\n    return \"bold\"\n\nprint(text())", "填空标签装饰器。", "def wrap(tag):\n    def decorator(func):\n        def wrapper(*args):\n            return f\"<{tag}>{func(*args)}</{tag}>\"\n        return wrapper\n    return decorator\n\n@wrap(\"b\")\ndef text():\n    return \"bold\"\n\nprint(text())"),
    (27, "闭包实现 LRU 缓存雏形。", "def make_lru(capacity):\n    cache = {}\n    order = []\n    def get(k):\n        if k in cache:\n            order.remove(k)\n            order.append(k)\n            return cache[k]\n        return None\n    def put(k, v):\n        if k in cache:\n            order.remove(k)\n        elif len(order) >= capacity:\n            oldest = order.pop(0)\n            del cache[oldest]\n        cache[k] = v\n        order.append(k)\n    return get, put\n\nget, put = make_lru(2)\nput(\"a\", 1)\nput(\"b\", 2)\nput(\"c\", 3)\nprint(get(\"a\"))\nprint(get(\"b\"))", "填空 LRU 闭包。", "def make_lru(capacity):\n    cache = {}\n    order = []\n    def get(k):\n        if k in cache:\n            order.remove(k)\n            order.append(k)\n            return cache[k]\n        return None\n    def put(k, v):\n        if k in cache:\n            order.remove(k)\n        elif len(order) >= capacity:\n            oldest = order.pop(0)\n            del cache[oldest]\n        cache[k] = v\n        order.append(k)\n    return get, put\n\nget, put = make_lru(2)\nput(\"a\", 1)\nput(\"b\", 2)\nput(\"c\", 3)\nprint(get(\"a\"))\nprint(get(\"b\"))"),
    (28, "global 与递归函数。", "depth = 0\ndef recurse(n):\n    global depth\n    depth += 1\n    if n <= 0:\n        return depth\n    return recurse(n - 1)\n\nprint('Depth:', recurse(5))", "填空递归深度。", "depth = 0\ndef recurse(n):\n    global depth\n    depth += 1\n    if n <= 0:\n        return depth\n    return recurse(n - 1)\n\nprint('Depth:', recurse(5))"),
    (29, "闭包实现可重置计数器。", "def make_counter():\n    count = 0\n    def action(op):\n        nonlocal count\n        if op == \"inc\":\n            count += 1\n        elif op == \"get\":\n            pass\n        elif op == \"reset\":\n            count = 0\n        return count\n    return action\n\nc = make_counter()\nprint(c(\"inc\"))\nprint(c(\"inc\"))\nprint(c(\"reset\"))\nprint(c(\"get\"))", "填空可重置计数器。", "def make_counter():\n    count = 0\n    def action(op):\n        nonlocal count\n        if op == \"inc\":\n            count += 1\n        elif op == \"get\":\n            pass\n        elif op == \"reset\":\n            count = 0\n        return count\n    return action\n\nc = make_counter()\nprint(c(\"inc\"))\nprint(c(\"inc\"))\nprint(c(\"reset\"))\nprint(c(\"get\"))"),
    (30, "综合：作用域与闭包完整演示。", "def make_processor():\n    data = []\n    total = 0\n    def add(n):\n        nonlocal total\n        data.append(n)\n        total += n\n        return total\n    def summary():\n        return len(data), total, total / len(data)\n    return add, summary\n\nadd_item, get_summary = make_processor()\nadd_item(10)\nadd_item(20)\ncount, total, avg = get_summary()\nprint(count, total, avg)", "填空完整闭包。", "def make_processor():\n    data = []\n    total = 0\n    def add(n):\n        nonlocal total\n        data.append(n)\n        total += n\n        return total\n    def summary():\n        return len(data), total, total / len(data)\n    return add, summary\n\nadd_item, get_summary = make_processor()\nadd_item(10)\nadd_item(20)\ncount, total, avg = get_summary()\nprint(count, total, avg)"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
