# -*- coding: utf-8 -*-
"""生成 CH07 循环 (for) 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH07"
TITLE = "循环 (for)"
OUT_DIR = "CH07_For_Loops"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "用 for 输出 1 到 5。", "for i in range(1, 6):\n    print(___)", "输出变量 i。", "for i in range(1, 6):\n    print(i)"),
    (2, "用 for 输出 0 到 4。", "for i in range(5):\n    print(___)", "输出变量 i。", "for i in range(5):\n    print(i)"),
    (3, "用步长输出 0、2、4、6。", "for i in range(0, 7, 2):\n    print(___)", "输出变量 i。", "for i in range(0, 7, 2):\n    print(i)"),
    (4, "遍历列表逐行输出。", "for fruit in [\"apple\", \"banana\"]:\n    print(___)", "输出变量 fruit。", "for fruit in [\"apple\", \"banana\"]:\n    print(fruit)"),
    (5, "遍历字符串逐字符输出。", "for ch in \"Hi\":\n    print(___)", "输出变量 ch。", "for ch in \"Hi\":\n    print(ch)"),
    (6, "遍历字典的键。", "d = {\"a\": 1, \"b\": 2}\nfor key in d:\n    print(___)", "输出变量 key。", "d = {\"a\": 1, \"b\": 2}\nfor key in d:\n    print(key)"),
    (7, "用倒序 range 输出 3、2、1。", "for i in range(3, 0, -1):\n    print(___)", "输出变量 i。", "for i in range(3, 0, -1):\n    print(i)"),
    (8, "用循环累加 1 到 5。", "total = 0\nfor i in range(1, 6):\n    total += i\nprint(___)\n", "输出 total。", "total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)"),
    (9, "用循环累乘 1 到 4。", "product = 1\nfor i in range(1, 5):\n    product *= i\nprint(___)\n", "输出 product。", "product = 1\nfor i in range(1, 5):\n    product *= i\nprint(product)"),
    (10, "用循环计数 1 到 5 的个数。", "count = 0\nfor i in range(1, 6):\n    count += 1\nprint(___)\n", "输出 count。", "count = 0\nfor i in range(1, 6):\n    count += 1\nprint(count)"),
    (11, "用 enumerate 输出索引和值。", "for i, v in enumerate([\"a\", \"b\"]):\n    print(___, v)", "输出 i。", "for i, v in enumerate([\"a\", \"b\"]):\n    print(i, v)"),
    (12, "循环中遇到 3 用 break 退出。", "for i in range(1, 6):\n    if i == 3:\n        break\n    print(___)", "输出变量 i。", "for i in range(1, 6):\n    if i == 3:\n        break\n    print(i)"),
    (13, "循环中用 continue 跳过 3。", "for i in range(1, 6):\n    if i == 3:\n        continue\n    print(___)", "输出变量 i。", "for i in range(1, 6):\n    if i == 3:\n        continue\n    print(i)"),
    (14, "for 循环正常结束后执行 else。", "for i in range(3):\n    print(i)\nelse:\n    print(\"done\")", "填空 else 输出。", "for i in range(3):\n    print(i)\nelse:\n    print(\"done\")"),
    (15, "嵌套循环输出乘法表一列。", "for i in range(1, 4):\n    for j in range(1, 4):\n        print(i * j, end=\" \")\n    print()", "填空嵌套循环。", "for i in range(1, 4):\n    for j in range(1, 4):\n        print(i * j, end=\" \")\n    print()"),
    (16, "用 zip 并行遍历两个列表。", "for a, b in zip([1, 2], [3, 4]):\n    print(___, b)", "输出变量 a。", "for a, b in zip([1, 2], [3, 4]):\n    print(a, b)"),
    (17, "用列表推导式生成平方。", "squares = [n * n for n in range(1, 4)]\nprint(___)", "输出 squares。", "squares = [n * n for n in range(1, 4)]\nprint(squares)"),
    (18, "遍历元组输出。", "for v in (10, 20):\n    print(___)", "输出变量 v。", "for v in (10, 20):\n    print(v)"),
    (19, "遍历排序后的集合。", "for v in sorted({3, 1, 2}):\n    print(___)", "输出变量 v。", "for v in sorted({3, 1, 2}):\n    print(v)"),
    (20, "循环拼接字符串。", "result = \"\"\nfor ch in \"abc\":\n    result += ch\nprint(___)\n", "输出 result。", "result = \"\"\nfor ch in \"abc\":\n    result += ch\nprint(result)"),
    (21, "输出 1 到 4 的平方。", "for i in range(1, 5):\n    print(___ * i)", "填 i。", "for i in range(1, 5):\n    print(i * i)"),
    (22, "输出 1 到 10 中的偶数。", "for i in range(1, 11):\n    if i % 2 == 0:\n        print(___)", "输出变量 i。", "for i in range(1, 11):\n    if i % 2 == 0:\n        print(i)"),
    (23, "输出 1 到 10 中的奇数。", "for i in range(1, 11):\n    if i % 2 == 1:\n        print(___)", "输出变量 i。", "for i in range(1, 11):\n    if i % 2 == 1:\n        print(i)"),
    (24, "累加 1 到 10 中的偶数。", "total = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        total += i\nprint(___)\n", "输出 total。", "total = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        total += i\nprint(total)"),
    (25, "循环变量参与运算。", "for i in range(1, 4):\n    print(i + 10)", "填 i + 10。", "for i in range(1, 4):\n    print(i + 10)"),
    (26, "用三参数 range 输出 5、4、3。", "for i in range(5, 2, -1):\n    print(___)", "输出变量 i。", "for i in range(5, 2, -1):\n    print(i)"),
    (27, "循环结束后输出总数。", "for i in range(1, 4):\n    pass\nprint(\"total:\", i)", "填空 pass 与输出。", "for i in range(1, 4):\n    pass\nprint(\"total:\", i)"),
    (28, "解包遍历二维列表。", "for a, b in [[1, 2], [3, 4]]:\n    print(a + b)", "填 a + b。", "for a, b in [[1, 2], [3, 4]]:\n    print(a + b)"),
    (29, "用 reversed 逆序输出。", "for v in reversed([1, 2, 3, 4]):\n    print(___)", "输出变量 v。", "for v in reversed([1, 2, 3, 4]):\n    print(v)"),
    (30, "输出 3 次问候。", "for i in range(3):\n    print(\"Hi\")", "填空循环体。", "for i in range(3):\n    print(\"Hi\")"),
]

SIMPLE = [
    (1, "求 1 到 100 的和（for 累加）。", "total = 0\nfor i in range(1, 101):\n    total += i\nprint(f\"Sum: {total}\")", "填空累加。", "total = 0\nfor i in range(1, 101):\n    total += i\nprint(f\"Sum: {total}\")"),
    (2, "求 1 到 10 的平方和。", "total = 0\nfor i in range(1, 11):\n    total += i * i\nprint(f\"Sum of squares: {total}\")", "填空平方累加。", "total = 0\nfor i in range(1, 11):\n    total += i * i\nprint(f\"Sum of squares: {total}\")"),
    (3, "计算列表平均值。", "nums = [4, 8, 6, 10]\ntotal = 0\nfor n in nums:\n    total += n\navg = total / len(nums)\nprint(f\"Average: {avg}\")", "填空求和与平均。", "nums = [4, 8, 6, 10]\ntotal = 0\nfor n in nums:\n    total += n\navg = total / len(nums)\nprint(f\"Average: {avg}\")"),
    (4, "统计字符串中字母 a 的个数。", "text = \"banana\"\ncount = 0\nfor ch in text:\n    if ch == \"a\":\n        count += 1\nprint(f\"a count: {count}\")", "填空计数。", "text = \"banana\"\ncount = 0\nfor ch in text:\n    if ch == \"a\":\n        count += 1\nprint(f\"a count: {count}\")"),
    (5, "找列表中的最大值（循环版）。", "nums = [3, 9, 5, 7]\nmaximum = nums[0]\nfor n in nums:\n    if n > maximum:\n        maximum = n\nprint(f\"Max: {maximum}\")", "填空比较更新。", "nums = [3, 9, 5, 7]\nmaximum = nums[0]\nfor n in nums:\n    if n > maximum:\n        maximum = n\nprint(f\"Max: {maximum}\")"),
    (6, "把列表元素转成大写输出。", "words = [\"hi\", \"bye\"]\nfor w in words:\n    print(w.___())", "方法名填 upper。", "words = [\"hi\", \"bye\"]\nfor w in words:\n    print(w.upper())"),
    (7, "用 enumerate 输出带编号列表。", "names = [\"Tom\", \"Ada\"]\nfor i, name in enumerate(names, 1):\n    print(f\"{i}. {name}\")", "填空 enumerate。", "names = [\"Tom\", \"Ada\"]\nfor i, name in enumerate(names, 1):\n    print(f\"{i}. {name}\")"),
    (8, "用 zip 对应相加两个列表。", "a = [1, 2, 3]\nb = [10, 20, 30]\nfor x, y in zip(a, b):\n    print(x + y)", "填空 zip。", "a = [1, 2, 3]\nb = [10, 20, 30]\nfor x, y in zip(a, b):\n    print(x + y)"),
    (9, "打印 1 到 5 的阶乘（for 累积）。", "fact = 1\nfor i in range(1, 6):\n    fact *= i\nprint(f\"5! = {fact}\")", "填空累乘。", "fact = 1\nfor i in range(1, 6):\n    fact *= i\nprint(f\"5! = {fact}\")"),
    (10, "输出 2 的 1 到 5 次幂。", "for i in range(1, 6):\n    print(2 ** i)", "填空幂运算。", "for i in range(1, 6):\n    print(2 ** i)"),
    (11, "过滤并输出列表中的正数。", "nums = [3, -1, 5, -2, 7]\nfor n in nums:\n    if n > 0:\n        print(n)", "填空条件过滤。", "nums = [3, -1, 5, -2, 7]\nfor n in nums:\n    if n > 0:\n        print(n)"),
    (12, "循环拼接列表元素为字符串。", "words = [\"Py\", \"Quest\"]\nresult = \"\"\nfor w in words:\n    result += w\nprint(result)", "填空拼接。", "words = [\"Py\", \"Quest\"]\nresult = \"\"\nfor w in words:\n    result += w\nprint(result)"),
    (13, "统计列表中偶数的个数。", "nums = [1, 2, 3, 4, 5, 6]\neven_count = 0\nfor n in nums:\n    if n % 2 == 0:\n        even_count += 1\nprint(f\"Evens: {even_count}\")", "填空计数。", "nums = [1, 2, 3, 4, 5, 6]\neven_count = 0\nfor n in nums:\n    if n % 2 == 0:\n        even_count += 1\nprint(f\"Evens: {even_count}\")"),
    (14, "用 for 生成 1 到 10 的偶数列表。", "evens = []\nfor i in range(1, 11):\n    if i % 2 == 0:\n        evens.append(i)\nprint(evens)", "填空 append。", "evens = []\nfor i in range(1, 11):\n    if i % 2 == 0:\n        evens.append(i)\nprint(evens)"),
    (15, "用 for 实现简单选择（找最小）。", "nums = [7, 2, 9, 4]\nminimum = nums[0]\nfor n in nums:\n    if n < minimum:\n        minimum = n\nprint(f\"Min: {minimum}\")", "填空比较更新。", "nums = [7, 2, 9, 4]\nminimum = nums[0]\nfor n in nums:\n    if n < minimum:\n        minimum = n\nprint(f\"Min: {minimum}\")"),
    (16, "字符串反转（循环版）。", "s = \"abc\"\nreversed_s = \"\"\nfor ch in s:\n    reversed_s = ch + reversed_s\nprint(reversed_s)", "填空反转拼接。", "s = \"abc\"\nreversed_s = \"\"\nfor ch in s:\n    reversed_s = ch + reversed_s\nprint(reversed_s)"),
    (17, "输出每个单词的长度。", "words = [\"hi\", \"hello\"]\nfor w in words:\n    print(len(w))", "填空 len。", "words = [\"hi\", \"hello\"]\nfor w in words:\n    print(len(w))"),
    (18, "循环累加字符串数字。", "strs = [\"1\", \"2\", \"3\"]\ntotal = 0\nfor s in strs:\n    total += int(s)\nprint(f\"Total: {total}\")", "填空 int 转换。", "strs = [\"1\", \"2\", \"3\"]\ntotal = 0\nfor s in strs:\n    total += int(s)\nprint(f\"Total: {total}\")"),
    (19, "打印右对齐的星号行。", "for i in range(1, 4):\n    print(\" \" * (3 - i) + \"*\" * i)", "填空对齐输出。", "for i in range(1, 4):\n    print(\" \" * (3 - i) + \"*\" * i)"),
    (20, "循环输出索引与平方。", "for i in range(1, 4):\n    print(i, i * i)", "填空 i 与平方。", "for i in range(1, 4):\n    print(i, i * i)"),
    (21, "用 for 遍历字典并输出键值。", "d = {\"x\": 1, \"y\": 2}\nfor k, v in d.items():\n    print(k, v)", "填空 items。", "d = {\"x\": 1, \"y\": 2}\nfor k, v in d.items():\n    print(k, v)"),
    (22, "循环中 break 提前求和停止。", "total = 0\nfor i in range(1, 11):\n    if total > 10:\n        break\n    total += i\nprint(f\"Total: {total}\")", "填空 break 条件。", "total = 0\nfor i in range(1, 11):\n    if total > 10:\n        break\n    total += i\nprint(f\"Total: {total}\")"),
    (23, "循环中用 continue 跳过特定值。", "for i in range(1, 7):\n    if i == 4:\n        continue\n    print(i, end=\" \")", "填空 continue。", "for i in range(1, 7):\n    if i == 4:\n        continue\n    print(i, end=\" \")"),
    (24, "计算字符串中元音个数。", "text = \"hello\"\nvowels = 0\nfor ch in text:\n    if ch in \"aeiou\":\n        vowels += 1\nprint(f\"Vowels: {vowels}\")", "填空元音判断。", "text = \"hello\"\nvowels = 0\nfor ch in text:\n    if ch in \"aeiou\":\n        vowels += 1\nprint(f\"Vowels: {vowels}\")"),
    (25, "生成 1 到 10 的平方字典。", "squares = {}\nfor i in range(1, 6):\n    squares[i] = i * i\nprint(squares)", "填空字典赋值。", "squares = {}\nfor i in range(1, 6):\n    squares[i] = i * i\nprint(squares)"),
    (26, "打印 1 到 5 的乘法表行。", "n = 5\nfor i in range(1, 6):\n    print(f\"{n} x {i} = {n * i}\")", "填空乘法行。", "n = 5\nfor i in range(1, 6):\n    print(f\"{n} x {i} = {n * i}\")"),
    (27, "统计列表中大于平均值的个数。", "nums = [3, 8, 5, 10]\navg = sum(nums) / len(nums)\ncount = 0\nfor n in nums:\n    if n > avg:\n        count += 1\nprint(f\"Above average: {count}\")", "填空比较计数。", "nums = [3, 8, 5, 10]\navg = sum(nums) / len(nums)\ncount = 0\nfor n in nums:\n    if n > avg:\n        count += 1\nprint(f\"Above average: {count}\")"),
    (28, "循环生成字符串重复。", "symbol = \"#\"\nfor i in range(1, 4):\n    print(symbol * i)", "填空重复。", "symbol = \"#\"\nfor i in range(1, 4):\n    print(symbol * i)"),
    (29, "求 1 到 20 的奇数之和。", "total = 0\nfor i in range(1, 21):\n    if i % 2 == 1:\n        total += i\nprint(f\"Odd sum: {total}\")", "填空奇数累加。", "total = 0\nfor i in range(1, 21):\n    if i % 2 == 1:\n        total += i\nprint(f\"Odd sum: {total}\")"),
    (30, "输出列表的索引与值的平方。", "nums = [2, 4, 6]\nfor i, n in enumerate(nums):\n    print(f\"{i}: {n * n}\")", "填空 enumerate 与平方。", "nums = [2, 4, 6]\nfor i, n in enumerate(nums):\n    print(f\"{i}: {n * n}\")"),
]

MEDIUM = [
    (1, "用嵌套循环打印 3x3 星号矩阵。", "for i in range(3):\n    row = \"\"\n    for j in range(3):\n        row += \"* \"\n    print(row)", "填空嵌套循环。", "for i in range(3):\n    row = \"\"\n    for j in range(3):\n        row += \"* \"\n    print(row)"),
    (2, "打印 1 到 5 的阶乘表。", "fact = 1\nfor i in range(1, 6):\n    fact *= i\n    print(f\"{i}! = {fact}\")", "填空累乘输出。", "fact = 1\nfor i in range(1, 6):\n    fact *= i\n    print(f\"{i}! = {fact}\")"),
    (3, "输出 1 到 10 中 3 的倍数。", "for i in range(1, 11):\n    if i % 3 == 0:\n        print(i)", "填空倍数判断。", "for i in range(1, 11):\n    if i % 3 == 0:\n        print(i)"),
    (4, "求 1 到 50 中偶数的平方和。", "total = 0\nfor i in range(1, 51):\n    if i % 2 == 0:\n        total += i * i\nprint(f\"Sum: {total}\")", "填空偶数平方累加。", "total = 0\nfor i in range(1, 51):\n    if i % 2 == 0:\n        total += i * i\nprint(f\"Sum: {total}\")"),
    (5, "用 for 生成斐波那契前 10 项。", "fib = [0, 1]\nfor i in range(2, 10):\n    fib.append(fib[i - 1] + fib[i - 2])\nprint(fib)", "填空递推。", "fib = [0, 1]\nfor i in range(2, 10):\n    fib.append(fib[i - 1] + fib[i - 2])\nprint(fib)"),
    (6, "统计字符串中每个字母出现次数。", "text = \"hello\"\ncounts = {}\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\nprint(counts)", "填空计数。", "text = \"hello\"\ncounts = {}\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\nprint(counts)"),
    (7, "用 for 实现列表反转（新列表）。", "nums = [1, 2, 3, 4]\nreversed_nums = []\nfor n in nums:\n    reversed_nums.insert(0, n)\nprint(reversed_nums)", "填空头插反转。", "nums = [1, 2, 3, 4]\nreversed_nums = []\nfor n in nums:\n    reversed_nums.insert(0, n)\nprint(reversed_nums)"),
    (8, "打印数字三角形（递加）。", "for i in range(1, 6):\n    line = \"\"\n    for j in range(1, i + 1):\n        line += str(j)\n    print(line)", "填空三角生成。", "for i in range(1, 6):\n    line = \"\"\n    for j in range(1, i + 1):\n        line += str(j)\n    print(line)"),
    (9, "求两个列表的对应元素乘积和。", "a = [1, 2, 3]\nb = [4, 5, 6]\ntotal = 0\nfor x, y in zip(a, b):\n    total += x * y\nprint(f\"Dot product: {total}\")", "填空点积。", "a = [1, 2, 3]\nb = [4, 5, 6]\ntotal = 0\nfor x, y in zip(a, b):\n    total += x * y\nprint(f\"Dot product: {total}\")"),
    (10, "用 for 找出列表中的重复元素。", "nums = [1, 2, 2, 3, 3, 3]\nseen = set()\ndupes = []\nfor n in nums:\n    if n in seen and n not in dupes:\n        dupes.append(n)\n    seen.add(n)\nprint(dupes)", "填空去重查找。", "nums = [1, 2, 2, 3, 3, 3]\nseen = set()\ndupes = []\nfor n in nums:\n    if n in seen and n not in dupes:\n        dupes.append(n)\n    seen.add(n)\nprint(dupes)"),
    (11, "打印 5x5 棋盘（# 和 . 交替）。", "for i in range(5):\n    row = \"\"\n    for j in range(5):\n        row += \"#\" if (i + j) % 2 == 0 else \".\"\n    print(row)", "填空交替生成。", "for i in range(5):\n    row = \"\"\n    for j in range(5):\n        row += \"#\" if (i + j) % 2 == 0 else \".\"\n    print(row)"),
    (12, "求 1 到 n 的累加（for 版高斯）。", "n = 100\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(f\"1+2+...+{n} = {total}\")", "填空累加。", "n = 100\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(f\"1+2+...+{n} = {total}\")"),
    (13, "把嵌套列表扁平化（for 版）。", "matrix = [[1, 2], [3, 4]]\nflat = []\nfor row in matrix:\n    for n in row:\n        flat.append(n)\nprint(flat)", "填空双重遍历。", "matrix = [[1, 2], [3, 4]]\nflat = []\nfor row in matrix:\n    for n in row:\n        flat.append(n)\nprint(flat)"),
    (14, "统计各数字出现次数（1-5 骰子模拟）。", "rolls = [3, 5, 3, 2, 3, 1, 5]\ncounts = {}\nfor r in rolls:\n    counts[r] = counts.get(r, 0) + 1\nfor n in range(1, 6):\n    print(f\"{n}: {counts.get(n, 0)}\")", "填空频次统计。", "rolls = [3, 5, 3, 2, 3, 1, 5]\ncounts = {}\nfor r in rolls:\n    counts[r] = counts.get(r, 0) + 1\nfor n in range(1, 6):\n    print(f\"{n}: {counts.get(n, 0)}\")"),
    (15, "用 for 实现简单冒泡排序一轮。", "nums = [3, 1, 4, 2]\nfor i in range(len(nums) - 1):\n    if nums[i] > nums[i + 1]:\n        nums[i], nums[i + 1] = nums[i + 1], nums[i]\nprint(nums)", "填空相邻交换。", "nums = [3, 1, 4, 2]\nfor i in range(len(nums) - 1):\n    if nums[i] > nums[i + 1]:\n        nums[i], nums[i + 1] = nums[i + 1], nums[i]\nprint(nums)"),
    (16, "输出每行递增的数字塔。", "for i in range(1, 5):\n    print(str(i) * i)", "填空重复。", "for i in range(1, 5):\n    print(str(i) * i)"),
    (17, "求字符串中数字之和。", "text = \"a1b2c3\"\ntotal = 0\nfor ch in text:\n    if ch.isdigit():\n        total += int(ch)\nprint(f\"Digit sum: {total}\")", "填空数字提取。", "text = \"a1b2c3\"\ntotal = 0\nfor ch in text:\n    if ch.isdigit():\n        total += int(ch)\nprint(f\"Digit sum: {total}\")"),
    (18, "用 for 求最大公约数（递减试探）。", "a, b = 12, 18\ngcd = 1\nfor d in range(1, min(a, b) + 1):\n    if a % d == 0 and b % d == 0:\n        gcd = d\nprint(f\"GCD: {gcd}\")", "填空试探求 gcd。", "a, b = 12, 18\ngcd = 1\nfor d in range(1, min(a, b) + 1):\n    if a % d == 0 and b % d == 0:\n        gcd = d\nprint(f\"GCD: {gcd}\")"),
    (19, "生成 1 到 5 的乘法口诀表。", "for i in range(1, 6):\n    row = []\n    for j in range(1, 6):\n        row.append(f\"{i}x{j}={i * j}\")\n    print(\" \".join(row))", "填空口诀行。", "for i in range(1, 6):\n    row = []\n    for j in range(1, 6):\n        row.append(f\"{i}x{j}={i * j}\")\n    print(\" \".join(row))"),
    (20, "筛选并输出质数（for 遍历）。", "for n in range(2, 21):\n    is_prime = True\n    for d in range(2, n):\n        if n % d == 0:\n            is_prime = False\n            break\n    if is_prime:\n        print(n, end=\" \")", "填空质数判断。", "for n in range(2, 21):\n    is_prime = True\n    for d in range(2, n):\n        if n % d == 0:\n            is_prime = False\n            break\n    if is_prime:\n        print(n, end=\" \")"),
    (21, "把列表元素按奇偶分组。", "nums = [1, 2, 3, 4, 5]\nevens = []\nodds = []\nfor n in nums:\n    if n % 2 == 0:\n        evens.append(n)\n    else:\n        odds.append(n)\nprint(f\"Evens: {evens}\")\nprint(f\"Odds: {odds}\")", "填空分组。", "nums = [1, 2, 3, 4, 5]\nevens = []\nodds = []\nfor n in nums:\n    if n % 2 == 0:\n        evens.append(n)\n    else:\n        odds.append(n)\nprint(f\"Evens: {evens}\")\nprint(f\"Odds: {odds}\")"),
    (22, "计算单词平均长度。", "words = [\"apple\", \"pear\", \"kiwi\"]\ntotal_len = 0\nfor w in words:\n    total_len += len(w)\navg = total_len / len(words)\nprint(f\"Average length: {avg}\")", "填空长度累加。", "words = [\"apple\", \"pear\", \"kiwi\"]\ntotal_len = 0\nfor w in words:\n    total_len += len(w)\navg = total_len / len(words)\nprint(f\"Average length: {avg}\")"),
    (23, "用 for 生成等差序列并输出。", "start, step, count = 2, 3, 5\nseq = []\nfor i in range(count):\n    seq.append(start + i * step)\nprint(seq)", "填空等差生成。", "start, step, count = 2, 3, 5\nseq = []\nfor i in range(count):\n    seq.append(start + i * step)\nprint(seq)"),
    (24, "输出数字 1 到 20 的因式提示。", "for n in range(1, 21):\n    if n % 2 == 0 and n % 5 == 0:\n        print(f\"{n}: both\")\n    elif n % 2 == 0:\n        print(f\"{n}: even\")\n    elif n % 5 == 0:\n        print(f\"{n}: five\")\n    else:\n        print(f\"{n}: other\")", "填空分类输出。", "for n in range(1, 21):\n    if n % 2 == 0 and n % 5 == 0:\n        print(f\"{n}: both\")\n    elif n % 2 == 0:\n        print(f\"{n}: even\")\n    elif n % 5 == 0:\n        print(f\"{n}: five\")\n    else:\n        print(f\"{n}: other\")"),
    (25, "求列表元素的最大差值。", "nums = [3, 10, 6, 2]\nmaximum = nums[0]\nminimum = nums[0]\nfor n in nums:\n    if n > maximum:\n        maximum = n\n    if n < minimum:\n        minimum = n\nprint(f\"Diff: {maximum - minimum}\")", "填空最大最小。", "nums = [3, 10, 6, 2]\nmaximum = nums[0]\nminimum = nums[0]\nfor n in nums:\n    if n > maximum:\n        maximum = n\n    if n < minimum:\n        minimum = n\nprint(f\"Diff: {maximum - minimum}\")"),
    (26, "把字符串按单词长度分类。", "text = \"a bb ccc dddd\"\nfor w in text.split():\n    print(f\"{w}: {len(w)}\")", "填空拆分统计。", "text = \"a bb ccc dddd\"\nfor w in text.split():\n    print(f\"{w}: {len(w)}\")"),
    (27, "求 1 到 30 中完全平方数。", "squares = []\nfor n in range(1, 31):\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares.append(n)\nprint(squares)", "填空平方判断。", "squares = []\nfor n in range(1, 31):\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares.append(n)\nprint(squares)"),
    (28, "用 for 生成字母序列。", "letters = []\nfor i in range(65, 70):\n    letters.append(chr(i))\nprint(letters)", "填空 chr。", "letters = []\nfor i in range(65, 70):\n    letters.append(chr(i))\nprint(letters)"),
    (29, "统计列表中的连续递增段数。", "nums = [1, 2, 3, 1, 2, 1]\nsegments = 1\nfor i in range(1, len(nums)):\n    if nums[i] <= nums[i - 1]:\n        segments += 1\nprint(f\"Segments: {segments}\")", "填空递增判断。", "nums = [1, 2, 3, 1, 2, 1]\nsegments = 1\nfor i in range(1, len(nums)):\n    if nums[i] <= nums[i - 1]:\n        segments += 1\nprint(f\"Segments: {segments}\")"),
    (30, "综合：for 生成成绩统计表。", "scores = [88, 92, 76, 95]\nprint(f\"{'Score':>6}{'Grade':>8}\")\nfor s in scores:\n    if s >= 90:\n        grade = \"A\"\n    elif s >= 80:\n        grade = \"B\"\n    else:\n        grade = \"C\"\n    print(f\"{s:>6}{grade:>8}\")", "填空统计表。", "scores = [88, 92, 76, 95]\nprint(f\"{'Score':>6}{'Grade':>8}\")\nfor s in scores:\n    if s >= 90:\n        grade = \"A\"\n    elif s >= 80:\n        grade = \"B\"\n    else:\n        grade = \"C\"\n    print(f\"{s:>6}{grade:>8}\")"),
]

HARD = [
    (1, "用 for 实现完整冒泡排序并输出每轮。", "nums = [5, 3, 8, 1]\nfor i in range(len(nums) - 1):\n    for j in range(len(nums) - 1 - i):\n        if nums[j] > nums[j + 1]:\n            nums[j], nums[j + 1] = nums[j + 1], nums[j]\n    print(f\"Pass {i + 1}: {nums}\")", "填空冒泡排序。", "nums = [5, 3, 8, 1]\nfor i in range(len(nums) - 1):\n    for j in range(len(nums) - 1 - i):\n        if nums[j] > nums[j + 1]:\n            nums[j], nums[j + 1] = nums[j + 1], nums[j]\n    print(f\"Pass {i + 1}: {nums}\")"),
    (2, "用 for 生成杨辉三角前 5 行。", "rows = 5\ntriangle = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    for j in range(1, i):\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n    triangle.append(row)\nfor row in triangle:\n    print(row)", "填空杨辉三角。", "rows = 5\ntriangle = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    for j in range(1, i):\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n    triangle.append(row)\nfor row in triangle:\n    print(row)"),
    (3, "求 100 以内所有质数之和。", "total = 0\nfor n in range(2, 101):\n    is_prime = True\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            is_prime = False\n            break\n    if is_prime:\n        total += n\nprint(f\"Prime sum: {total}\")", "填空质数累加。", "total = 0\nfor n in range(2, 101):\n    is_prime = True\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            is_prime = False\n            break\n    if is_prime:\n        total += n\nprint(f\"Prime sum: {total}\")"),
    (4, "用 for 实现选择排序。", "nums = [5, 3, 8, 1, 2]\nfor i in range(len(nums)):\n    min_idx = i\n    for j in range(i + 1, len(nums)):\n        if nums[j] < nums[min_idx]:\n            min_idx = j\n    nums[i], nums[min_idx] = nums[min_idx], nums[i]\nprint(nums)", "填空选择排序。", "nums = [5, 3, 8, 1, 2]\nfor i in range(len(nums)):\n    min_idx = i\n    for j in range(i + 1, len(nums)):\n        if nums[j] < nums[min_idx]:\n            min_idx = j\n    nums[i], nums[min_idx] = nums[min_idx], nums[i]\nprint(nums)"),
    (5, "生成螺旋矩阵（for 版简化）。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\nnum = 1\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nwhile top <= bottom and left <= right:\n    for j in range(left, right + 1):\n        matrix[top][j] = num\n        num += 1\n    top += 1\n    for i in range(top, bottom + 1):\n        matrix[i][right] = num\n        num += 1\n    right -= 1\n    for j in range(right, left - 1, -1):\n        matrix[bottom][j] = num\n        num += 1\n    bottom -= 1\n    for i in range(bottom, top - 1, -1):\n        matrix[i][left] = num\n        num += 1\n    left += 1\nfor row in matrix:\n    print(row)", "填空螺旋填充。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\nnum = 1\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nwhile top <= bottom and left <= right:\n    for j in range(left, right + 1):\n        matrix[top][j] = num\n        num += 1\n    top += 1\n    for i in range(top, bottom + 1):\n        matrix[i][right] = num\n        num += 1\n    right -= 1\n    for j in range(right, left - 1, -1):\n        matrix[bottom][j] = num\n        num += 1\n    bottom -= 1\n    for i in range(bottom, top - 1, -1):\n        matrix[i][left] = num\n        num += 1\n    left += 1\nfor row in matrix:\n    print(row)"),
    (6, "用 for 求最大子段和（Kadane）。", "nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\nmax_sum = nums[0]\ncur = 0\nfor n in nums:\n    cur = max(n, cur + n)\n    max_sum = max(max_sum, cur)\nprint(max_sum)", "填空 Kadane。", "nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\nmax_sum = nums[0]\ncur = 0\nfor n in nums:\n    cur = max(n, cur + n)\n    max_sum = max(max_sum, cur)\nprint(max_sum)"),
    (7, "求 1000 以内的完数。", "for n in range(2, 1001):\n    total = 0\n    for d in range(1, n):\n        if n % d == 0:\n            total += d\n    if total == n:\n        print(n)", "填空完数判断。", "for n in range(2, 1001):\n    total = 0\n    for d in range(1, n):\n        if n % d == 0:\n            total += d\n    if total == n:\n        print(n)"),
    (8, "统计单词频率并输出前 3。", "text = \"the cat and the dog and the bird and fish\"\nwords = text.split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in sorted(counts.items(), key=lambda x: x[1], reverse=True)[:3]:\n    print(f\"{w}: {c}\")", "填空词频排序。", "text = \"the cat and the dog and the bird and fish\"\nwords = text.split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in sorted(counts.items(), key=lambda x: x[1], reverse=True)[:3]:\n    print(f\"{w}: {c}\")"),
    (9, "用 for 求两数之和索引（暴力）。", "nums = [2, 7, 11, 15]\ntarget = 9\nfor i in range(len(nums)):\n    for j in range(i + 1, len(nums)):\n        if nums[i] + nums[j] == target:\n            print(f\"{i} + {j} = {target}\")", "填空双重循环。", "nums = [2, 7, 11, 15]\ntarget = 9\nfor i in range(len(nums)):\n    for j in range(i + 1, len(nums)):\n        if nums[i] + nums[j] == target:\n            print(f\"{i} + {j} = {target}\")"),
    (10, "生成 8x8 国际象棋棋盘。", "for i in range(8):\n    row = \"\"\n    for j in range(8):\n        row += \"X\" if (i + j) % 2 == 0 else \"O\"\n    print(row)", "填空棋盘生成。", "for i in range(8):\n    row = \"\"\n    for j in range(8):\n        row += \"X\" if (i + j) % 2 == 0 else \"O\"\n    print(row)"),
    (11, "求 1 到 500 的水仙花数。", "for n in range(100, 500):\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)", "填空水仙花。", "for n in range(100, 500):\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)"),
    (12, "用 for 实现插入排序。", "nums = [5, 3, 8, 1]\nfor i in range(1, len(nums)):\n    key = nums[i]\n    j = i - 1\n    while j >= 0 and nums[j] > key:\n        nums[j + 1] = nums[j]\n        j -= 1\n    nums[j + 1] = key\nprint(nums)", "填空插入排序。", "nums = [5, 3, 8, 1]\nfor i in range(1, len(nums)):\n    key = nums[i]\n    j = i - 1\n    while j >= 0 and nums[j] > key:\n        nums[j + 1] = nums[j]\n        j -= 1\n    nums[j + 1] = key\nprint(nums)"),
    (13, "输出九九乘法表（for 嵌套）。", "for i in range(1, 10):\n    line = []\n    for j in range(1, i + 1):\n        line.append(f\"{j}x{i}={i * j}\")\n    print(\" \".join(line))", "填空乘法表。", "for i in range(1, 10):\n    line = []\n    for j in range(1, i + 1):\n        line.append(f\"{j}x{i}={i * j}\")\n    print(\" \".join(line))"),
    (14, "判断回文数并输出验证过程。", "for n in [12321, 12345, 11]:\n    s = str(n)\n    if s == s[::-1]:\n        print(f\"{n} is palindrome\")\n    else:\n        print(f\"{n} is not palindrome\")", "填空回文判断。", "for n in [12321, 12345, 11]:\n    s = str(n)\n    if s == s[::-1]:\n        print(f\"{n} is palindrome\")\n    else:\n        print(f\"{n} is not palindrome\")"),
    (15, "用 for 求矩阵主对角线和。", "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ntotal = 0\nfor i in range(3):\n    total += matrix[i][i]\nprint(f\"Diagonal sum: {total}\")", "填空对角线。", "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ntotal = 0\nfor i in range(3):\n    total += matrix[i][i]\nprint(f\"Diagonal sum: {total}\")"),
    (16, "统计并输出字符类型分布。", "text = \"Hello, Python 3.12!\"\nletters = digits = other = 0\nfor ch in text:\n    if ch.isalpha():\n        letters += 1\n    elif ch.isdigit():\n        digits += 1\n    else:\n        other += 1\nprint(f\"Letters: {letters}, Digits: {digits}, Other: {other}\")", "填空字符分类。", "text = \"Hello, Python 3.12!\"\nletters = digits = other = 0\nfor ch in text:\n    if ch.isalpha():\n        letters += 1\n    elif ch.isdigit():\n        digits += 1\n    else:\n        other += 1\nprint(f\"Letters: {letters}, Digits: {digits}, Other: {other}\")"),
    (17, "求列表第二大的数。", "nums = [4, 9, 7, 9, 2]\nunique = sorted(set(nums))\nprint(f\"Second largest: {unique[-2]}\")", "填空去重取第二大。", "nums = [4, 9, 7, 9, 2]\nunique = sorted(set(nums))\nprint(f\"Second largest: {unique[-2]}\")"),
    (18, "用 for 输出斐波那契对。", "a, b = 0, 1\nfor i in range(8):\n    print(f\"fib({i}) = {a}\")\n    a, b = b, a + b", "填空递推。", "a, b = 0, 1\nfor i in range(8):\n    print(f\"fib({i}) = {a}\")\n    a, b = b, a + b"),
    (19, "统计矩阵中偶数的个数。", "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ncount = 0\nfor row in matrix:\n    for n in row:\n        if n % 2 == 0:\n            count += 1\nprint(f\"Evens: {count}\")", "填空矩阵计数。", "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ncount = 0\nfor row in matrix:\n    for n in row:\n        if n % 2 == 0:\n            count += 1\nprint(f\"Evens: {count}\")"),
    (20, "求 1 到 100 的阶乘和（大数）。", "def fact(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\ntotal = 0\nfor i in range(1, 11):\n    total += fact(i)\nprint(f\"Sum: {total}\")", "填空阶乘和。", "def fact(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\ntotal = 0\nfor i in range(1, 11):\n    total += fact(i)\nprint(f\"Sum: {total}\")"),
    (21, "模拟约瑟夫环（for 辅助）。", "people = list(range(1, 7))\nk = 3\nidx = 0\norder = []\nwhile people:\n    idx = (idx + k - 1) % len(people)\n    order.append(people.pop(idx))\nprint(order)", "填空约瑟夫。", "people = list(range(1, 7))\nk = 3\nidx = 0\norder = []\nwhile people:\n    idx = (idx + k - 1) % len(people)\n    order.append(people.pop(idx))\nprint(order)"),
    (22, "用 for 找连续最大乘积（简化）。", "nums = [2, 3, -2, 4]\nmax_prod = nums[0]\nfor i in range(len(nums)):\n    prod = 1\n    for j in range(i, len(nums)):\n        prod *= nums[j]\n        max_prod = max(max_prod, prod)\nprint(f\"Max product: {max_prod}\")", "填空乘积扫描。", "nums = [2, 3, -2, 4]\nmax_prod = nums[0]\nfor i in range(len(nums)):\n    prod = 1\n    for j in range(i, len(nums)):\n        prod *= nums[j]\n        max_prod = max(max_prod, prod)\nprint(f\"Max product: {max_prod}\")"),
    (23, "生成数字金字塔（居中）。", "n = 5\nfor i in range(1, n + 1):\n    line = \" \".join(str(j) for j in range(1, i + 1))\n    print(f\"{line:^{n * 2}}\")", "填空居中金字塔。", "n = 5\nfor i in range(1, n + 1):\n    line = \" \".join(str(j) for j in range(1, i + 1))\n    print(f\"{line:^{n * 2}}\")"),
    (24, "统计每个字符出现次数（含空格）。", "text = \"ab a bb\"\ncounts = {}\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\nfor ch in sorted(counts):\n    print(f\"{repr(ch)}: {counts[ch]}\")", "填空字符统计。", "text = \"ab a bb\"\ncounts = {}\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\nfor ch in sorted(counts):\n    print(f\"{repr(ch)}: {counts[ch]}\")"),
    (25, "判断序列是否单调。", "nums = [1, 3, 5, 6]\nincreasing = True\ndecreasing = True\nfor i in range(1, len(nums)):\n    if nums[i] < nums[i - 1]:\n        increasing = False\n    if nums[i] > nums[i - 1]:\n        decreasing = False\nif increasing:\n    print(\"increasing\")\nelif decreasing:\n    print(\"decreasing\")\nelse:\n    print(\"neither\")", "填空单调判断。", "nums = [1, 3, 5, 6]\nincreasing = True\ndecreasing = True\nfor i in range(1, len(nums)):\n    if nums[i] < nums[i - 1]:\n        increasing = False\n    if nums[i] > nums[i - 1]:\n        decreasing = False\nif increasing:\n    print(\"increasing\")\nelif decreasing:\n    print(\"decreasing\")\nelse:\n    print(\"neither\")"),
    (26, "求 1 到 n 各数的约数个数表。", "for n in range(1, 8):\n    count = 0\n    for d in range(1, n + 1):\n        if n % d == 0:\n            count += 1\n    print(f\"{n}: {count} divisors\")", "填空约数计数。", "for n in range(1, 8):\n    count = 0\n    for d in range(1, n + 1):\n        if n % d == 0:\n            count += 1\n    print(f\"{n}: {count} divisors\")"),
    (27, "把列表循环左移 k 位。", "nums = [1, 2, 3, 4, 5]\nk = 2\nshifted = nums[k:] + nums[:k]\nprint(shifted)", "填空循环移位。", "nums = [1, 2, 3, 4, 5]\nk = 2\nshifted = nums[k:] + nums[:k]\nprint(shifted)"),
    (28, "输出 100 以内的孪生素数对。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nfor n in range(2, 98):\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)", "填空孪生素数。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nfor n in range(2, 98):\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)"),
    (29, "用 for 生成乘法表并求和。", "total = 0\nfor i in range(1, 6):\n    for j in range(1, 6):\n        total += i * j\nprint(f\"Sum of 5x5 table: {total}\")", "填空表内求和。", "total = 0\nfor i in range(1, 6):\n    for j in range(1, 6):\n        total += i * j\nprint(f\"Sum of 5x5 table: {total}\")"),
    (30, "综合：for 输出学生成绩报告。", "students = [(\"Alice\", 92), (\"Bob\", 78), (\"Cara\", 88)]\nprint(f\"{'Name':<8}{'Score':>6}{'Grade':>8}\")\nfor name, score in students:\n    if score >= 90:\n        grade = \"A\"\n    elif score >= 80:\n        grade = \"B\"\n    else:\n        grade = \"C\"\n    print(f\"{name:<8}{score:>6}{grade:>8}\")", "填空成绩报告。", "students = [(\"Alice\", 92), (\"Bob\", 78), (\"Cara\", 88)]\nprint(f\"{'Name':<8}{'Score':>6}{'Grade':>8}\")\nfor name, score in students:\n    if score >= 90:\n        grade = \"A\"\n    elif score >= 80:\n        grade = \"B\"\n    else:\n        grade = \"C\"\n    print(f\"{name:<8}{score:>6}{grade:>8}\")"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
