# -*- coding: utf-8 -*-
"""生成 CH05 字符串格式化 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH05"
TITLE = "字符串格式化"
OUT_DIR = "CH05_String_Formatting"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "用 f-string 输出问候语。", "name = \"Tom\"\nprint(f\"Hello, {___}!\")", "花括号内填 name。", "name = \"Tom\"\nprint(f\"Hello, {name}!\")"),
    (2, "用 f-string 输出变量的值。", "x = 5\nprint(f\"Value: {___}\")", "花括号内填 x。", "x = 5\nprint(f\"Value: {x}\")"),
    (3, "用 format() 输出两个值。", "print(\"{} and {}\".format(___, ___))", "依次填 \"a\"、\"b\"。", "print(\"{} and {}\".format(\"a\", \"b\"))"),
    (4, "用 format() 关键字参数。", "print(\"{x} + {y}\".format(x=___, y=___))", "依次填 1、2。", "print(\"{x} + {y}\".format(x=1, y=2))"),
    (5, "用 %s 和 %d 格式化。", "print(\"%s is %d\" % (___, ___))", "依次填 \"Bob\"、25。", "print(\"%s is %d\" % (\"Bob\", 25))"),
    (6, "用 %.3f 保留三位小数。", "print(\"%.3f\" % ___)", "填 3.14159。", "print(\"%.3f\" % 3.14159)"),
    (7, "用 f-string 保留两位小数。", "pi = 3.14159\nprint(f\"{___:.2f}\")", "花括号内填 pi。", "pi = 3.14159\nprint(f\"{pi:.2f}\")"),
    (8, "用 f-string 设置数字宽度。", "n = 42\nprint(f\"{___:5d}\")", "花括号内填 n。", "n = 42\nprint(f\"{n:5d}\")"),
    (9, "用 f-string 左对齐字符串。", "name = \"ab\"\nprint(f\"{name:___}|\")", "对齐符填 <5。", "name = \"ab\"\nprint(f\"{name:<5}|\")"),
    (10, "用 f-string 右对齐字符串。", "print(f\"{'ab':___}|\")", "对齐符填 >5。", "print(f\"{'ab':>5}|\")"),
    (11, "用 f-string 居中字符串。", "print(f\"{'ab':___}\")", "对齐符填 ^5。", "print(f\"{'ab':^5}\")"),
    (12, "用 f-string 填充字符。", "print(f\"{'ab':___^6}\")", "填充符填 *。", "print(f\"{'ab':*^6}\")"),
    (13, "用 f-string 输出千分位。", "amount = 1234567\nprint(f\"{___:,}\")", "花括号内填 amount。", "amount = 1234567\nprint(f\"{amount:,}\")"),
    (14, "用 f-string 输出百分比。", "ratio = 0.25\nprint(f\"{___:.1%}\")", "花括号内填 ratio。", "ratio = 0.25\nprint(f\"{ratio:.1%}\")"),
    (15, "用 f-string 输出十六进制。", "n = 255\nprint(f\"{___:x}\")", "花括号内填 n。", "n = 255\nprint(f\"{n:x}\")"),
    (16, "用 f-string 输出二进制。", "print(f\"{___:b}\")", "花括号内填 5。", "print(f\"{5:b}\")"),
    (17, "输出含转义字符的字符串。", "print(\"Tab:\\tA\\nLine2\")", "填空转义序列。", "print(\"Tab:\\tA\\nLine2\")"),
    (18, "用 + 拼接字符串。", "print(\"Py\" + ___)", "填 \"Quest\"。", "print(\"Py\" + \"Quest\")"),
    (19, "用 * 重复字符串。", "print(___ * 10)", "填 \"-\"。", "print(\"-\" * 10)"),
    (20, "用 upper() 转大写。", "name = \"python\"\nprint(name.___())", "方法名填 upper。", "name = \"python\"\nprint(name.upper())"),
    (21, "用 capitalize() 首字母大写。", "print(\"hello\".___())", "方法名填 capitalize。", "print(\"hello\".capitalize())"),
    (22, "用 replace() 替换字符。", "print(\"a-b-c\".replace(___, \"\"))", "替换目标填 \"-\"。", "print(\"a-b-c\".replace(\"-\", \"\"))"),
    (23, "用 split() 分割字符串。", "print(\"a,b,c\".split(___,))", "分隔符填 \",\"。", "print(\"a,b,c\".split(\",\"))"),
    (24, "用 strip() 去除两端空格。", "print(\"  hi  \".___())", "方法名填 strip。", "print(\"  hi  \".strip())"),
    (25, "用 len() 求字符串长度。", "print(len(___))", "填 \"Python\"。", "print(len(\"Python\"))"),
    (26, "用索引访问字符串首字符。", "word = \"Python\"\nprint(word[___])", "索引填 0。", "word = \"Python\"\nprint(word[0])"),
    (27, "用切片截取字符串。", "print(\"Python\"[___])", "切片填 0:4。", "print(\"Python\"[0:4])"),
    (28, "用切片反转字符串。", "print(\"abc\"[___])", "切片填 ::-1。", "print(\"abc\"[::-1])"),
    (29, "用 in 判断子串存在。", "print(\"ell\" in ___)", "填 \"hello\"。", "print(\"ell\" in \"hello\")"),
    (30, "用 %% 输出百分号。", "print(\"%d%%\" % ___)", "填 50。", "print(\"%d%%\" % 50)"),
]

SIMPLE = [
    (1, "用 f-string 输出多个变量。", "name = \"Bob\"\nage = 25\nprint(f\"{___} is {___} years old\")", "依次填 name、age。", "name = \"Bob\"\nage = 25\nprint(f\"{name} is {age} years old\")"),
    (2, "三种对齐方式输出。", "s = \"ab\"\nprint(f\"|{s:___}|\")\nprint(f\"|{s:___}|\")\nprint(f\"|{s:___}|\")", "依次填 <5、>5、^5。", "s = \"ab\"\nprint(f\"|{s:<5}|\")\nprint(f\"|{s:>5}|\")\nprint(f\"|{s:^5}|\")"),
    (3, "千分位加两位小数。", "amount = 1234567.891\nprint(f\"{___:,.2f}\")", "花括号内填 amount。", "amount = 1234567.891\nprint(f\"{amount:,.2f}\")"),
    (4, "百分比带符号输出。", "rate = 0.125\nprint(f\"{___:+.1%}\")", "花括号内填 rate。", "rate = 0.125\nprint(f\"{rate:+.1%}\")"),
    (5, "宽度加填充对齐。", "print(f\"{42:___}\")\nprint(f\"{42:___}\")", "依次填 >8、0>8。", "print(f\"{42:>8}\")\nprint(f\"{42:0>8}\")"),
    (6, "format() 混合位置与关键字。", "print(\"{0} loves {lang}\".format(\"Tom\", lang=___))", "填 \"Python\"。", "print(\"{0} loves {lang}\".format(\"Tom\", lang=\"Python\"))"),
    (7, "用 % 输出多种类型。", "print(\"%s scored %d (%.1f%%)\" % (___, ___, ___))", "依次填 \"Bob\"、92、92.5。", "print(\"%s scored %d (%.1f%%)\" % (\"Bob\", 92, 92.5))"),
    (8, "转义与格式组合输出。", "print(\"Name\\tScore\")\nprint(\"%s\\t%d\" % (___, ___))", "依次填 \"Alice\"、90。", "print(\"Name\\tScore\")\nprint(\"%s\\t%d\" % (\"Alice\", 90))"),
    (9, "拼接后格式化输出。", "name = \"Bob\"\nmsg = \"Hello, \" + name + \"!\"\nprint(f\"{___:>20}\")", "花括号内填 msg。", "name = \"Bob\"\nmsg = \"Hello, \" + name + \"!\"\nprint(f\"{msg:>20}\")"),
    (10, "居中加填充字符。", "title = \"PyQuest\"\nprint(f\"{___:=^30}\")", "花括号内填 title。", "title = \"PyQuest\"\nprint(f\"{title:=^30}\")"),
    (11, "数字转字符串并填充。", "n = 7\nprint(f\"{str(___):0>3}\")", "括号内填 n。", "n = 7\nprint(f\"{str(n):0>3}\")"),
    (12, "根据条件格式化输出。", "score = 85\ngrade = \"A\" if score >= 90 else \"B\"\nprint(f\"Score: {___}, Grade: {___}\")", "依次填 score、grade。", "score = 85\ngrade = \"A\" if score >= 90 else \"B\"\nprint(f\"Score: {score}, Grade: {grade}\")"),
    (13, "把列表 join 成格式化字符串。", "nums = [1, 2, 3]\nprint(\"|\".join(f\"{n:>2}\" for n in nums))", "填空生成器表达式。", "nums = [1, 2, 3]\nprint(\"|\".join(f\"{n:>2}\" for n in nums))"),
    (14, "格式化字典中的值。", "scores = {\"Alice\": 90, \"Bob\": 85}\nfor name, score in scores.items():\n    print(f\"{___}: {___}\")", "依次填 name、score。", "scores = {\"Alice\": 90, \"Bob\": 85}\nfor name, score in scores.items():\n    print(f\"{name}: {score}\")"),
    (15, "循环中格式化输出序号。", "items = [\"a\", \"b\", \"c\"]\nfor i, item in enumerate(items, 1):\n    print(f\"{i:>2}. {___}\")", "花括号内填 item。", "items = [\"a\", \"b\", \"c\"]\nfor i, item in enumerate(items, 1):\n    print(f\"{i:>2}. {item}\")"),
    (16, "用换行连接多段文本。", "print(\"Line1\\n\" + \"Line2\\n\" + ___ + \"\\nLine4\")", "填 \"Line3\"。", "print(\"Line1\\n\" + \"Line2\\n\" + \"Line3\" + \"\\nLine4\")"),
    (17, "输出格式化的表格行。", "row = (\"Alice\", 90, \"A\")\nprint(f\"{row[___]:<8}{row[___]:>5}{row[___]:>4}\")", "依次填 0、1、2。", "row = (\"Alice\", 90, \"A\")\nprint(f\"{row[0]:<8}{row[1]:>5}{row[2]:>4}\")"),
    (18, "格式化模拟时间。", "h, m, s = 9, 5, 3\nprint(f\"{h:02d}:{m:02d}:{___:02d}\")", "花括号内填 s。", "h, m, s = 9, 5, 3\nprint(f\"{h:02d}:{m:02d}:{s:02d}\")"),
    (19, "格式化金额输出。", "price = 19.5\nqty = 3\nprint(f\"Total: ${price * qty:___}\")", "格式符填 .2f。", "price = 19.5\nqty = 3\nprint(f\"Total: ${price * qty:.2f}\")"),
    (20, "输出得分百分比。", "correct = 18\ntotal = 20\nprint(f\"Accuracy: {correct / total:___}\")", "格式符填 .1% 。", "correct = 18\ntotal = 20\nprint(f\"Accuracy: {correct / total:.1%}\")"),
    (21, "表头与数据对齐。", "print(f\"{'Name':<10}{'Score':>6}\")\nprint(f\"{'Alice':<10}{90:>6}\")", "填空对齐格式。", "print(f\"{'Name':<10}{'Score':>6}\")\nprint(f\"{'Alice':<10}{90:>6}\")"),
    (22, "字符串乘法拼边框。", "print(\"+\" + \"-\" * 8 + \"+\")\nprint(\"|\" + \" Hi \" + \"|\")", "填空边框拼接。", "print(\"+\" + \"-\" * 8 + \"+\")\nprint(\"|\" + \" Hi \" + \"|\")"),
    (23, "科学计数法格式化。", "big = 123456789.0\nprint(f\"{___:.2e}\")", "花括号内填 big。", "big = 123456789.0\nprint(f\"{big:.2e}\")"),
    (24, "带符号输出数字。", "a, b = 5, -3\nprint(f\"{a:+d} {___:+d}\")", "花括号内填 b。", "a, b = 5, -3\nprint(f\"{a:+d} {b:+d}\")"),
    (25, "进制前缀输出。", "n = 255\nprint(f\"{n:#x} {n:#o} {___:#b}\")", "花括号内填 n。", "n = 255\nprint(f\"{n:#x} {n:#o} {n:#b}\")"),
    (26, "截断字符串输出。", "text = \"Python Programming\"\nprint(f\"{___:.6}...\")", "花括号内填 text。", "text = \"Python Programming\"\nprint(f\"{text:.6}...\")"),
    (27, "保留指定精度。", "value = 2.7182818\nprint(f\"{___:.4f}\")", "花括号内填 value。", "value = 2.7182818\nprint(f\"{value:.4f}\")"),
    (28, "统计并格式化文本信息。", "text = \"hello world\"\nprint(f\"Chars: {len(text)}, Words: {len(text.split())}\")", "填空 len 统计。", "text = \"hello world\"\nprint(f\"Chars: {len(text)}, Words: {len(text.split())}\")"),
    (29, "多维数据格式化输出。", "data = [[1, 2], [3, 4]]\nfor row in data:\n    print(f\"{row[0]:>2} {row[___]:>2}\")", "索引填 1。", "data = [[1, 2], [3, 4]]\nfor row in data:\n    print(f\"{row[0]:>2} {row[1]:>2}\")"),
    (30, "综合格式化输出名片。", "name = \"Ada\"\nage = 36\ncity = \"London\"\nprint(f\"{name:<6}{age:>4}{city:>10}\")", "填空对齐格式。", "name = \"Ada\"\nage = 36\ncity = \"London\"\nprint(f\"{name:<6}{age:>4}{city:>10}\")"),
]

MEDIUM = [
    (1, "输出对齐的成绩表。", "scores = [(\"Alice\", 90), (\"Bob\", 85), (\"Cara\", 92)]\nprint(f\"{'Name':<8}{'Score':>6}\")\nprint(\"-\" * 14)\nfor name, score in scores:\n    print(f\"{name:<8}{score:>6}\")", "填空表头与行格式。", "scores = [(\"Alice\", 90), (\"Bob\", 85), (\"Cara\", 92)]\nprint(f\"{'Name':<8}{'Score':>6}\")\nprint(\"-\" * 14)\nfor name, score in scores:\n    print(f\"{name:<8}{score:>6}\")"),
    (2, "用格式输出数字三角形。", "n = 5\nfor i in range(1, n + 1):\n    line = \" \".join(f\"{j:>2}\" for j in range(1, i + 1))\n    print(f\"{line:^{n * 3}}\")", "填空对齐与宽度。", "n = 5\nfor i in range(1, n + 1):\n    line = \" \".join(f\"{j:>2}\" for j in range(1, i + 1))\n    print(f\"{line:^{n * 3}}\")"),
    (3, "输出带千分位的价格清单。", "items = [(\"apple\", 3.5, 2), (\"milk\", 5.0, 1)]\ntotal = 0\nprint(f\"{'Item':<10}{'Price':>8}{'Qty':>4}{'Sub':>10}\")\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name:<10}{price:>8.2f}{qty:>4}{sub:>10,.2f}\")\nprint(f\"{'TOTAL':<10}{'':>12}{total:>10,.2f}\")", "填空对齐与千分位。", "items = [(\"apple\", 3.5, 2), (\"milk\", 5.0, 1)]\ntotal = 0\nprint(f\"{'Item':<10}{'Price':>8}{'Qty':>4}{'Sub':>10}\")\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name:<10}{price:>8.2f}{qty:>4}{sub:>10,.2f}\")\nprint(f\"{'TOTAL':<10}{'':>12}{total:>10,.2f}\")"),
    (4, "用字符绘制横向进度条。", "progress = 0.65\nwidth = 20\nfilled = int(progress * width)\nbar = \"#\" * filled + \".\" * (width - filled)\nprint(f\"[{bar}] {progress:.0%}\")", "填空进度条计算。", "progress = 0.65\nwidth = 20\nfilled = int(progress * width)\nbar = \"#\" * filled + \".\" * (width - filled)\nprint(f\"[{bar}] {progress:.0%}\")"),
    (5, "输出居中的标题装饰。", "title = \"PYQUEST\"\nwidth = 30\nborder = \"=\" * width\nprint(border)\nprint(f\"{title:^{width}}\")\nprint(border)", "填空居中格式。", "title = \"PYQUEST\"\nwidth = 30\nborder = \"=\" * width\nprint(border)\nprint(f\"{title:^{width}}\")\nprint(border)"),
    (6, "统计单词并格式化报告。", "text = \"the cat and the dog and the bird\"\nwords = text.split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in sorted(counts.items()):\n    print(f\"{w:<8}{c:>3}\")", "填空统计与格式化。", "text = \"the cat and the dog and the bird\"\nwords = text.split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in sorted(counts.items()):\n    print(f\"{w:<8}{c:>3}\")"),
    (7, "格式化输出摄氏华氏对照表。", "print(f\"{'C':>5}{'F':>10}\")\nfor c in range(0, 101, 20):\n    f = c * 9 / 5 + 32\n    print(f\"{c:>5d}{f:>10.1f}\")", "填空表头与数据格式。", "print(f\"{'C':>5}{'F':>10}\")\nfor c in range(0, 101, 20):\n    f = c * 9 / 5 + 32\n    print(f\"{c:>5d}{f:>10.1f}\")"),
    (8, "输出银行账户余额报告。", "transactions = [(\"deposit\", 1000), (\"withdraw\", 200), (\"deposit\", 500)]\nbalance = 0\nprint(f\"{'Type':<10}{'Amount':>10}{'Balance':>12}\")\nfor t, amount in transactions:\n    if t == \"deposit\":\n        balance += amount\n    else:\n        balance -= amount\n    print(f\"{t:<10}{amount:>10,d}{balance:>12,d}\")", "填空交易报告格式。", "transactions = [(\"deposit\", 1000), (\"withdraw\", 200), (\"deposit\", 500)]\nbalance = 0\nprint(f\"{'Type':<10}{'Amount':>10}{'Balance':>12}\")\nfor t, amount in transactions:\n    if t == \"deposit\":\n        balance += amount\n    else:\n        balance -= amount\n    print(f\"{t:<10}{amount:>10,d}{balance:>12,d}\")"),
    (9, "把数字列右对齐输出。", "nums = [3, 42, 555, 1234]\nfor n in nums:\n    print(f\"{n:>6}\")", "填空右对齐宽度。", "nums = [3, 42, 555, 1234]\nfor n in nums:\n    print(f\"{n:>6}\")"),
    (10, "绘制字符直方图。", "data = {\"A\": 3, \"B\": 5, \"C\": 2}\nfor key, value in data.items():\n    print(f\"{key}: {'#' * value}\")", "填空直方图生成。", "data = {\"A\": 3, \"B\": 5, \"C\": 2}\nfor key, value in data.items():\n    print(f\"{key}: {'#' * value}\")"),
    (11, "输出学生信息卡片。", "student = {\"name\": \"Alice\", \"age\": 20, \"grade\": \"A\"}\nprint(\"=\" * 20)\nfor key, value in student.items():\n    print(f\"{key.capitalize():<8}: {value}\")\nprint(\"=\" * 20)", "填空卡片格式化。", "student = {\"name\": \"Alice\", \"age\": 20, \"grade\": \"A\"}\nprint(\"=\" * 20)\nfor key, value in student.items():\n    print(f\"{key.capitalize():<8}: {value}\")\nprint(\"=\" * 20)"),
    (12, "格式化输出坐标网格。", "for x in range(1, 4):\n    row = []\n    for y in range(1, 4):\n        row.append(f\"({x},{y})\")\n    print(\" \".join(row))", "填空坐标格式。", "for x in range(1, 4):\n    row = []\n    for y in range(1, 4):\n        row.append(f\"({x},{y})\")\n    print(\" \".join(row))"),
    (13, "输出分数成绩单。", "subjects = [(\"Math\", 92), (\"English\", 88), (\"Science\", 95)]\ntotal = sum(s for _, s in subjects)\navg = total / len(subjects)\nprint(f\"{'Subject':<10}{'Score':>6}\")\nfor sub, score in subjects:\n    print(f\"{sub:<10}{score:>6}\")\nprint(f\"{'Average':<10}{avg:>6.1f}\")", "填空成绩单格式。", "subjects = [(\"Math\", 92), (\"English\", 88), (\"Science\", 95)]\ntotal = sum(s for _, s in subjects)\navg = total / len(subjects)\nprint(f\"{'Subject':<10}{'Score':>6}\")\nfor sub, score in subjects:\n    print(f\"{sub:<10}{score:>6}\")\nprint(f\"{'Average':<10}{avg:>6.1f}\")"),
    (14, "用格式输出乘法口诀表。", "for i in range(1, 6):\n    line = \"  \".join(f\"{i}x{j}={i * j:>2}\" for j in range(1, 6))\n    print(line)", "填空乘法表格式。", "for i in range(1, 6):\n    line = \"  \".join(f\"{i}x{j}={i * j:>2}\" for j in range(1, 6))\n    print(line)"),
    (15, "输出带边框的菜单。", "menu = [\"1. Start\", \"2. Options\", \"3. Exit\"]\nprint(\"+\" + \"-\" * 16 + \"+\")\nfor item in menu:\n    print(f\"|{item:<16}|\")\nprint(\"+\" + \"-\" * 16 + \"+\")", "填空菜单边框。", "menu = [\"1. Start\", \"2. Options\", \"3. Exit\"]\nprint(\"+\" + \"-\" * 16 + \"+\")\nfor item in menu:\n    print(f\"|{item:<16}|\")\nprint(\"+\" + \"-\" * 16 + \"+\")"),
    (16, "格式化输出 2 的幂表。", "print(f\"{'n':>3}{'2^n':>10}\")\nfor n in range(1, 11):\n    print(f\"{n:>3}{2 ** n:>10,}\")", "填空幂表格式。", "print(f\"{'n':>3}{'2^n':>10}\")\nfor n in range(1, 11):\n    print(f\"{n:>3}{2 ** n:>10,}\")"),
    (17, "输出购物小票。", "items = [(\"apple\", 3.5, 2), (\"milk\", 5.0, 3)]\ntotal = 0\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name} x{qty} @ {price:.2f} = {sub:.2f}\")\nprint(f\"Total: {total:.2f}\")", "填空小票格式。", "items = [(\"apple\", 3.5, 2), (\"milk\", 5.0, 3)]\ntotal = 0\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name} x{qty} @ {price:.2f} = {sub:.2f}\")\nprint(f\"Total: {total:.2f}\")"),
    (18, "输出单词长度分布。", "words = [\"hi\", \"hello\", \"world\", \"python\", \"programming\"]\nfor w in words:\n    print(f\"{w:<12}{len(w):>3} {'*' * len(w)}\")", "填空分布格式。", "words = [\"hi\", \"hello\", \"world\", \"python\", \"programming\"]\nfor w in words:\n    print(f\"{w:<12}{len(w):>3} {'*' * len(w)}\")"),
    (19, "格式化输出日期。", "year, month, day = 2026, 8, 12\nprint(f\"{year}-{month:02d}-{day:02d}\")\nprint(f\"{month}/{day}/{year}\")", "填空日期格式。", "year, month, day = 2026, 8, 12\nprint(f\"{year}-{month:02d}-{day:02d}\")\nprint(f\"{month}/{day}/{year}\")"),
    (20, "输出数字金字塔（居中）。", "n = 5\nfor i in range(1, n + 1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    print(f\"{line:^{2 * n}}\")", "填空居中宽度。", "n = 5\nfor i in range(1, n + 1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    print(f\"{line:^{2 * n}}\")"),
    (21, "输出三列对齐数据。", "rows = [(\"Tom\", 25, \"BEIJING\"), (\"Ada\", 36, \"LONDON\")]\nprint(f\"{'Name':<8}{'Age':>5}{'City':>10}\")\nfor name, age, city in rows:\n    print(f\"{name:<8}{age:>5}{city:>10}\")", "填空三列对齐。", "rows = [(\"Tom\", 25, \"BEIJING\"), (\"Ada\", 36, \"LONDON\")]\nprint(f\"{'Name':<8}{'Age':>5}{'City':>10}\")\nfor name, age, city in rows:\n    print(f\"{name:<8}{age:>5}{city:>10}\")"),
    (22, "格式化输出百分比成绩。", "scores = [(\"quiz1\", 8, 10), (\"quiz2\", 9, 10)]\nfor name, got, total in scores:\n    print(f\"{name:<6}{got}/{total} = {got / total:.0%}\")", "填空百分比格式。", "scores = [(\"quiz1\", 8, 10), (\"quiz2\", 9, 10)]\nfor name, got, total in scores:\n    print(f\"{name:<6}{got}/{total} = {got / total:.0%}\")"),
    (23, "把浮点数表格式化为整数表。", "values = [3.7, 2.1, 9.9, 1.5]\nfor v in values:\n    print(f\"{v:>6.1f} -> {v:>5.0f}\")", "填空双格式。", "values = [3.7, 2.1, 9.9, 1.5]\nfor v in values:\n    print(f\"{v:>6.1f} -> {v:>5.0f}\")"),
    (24, "输出缩进的目录结构。", "tree = [(\"src\", 0), (\"main.py\", 1), (\"utils\", 1), (\"helper.py\", 2)]\nfor name, level in tree:\n    print(\"  \" * level + name)", "填空缩进生成。", "tree = [(\"src\", 0), (\"main.py\", 1), (\"utils\", 1), (\"helper.py\", 2)]\nfor name, level in tree:\n    print(\"  \" * level + name)"),
    (25, "格式化输出收支报表。", "flows = [(\"Jan\", 8000, 6000), (\"Feb\", 9000, 7500)]\nprint(f\"{'Month':<6}{'Income':>10}{'Expense':>10}{'Net':>8}\")\nfor month, inc, exp in flows:\n    print(f\"{month:<6}{inc:>10,d}{exp:>10,d}{inc - exp:>8,d}\")", "填空报表格式。", "flows = [(\"Jan\", 8000, 6000), (\"Feb\", 9000, 7500)]\nprint(f\"{'Month':<6}{'Income':>10}{'Expense':>10}{'Net':>8}\")\nfor month, inc, exp in flows:\n    print(f\"{month:<6}{inc:>10,d}{exp:>10,d}{inc - exp:>8,d}\")"),
    (26, "输出居中菱形（字符）。", "n = 3\nfor i in range(1, n + 1):\n    print(f\"{'*' * (2 * i - 1):^{2 * n - 1}}\")\nfor i in range(n - 1, 0, -1):\n    print(f\"{'*' * (2 * i - 1):^{2 * n - 1}}\")", "填空居中格式。", "n = 3\nfor i in range(1, n + 1):\n    print(f\"{'*' * (2 * i - 1):^{2 * n - 1}}\")\nfor i in range(n - 1, 0, -1):\n    print(f\"{'*' * (2 * i - 1):^{2 * n - 1}}\")"),
    (27, "输出数字与平方立方对照表。", "print(f\"{'n':>3}{'sq':>6}{'cube':>8}\")\nfor n in range(1, 6):\n    print(f\"{n:>3}{n ** 2:>6}{n ** 3:>8}\")", "填空对照表格式。", "print(f\"{'n':>3}{'sq':>6}{'cube':>8}\")\nfor n in range(1, 6):\n    print(f\"{n:>3}{n ** 2:>6}{n ** 3:>8}\")"),
    (28, "格式化输出员工工时表。", "staff = [(\"Alice\", 40), (\"Bob\", 35), (\"Cara\", 42)]\nprint(f\"{'Name':<8}{'Hours':>6}{'Overtime':>10}\")\nfor name, hours in staff:\n    ot = max(0, hours - 40)\n    print(f\"{name:<8}{hours:>6}{ot:>10}\")", "填空工时表格式。", "staff = [(\"Alice\", 40), (\"Bob\", 35), (\"Cara\", 42)]\nprint(f\"{'Name':<8}{'Hours':>6}{'Overtime':>10}\")\nfor name, hours in staff:\n    ot = max(0, hours - 40)\n    print(f\"{name:<8}{hours:>6}{ot:>10}\")"),
    (29, "用格式输出字母三角形。", "for i in range(1, 6):\n    line = \"\".join(chr(64 + j) for j in range(1, i + 1))\n    print(f\"{line:^10}\")", "填空居中输出。", "for i in range(1, 6):\n    line = \"\".join(chr(64 + j) for j in range(1, i + 1))\n    print(f\"{line:^10}\")"),
    (30, "综合格式化输出统计报告。", "data = {\"total\": 120, \"passed\": 96, \"failed\": 24}\nrate = data[\"passed\"] / data[\"total\"]\nprint(f\"Total: {data['total']}\")\nprint(f\"Passed: {data['passed']} ({rate:.1%})\")\nprint(f\"Failed: {data['failed']} ({1 - rate:.1%})\")", "填空综合报告。", "data = {\"total\": 120, \"passed\": 96, \"failed\": 24}\nrate = data[\"passed\"] / data[\"total\"]\nprint(f\"Total: {data['total']}\")\nprint(f\"Passed: {data['passed']} ({rate:.1%})\")\nprint(f\"Failed: {data['failed']} ({1 - rate:.1%})\")"),
]

HARD = [
    (1, "生成任意行数的对齐表格。", "headers = [\"Name\", \"Age\", \"Score\"]\nrows = [[\"Alice\", 20, 92], [\"Bob\", 21, 88], [\"Cara\", 22, 95]]\nwidths = [max(len(str(r[i])) for r in [headers] + rows) + 2 for i in range(3)]\nline = \"+\" + \"+\".join(\"-\" * w for w in widths) + \"+\"\nprint(line)\nfor row in [headers] + rows:\n    cells = [str(v).ljust(w - 1) for v, w in zip(row, widths)]\n    print(\"|\" + \"|\".join(cells) + \"|\")\n    print(line)", "填空表格生成。", "headers = [\"Name\", \"Age\", \"Score\"]\nrows = [[\"Alice\", 20, 92], [\"Bob\", 21, 88], [\"Cara\", 22, 95]]\nwidths = [max(len(str(r[i])) for r in [headers] + rows) + 2 for i in range(3)]\nline = \"+\" + \"+\".join(\"-\" * w for w in widths) + \"+\"\nprint(line)\nfor row in [headers] + rows:\n    cells = [str(v).ljust(w - 1) for v, w in zip(row, widths)]\n    print(\"|\" + \"|\".join(cells) + \"|\")\n    print(line)"),
    (2, "绘制垂直直方图。", "data = {\"A\": 3, \"B\": 5, \"C\": 4}\nmax_h = max(data.values())\nfor level in range(max_h, 0, -1):\n    line = \"\"\n    for v in data.values():\n        line += \" # \" if v >= level else \"   \"\n    print(line)\nprint(\" \" + \" \".join(data.keys()))", "填空垂直直方图。", "data = {\"A\": 3, \"B\": 5, \"C\": 4}\nmax_h = max(data.values())\nfor level in range(max_h, 0, -1):\n    line = \"\"\n    for v in data.values():\n        line += \" # \" if v >= level else \"   \"\n    print(line)\nprint(\" \" + \" \".join(data.keys()))"),
    (3, "生成 3 月日历（模拟）。", "month = 3\ndays = 31\nstart = 2\nprint(f\"{'March 2026':^21}\")\nprint(\"Mo Tu We Th Fr Sa Su\")\nprint(\"   \" * start, end=\"\")\nfor day in range(1, days + 1):\n    print(f\"{day:>2} \", end=\"\")\n    if (day + start) % 7 == 0:\n        print()", "填空日历生成。", "month = 3\ndays = 31\nstart = 2\nprint(f\"{'March 2026':^21}\")\nprint(\"Mo Tu We Th Fr Sa Su\")\nprint(\"   \" * start, end=\"\")\nfor day in range(1, days + 1):\n    print(f\"{day:>2} \", end=\"\")\n    if (day + start) % 7 == 0:\n        print()"),
    (4, "实现两端对齐文本。", "words = \"the quick brown fox jumps\".split()\nwidth = 20\nline = \"\"\nresult = []\nfor w in words:\n    if len(line) + len(w) <= width:\n        line += w + \" \"\n    else:\n        result.append(line.strip().ljust(width))\n        line = w + \" \"\nresult.append(line.strip())\nfor l in result:\n    print(l)", "填空两端对齐。", "words = \"the quick brown fox jumps\".split()\nwidth = 20\nline = \"\"\nresult = []\nfor w in words:\n    if len(line) + len(w) <= width:\n        line += w + \" \"\n    else:\n        result.append(line.strip().ljust(width))\n        line = w + \" \"\nresult.append(line.strip())\nfor l in result:\n    print(l)"),
    (5, "输出螺旋矩阵并格式化。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nnum = 1\nwhile top <= bottom and left <= right:\n    for j in range(left, right + 1):\n        matrix[top][j] = num\n        num += 1\n    top += 1\n    for i in range(top, bottom + 1):\n        matrix[i][right] = num\n        num += 1\n    right -= 1\n    for j in range(right, left - 1, -1):\n        matrix[bottom][j] = num\n        num += 1\n    bottom -= 1\n    for i in range(bottom, top - 1, -1):\n        matrix[i][left] = num\n        num += 1\n    left += 1\nfor row in matrix:\n    print(\" \".join(f\"{v:>2}\" for v in row))", "填空螺旋与格式化。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nnum = 1\nwhile top <= bottom and left <= right:\n    for j in range(left, right + 1):\n        matrix[top][j] = num\n        num += 1\n    top += 1\n    for i in range(top, bottom + 1):\n        matrix[i][right] = num\n        num += 1\n    right -= 1\n    for j in range(right, left - 1, -1):\n        matrix[bottom][j] = num\n        num += 1\n    bottom -= 1\n    for i in range(bottom, top - 1, -1):\n        matrix[i][left] = num\n        num += 1\n    left += 1\nfor row in matrix:\n    print(\" \".join(f\"{v:>2}\" for v in row))"),
    (6, "输出十六进制转储（hexdump）。", "text = \"Hello\"\nfor i in range(0, len(text), 2):\n    chunk = text[i:i + 2]\n    hex_part = \" \".join(f\"{ord(c):02x}\" for c in chunk)\n    ascii_part = \"\".join(c if c.isprintable() else \".\" for c in chunk)\n    print(f\"{i:04x}  {hex_part:<6}  {ascii_part}\")", "填空 hexdump。", "text = \"Hello\"\nfor i in range(0, len(text), 2):\n    chunk = text[i:i + 2]\n    hex_part = \" \".join(f\"{ord(c):02x}\" for c in chunk)\n    ascii_part = \"\".join(c if c.isprintable() else \".\" for c in chunk)\n    print(f\"{i:04x}  {hex_part:<6}  {ascii_part}\")"),
    (7, "生成乘法表大表格（5x5 对齐）。", "size = 5\nprint(f\"{'x':>4}\" + \"\".join(f\"{j:>4}\" for j in range(1, size + 1)))\nfor i in range(1, size + 1):\n    print(f\"{i:>4}\" + \"\".join(f\"{i * j:>4}\" for j in range(1, size + 1)))", "填空大表格。", "size = 5\nprint(f\"{'x':>4}\" + \"\".join(f\"{j:>4}\" for j in range(1, size + 1)))\nfor i in range(1, size + 1):\n    print(f\"{i:>4}\" + \"\".join(f\"{i * j:>4}\" for j in range(1, size + 1)))"),
    (8, "输出数字菱形。", "n = 3\nfor i in range(1, n + 1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    line += \"\".join(str(j) for j in range(i - 1, 0, -1))\n    print(f\"{line:^{2 * n - 1}}\")\nfor i in range(n - 1, 0, -1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    line += \"\".join(str(j) for j in range(i - 1, 0, -1))\n    print(f\"{line:^{2 * n - 1}}\")", "填空数字菱形。", "n = 3\nfor i in range(1, n + 1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    line += \"\".join(str(j) for j in range(i - 1, 0, -1))\n    print(f\"{line:^{2 * n - 1}}\")\nfor i in range(n - 1, 0, -1):\n    line = \"\".join(str(j) for j in range(1, i + 1))\n    line += \"\".join(str(j) for j in range(i - 1, 0, -1))\n    print(f\"{line:^{2 * n - 1}}\")"),
    (9, "生成学生成绩分布统计图。", "scores = [55, 72, 88, 91, 63, 77, 85, 95, 68, 80]\nbuckets = {\"A(90+)\": 0, \"B(80+)\": 0, \"C(70+)\": 0, \"D(<70)\": 0}\nfor s in scores:\n    if s >= 90:\n        buckets[\"A(90+)\"] += 1\n    elif s >= 80:\n        buckets[\"B(80+)\"] += 1\n    elif s >= 70:\n        buckets[\"C(70+)\"] += 1\n    else:\n        buckets[\"D(<70)\"] += 1\nfor k, v in buckets.items():\n    print(f\"{k:<8}{'#' * v} ({v})\")", "填空分布统计。", "scores = [55, 72, 88, 91, 63, 77, 85, 95, 68, 80]\nbuckets = {\"A(90+)\": 0, \"B(80+)\": 0, \"C(70+)\": 0, \"D(<70)\": 0}\nfor s in scores:\n    if s >= 90:\n        buckets[\"A(90+)\"] += 1\n    elif s >= 80:\n        buckets[\"B(80+)\"] += 1\n    elif s >= 70:\n        buckets[\"C(70+)\"] += 1\n    else:\n        buckets[\"D(<70)\"] += 1\nfor k, v in buckets.items():\n    print(f\"{k:<8}{'#' * v} ({v})\")"),
    (10, "格式化输出对数表。", "import math\nprint(f\"{'n':>4}{'log10':>10}\")\nfor n in [1, 2, 5, 10, 20]:\n    print(f\"{n:>4}{math.log10(n):>10.4f}\")", "填空对数表。", "import math\nprint(f\"{'n':>4}{'log10':>10}\")\nfor n in [1, 2, 5, 10, 20]:\n    print(f\"{n:>4}{math.log10(n):>10.4f}\")"),
    (11, "生成 4x4 棋盘并格式化。", "size = 4\nfor i in range(size):\n    row = \"\"\n    for j in range(size):\n        row += \"# \" if (i + j) % 2 == 0 else \". \"\n    print(row)", "填空棋盘格式。", "size = 4\nfor i in range(size):\n    row = \"\"\n    for j in range(size):\n        row += \"# \" if (i + j) % 2 == 0 else \". \"\n    print(row)"),
    (12, "输出单词长度统计报告。", "text = \"python programming is fun and powerful\"\nwords = text.split()\nlengths = {}\nfor w in words:\n    lengths[len(w)] = lengths.get(len(w), 0) + 1\nprint(f\"{'Len':>4}{'Count':>8}\")\nfor length in sorted(lengths):\n    print(f\"{length:>4}{lengths[length]:>8}\")", "填空长度统计。", "text = \"python programming is fun and powerful\"\nwords = text.split()\nlengths = {}\nfor w in words:\n    lengths[len(w)] = lengths.get(len(w), 0) + 1\nprint(f\"{'Len':>4}{'Count':>8}\")\nfor length in sorted(lengths):\n    print(f\"{length:>4}{lengths[length]:>8}\")"),
    (13, "格式化输出斐波那契对照表。", "a, b = 0, 1\nprint(f\"{'n':>3}{'fib':>8}\")\nfor n in range(1, 11):\n    print(f\"{n:>3}{a:>8}\")\n    a, b = b, a + b", "填空斐波那契表。", "a, b = 0, 1\nprint(f\"{'n':>3}{'fib':>8}\")\nfor n in range(1, 11):\n    print(f\"{n:>3}{a:>8}\")\n    a, b = b, a + b"),
    (14, "生成 ASCII 表片段。", "print(f\"{'Char':<6}{'Dec':>5}{'Hex':>5}\")\nfor code in range(65, 75):\n    print(f\"{chr(code):<6}{code:>5}{code:>#6x}\")", "填空 ASCII 表。", "print(f\"{'Char':<6}{'Dec':>5}{'Hex':>5}\")\nfor code in range(65, 75):\n    print(f\"{chr(code):<6}{code:>5}{code:>#6x}\")"),
    (15, "输出居中多行欢迎横幅。", "lines = [\"WELCOME\", \"TO\", \"PYQUEST\"]\nwidth = 24\nborder = \"*\" * width\nprint(border)\nfor line in lines:\n    print(f\"*{line:^{width - 2}}*\")\nprint(border)", "填空横幅格式。", "lines = [\"WELCOME\", \"TO\", \"PYQUEST\"]\nwidth = 24\nborder = \"*\" * width\nprint(border)\nfor line in lines:\n    print(f\"*{line:^{width - 2}}*\")\nprint(border)"),
    (16, "格式化输出摄氏/华氏/开氏对照表。", "print(f\"{'C':>6}{'F':>8}{'K':>8}\")\nfor c in [0, 20, 37, 100]:\n    f = c * 9 / 5 + 32\n    k = c + 273.15\n    print(f\"{c:>6.1f}{f:>8.1f}{k:>8.2f}\")", "填空三单位表。", "print(f\"{'C':>6}{'F':>8}{'K':>8}\")\nfor c in [0, 20, 37, 100]:\n    f = c * 9 / 5 + 32\n    k = c + 273.15\n    print(f\"{c:>6.1f}{f:>8.1f}{k:>8.2f}\")"),
    (17, "用格式输出帕斯卡三角。", "rows = 5\ntriangle = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    for j in range(1, i):\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n    triangle.append(row)\nfor row in triangle:\n    text = \" \".join(str(v) for v in row)\n    print(f\"{text:^{rows * 4}}\")", "填空帕斯卡三角。", "rows = 5\ntriangle = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    for j in range(1, i):\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n    triangle.append(row)\nfor row in triangle:\n    text = \" \".join(str(v) for v in row)\n    print(f\"{text:^{rows * 4}}\")"),
    (18, "生成购物小票（含边框）。", "items = [(\"Apple\", 3.5, 2), (\"Milk\", 5.0, 1), (\"Bread\", 4.5, 1)]\ntotal = 0\nprint(\"-\" * 28)\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name:<8} x{qty}  {sub:>8.2f}\")\nprint(\"-\" * 28)\nprint(f\"{'TOTAL':<12}{total:>10.2f}\")\nprint(\"-\" * 28)", "填空小票边框。", "items = [(\"Apple\", 3.5, 2), (\"Milk\", 5.0, 1), (\"Bread\", 4.5, 1)]\ntotal = 0\nprint(\"-\" * 28)\nfor name, price, qty in items:\n    sub = price * qty\n    total += sub\n    print(f\"{name:<8} x{qty}  {sub:>8.2f}\")\nprint(\"-\" * 28)\nprint(f\"{'TOTAL':<12}{total:>10.2f}\")\nprint(\"-\" * 28)"),
    (19, "格式化输出秒数分解。", "total_seconds = 3725\nhours = total_seconds // 3600\nminutes = (total_seconds % 3600) // 60\nseconds = total_seconds % 60\nprint(f\"{hours:02d}:{minutes:02d}:{seconds:02d}\")\nprint(f\"{total_seconds} seconds\")", "填空时间分解。", "total_seconds = 3725\nhours = total_seconds // 3600\nminutes = (total_seconds % 3600) // 60\nseconds = total_seconds % 60\nprint(f\"{hours:02d}:{minutes:02d}:{seconds:02d}\")\nprint(f\"{total_seconds} seconds\")"),
    (20, "输出金额大写辅助表。", "amounts = [0.5, 1.25, 100.75]\nfor a in amounts:\n    print(f\"{a:>10,.2f}  ({a:>8.0f} 元)\")", "填空金额格式。", "amounts = [0.5, 1.25, 100.75]\nfor a in amounts:\n    print(f\"{a:>10,.2f}  ({a:>8.0f} 元)\")"),
    (21, "生成统计柱状图（横向 + 数值）。", "data = [(\"Python\", 9), (\"Java\", 7), (\"C\", 5)]\nmax_v = max(v for _, v in data)\nfor name, v in data:\n    bar = \"#\" * v + \".\" * (max_v - v)\n    print(f\"{name:<8}{bar} {v}\")", "填空柱状图。", "data = [(\"Python\", 9), (\"Java\", 7), (\"C\", 5)]\nmax_v = max(v for _, v in data)\nfor name, v in data:\n    bar = \"#\" * v + \".\" * (max_v - v)\n    print(f\"{name:<8}{bar} {v}\")"),
    (22, "格式化输出质数表。", "primes = []\nfor n in range(2, 40):\n    if all(n % d for d in range(2, int(n ** 0.5) + 1)):\n        primes.append(n)\nfor i in range(0, len(primes), 5):\n    print(\" \".join(f\"{p:>3}\" for p in primes[i:i + 5]))", "填空质数表。", "primes = []\nfor n in range(2, 40):\n    if all(n % d for d in range(2, int(n ** 0.5) + 1)):\n        primes.append(n)\nfor i in range(0, len(primes), 5):\n    print(\" \".join(f\"{p:>3}\" for p in primes[i:i + 5]))"),
    (23, "输出坐标平面网格点。", "for y in range(3, 0, -1):\n    row = \" \".join(f\"({x},{y})\" for x in range(1, 4))\n    print(row)\nprint(\"  \" + \" \".join(f\" x={x}\" for x in range(1, 4)))", "填空坐标网格。", "for y in range(3, 0, -1):\n    row = \" \".join(f\"({x},{y})\" for x in range(1, 4))\n    print(row)\nprint(\"  \" + \" \".join(f\" x={x}\" for x in range(1, 4)))"),
    (24, "用格式生成菱形数字表。", "n = 4\nfor i in range(1, n + 1):\n    print(\" \" * (n - i) + \"\".join(str(i) for _ in range(2 * i - 1)))\nfor i in range(n - 1, 0, -1):\n    print(\" \" * (n - i) + \"\".join(str(i) for _ in range(2 * i - 1)))", "填空数字菱形表。", "n = 4\nfor i in range(1, n + 1):\n    print(\" \" * (n - i) + \"\".join(str(i) for _ in range(2 * i - 1)))\nfor i in range(n - 1, 0, -1):\n    print(\" \" * (n - i) + \"\".join(str(i) for _ in range(2 * i - 1)))"),
    (25, "格式化输出模拟日志。", "logs = [(1, \"INFO\", \"start\"), (2, \"WARN\", \"retry\"), (3, \"ERROR\", \"fail\")]\nfor num, level, msg in logs:\n    print(f\"[{num:03d}] {level:<5} {msg}\")", "填空日志格式。", "logs = [(1, \"INFO\", \"start\"), (2, \"WARN\", \"retry\"), (3, \"ERROR\", \"fail\")]\nfor num, level, msg in logs:\n    print(f\"[{num:03d}] {level:<5} {msg}\")"),
    (26, "输出科学计数法对比表。", "print(f\"{'n':>12}{'sci':>14}\")\nfor n in [0.0001, 0.5, 12345.0, 1e6]:\n    print(f\"{n:>12.4f}{n:>14.3e}\")", "填空科学计数法。", "print(f\"{'n':>12}{'sci':>14}\")\nfor n in [0.0001, 0.5, 12345.0, 1e6]:\n    print(f\"{n:>12.4f}{n:>14.3e}\")"),
    (27, "生成分数与小数对照表。", "print(f\"{'Fraction':<10}{'Decimal':>10}\")\nfor num, den in [(1, 2), (1, 3), (2, 3), (1, 8)]:\n    print(f\"{num}/{den:<8}{num / den:>10.4f}\")", "填空分数小数表。", "print(f\"{'Fraction':<10}{'Decimal':>10}\")\nfor num, den in [(1, 2), (1, 3), (2, 3), (1, 8)]:\n    print(f\"{num}/{den:<8}{num / den:>10.4f}\")"),
    (28, "输出多语言问候横幅。", "greetings = [(\"English\", \"Hello\"), (\"中文\", \"你好\"), (\"日本語\", \"こんにちは\")]\nwidth = 26\nprint(\"*\" * width)\nfor lang, text in greetings:\n    print(f\"* {lang:<8}{text:>10} *\")\nprint(\"*\" * width)", "填空问候横幅。", "greetings = [(\"English\", \"Hello\"), (\"中文\", \"你好\"), (\"日本語\", \"こんにちは\")]\nwidth = 26\nprint(\"*\" * width)\nfor lang, text in greetings:\n    print(f\"* {lang:<8}{text:>10} *\")\nprint(\"*\" * width)"),
    (29, "格式化输出 BMI 计算表。", "print(f\"{'Height':>8}{'Weight':>8}{'BMI':>8}{'Status':>10}\")\nfor h, w in [(1.6, 50), (1.7, 65), (1.75, 80)]:\n    bmi = w / h ** 2\n    status = \"Normal\" if bmi < 24 else \"Overweight\"\n    print(f\"{h:>8.2f}{w:>8.1f}{bmi:>8.1f}{status:>10}\")", "填空 BMI 表。", "print(f\"{'Height':>8}{'Weight':>8}{'BMI':>8}{'Status':>10}\")\nfor h, w in [(1.6, 50), (1.7, 65), (1.75, 80)]:\n    bmi = w / h ** 2\n    status = \"Normal\" if bmi < 24 else \"Overweight\"\n    print(f\"{h:>8.2f}{w:>8.1f}{bmi:>8.1f}{status:>10}\")"),
    (30, "综合：格式化学生成绩报告单。", "students = [(\"Alice\", 92, 88), (\"Bob\", 78, 84)]\nprint(f\"{'Name':<8}{'Math':>6}{'English':>8}{'Avg':>8}\")\nprint(\"-\" * 30)\nfor name, math, eng in students:\n    avg = (math + eng) / 2\n    print(f\"{name:<8}{math:>6}{eng:>8}{avg:>8.1f}\")", "填空成绩报告单。", "students = [(\"Alice\", 92, 88), (\"Bob\", 78, 84)]\nprint(f\"{'Name':<8}{'Math':>6}{'English':>8}{'Avg':>8}\")\nprint(\"-\" * 30)\nfor name, math, eng in students:\n    avg = (math + eng) / 2\n    print(f\"{name:<8}{math:>6}{eng:>8}{avg:>8.1f}\")"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
