# -*- coding: utf-8 -*-
"""生成 CH06 条件语句 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH06"
TITLE = "条件语句"
OUT_DIR = "CH06_Conditionals"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "若 x 大于 3 则输出 big。", "x = 5\nif x > 3:\n    print(___)", "填 \"big\"。", "x = 5\nif x > 3:\n    print(\"big\")"),
    (2, "若 x 大于 3 输出 big，否则输出 small。", "x = 2\nif x > 3:\n    print(\"big\")\nelse:\n    print(___)", "填 \"small\"。", "x = 2\nif x > 3:\n    print(\"big\")\nelse:\n    print(\"small\")"),
    (3, "判断数字 7 的奇偶并输出。", "n = 7\nif n % 2 == 0:\n    print(\"even\")\nelse:\n    print(___)", "填 \"odd\"。", "n = 7\nif n % 2 == 0:\n    print(\"even\")\nelse:\n    print(\"odd\")"),
    (4, "判断数字 -5 是否为正数。", "n = -5\nif n > 0:\n    print(\"positive\")\nelse:\n    print(___)", "填 \"non-positive\"。", "n = -5\nif n > 0:\n    print(\"positive\")\nelse:\n    print(\"non-positive\")"),
    (5, "判断两个数是否相等。", "a = 5\nb = 5\nif a == b:\n    print(___)", "填 \"equal\"。", "a = 5\nb = 5\nif a == b:\n    print(\"equal\")"),
    (6, "判断两个数是否不相等。", "a = 5\nb = 3\nif a != b:\n    print(___)", "填 \"different\"。", "a = 5\nb = 3\nif a != b:\n    print(\"different\")"),
    (7, "判断 x 是否大于等于 10。", "x = 10\nif x >= 10:\n    print(___)", "填 \"ten or more\"。", "x = 10\nif x >= 10:\n    print(\"ten or more\")"),
    (8, "判断 x 是否小于 5。", "x = 4\nif x < 5:\n    print(___)", "填 \"less than 5\"。", "x = 4\nif x < 5:\n    print(\"less than 5\")"),
    (9, "用 and 判断是否为成年人。", "age = 20\nif age >= 18 and age < 60:\n    print(___)", "填 \"adult\"。", "age = 20\nif age >= 18 and age < 60:\n    print(\"adult\")"),
    (10, "用 or 判断是否为优秀。", "score = 95\nif score >= 90 or score == 100:\n    print(___)", "填 \"excellent\"。", "score = 95\nif score >= 90 or score == 100:\n    print(\"excellent\")"),
    (11, "用 not 判断布尔变量。", "flag = False\nif not flag:\n    print(___)", "填 \"flag is False\"。", "flag = False\nif not flag:\n    print(\"flag is False\")"),
    (12, "按分数 75 输出等级。", "score = 75\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelse:\n    grade = \"D\"\nprint(___)\n", "填 grade。", "score = 75\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelse:\n    grade = \"D\"\nprint(grade)"),
    (13, "判断 x 是否在 10 到 20 之间。", "x = 15\nif 10 < x < 20:\n    print(___)", "填 \"middle\"。", "x = 15\nif 10 < x < 20:\n    print(\"middle\")"),
    (14, "用三元表达式取较大者。", "a = 7\nb = 3\nresult = \"a\" if a > b else \"b\"\nprint(___)", "填 result。", "a = 7\nb = 3\nresult = \"a\" if a > b else \"b\"\nprint(result)"),
    (15, "用 in 判断字符是否存在。", "fruit = \"apple\"\nif \"a\" in fruit:\n    print(___)", "填 \"has a\"。", "fruit = \"apple\"\nif \"a\" in fruit:\n    print(\"has a\")"),
    (16, "判断字符串是否为空。", "s = \"\"\nif s:\n    print(\"not empty\")\nelse:\n    print(___)", "填 \"empty\"。", "s = \"\"\nif s:\n    print(\"not empty\")\nelse:\n    print(\"empty\")"),
    (17, "判断名字是否为三个字母。", "name = \"Bob\"\nif len(name) == 3:\n    print(___)", "填 \"three letters\"。", "name = \"Bob\"\nif len(name) == 3:\n    print(\"three letters\")"),
    (18, "判断数字是否为 5 的倍数。", "n = 15\nif n % 5 == 0:\n    print(___)", "填 \"multiple of 5\"。", "n = 15\nif n % 5 == 0:\n    print(\"multiple of 5\")"),
    (19, "直接判断布尔变量。", "is_ready = True\nif is_ready:\n    print(___)", "填 \"ready\"。", "is_ready = True\nif is_ready:\n    print(\"ready\")"),
    (20, "用嵌套 if 判断正且大。", "x = 6\nif x > 0:\n    if x > 5:\n        print(___)", "填 \"positive and large\"。", "x = 6\nif x > 0:\n    if x > 5:\n        print(\"positive and large\")"),
    (21, "判断单词首字母是否为 P。", "word = \"Python\"\nif word[0] == \"P\":\n    print(___)", "填 \"starts with P\"。", "word = \"Python\"\nif word[0] == \"P\":\n    print(\"starts with P\")"),
    (22, "比较两个字符串的大小。", "word = \"apple\"\nif word < \"banana\":\n    print(___)", "填 \"apple first\"。", "word = \"apple\"\nif word < \"banana\":\n    print(\"apple first\")"),
    (23, "判断数字是否为零。", "n = 0\nif n == 0:\n    print(___)", "填 \"zero\"。", "n = 0\nif n == 0:\n    print(\"zero\")"),
    (24, "用 and 组合两个条件。", "x = 4\ny = 6\nif x < y and x % 2 == 0:\n    print(___)", "填 \"even and less\"。", "x = 4\ny = 6\nif x < y and x % 2 == 0:\n    print(\"even and less\")"),
    (25, "用 elif 链判断温度。", "temp = 25\nif temp > 30:\n    weather = \"hot\"\nelif temp > 20:\n    weather = \"warm\"\nelse:\n    weather = \"cold\"\nprint(___)\n", "填 weather。", "temp = 25\nif temp > 30:\n    weather = \"hot\"\nelif temp > 20:\n    weather = \"warm\"\nelse:\n    weather = \"cold\"\nprint(weather)"),
    (26, "用 not 取反比较结果。", "x = 8\nif not (x < 5):\n    print(___)", "填 \"not small\"。", "x = 8\nif not (x < 5):\n    print(\"not small\")"),
    (27, "判断数字末位是否为 3。", "n = 23\nif n % 10 == 3:\n    print(___)", "填 \"ends with 3\"。", "n = 23\nif n % 10 == 3:\n    print(\"ends with 3\")"),
    (28, "判断数字是否在区间外。", "x = 25\nif x > 20 or x < 5:\n    print(___)", "填 \"out of range\"。", "x = 25\nif x > 20 or x < 5:\n    print(\"out of range\")"),
    (29, "判断变量是否为字符串类型。", "x = \"hi\"\nif type(x) == str:\n    print(___)", "填 \"is string\"。", "x = \"hi\"\nif type(x) == str:\n    print(\"is string\")"),
    (30, "用三元表达式判断是否及格。", "score = 85\nstatus = \"pass\" if score >= 60 else \"fail\"\nprint(___)", "填 status。", "score = 85\nstatus = \"pass\" if score >= 60 else \"fail\"\nprint(status)"),
]

SIMPLE = [
    (1, "按分数 83 输出 A-E 五档等级。", "score = 83\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelif score >= 60:\n    grade = \"D\"\nelse:\n    grade = \"E\"\nprint(f\"Grade: {grade}\")", "填空多分支判断。", "score = 83\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelif score >= 60:\n    grade = \"D\"\nelse:\n    grade = \"E\"\nprint(f\"Grade: {grade}\")"),
    (2, "统计列表中的正数、负数和零。", "nums = [3, -1, 0, 5, -2]\npos = neg = zero = 0\nfor n in nums:\n    if n > 0:\n        pos += 1\n    elif n < 0:\n        neg += 1\n    else:\n        zero += 1\nprint(f\"Positive: {pos}, Negative: {neg}, Zero: {zero}\")", "填空三路计数。", "nums = [3, -1, 0, 5, -2]\npos = neg = zero = 0\nfor n in nums:\n    if n > 0:\n        pos += 1\n    elif n < 0:\n        neg += 1\n    else:\n        zero += 1\nprint(f\"Positive: {pos}, Negative: {neg}, Zero: {zero}\")"),
    (3, "用 if-else 求两个数的最大值。", "a, b = 7, 9\nif a > b:\n    larger = a\nelse:\n    larger = b\nprint(f\"Larger: {larger}\")", "填空比较与赋值。", "a, b = 7, 9\nif a > b:\n    larger = a\nelse:\n    larger = b\nprint(f\"Larger: {larger}\")"),
    (4, "判断年份 2024 是否为闰年。", "year = 2024\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print(\"leap\")\nelse:\n    print(\"common\")", "填空闰年条件。", "year = 2024\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print(\"leap\")\nelse:\n    print(\"common\")"),
    (5, "根据月份输出天数（简化）。", "month = 2\nif month in (1, 3, 5, 7, 8, 10, 12):\n    days = 31\nelif month in (4, 6, 9, 11):\n    days = 30\nelse:\n    days = 28\nprint(f\"{month}月有{days}天\")", "填空月份分组。", "month = 2\nif month in (1, 3, 5, 7, 8, 10, 12):\n    days = 31\nelif month in (4, 6, 9, 11):\n    days = 30\nelse:\n    days = 28\nprint(f\"{month}月有{days}天\")"),
    (6, "分类字符：字母、数字或其他。", "ch = '7'\nif ch.isalpha():\n    kind = \"letter\"\nelif ch.isdigit():\n    kind = \"digit\"\nelse:\n    kind = \"other\"\nprint(f\"{ch} is {kind}\")", "填空字符分类。", "ch = '7'\nif ch.isalpha():\n    kind = \"letter\"\nelif ch.isdigit():\n    kind = \"digit\"\nelse:\n    kind = \"other\"\nprint(f\"{ch} is {kind}\")"),
    (7, "判断密码强度（含长度与字符组合）。", "password = \"abc123\"\nif len(password) < 6:\n    strength = \"weak\"\nelif password.isalpha() or password.isdigit():\n    strength = \"medium\"\nelse:\n    strength = \"strong\"\nprint(f\"Strength: {strength}\")", "填空强度判断。", "password = \"abc123\"\nif len(password) < 6:\n    strength = \"weak\"\nelif password.isalpha() or password.isdigit():\n    strength = \"medium\"\nelse:\n    strength = \"strong\"\nprint(f\"Strength: {strength}\")"),
    (8, "根据温度输出天气提示。", "temp = 12\nif temp >= 30:\n    weather = \"hot\"\nelif temp >= 15:\n    weather = \"mild\"\nelif temp >= 0:\n    weather = \"cool\"\nelse:\n    weather = \"freezing\"\nprint(weather)", "填空温度分档。", "temp = 12\nif temp >= 30:\n    weather = \"hot\"\nelif temp >= 15:\n    weather = \"mild\"\nelif temp >= 0:\n    weather = \"cool\"\nelse:\n    weather = \"freezing\"\nprint(weather)"),
    (9, "成绩评级并附加评语。", "score = 88\nif score >= 90:\n    comment = \"excellent\"\nelif score >= 80:\n    comment = \"good\"\nelif score >= 70:\n    comment = \"average\"\nelse:\n    comment = \"needs work\"\nprint(f\"Score {score}: {comment}\")", "填空评语分支。", "score = 88\nif score >= 90:\n    comment = \"excellent\"\nelif score >= 80:\n    comment = \"good\"\nelif score >= 70:\n    comment = \"average\"\nelse:\n    comment = \"needs work\"\nprint(f\"Score {score}: {comment}\")"),
    (10, "石头剪刀布模拟（固定出招）。", "player = \"rock\"\ncomputer = \"scissors\"\nif player == computer:\n    result = \"draw\"\nelif (player == \"rock\" and computer == \"scissors\") or \\\n     (player == \"scissors\" and computer == \"paper\") or \\\n     (player == \"paper\" and computer == \"rock\"):\n    result = \"win\"\nelse:\n    result = \"lose\"\nprint(result)", "填空胜负判断。", "player = \"rock\"\ncomputer = \"scissors\"\nif player == computer:\n    result = \"draw\"\nelif (player == \"rock\" and computer == \"scissors\") or \\\n     (player == \"scissors\" and computer == \"paper\") or \\\n     (player == \"paper\" and computer == \"rock\"):\n    result = \"win\"\nelse:\n    result = \"lose\"\nprint(result)"),
    (11, "判断三边能否构成三角形。", "a, b, c = 3, 4, 5\nif a + b > c and a + c > b and b + c > a:\n    print(\"valid triangle\")\nelse:\n    print(\"invalid triangle\")", "填空三角不等式。", "a, b, c = 3, 4, 5\nif a + b > c and a + c > b and b + c > a:\n    print(\"valid triangle\")\nelse:\n    print(\"invalid triangle\")"),
    (12, "用 if-elif 实现简易四则计算器。", "op = \"+\"\na, b = 8, 3\nif op == \"+\":\n    result = a + b\nelif op == \"-\":\n    result = a - b\nelif op == \"*\":\n    result = a * b\nelse:\n    result = a / b\nprint(f\"{a} {op} {b} = {result}\")", "填空运算分发。", "op = \"+\"\na, b = 8, 3\nif op == \"+\":\n    result = a + b\nelif op == \"-\":\n    result = a - b\nelif op == \"*\":\n    result = a * b\nelse:\n    result = a / b\nprint(f\"{a} {op} {b} = {result}\")"),
    (13, "统计及格与不及格人数。", "scores = [55, 72, 88, 45, 90]\npassed = 0\nfor s in scores:\n    if s >= 60:\n        passed += 1\nfailed = len(scores) - passed\nprint(f\"Passed: {passed}, Failed: {failed}\")", "填空计数。", "scores = [55, 72, 88, 45, 90]\npassed = 0\nfor s in scores:\n    if s >= 60:\n        passed += 1\nfailed = len(scores) - passed\nprint(f\"Passed: {passed}, Failed: {failed}\")"),
    (14, "根据年龄判断购票类型。", "age = 65\nif age < 6:\n    ticket = \"free\"\nelif age < 18:\n    ticket = \"child\"\nelif age < 60:\n    ticket = \"adult\"\nelse:\n    ticket = \"senior\"\nprint(f\"Ticket: {ticket}\")", "填空年龄分档。", "age = 65\nif age < 6:\n    ticket = \"free\"\nelif age < 18:\n    ticket = \"child\"\nelif age < 60:\n    ticket = \"adult\"\nelse:\n    ticket = \"senior\"\nprint(f\"Ticket: {ticket}\")"),
    (15, "实现符号函数 sign。", "def sign(n):\n    if n > 0:\n        return 1\n    elif n < 0:\n        return -1\n    else:\n        return 0\nfor n in [-3, 0, 4]:\n    print(n, sign(n))", "填空三分支函数。", "def sign(n):\n    if n > 0:\n        return 1\n    elif n < 0:\n        return -1\n    else:\n        return 0\nfor n in [-3, 0, 4]:\n    print(n, sign(n))"),
    (16, "判断字符串是否为回文。", "word = \"radar\"\nif word == word[::-1]:\n    print(\"palindrome\")\nelse:\n    print(\"not palindrome\")", "填空反转比较。", "word = \"radar\"\nif word == word[::-1]:\n    print(\"palindrome\")\nelse:\n    print(\"not palindrome\")"),
    (17, "判断 17 是否为质数。", "n = 17\nis_prime = True\nif n < 2:\n    is_prime = False\nelse:\n    for d in range(2, n):\n        if n % d == 0:\n            is_prime = False\n            break\nprint(f\"{n} is prime: {is_prime}\")", "填空质数判断。", "n = 17\nis_prime = True\nif n < 2:\n    is_prime = False\nelse:\n    for d in range(2, n):\n        if n % d == 0:\n            is_prime = False\n            break\nprint(f\"{n} is prime: {is_prime}\")"),
    (18, "数字转星期名称。", "day = 3\nif day == 1:\n    name = \"Monday\"\nelif day == 2:\n    name = \"Tuesday\"\nelif day == 3:\n    name = \"Wednesday\"\nelif day == 4:\n    name = \"Thursday\"\nelif day == 5:\n    name = \"Friday\"\nelif day == 6:\n    name = \"Saturday\"\nelse:\n    name = \"Sunday\"\nprint(name)", "填空星期映射。", "day = 3\nif day == 1:\n    name = \"Monday\"\nelif day == 2:\n    name = \"Tuesday\"\nelif day == 3:\n    name = \"Wednesday\"\nelif day == 4:\n    name = \"Thursday\"\nelif day == 5:\n    name = \"Friday\"\nelif day == 6:\n    name = \"Saturday\"\nelse:\n    name = \"Sunday\"\nprint(name)"),
    (19, "计算两数的绝对差。", "a, b = 10, 3\nif a > b:\n    diff = a - b\nelse:\n    diff = b - a\nprint(f\"Absolute diff: {diff}\")", "填空绝对差。", "a, b = 10, 3\nif a > b:\n    diff = a - b\nelse:\n    diff = b - a\nprint(f\"Absolute diff: {diff}\")"),
    (20, "根据总价计算折扣。", "total = 150\nif total >= 200:\n    discount = 0.2\nelif total >= 100:\n    discount = 0.1\nelse:\n    discount = 0\nfinal = total * (1 - discount)\nprint(f\"Final: {final}\")", "填空折扣档位。", "total = 150\nif total >= 200:\n    discount = 0.2\nelif total >= 100:\n    discount = 0.1\nelse:\n    discount = 0\nfinal = total * (1 - discount)\nprint(f\"Final: {final}\")"),
    (21, "根据身高体重计算 BMI 分类。", "bmi = 26.5\nif bmi < 18.5:\n    category = \"underweight\"\nelif bmi < 24:\n    category = \"normal\"\nelif bmi < 28:\n    category = \"overweight\"\nelse:\n    category = \"obese\"\nprint(f\"BMI {bmi}: {category}\")", "填空 BMI 分档。", "bmi = 26.5\nif bmi < 18.5:\n    category = \"underweight\"\nelif bmi < 24:\n    category = \"normal\"\nelif bmi < 28:\n    category = \"overweight\"\nelse:\n    category = \"obese\"\nprint(f\"BMI {bmi}: {category}\")"),
    (22, "判断数字所在区间并输出。", "x = 42\nif x < 0:\n    zone = \"negative\"\nelif x <= 10:\n    zone = \"0-10\"\nelif x <= 50:\n    zone = \"11-50\"\nelse:\n    zone = \"50+\"\nprint(f\"{x} in {zone}\")", "填空区间判断。", "x = 42\nif x < 0:\n    zone = \"negative\"\nelif x <= 10:\n    zone = \"0-10\"\nelif x <= 50:\n    zone = \"11-50\"\nelse:\n    zone = \"50+\"\nprint(f\"{x} in {zone}\")"),
    (23, "判断两个字符串是否互为反转。", "a = \"abc\"\nb = \"cba\"\nif a == b[::-1]:\n    print(\"reversed\")\nelse:\n    print(\"not reversed\")", "填空反转比较。", "a = \"abc\"\nb = \"cba\"\nif a == b[::-1]:\n    print(\"reversed\")\nelse:\n    print(\"not reversed\")"),
    (24, "找出三个数中的最大值。", "a, b, c = 3, 9, 5\nif a >= b and a >= c:\n    maximum = a\nelif b >= a and b >= c:\n    maximum = b\nelse:\n    maximum = c\nprint(f\"Max: {maximum}\")", "填空三数比较。", "a, b, c = 3, 9, 5\nif a >= b and a >= c:\n    maximum = a\nelif b >= a and b >= c:\n    maximum = b\nelse:\n    maximum = c\nprint(f\"Max: {maximum}\")"),
    (25, "判断数字是否为完全平方数。", "n = 81\nroot = int(n ** 0.5)\nif root * root == n:\n    print(\"perfect square\")\nelse:\n    print(\"not perfect square\")", "填空开方判断。", "n = 81\nroot = int(n ** 0.5)\nif root * root == n:\n    print(\"perfect square\")\nelse:\n    print(\"not perfect square\")"),
    (26, "根据分数判断是否需补考。", "score = 58\nif score >= 60:\n    result = \"pass\"\nelif score >= 50:\n    result = \"makeup\"\nelse:\n    result = \"fail\"\nprint(f\"Result: {result}\")", "填空补考判断。", "score = 58\nif score >= 60:\n    result = \"pass\"\nelif score >= 50:\n    result = \"makeup\"\nelse:\n    result = \"fail\"\nprint(f\"Result: {result}\")"),
    (27, "判断年份是否为本世纪。", "year = 2026\nif 2000 <= year < 2100:\n    print(\"21st century\")\nelse:\n    print(\"other century\")", "填空世纪判断。", "year = 2026\nif 2000 <= year < 2100:\n    print(\"21st century\")\nelse:\n    print(\"other century\")"),
    (28, "根据登录状态输出提示。", "logged_in = True\nrole = \"admin\"\nif logged_in and role == \"admin\":\n    print(\"Welcome, admin!\")\nelif logged_in:\n    print(\"Welcome, user!\")\nelse:\n    print(\"Please log in\")", "填空登录判断。", "logged_in = True\nrole = \"admin\"\nif logged_in and role == \"admin\":\n    print(\"Welcome, admin!\")\nelif logged_in:\n    print(\"Welcome, user!\")\nelse:\n    print(\"Please log in\")"),
    (29, "判断文件名是否为 Python 文件。", "filename = \"main.py\"\nif filename.endswith(\".py\"):\n    print(\"Python file\")\nelse:\n    print(\"other file\")", "填空后缀判断。", "filename = \"main.py\"\nif filename.endswith(\".py\"):\n    print(\"Python file\")\nelse:\n    print(\"other file\")"),
    (30, "综合：判断整数奇偶并输出说明。", "n = 14\nif n % 2 == 0:\n    desc = \"even number\"\nelse:\n    desc = \"odd number\"\nprint(f\"{n} is an {desc}\")", "填空奇偶说明。", "n = 14\nif n % 2 == 0:\n    desc = \"even number\"\nelse:\n    desc = \"odd number\"\nprint(f\"{n} is an {desc}\")"),
]

MEDIUM = [
    (1, "嵌套条件：判断成绩等级并给评语。", "score = 86\nif score >= 90:\n    print(\"Excellent!\")\nelse:\n    if score >= 80:\n        print(\"Good job\")\n    else:\n        if score >= 70:\n            print(\"Keep trying\")\n        else:\n            print(\"Needs work\")", "填空嵌套条件。", "score = 86\nif score >= 90:\n    print(\"Excellent!\")\nelse:\n    if score >= 80:\n        print(\"Good job\")\n    else:\n        if score >= 70:\n            print(\"Keep trying\")\n        else:\n            print(\"Needs work\")"),
    (2, "判断三条边构成何种三角形。", "a, b, c = 3, 4, 5\nif a == b == c:\n    kind = \"equilateral\"\nelif a == b or b == c or a == c:\n    kind = \"isosceles\"\nelif a * a + b * b == c * c or a * a + c * c == b * b or b * b + c * c == a * a:\n    kind = \"right\"\nelse:\n    kind = \"scalene\"\nprint(kind)", "填空三角形分类。", "a, b, c = 3, 4, 5\nif a == b == c:\n    kind = \"equilateral\"\nelif a == b or b == c or a == c:\n    kind = \"isosceles\"\nelif a * a + b * b == c * c or a * a + c * c == b * b or b * b + c * c == a * a:\n    kind = \"right\"\nelse:\n    kind = \"scalene\"\nprint(kind)"),
    (3, "根据日期判断季节。", "month = 7\nif month in (3, 4, 5):\n    season = \"spring\"\nelif month in (6, 7, 8):\n    season = \"summer\"\nelif month in (9, 10, 11):\n    season = \"autumn\"\nelse:\n    season = \"winter\"\nprint(season)", "填空季节映射。", "month = 7\nif month in (3, 4, 5):\n    season = \"spring\"\nelif month in (6, 7, 8):\n    season = \"summer\"\nelif month in (9, 10, 11):\n    season = \"autumn\"\nelse:\n    season = \"winter\"\nprint(season)"),
    (4, "模拟自动售货机（多商品选择）。", "item = \"cola\"\nprices = {\"water\": 2, \"cola\": 3, \"juice\": 5}\nif item in prices:\n    print(f\"Price: {prices[item]}\")\nelse:\n    print(\"Item not found\")", "填空售货机逻辑。", "item = \"cola\"\nprices = {\"water\": 2, \"cola\": 3, \"juice\": 5}\nif item in prices:\n    print(f\"Price: {prices[item]}\")\nelse:\n    print(\"Item not found\")"),
    (5, "判断字符串包含哪些字符类型。", "text = \"Py3!\"\nhas_letter = any(c.isalpha() for c in text)\nhas_digit = any(c.isdigit() for c in text)\nhas_symbol = any(not c.isalnum() for c in text)\nif has_letter and has_digit and has_symbol:\n    print(\"all types\")\nelif has_letter and has_digit:\n    print(\"letters and digits\")\nelif has_letter:\n    print(\"letters only\")\nelse:\n    print(\"other\")", "填空字符类型组合判断。", "text = \"Py3!\"\nhas_letter = any(c.isalpha() for c in text)\nhas_digit = any(c.isdigit() for c in text)\nhas_symbol = any(not c.isalnum() for c in text)\nif has_letter and has_digit and has_symbol:\n    print(\"all types\")\nelif has_letter and has_digit:\n    print(\"letters and digits\")\nelif has_letter:\n    print(\"letters only\")\nelse:\n    print(\"other\")"),
    (6, "判断成绩等级分布并输出统计。", "scores = [55, 72, 88, 91, 63]\ncounts = {\"A\": 0, \"B\": 0, \"C\": 0, \"D\": 0, \"F\": 0}\nfor s in scores:\n    if s >= 90:\n        counts[\"A\"] += 1\n    elif s >= 80:\n        counts[\"B\"] += 1\n    elif s >= 70:\n        counts[\"C\"] += 1\n    elif s >= 60:\n        counts[\"D\"] += 1\n    else:\n        counts[\"F\"] += 1\nprint(counts)", "填空等级统计。", "scores = [55, 72, 88, 91, 63]\ncounts = {\"A\": 0, \"B\": 0, \"C\": 0, \"D\": 0, \"F\": 0}\nfor s in scores:\n    if s >= 90:\n        counts[\"A\"] += 1\n    elif s >= 80:\n        counts[\"B\"] += 1\n    elif s >= 70:\n        counts[\"C\"] += 1\n    elif s >= 60:\n        counts[\"D\"] += 1\n    else:\n        counts[\"F\"] += 1\nprint(counts)"),
    (7, "判断两个字符串是否为变位词（简化）。", "a = \"listen\"\nb = \"silent\"\nif sorted(a) == sorted(b):\n    print(\"anagram\")\nelse:\n    print(\"not anagram\")", "填空排序比较。", "a = \"listen\"\nb = \"silent\"\nif sorted(a) == sorted(b):\n    print(\"anagram\")\nelse:\n    print(\"not anagram\")"),
    (8, "判断数组是否严格递增。", "nums = [1, 3, 5, 7]\nincreasing = True\nfor i in range(1, len(nums)):\n    if nums[i] <= nums[i - 1]:\n        increasing = False\n        break\nif increasing:\n    print(\"strictly increasing\")\nelse:\n    print(\"not increasing\")", "填空递增判断。", "nums = [1, 3, 5, 7]\nincreasing = True\nfor i in range(1, len(nums)):\n    if nums[i] <= nums[i - 1]:\n        increasing = False\n        break\nif increasing:\n    print(\"strictly increasing\")\nelse:\n    print(\"not increasing\")"),
    (9, "模拟优惠券使用（条件组合）。", "total = 120\nhas_coupon = True\nif total >= 100 and has_coupon:\n    final = total * 0.8\nelif total >= 100:\n    final = total * 0.9\nelse:\n    final = total\nprint(f\"Final: {final}\")", "填空优惠组合。", "total = 120\nhas_coupon = True\nif total >= 100 and has_coupon:\n    final = total * 0.8\nelif total >= 100:\n    final = total * 0.9\nelse:\n    final = total\nprint(f\"Final: {final}\")"),
    (10, "判断数字属于哪个数集（自然/整数/实数）。", "n = 7\nif n > 0 and n == int(n):\n    print(\"natural number\")\nelif n == int(n):\n    print(\"integer\")\nelse:\n    print(\"real number\")", "填空数集判断。", "n = 7\nif n > 0 and n == int(n):\n    print(\"natural number\")\nelif n == int(n):\n    print(\"integer\")\nelse:\n    print(\"real number\")"),
    (11, "根据行驶时间判断是否超时。", "planned = 120\nactual = 135\nif actual <= planned:\n    print(\"on time\")\nelif actual <= planned + 20:\n    print(\"slightly late\")\nelse:\n    print(\"very late\")", "填空超时判断。", "planned = 120\nactual = 135\nif actual <= planned:\n    print(\"on time\")\nelif actual <= planned + 20:\n    print(\"slightly late\")\nelse:\n    print(\"very late\")"),
    (12, "判断密码是否安全（多规则）。", "pwd = \"Abcdef1\"\nif len(pwd) < 8:\n    print(\"too short\")\nelif not any(c.isupper() for c in pwd):\n    print(\"no uppercase\")\nelif not any(c.isdigit() for c in pwd):\n    print(\"no digit\")\nelse:\n    print(\"secure\")", "填空多规则判断。", "pwd = \"Abcdef1\"\nif len(pwd) < 8:\n    print(\"too short\")\nelif not any(c.isupper() for c in pwd):\n    print(\"no uppercase\")\nelif not any(c.isdigit() for c in pwd):\n    print(\"no digit\")\nelse:\n    print(\"secure\")"),
    (13, "判断三个数是否构成勾股数。", "a, b, c = 6, 8, 10\nif a * a + b * b == c * c:\n    print(\"Pythagorean triple\")\nelse:\n    print(\"not a triple\")", "填空勾股判断。", "a, b, c = 6, 8, 10\nif a * a + b * b == c * c:\n    print(\"Pythagorean triple\")\nelse:\n    print(\"not a triple\")"),
    (14, "根据消费金额返回会员等级。", "spent = 850\nif spent >= 1000:\n    level = \"gold\"\nelif spent >= 500:\n    level = \"silver\"\nelif spent >= 200:\n    level = \"bronze\"\nelse:\n    level = \"new\"\nprint(f\"Level: {level}\")", "填空会员等级。", "spent = 850\nif spent >= 1000:\n    level = \"gold\"\nelif spent >= 500:\n    level = \"silver\"\nelif spent >= 200:\n    level = \"bronze\"\nelse:\n    level = \"new\"\nprint(f\"Level: {level}\")"),
    (15, "判断字符串括号是否配对（简化）。", "s = \"(a+b)\"\nif s.count(\"(\") == s.count(\")\"):\n    print(\"balanced\")\nelse:\n    print(\"unbalanced\")", "填空括号计数。", "s = \"(a+b)\"\nif s.count(\"(\") == s.count(\")\"):\n    print(\"balanced\")\nelse:\n    print(\"unbalanced\")"),
    (16, "判断一个数是否为快乐数前驱（简化）。", "n = 19\nseen = set()\nwhile n != 1 and n not in seen:\n    seen.add(n)\n    n = sum(int(d) ** 2 for d in str(n))\nif n == 1:\n    print(\"happy\")\nelse:\n    print(\"unhappy\")", "填空快乐数判断。", "n = 19\nseen = set()\nwhile n != 1 and n not in seen:\n    seen.add(n)\n    n = sum(int(d) ** 2 for d in str(n))\nif n == 1:\n    print(\"happy\")\nelse:\n    print(\"unhappy\")"),
    (17, "根据分数段输出不同提示并统计。", "score = 93\nif score == 100:\n    print(\"Perfect!\")\nelif score >= 90:\n    print(\"Excellent!\")\nelif score >= 80:\n    print(\"Great!\")\nelif score >= 70:\n    print(\"Good!\")\nelse:\n    print(\"Keep working!\")", "填空分数提示。", "score = 93\nif score == 100:\n    print(\"Perfect!\")\nelif score >= 90:\n    print(\"Excellent!\")\nelif score >= 80:\n    print(\"Great!\")\nelif score >= 70:\n    print(\"Good!\")\nelse:\n    print(\"Keep working!\")"),
    (18, "判断两个数是否同号。", "a, b = -3, -7\nif a > 0 and b > 0:\n    print(\"both positive\")\nelif a < 0 and b < 0:\n    print(\"both negative\")\nelse:\n    print(\"opposite signs\")", "填空同号判断。", "a, b = -3, -7\nif a > 0 and b > 0:\n    print(\"both positive\")\nelif a < 0 and b < 0:\n    print(\"both negative\")\nelse:\n    print(\"opposite signs\")"),
    (19, "判断数字是否为偶数且为平方数。", "n = 16\nif n % 2 == 0 and int(n ** 0.5) ** 2 == n:\n    print(\"even square\")\nelif n % 2 == 0:\n    print(\"even only\")\nelif int(n ** 0.5) ** 2 == n:\n    print(\"square only\")\nelse:\n    print(\"neither\")", "填空复合判断。", "n = 16\nif n % 2 == 0 and int(n ** 0.5) ** 2 == n:\n    print(\"even square\")\nelif n % 2 == 0:\n    print(\"even only\")\nelif int(n ** 0.5) ** 2 == n:\n    print(\"square only\")\nelse:\n    print(\"neither\")"),
    (20, "模拟考试结果判定（含补考）。", "score = 45\nif score >= 60:\n    print(\"Passed\")\nelif score >= 50:\n    print(\"Makeup exam\")\nelif score >= 40:\n    print(\"Retake course\")\nelse:\n    print(\"Failed\")", "填空考试判定。", "score = 45\nif score >= 60:\n    print(\"Passed\")\nelif score >= 50:\n    print(\"Makeup exam\")\nelif score >= 40:\n    print(\"Retake course\")\nelse:\n    print(\"Failed\")"),
    (21, "判断字符串首尾字符是否相同。", "word = \"level\"\nif word[0] == word[-1]:\n    print(\"same ends\")\nelse:\n    print(\"different ends\")", "填空首尾判断。", "word = \"level\"\nif word[0] == word[-1]:\n    print(\"same ends\")\nelse:\n    print(\"different ends\")"),
    (22, "根据库存判断订单是否可发货。", "stock = 5\nordered = 8\nif ordered <= stock:\n    print(\"shipped\")\nelif ordered <= stock * 2:\n    print(\"partial shipment\")\nelse:\n    print(\"out of stock\")", "填空库存判断。", "stock = 5\nordered = 8\nif ordered <= stock:\n    print(\"shipped\")\nelif ordered <= stock * 2:\n    print(\"partial shipment\")\nelse:\n    print(\"out of stock\")"),
    (23, "判断数字是否为 2 的幂。", "n = 32\nif n > 0 and (n & (n - 1)) == 0:\n    print(\"power of two\")\nelse:\n    print(\"not power of two\")", "填空位运算判断。", "n = 32\nif n > 0 and (n & (n - 1)) == 0:\n    print(\"power of two\")\nelse:\n    print(\"not power of two\")"),
    (24, "根据成绩计算奖学金等级。", "score = 92\nif score >= 95:\n    scholarship = \"full\"\nelif score >= 90:\n    scholarship = \"half\"\nelif score >= 85:\n    scholarship = \"quarter\"\nelse:\n    scholarship = \"none\"\nprint(f\"Scholarship: {scholarship}\")", "填空奖学金判断。", "score = 92\nif score >= 95:\n    scholarship = \"full\"\nelif score >= 90:\n    scholarship = \"half\"\nelif score >= 85:\n    scholarship = \"quarter\"\nelse:\n    scholarship = \"none\"\nprint(f\"Scholarship: {scholarship}\")"),
    (25, "判断时间段并输出问候。", "hour = 9\nif hour < 12:\n    greeting = \"Good morning\"\nelif hour < 18:\n    greeting = \"Good afternoon\"\nelse:\n    greeting = \"Good evening\"\nprint(greeting)", "填空时段问候。", "hour = 9\nif hour < 12:\n    greeting = \"Good morning\"\nelif hour < 18:\n    greeting = \"Good afternoon\"\nelse:\n    greeting = \"Good evening\"\nprint(greeting)"),
    (26, "判断字符串是否以元音开头。", "word = \"apple\"\nif word[0].lower() in \"aeiou\":\n    print(\"vowel start\")\nelse:\n    print(\"consonant start\")", "填空元音判断。", "word = \"apple\"\nif word[0].lower() in \"aeiou\":\n    print(\"vowel start\")\nelse:\n    print(\"consonant start\")"),
    (27, "判断三个点是否共线（简化）。", "x1, y1, x2, y2, x3, y3 = 0, 0, 1, 1, 2, 2\nif (y2 - y1) * (x3 - x1) == (y3 - y1) * (x2 - x1):\n    print(\"collinear\")\nelse:\n    print(\"not collinear\")", "填空共线判断。", "x1, y1, x2, y2, x3, y3 = 0, 0, 1, 1, 2, 2\nif (y2 - y1) * (x3 - x1) == (y3 - y1) * (x2 - x1):\n    print(\"collinear\")\nelse:\n    print(\"not collinear\")"),
    (28, "判断版本号大小（简化）。", "v1 = \"1.2\"\nv2 = \"1.10\"\nif int(v1.split(\".\")[1]) > int(v2.split(\".\")[1]):\n    print(\"v1 newer\")\nelif int(v1.split(\".\")[1]) < int(v2.split(\".\")[1]):\n    print(\"v2 newer\")\nelse:\n    print(\"same\")", "填空版本比较。", "v1 = \"1.2\"\nv2 = \"1.10\"\nif int(v1.split(\".\")[1]) > int(v2.split(\".\")[1]):\n    print(\"v1 newer\")\nelif int(v1.split(\".\")[1]) < int(v2.split(\".\")[1]):\n    print(\"v2 newer\")\nelse:\n    print(\"same\")"),
    (29, "综合：判断并输出多个数的特性。", "nums = [4, 7, 9, 10]\nfor n in nums:\n    features = []\n    if n % 2 == 0:\n        features.append(\"even\")\n    else:\n        features.append(\"odd\")\n    if int(n ** 0.5) ** 2 == n:\n        features.append(\"square\")\n    print(f\"{n}: {', '.join(features)}\")", "填空特性收集。", "nums = [4, 7, 9, 10]\nfor n in nums:\n    features = []\n    if n % 2 == 0:\n        features.append(\"even\")\n    else:\n        features.append(\"odd\")\n    if int(n ** 0.5) ** 2 == n:\n        features.append(\"square\")\n    print(f\"{n}: {', '.join(features)}\")"),
    (30, "模拟抽奖（多档中奖）。", "ticket = 88\nif ticket == 100:\n    prize = \"grand\"\nelif ticket >= 90:\n    prize = \"first\"\nelif ticket >= 80:\n    prize = \"second\"\nelif ticket >= 60:\n    prize = \"third\"\nelse:\n    prize = \"none\"\nprint(f\"Prize: {prize}\")", "填空抽奖分档。", "ticket = 88\nif ticket == 100:\n    prize = \"grand\"\nelif ticket >= 90:\n    prize = \"first\"\nelif ticket >= 80:\n    prize = \"second\"\nelif ticket >= 60:\n    prize = \"third\"\nelse:\n    prize = \"none\"\nprint(f\"Prize: {prize}\")"),
]

HARD = [
    (1, "用条件语句求三个数的最大值与最小值。", "a, b, c = 12, 7, 19\nmaximum = a\nminimum = a\nif b > maximum:\n    maximum = b\nif c > maximum:\n    maximum = c\nif b < minimum:\n    minimum = b\nif c < minimum:\n    minimum = c\nprint(f\"Max: {maximum}, Min: {minimum}\")", "填空比较更新。", "a, b, c = 12, 7, 19\nmaximum = a\nminimum = a\nif b > maximum:\n    maximum = b\nif c > maximum:\n    maximum = c\nif b < minimum:\n    minimum = b\nif c < minimum:\n    minimum = c\nprint(f\"Max: {maximum}, Min: {minimum}\")"),
    (2, "判断年份并输出完整描述。", "year = 2000\nif year % 400 == 0:\n    print(f\"{year}: leap (divisible by 400)\")\nelif year % 100 == 0:\n    print(f\"{year}: common (century)\")\nelif year % 4 == 0:\n    print(f\"{year}: leap\")\nelse:\n    print(f\"{year}: common\")", "填空闰年全判定。", "year = 2000\nif year % 400 == 0:\n    print(f\"{year}: leap (divisible by 400)\")\nelif year % 100 == 0:\n    print(f\"{year}: common (century)\")\nelif year % 4 == 0:\n    print(f\"{year}: leap\")\nelse:\n    print(f\"{year}: common\")"),
    (3, "实现分数化简（求最大公约数后约分）。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\nnum, den = 12, 18\ng = gcd(num, den)\nprint(f\"{num}/{den} = {num // g}/{den // g}\")", "填空约分。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\nnum, den = 12, 18\ng = gcd(num, den)\nprint(f\"{num}/{den} = {num // g}/{den // g}\")"),
    (4, "根据成绩列表输出统计报告。", "scores = [88, 92, 76, 95, 84, 57]\npassed = [s for s in scores if s >= 60]\nfailed = [s for s in scores if s < 60]\nprint(f\"Passed: {len(passed)}, Failed: {len(failed)}\")\nprint(f\"Highest: {max(scores)}, Lowest: {min(scores)}\")\nprint(f\"Average: {sum(scores) / len(scores):.1f}\")", "填空成绩报告。", "scores = [88, 92, 76, 95, 84, 57]\npassed = [s for s in scores if s >= 60]\nfailed = [s for s in scores if s < 60]\nprint(f\"Passed: {len(passed)}, Failed: {len(failed)}\")\nprint(f\"Highest: {max(scores)}, Lowest: {min(scores)}\")\nprint(f\"Average: {sum(scores) / len(scores):.1f}\")"),
    (5, "判断是否为回文数（数字反转法）。", "n = 121\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif rev == n:\n    print(f\"{n} is palindrome\")\nelse:\n    print(f\"{n} is not palindrome\")", "填空反转判断。", "n = 121\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif rev == n:\n    print(f\"{n} is palindrome\")\nelse:\n    print(f\"{n} is not palindrome\")"),
    (6, "计算个人所得税（阶梯税率）。", "income = 8000\nif income <= 3000:\n    tax = income * 0.03\nelif income <= 12000:\n    tax = 3000 * 0.03 + (income - 3000) * 0.1\nelif income <= 25000:\n    tax = 3000 * 0.03 + 9000 * 0.1 + (income - 12000) * 0.2\nelse:\n    tax = 3000 * 0.03 + 9000 * 0.1 + 13000 * 0.2 + (income - 25000) * 0.25\nprint(f\"Tax: {tax:.2f}\")", "填空阶梯税。", "income = 8000\nif income <= 3000:\n    tax = income * 0.03\nelif income <= 12000:\n    tax = 3000 * 0.03 + (income - 3000) * 0.1\nelif income <= 25000:\n    tax = 3000 * 0.03 + 9000 * 0.1 + (income - 12000) * 0.2\nelse:\n    tax = 3000 * 0.03 + 9000 * 0.1 + 13000 * 0.2 + (income - 25000) * 0.25\nprint(f\"Tax: {tax:.2f}\")"),
    (7, "用条件实现二分查找判定过程。", "nums = [1, 3, 5, 7, 9]\ntarget = 7\nlow, high = 0, len(nums) - 1\nfound = False\nwhile low <= high:\n    mid = (low + high) // 2\n    if nums[mid] == target:\n        found = True\n        break\n    elif nums[mid] < target:\n        low = mid + 1\n    else:\n        high = mid - 1\nif found:\n    print(f\"Found {target} at index {mid}\")\nelse:\n    print(f\"{target} not found\")", "填空二分条件。", "nums = [1, 3, 5, 7, 9]\ntarget = 7\nlow, high = 0, len(nums) - 1\nfound = False\nwhile low <= high:\n    mid = (low + high) // 2\n    if nums[mid] == target:\n        found = True\n        break\n    elif nums[mid] < target:\n        low = mid + 1\n    else:\n        high = mid - 1\nif found:\n    print(f\"Found {target} at index {mid}\")\nelse:\n    print(f\"{target} not found\")"),
    (8, "判断字符串是否为合法的变量名。", "name = \"my_var1\"\nif not name or name[0].isdigit():\n    print(\"invalid\")\nelif not all(c.isalnum() or c == \"_\" for c in name):\n    print(\"invalid\")\nelif name in (\"if\", \"for\", \"while\"):\n    print(\"keyword\")\nelse:\n    print(\"valid\")", "填空变量名判断。", "name = \"my_var1\"\nif not name or name[0].isdigit():\n    print(\"invalid\")\nelif not all(c.isalnum() or c == \"_\" for c in name):\n    print(\"invalid\")\nelif name in (\"if\", \"for\", \"while\"):\n    print(\"keyword\")\nelse:\n    print(\"valid\")"),
    (9, "根据三边判断三角形并计算面积（海伦公式）。", "a, b, c = 5, 12, 13\nif a + b > c and a + c > b and b + c > a:\n    s = (a + b + c) / 2\n    area = (s * (s - a) * (s - b) * (s - c)) ** 0.5\n    print(f\"Area: {area:.2f}\")\nelse:\n    print(\"Invalid triangle\")", "填空海伦公式。", "a, b, c = 5, 12, 13\nif a + b > c and a + c > b and b + c > a:\n    s = (a + b + c) / 2\n    area = (s * (s - a) * (s - b) * (s - c)) ** 0.5\n    print(f\"Area: {area:.2f}\")\nelse:\n    print(\"Invalid triangle\")"),
    (10, "模拟电梯调度（多条件）。", "current = 3\nrequested = 7\nif requested > current:\n    print(f\"Going up to floor {requested}\")\nelif requested < current:\n    print(f\"Going down to floor {requested}\")\nelse:\n    print(\"Already at floor\")", "填空电梯逻辑。", "current = 3\nrequested = 7\nif requested > current:\n    print(f\"Going up to floor {requested}\")\nelif requested < current:\n    print(f\"Going down to floor {requested}\")\nelse:\n    print(\"Already at floor\")"),
    (11, "判断数字是否同时满足多个条件。", "n = 30\nif n % 2 == 0 and n % 3 == 0 and n % 5 == 0:\n    print(\"divisible by 2, 3, 5\")\nelif n % 2 == 0 and n % 3 == 0:\n    print(\"divisible by 2 and 3\")\nelif n % 2 == 0:\n    print(\"even only\")\nelse:\n    print(\"other\")", "填空多重整除。", "n = 30\nif n % 2 == 0 and n % 3 == 0 and n % 5 == 0:\n    print(\"divisible by 2, 3, 5\")\nelif n % 2 == 0 and n % 3 == 0:\n    print(\"divisible by 2 and 3\")\nelif n % 2 == 0:\n    print(\"even only\")\nelse:\n    print(\"other\")"),
    (12, "实现简易成绩转换（百分制到等级分）。", "def to_grade(score):\n    if score >= 90:\n        return \"A\"\n    elif score >= 80:\n        return \"B\"\n    elif score >= 70:\n        return \"C\"\n    elif score >= 60:\n        return \"D\"\n    else:\n        return \"F\"\nscores = [59, 62, 75, 88, 99]\nfor s in scores:\n    print(f\"{s} -> {to_grade(s)}\")", "填空等级函数。", "def to_grade(score):\n    if score >= 90:\n        return \"A\"\n    elif score >= 80:\n        return \"B\"\n    elif score >= 70:\n        return \"C\"\n    elif score >= 60:\n        return \"D\"\n    else:\n        return \"F\"\nscores = [59, 62, 75, 88, 99]\nfor s in scores:\n    print(f\"{s} -> {to_grade(s)}\")"),
    (13, "判断两个区间是否重叠。", "a1, a2 = 1, 5\nb1, b2 = 4, 8\nif a2 < b1 or b2 < a1:\n    print(\"no overlap\")\nelse:\n    overlap_start = max(a1, b1)\n    overlap_end = min(a2, b2)\n    print(f\"overlap: {overlap_start}-{overlap_end}\")", "填空区间重叠。", "a1, a2 = 1, 5\nb1, b2 = 4, 8\nif a2 < b1 or b2 < a1:\n    print(\"no overlap\")\nelse:\n    overlap_start = max(a1, b1)\n    overlap_end = min(a2, b2)\n    print(f\"overlap: {overlap_start}-{overlap_end}\")"),
    (14, "判断列表是否包含重复元素。", "nums = [1, 3, 2, 3]\nif len(nums) != len(set(nums)):\n    print(\"has duplicates\")\nelse:\n    print(\"all unique\")", "填空重复判断。", "nums = [1, 3, 2, 3]\nif len(nums) != len(set(nums)):\n    print(\"has duplicates\")\nelse:\n    print(\"all unique\")"),
    (15, "根据成绩决定课程等级并输出。", "course_scores = {\"Math\": 92, \"English\": 78, \"Science\": 85}\nfor course, score in course_scores.items():\n    if score >= 90:\n        level = \"advanced\"\n    elif score >= 80:\n        level = \"intermediate\"\n    else:\n        level = \"foundation\"\n    print(f\"{course}: {level}\")", "填空课程分档。", "course_scores = {\"Math\": 92, \"English\": 78, \"Science\": 85}\nfor course, score in course_scores.items():\n    if score >= 90:\n        level = \"advanced\"\n    elif score >= 80:\n        level = \"intermediate\"\n    else:\n        level = \"foundation\"\n    print(f\"{course}: {level}\")"),
    (16, "判断一个数是否为自幂数（水仙花数）。", "n = 153\ndigits = [int(d) for d in str(n)]\npower = sum(d ** len(digits) for d in digits)\nif power == n:\n    print(f\"{n} is an Armstrong number\")\nelse:\n    print(f\"{n} is not\")", "填空自幂判断。", "n = 153\ndigits = [int(d) for d in str(n)]\npower = sum(d ** len(digits) for d in digits)\nif power == n:\n    print(f\"{n} is an Armstrong number\")\nelse:\n    print(f\"{n} is not\")"),
    (17, "模拟红绿灯控制输出。", "signal = \"red\"\nif signal == \"red\":\n    print(\"Stop\")\nelif signal == \"yellow\":\n    print(\"Slow down\")\nelif signal == \"green\":\n    print(\"Go\")\nelse:\n    print(\"Invalid signal\")", "填空红绿灯。", "signal = \"red\"\nif signal == \"red\":\n    print(\"Stop\")\nelif signal == \"yellow\":\n    print(\"Slow down\")\nelif signal == \"green\":\n    print(\"Go\")\nelse:\n    print(\"Invalid signal\")"),
    (18, "判断表达式结果的正负。", "a, b, c = 3, -4, 5\nresult = a * b + c\nif result > 0:\n    print(f\"{result} is positive\")\nelif result < 0:\n    print(f\"{result} is negative\")\nelse:\n    print(\"zero\")", "填空表达式判断。", "a, b, c = 3, -4, 5\nresult = a * b + c\nif result > 0:\n    print(f\"{result} is positive\")\nelif result < 0:\n    print(f\"{result} is negative\")\nelse:\n    print(\"zero\")"),
    (19, "判断密码强度并输出规则详情。", "pwd = \"P@ssw0rd\"\nlength_ok = len(pwd) >= 8\nupper_ok = any(c.isupper() for c in pwd)\ndigit_ok = any(c.isdigit() for c in pwd)\nsymbol_ok = any(not c.isalnum() for c in pwd)\nscore = sum([length_ok, upper_ok, digit_ok, symbol_ok])\nif score == 4:\n    print(\"very strong\")\nelif score == 3:\n    print(\"strong\")\nelif score == 2:\n    print(\"medium\")\nelse:\n    print(\"weak\")", "填空密码评分。", "pwd = \"P@ssw0rd\"\nlength_ok = len(pwd) >= 8\nupper_ok = any(c.isupper() for c in pwd)\ndigit_ok = any(c.isdigit() for c in pwd)\nsymbol_ok = any(not c.isalnum() for c in pwd)\nscore = sum([length_ok, upper_ok, digit_ok, symbol_ok])\nif score == 4:\n    print(\"very strong\")\nelif score == 3:\n    print(\"strong\")\nelif score == 2:\n    print(\"medium\")\nelse:\n    print(\"weak\")"),
    (20, "判断字符串是否包含连续三个相同字符。", "s = \"aaab\"\nhas_three = False\nfor i in range(len(s) - 2):\n    if s[i] == s[i + 1] == s[i + 2]:\n        has_three = True\n        break\nif has_three:\n    print(\"has triple\")\nelse:\n    print(\"no triple\")", "填空三连判断。", "s = \"aaab\"\nhas_three = False\nfor i in range(len(s) - 2):\n    if s[i] == s[i + 1] == s[i + 2]:\n        has_three = True\n        break\nif has_three:\n    print(\"has triple\")\nelse:\n    print(\"no triple\")"),
    (21, "综合：判断并输出多行统计。", "nums = [5, -3, 0, 8, -2, 7]\npositive = [n for n in nums if n > 0]\nnegative = [n for n in nums if n < 0]\nprint(f\"Positive: {len(positive)}, Negative: {len(negative)}, Zero: {len(nums) - len(positive) - len(negative)}\")\nprint(f\"Sum positive: {sum(positive)}\")\nprint(f\"Sum negative: {sum(negative)}\")", "填空综合统计。", "nums = [5, -3, 0, 8, -2, 7]\npositive = [n for n in nums if n > 0]\nnegative = [n for n in nums if n < 0]\nprint(f\"Positive: {len(positive)}, Negative: {len(negative)}, Zero: {len(nums) - len(positive) - len(negative)}\")\nprint(f\"Sum positive: {sum(positive)}\")\nprint(f\"Sum negative: {sum(negative)}\")"),
    (22, "判断日期是否合法（年月日）。", "y, m, d = 2026, 2, 29\nif m in (1, 3, 5, 7, 8, 10, 12):\n    max_d = 31\nelif m in (4, 6, 9, 11):\n    max_d = 30\nelse:\n    max_d = 29 if (y % 4 == 0 and y % 100 != 0) or y % 400 == 0 else 28\nif 1 <= m <= 12 and 1 <= d <= max_d:\n    print(\"valid date\")\nelse:\n    print(\"invalid date\")", "填空日期合法性。", "y, m, d = 2026, 2, 29\nif m in (1, 3, 5, 7, 8, 10, 12):\n    max_d = 31\nelif m in (4, 6, 9, 11):\n    max_d = 30\nelse:\n    max_d = 29 if (y % 4 == 0 and y % 100 != 0) or y % 400 == 0 else 28\nif 1 <= m <= 12 and 1 <= d <= max_d:\n    print(\"valid date\")\nelse:\n    print(\"invalid date\")"),
    (23, "模拟考试系统判定（多条件，全部答对）。", "answers = 10\nquestions = 10\nif answers == questions:\n    print(\"perfect score\")\nelif answers >= questions * 0.8:\n    print(\"excellent\")\nelif answers >= questions * 0.6:\n    print(\"passed\")\nelse:\n    print(\"failed\")", "填空考试判定。", "answers = 10\nquestions = 10\nif answers == questions:\n    print(\"perfect score\")\nelif answers >= questions * 0.8:\n    print(\"excellent\")\nelif answers >= questions * 0.6:\n    print(\"passed\")\nelse:\n    print(\"failed\")"),
    (24, "判断点是否在圆内。", "x, y = 3, 4\ncx, cy, r = 0, 0, 5\nif (x - cx) ** 2 + (y - cy) ** 2 <= r ** 2:\n    print(\"inside circle\")\nelse:\n    print(\"outside circle\")", "填空圆内判断。", "x, y = 3, 4\ncx, cy, r = 0, 0, 5\nif (x - cx) ** 2 + (y - cy) ** 2 <= r ** 2:\n    print(\"inside circle\")\nelse:\n    print(\"outside circle\")"),
    (25, "判断回文素数（前几个）。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nresult = []\nfor n in range(2, 200):\n    if is_prime(n) and str(n) == str(n)[::-1]:\n        result.append(n)\nprint(result)", "填空回文素数。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nresult = []\nfor n in range(2, 200):\n    if is_prime(n) and str(n) == str(n)[::-1]:\n        result.append(n)\nprint(result)"),
    (26, "判断数字是否为快乐数（含过程）。", "def is_happy(n):\n    seen = set()\n    while n != 1:\n        if n in seen:\n            return False\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return True\nfor n in [19, 20, 7]:\n    print(f\"{n}: {is_happy(n)}\")", "填空快乐数函数。", "def is_happy(n):\n    seen = set()\n    while n != 1:\n        if n in seen:\n            return False\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return True\nfor n in [19, 20, 7]:\n    print(f\"{n}: {is_happy(n)}\")"),
    (27, "模拟优惠叠加（多重条件）。", "price = 200\nmember = True\nholiday = False\nif member and holiday:\n    final = price * 0.6\nelif member:\n    final = price * 0.8\nelif holiday:\n    final = price * 0.9\nelse:\n    final = price\nprint(f\"Final price: {final}\")", "填空优惠叠加。", "price = 200\nmember = True\nholiday = False\nif member and holiday:\n    final = price * 0.6\nelif member:\n    final = price * 0.8\nelif holiday:\n    final = price * 0.9\nelse:\n    final = price\nprint(f\"Final price: {final}\")"),
    (28, "判断三个字符串是否按字典序排列。", "a, b, c = \"apple\", \"banana\", \"cherry\"\nif a <= b <= c:\n    print(\"sorted\")\nelif a >= b >= c:\n    print(\"reverse sorted\")\nelse:\n    print(\"unsorted\")", "填空字典序判断。", "a, b, c = \"apple\", \"banana\", \"cherry\"\nif a <= b <= c:\n    print(\"sorted\")\nelif a >= b >= c:\n    print(\"reverse sorted\")\nelse:\n    print(\"unsorted\")"),
    (29, "综合：多条件筛选与分类输出。", "items = [(\"apple\", 3.5, 20), (\"milk\", 5.0, 5), (\"bread\", 4.5, 30)]\nfor name, price, stock in items:\n    if stock == 0:\n        status = \"out of stock\"\n    elif stock < 10:\n        status = \"low stock\"\n    elif price > 4:\n        status = \"premium\"\n    else:\n        status = \"normal\"\n    print(f\"{name}: {status}\")", "填空库存分类。", "items = [(\"apple\", 3.5, 20), (\"milk\", 5.0, 5), (\"bread\", 4.5, 30)]\nfor name, price, stock in items:\n    if stock == 0:\n        status = \"out of stock\"\n    elif stock < 10:\n        status = \"low stock\"\n    elif price > 4:\n        status = \"premium\"\n    else:\n        status = \"normal\"\n    print(f\"{name}: {status}\")"),
    (30, "验证哥德巴赫猜想（50 内偶数）。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nfor even in range(4, 31, 2):\n    for p in range(2, even):\n        if is_prime(p) and is_prime(even - p):\n            print(f\"{even} = {p} + {even - p}\")\n            break", "填空哥德巴赫。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\nfor even in range(4, 31, 2):\n    for p in range(2, even):\n        if is_prime(p) and is_prime(even - p):\n            print(f\"{even} = {p} + {even - p}\")\n            break"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
