# -*- coding: utf-8 -*-
"""生成 CH10 函数 (参数) 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH10"
TITLE = "函数 (参数)"
OUT_DIR = "CH10_Function_Params"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "定义带一个参数的函数并调用。", "def show(x):\n    print(x)\n\nshow(___)", "填 5。", "def show(x):\n    print(x)\n\nshow(5)"),
    (2, "函数接收两个参数并相加输出。", "def add(a, b):\n    print(a + b)\n\nadd(___, ___)", "依次填 3、4。", "def add(a, b):\n    print(a + b)\n\nadd(3, 4)"),
    (3, "使用默认参数调用函数。", "def greet(name=\"World\"):\n    print(name)\n\ngreet()", "填空默认参数。", "def greet(name=\"World\"):\n    print(name)\n\ngreet()"),
    (4, "用关键字参数调用函数。", "def info(name, age):\n    print(name, age)\n\ninfo(age=25, name=\"Bob\")", "填空关键字调用。", "def info(name, age):\n    print(name, age)\n\ninfo(age=25, name=\"Bob\")"),
    (5, "默认参数被传入值覆盖。", "def greet(name=\"World\"):\n    print(name)\n\ngreet(\"Alice\")", "填空覆盖调用。", "def greet(name=\"World\"):\n    print(name)\n\ngreet(\"Alice\")"),
    (6, "函数有两个默认参数。", "def box(w=10, h=5):\n    print(w, h)\n\nbox()", "填空默认调用。", "def box(w=10, h=5):\n    print(w, h)\n\nbox()"),
    (7, "用 *args 求参数个数。", "def count(*args):\n    print(len(args))\n\ncount(1, 2, 3)", "填空可变参数。", "def count(*args):\n    print(len(args))\n\ncount(1, 2, 3)"),
    (8, "用 *args 求和。", "def total(*args):\n    print(sum(args))\n\ntotal(1, 2, 3, 4)", "填空求和。", "def total(*args):\n    print(sum(args))\n\ntotal(1, 2, 3, 4)"),
    (9, "用 **kwargs 输出键。", "def show(**kwargs):\n    for k in kwargs:\n        print(k)\n\nshow(a=1, b=2)", "填空 kwargs 遍历。", "def show(**kwargs):\n    for k in kwargs:\n        print(k)\n\nshow(a=1, b=2)"),
    (10, "位置参数和关键字参数混合。", "def greet(name, msg=\"Hi\"):\n    print(msg, name)\n\ngreet(\"Tom\", msg=\"Hello\")", "填空混合调用。", "def greet(name, msg=\"Hi\"):\n    print(msg, name)\n\ngreet(\"Tom\", msg=\"Hello\")"),
    (11, "函数接收字符串参数。", "def echo(text):\n    print(text)\n\necho(\"Python\")", "填空字符串调用。", "def echo(text):\n    print(text)\n\necho(\"Python\")"),
    (12, "函数接收数字参数并乘 2。", "def double(x):\n    print(x * 2)\n\ndouble(6)", "填空调用。", "def double(x):\n    print(x * 2)\n\ndouble(6)"),
    (13, "函数接收布尔参数。", "def flag(f):\n    print(f)\n\nflag(True)", "填空布尔调用。", "def flag(f):\n    print(f)\n\nflag(True)"),
    (14, "函数接收列表参数并输出长度。", "def size(items):\n    print(len(items))\n\nsize([1, 2, 3, 4])", "填空 len。", "def size(items):\n    print(len(items))\n\nsize([1, 2, 3, 4])"),
    (15, "函数接收字典参数。", "def show(d):\n    print(d[\"x\"])\n\nshow({\"x\": 15})", "填空键访问。", "def show(d):\n    print(d[\"x\"])\n\nshow({\"x\": 15})"),
    (16, "默认参数为表达式。", "def add(x, y=2):\n    print(x + y)\n\nadd(6)", "填空默认调用。", "def add(x, y=2):\n    print(x + y)\n\nadd(6)"),
    (17, "位置参数按顺序传入。", "def pair(a, b):\n    print(a, b)\n\npair(1, 2)", "填空顺序调用。", "def pair(a, b):\n    print(a, b)\n\npair(1, 2)"),
    (18, "关键字参数任意顺序。", "def point(x, y):\n    print(x, y)\n\npoint(y=4, x=1)", "填空关键字顺序。", "def point(x, y):\n    print(x, y)\n\npoint(y=4, x=1)"),
    (19, "用 * 解包调用函数。", "def add(a, b):\n    print(a + b)\n\nargs = [5, 6]\nadd(*args)", "填空解包调用。", "def add(a, b):\n    print(a + b)\n\nargs = [5, 6]\nadd(*args)"),
    (20, "可变参数逐个输出。", "def show(*args):\n    for a in args:\n        print(a)\n\nshow(1, 2)", "填空遍历输出。", "def show(*args):\n    for a in args:\n        print(a)\n\nshow(1, 2)"),
    (21, "参数默认值不影响外部变量。", "x = 10\ndef show(x):\n    x = 20\n    print(x)\n\nshow(x)\nprint(x)", "填空作用域演示。", "x = 10\ndef show(x):\n    x = 20\n    print(x)\n\nshow(x)\nprint(x)"),
    (22, "同一函数用默认和传入各调用一次。", "def greet(name=\"Guest\"):\n    print(name)\n\ngreet()\ngreet(\"Ada\")", "填空两次调用。", "def greet(name=\"Guest\"):\n    print(name)\n\ngreet()\ngreet(\"Ada\")"),
    (23, "三个位置参数。", "def add3(a, b, c):\n    print(a + b + c)\n\nadd3(1, 2, 3)", "填空三参数调用。", "def add3(a, b, c):\n    print(a + b + c)\n\nadd3(1, 2, 3)"),
    (24, "位置、默认、关键字组合。", "def calc(a, b=2, c=3):\n    print(a + b + c)\n\ncalc(1, c=10)", "填空组合调用。", "def calc(a, b=2, c=3):\n    print(a + b + c)\n\ncalc(1, c=10)"),
    (25, "关键字参数全部指定。", "def area(w, h):\n    print(w * h)\n\narea(w=5, h=4)", "填空全部关键字。", "def area(w, h):\n    print(w * h)\n\narea(w=5, h=4)"),
    (26, "遍历 *args 并求平均。", "def avg(*args):\n    print(sum(args) / len(args))\n\navg(2, 4, 6)", "填空平均值。", "def avg(*args):\n    print(sum(args) / len(args))\n\navg(2, 4, 6)"),
    (27, "遍历 **kwargs 输出键值。", "def show(**kwargs):\n    for k, v in kwargs.items():\n        print(k, v)\n\nshow(a=1)", "填空键值输出。", "def show(**kwargs):\n    for k, v in kwargs.items():\n        print(k, v)\n\nshow(a=1)"),
    (28, "默认参数与传入参数同用。", "def greet(name, msg=\"Hello\"):\n    print(msg, name)\n\ngreet(\"Bob\")", "填空默认 msg。", "def greet(name, msg=\"Hello\"):\n    print(msg, name)\n\ngreet(\"Bob\")"),
    (29, "参数参与组合运算。", "def combo(a, b):\n    print(a * b + a)\n\ncombo(3, 2)", "填空组合运算。", "def combo(a, b):\n    print(a * b + a)\n\ncombo(3, 2)"),
    (30, "综合：多种参数调用。", "def f(a, b=1, *args, **kwargs):\n    print(a, b, len(args), len(kwargs))\n\nf(10, 2, 3, 4, x=5)", "填空综合参数。", "def f(a, b=1, *args, **kwargs):\n    print(a, b, len(args), len(kwargs))\n\nf(10, 2, 3, 4, x=5)"),
]

SIMPLE = [
    (1, "函数用默认参数计算折扣。", "def discount(price, rate=0.1):\n    print(price * (1 - rate))\n\ndiscount(100)", "填空折扣计算。", "def discount(price, rate=0.1):\n    print(price * (1 - rate))\n\ndiscount(100)"),
    (2, "函数接收任意数量参数求和。", "def total(*nums):\n    print(f\"Sum: {sum(nums)}\")\n\ntotal(1, 2, 3, 4)", "填空可变参数求和。", "def total(*nums):\n    print(f\"Sum: {sum(nums)}\")\n\ntotal(1, 2, 3, 4)"),
    (3, "函数接收关键字参数并格式化。", "def introduce(**info):\n    for key, value in info.items():\n        print(f\"{key}: {value}\")\n\nintroduce(name=\"Alice\", age=20)", "填空 kwargs 遍历。", "def introduce(**info):\n    for key, value in info.items():\n        print(f\"{key}: {value}\")\n\nintroduce(name=\"Alice\", age=20)"),
    (4, "默认参数只求值一次演示。", "def add_item(item, items=[]):\n    items.append(item)\n    print(items)\n\nadd_item(1)\nadd_item(2)", "填空默认列表行为。", "def add_item(item, items=[]):\n    items.append(item)\n    print(items)\n\nadd_item(1)\nadd_item(2)"),
    (5, "用 ** 解包字典调用函数。", "def info(name, age):\n    print(name, age)\n\nd = {\"name\": \"Bob\", \"age\": 30}\ninfo(**d)", "填空解包字典。", "def info(name, age):\n    print(name, age)\n\nd = {\"name\": \"Bob\", \"age\": 30}\ninfo(**d)"),
    (6, "函数参数传递列表并修改。", "def add_one(nums):\n    for i in range(len(nums)):\n        nums[i] += 1\n    print(nums)\n\nadd_one([1, 2, 3])", "填空列表修改。", "def add_one(nums):\n    for i in range(len(nums)):\n        nums[i] += 1\n    print(nums)\n\nadd_one([1, 2, 3])"),
    (7, "多个默认参数组合。", "def repeat(text, times=2, sep=\"-\"):\n    print(sep.join([text] * times))\n\nrepeat(\"ab\")", "填空默认组合。", "def repeat(text, times=2, sep=\"-\"):\n    print(sep.join([text] * times))\n\nrepeat(\"ab\")"),
    (8, "位置参数和 *args 混合。", "def combine(first, *rest):\n    print(first, len(rest))\n\ncombine(1, 2, 3, 4)", "填空混合参数。", "def combine(first, *rest):\n    print(first, len(rest))\n\ncombine(1, 2, 3, 4)"),
    (9, "*args 和 **kwargs 混合。", "def collect(*args, **kwargs):\n    print(len(args), len(kwargs))\n\ncollect(1, 2, x=3, y=4)", "填空混合收集。", "def collect(*args, **kwargs):\n    print(len(args), len(kwargs))\n\ncollect(1, 2, x=3, y=4)"),
    (10, "默认参数在中间位置。", "def config(name, debug=False, level=1):\n    print(name, debug, level)\n\nconfig(\"app\", level=3)", "填空默认中间参数。", "def config(name, debug=False, level=1):\n    print(name, debug, level)\n\nconfig(\"app\", level=3)"),
    (11, "参数传递字符串并统计长度。", "def lengths(*words):\n    for w in words:\n        print(len(w))\n\nlengths(\"hi\", \"hello\")", "填空长度统计。", "def lengths(*words):\n    for w in words:\n        print(len(w))\n\nlengths(\"hi\", \"hello\")"),
    (12, "关键字参数默认覆盖。", "def settings(sound=True, theme=\"light\"):\n    print(sound, theme)\n\nsettings(sound=False)", "填空关键字覆盖。", "def settings(sound=True, theme=\"light\"):\n    print(sound, theme)\n\nsettings(sound=False)"),
    (13, "参数参与条件判断。", "def check(n, limit=10):\n    if n > limit:\n        print(\"big\")\n    else:\n        print(\"small\")\n\ncheck(15)", "填空条件参数。", "def check(n, limit=10):\n    if n > limit:\n        print(\"big\")\n    else:\n        print(\"small\")\n\ncheck(15)"),
    (14, "函数接收多个数字求最大。", "def maximum(*nums):\n    print('Max:', max(nums))\n\nmaximum(3, 9, 5)", "填空 max。", "def maximum(*nums):\n    print('Max:', max(nums))\n\nmaximum(3, 9, 5)"),
    (15, "参数传递并循环输出。", "def show_all(*items):\n    for i, item in enumerate(items, 1):\n        print(f\"{i}. {item}\")\n\nshow_all(\"a\", \"b\", \"c\")", "填空编号输出。", "def show_all(*items):\n    for i, item in enumerate(items, 1):\n        print(f\"{i}. {item}\")\n\nshow_all(\"a\", \"b\", \"c\")"),
    (16, "默认参数用于格式化。", "def greet(name, punct=\"!\"):\n    print(f\"Hello {name}{punct}\")\n\ngreet(\"Tom\")", "填空默认标点。", "def greet(name, punct=\"!\"):\n    print(f\"Hello {name}{punct}\")\n\ngreet(\"Tom\")"),
    (17, "关键字参数批量传入。", "def report(**data):\n    print('Count:', len(data))\n\nreport(name=\"A\", age=1, city=\"B\")", "填空参数计数。", "def report(**data):\n    print('Count:', len(data))\n\nreport(name=\"A\", age=1, city=\"B\")"),
    (18, "参数作为字符串重复。", "def banner(char=\"*\", n=8):\n    print(char * n)\n\nbanner()", "填空重复输出。", "def banner(char=\"*\", n=8):\n    print(char * n)\n\nbanner()"),
    (19, "列表参数求和并输出。", "def list_total(items):\n    print('Total:', sum(items))\n\nlist_total([1, 2, 3, 4])", "填空求和。", "def list_total(items):\n    print('Total:', sum(items))\n\nlist_total([1, 2, 3, 4])"),
    (20, "参数默认值参与运算。", "def scale(x, factor=2):\n    print('Scaled:', x * factor)\n\nscale(5)", "填空缩放。", "def scale(x, factor=2):\n    print('Scaled:', x * factor)\n\nscale(5)"),
    (21, "两个默认参数分别调用。", "def area(w=2, h=3):\n    print(w * h)\n\narea(4)\narea(w=5, h=2)", "填空两种调用。", "def area(w=2, h=3):\n    print(w * h)\n\narea(4)\narea(w=5, h=2)"),
    (22, "参数解包元组。", "def add(a, b):\n    print(a + b)\n\npair = (10, 20)\nadd(*pair)", "填空元组解包。", "def add(a, b):\n    print(a + b)\n\npair = (10, 20)\nadd(*pair)"),
    (23, "kwargs 按字母序输出。", "def show(**kwargs):\n    for k in sorted(kwargs):\n        print(k, kwargs[k])\n\nshow(b=2, a=1)", "填空排序输出。", "def show(**kwargs):\n    for k in sorted(kwargs):\n        print(k, kwargs[k])\n\nshow(b=2, a=1)"),
    (24, "参数类型转换后使用。", "def add_str(s, n):\n    print(s + str(n))\n\nadd_str(\"Count: \", 5)", "填空拼接。", "def add_str(s, n):\n    print(s + str(n))\n\nadd_str(\"Count: \", 5)"),
    (25, "默认参数为 None 判断。", "def greet(name=None):\n    if name:\n        print(f\"Hello {name}\")\n    else:\n        print(\"Hello Guest\")\n\ngreet()", "填空 None 判断。", "def greet(name=None):\n    if name:\n        print(f\"Hello {name}\")\n    else:\n        print(\"Hello Guest\")\n\ngreet()"),
    (26, "多参数求幂。", "def power(base, exp=2):\n    print('Power:', base ** exp)\n\npower(3)", "填空默认幂。", "def power(base, exp=2):\n    print('Power:', base ** exp)\n\npower(3)"),
    (27, "参数传入嵌套结构。", "def extract(data):\n    print('Value:', data[0][1])\n\nextract([[1, 2], [3, 4]])", "填空嵌套访问。", "def extract(data):\n    print('Value:', data[0][1])\n\nextract([[1, 2], [3, 4]])"),
    (28, "可变参数求乘积。", "def multiply(*nums):\n    result = 1\n    for n in nums:\n        result *= n\n    print(result)\n\nmultiply(2, 3, 4)", "填空累乘。", "def multiply(*nums):\n    result = 1\n    for n in nums:\n        result *= n\n    print(result)\n\nmultiply(2, 3, 4)"),
    (29, "参数条件选择输出。", "def describe(name, age):\n    status = \"adult\" if age >= 18 else \"minor\"\n    print(f\"{name} is {status}\")\n\ndescribe(\"Tom\", 17)", "填空条件描述。", "def describe(name, age):\n    status = \"adult\" if age >= 18 else \"minor\"\n    print(f\"{name} is {status}\")\n\ndescribe(\"Tom\", 17)"),
    (30, "综合：默认+可变+关键字。", "def full(a=1, *args, **kwargs):\n    print(a, len(args), len(kwargs))\n\nfull(10, 20, 30, x=1, y=2)", "填空综合参数。", "def full(a=1, *args, **kwargs):\n    print(a, len(args), len(kwargs))\n\nfull(10, 20, 30, x=1, y=2)"),
]

MEDIUM = [
    (1, "函数用默认参数实现折扣阶梯。", "def final_price(price, coupon=0, member=False):\n    if member:\n        price *= 0.8\n    price -= coupon\n    print(price)\n\nfinal_price(100, coupon=10)", "填空多默认参数。", "def final_price(price, coupon=0, member=False):\n    if member:\n        price *= 0.8\n    price -= coupon\n    print(price)\n\nfinal_price(100, coupon=10)"),
    (2, "函数接收任意个数字求平均。", "def average(*nums):\n    print(f\"Average: {sum(nums) / len(nums)}\")\n\naverage(10, 20, 30, 40)", "填空可变参数平均。", "def average(*nums):\n    print(f\"Average: {sum(nums) / len(nums)}\")\n\naverage(10, 20, 30, 40)"),
    (3, "函数合并字典参数。", "def merge(base, **extra):\n    base.update(extra)\n    print(base)\n\nmerge({\"a\": 1}, b=2, c=3)", "填空字典合并。", "def merge(base, **extra):\n    base.update(extra)\n    print(base)\n\nmerge({\"a\": 1}, b=2, c=3)"),
    (4, "可变参数过滤偶数。", "def evens(*nums):\n    print([n for n in nums if n % 2 == 0])\n\nevens(1, 2, 3, 4, 5, 6)", "填空偶数过滤。", "def evens(*nums):\n    print([n for n in nums if n % 2 == 0])\n\nevens(1, 2, 3, 4, 5, 6)"),
    (5, "参数为列表并原地排序。", "def sort_list(items, reverse=False):\n    items.sort(reverse=reverse)\n    print(items)\n\nsort_list([3, 1, 2], reverse=True)", "填空排序参数。", "def sort_list(items, reverse=False):\n    items.sort(reverse=reverse)\n    print(items)\n\nsort_list([3, 1, 2], reverse=True)"),
    (6, "函数参数默认值陷阱与修复。", "def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    print(items)\n\nadd_item(1)\nadd_item(2)", "填空 None 修复。", "def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    print(items)\n\nadd_item(1)\nadd_item(2)"),
    (7, "参数解包与打包组合。", "def show(*args):\n    print(args)\n\nshow(*[1, 2], 3)", "填空解包组合。", "def show(*args):\n    print(args)\n\nshow(*[1, 2], 3)"),
    (8, "关键字参数传递到内层函数。", "def inner(x, y):\n    print('Sum:', x + y)\n\ndef outer(**kw):\n    inner(**kw)\n\nouter(x=3, y=4)", "填空传递 kwargs。", "def inner(x, y):\n    print('Sum:', x + y)\n\ndef outer(**kw):\n    inner(**kw)\n\nouter(x=3, y=4)"),
    (9, "参数个数统计并分类。", "def categorize(first, *mid, last):\n    print(first, len(mid), last)\n\ncategorize(1, 2, 3, last=4)", "填空分类参数。", "def categorize(first, *mid, last):\n    print(first, len(mid), last)\n\ncategorize(1, 2, 3, last=4)"),
    (10, "默认参数用于日志格式。", "def log(msg, level=\"INFO\", prefix=\"\"):\n    print(f\"[{level}] {prefix}{msg}\")\n\nlog(\"start\")\nlog(\"error\", level=\"ERROR\")", "填空日志参数。", "def log(msg, level=\"INFO\", prefix=\"\"):\n    print(f\"[{level}] {prefix}{msg}\")\n\nlog(\"start\")\nlog(\"error\", level=\"ERROR\")"),
    (11, "函数参数做数学变换。", "def transform(x, op=\"square\"):\n    if op == \"square\":\n        print(x * x)\n    elif op == \"cube\":\n        print(x ** 3)\n    else:\n        print(x)\n\ntransform(4, \"square\")", "填空变换分发。", "def transform(x, op=\"square\"):\n    if op == \"square\":\n        print(x * x)\n    elif op == \"cube\":\n        print(x ** 3)\n    else:\n        print(x)\n\ntransform(4, \"square\")"),
    (12, "参数传入字符串并分析。", "def analyze(text, ch=\"a\"):\n    print(text.count(ch), len(text))\n\nanalyze(\"banana\")", "填空字符分析。", "def analyze(text, ch=\"a\"):\n    print(text.count(ch), len(text))\n\nanalyze(\"banana\")"),
    (13, "可变参数实现拼接。", "def join_with(sep, *parts):\n    print(sep.join(parts))\n\njoin_with(\"-\", \"a\", \"b\", \"c\")", "填空拼接参数。", "def join_with(sep, *parts):\n    print(sep.join(parts))\n\njoin_with(\"-\", \"a\", \"b\", \"c\")"),
    (14, "参数默认值做单位换算。", "def convert(value, unit=\"cm\"):\n    if unit == \"cm\":\n        print(value / 100)\n    else:\n        print(value * 100)\n\nconvert(150)", "填空单位换算。", "def convert(value, unit=\"cm\"):\n    if unit == \"cm\":\n        print(value / 100)\n    else:\n        print(value * 100)\n\nconvert(150)"),
    (15, "函数统计参数类型分布。", "def type_count(*args):\n    ints = sum(1 for a in args if isinstance(a, int))\n    strs = sum(1 for a in args if isinstance(a, str))\n    print(f\"Ints: {ints}, Strings: {strs}\")\n\ntype_count(1, \"a\", 2, \"b\", \"c\")", "填空类型统计。", "def type_count(*args):\n    ints = sum(1 for a in args if isinstance(a, int))\n    strs = sum(1 for a in args if isinstance(a, str))\n    print(f\"Ints: {ints}, Strings: {strs}\")\n\ntype_count(1, \"a\", 2, \"b\", \"c\")"),
    (16, "参数传入字典并按键取值。", "def get_values(data, *keys):\n    for k in keys:\n        print(data.get(k))\n\nget_values({\"a\": 1, \"b\": 2, \"c\": 3}, \"a\", \"c\")", "填空键取值。", "def get_values(data, *keys):\n    for k in keys:\n        print(data.get(k))\n\nget_values({\"a\": 1, \"b\": 2, \"c\": 3}, \"a\", \"c\")"),
    (17, "默认参数组合输出表格。", "def table_row(name, score, rank=0):\n    print(f\"{name}: {score} (rank {rank})\")\n\ntable_row(\"Alice\", 90)\ntable_row(\"Bob\", 85, 3)", "填空表格行参数。", "def table_row(name, score, rank=0):\n    print(f\"{name}: {score} (rank {rank})\")\n\ntable_row(\"Alice\", 90)\ntable_row(\"Bob\", 85, 3)"),
    (18, "可变参数求范围。", "def span(*nums):\n    print('Span:', max(nums) - min(nums))\n\nspan(5, 2, 9, 1)", "填空范围差。", "def span(*nums):\n    print('Span:', max(nums) - min(nums))\n\nspan(5, 2, 9, 1)"),
    (19, "函数参数做矩阵行求和。", "def row_sums(matrix):\n    for row in matrix:\n        print(sum(row))\n\nrow_sums([[1, 2], [3, 4]])", "填空行求和。", "def row_sums(matrix):\n    for row in matrix:\n        print(sum(row))\n\nrow_sums([[1, 2], [3, 4]])"),
    (20, "参数默认值递增演示。", "def counter(n=1):\n    print(n)\n\ncounter()\ncounter(5)", "填空默认调用。", "def counter(n=1):\n    print(n)\n\ncounter()\ncounter(5)"),
    (21, "kwargs 用于配置输出。", "def configure(**config):\n    for k in sorted(config):\n        print(f\"{k} = {config[k]}\")\n\nconfigure(theme=\"dark\", font=14)", "填空配置输出。", "def configure(**config):\n    for k in sorted(config):\n        print(f\"{k} = {config[k]}\")\n\nconfigure(theme=\"dark\", font=14)"),
    (22, "参数判断并输出对应消息。", "def grade(score, perfect=100):\n    if score == perfect:\n        print(\"Perfect!\")\n    elif score >= 90:\n        print(\"Excellent\")\n    else:\n        print(\"Good\")\n\ngrade(100)", "填空分级参数。", "def grade(score, perfect=100):\n    if score == perfect:\n        print(\"Perfect!\")\n    elif score >= 90:\n        print(\"Excellent\")\n    else:\n        print(\"Good\")\n\ngrade(100)"),
    (23, "参数传入并处理嵌套列表。", "def flatten_pairs(pairs):\n    for a, b in pairs:\n        print(a + b)\n\nflatten_pairs([(1, 2), (3, 4), (5, 6)])", "填空解包求和。", "def flatten_pairs(pairs):\n    for a, b in pairs:\n        print(a + b)\n\nflatten_pairs([(1, 2), (3, 4), (5, 6)])"),
    (24, "默认参数做步长控制。", "def count_to(n, step=1):\n    for i in range(1, n + 1, step):\n        print(i, end=\" \")\n\ncount_to(6, 2)", "填空步长参数。", "def count_to(n, step=1):\n    for i in range(1, n + 1, step):\n        print(i, end=\" \")\n\ncount_to(6, 2)"),
    (25, "参数传入字符串并反转。", "def reverse(text, upper=False):\n    result = text[::-1]\n    if upper:\n        result = result.upper()\n    print(result)\n\nreverse(\"abc\", upper=True)", "填空反转参数。", "def reverse(text, upper=False):\n    result = text[::-1]\n    if upper:\n        result = result.upper()\n    print(result)\n\nreverse(\"abc\", upper=True)"),
    (26, "可变参数求众数。", "def mode(*nums):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    print('Mode:', max(counts, key=counts.get))\n\nmode(1, 2, 2, 3)", "填空众数。", "def mode(*nums):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    print('Mode:', max(counts, key=counts.get))\n\nmode(1, 2, 2, 3)"),
    (27, "参数传入并输出最大最小。", "def extremes(*nums):\n    print(f\"Max: {max(nums)}, Min: {min(nums)}\")\n\nextremes(4, 9, 2, 7)", "填空极值。", "def extremes(*nums):\n    print(f\"Max: {max(nums)}, Min: {min(nums)}\")\n\nextremes(4, 9, 2, 7)"),
    (28, "函数参数做过滤条件。", "def filter_above(nums, threshold=5):\n    print([n for n in nums if n > threshold])\n\nfilter_above([1, 6, 3, 8], 4)", "填空过滤参数。", "def filter_above(nums, threshold=5):\n    print([n for n in nums if n > threshold])\n\nfilter_above([1, 6, 3, 8], 4)"),
    (29, "kwargs 传入后批量处理。", "def process(**data):\n    total = sum(data.values())\n    print(f\"Sum: {total}, Count: {len(data)}\")\n\nprocess(a=1, b=2, c=3)", "填空汇总参数。", "def process(**data):\n    total = sum(data.values())\n    print(f\"Sum: {total}, Count: {len(data)}\")\n\nprocess(a=1, b=2, c=3)"),
    (30, "综合：参数驱动的迷你计算器。", "def calc(op, *nums):\n    if op == \"+\":\n        print(sum(nums))\n    elif op == \"*\":\n        result = 1\n        for n in nums:\n            result *= n\n        print(result)\n\ncalc(\"+\", 1, 2, 3)\ncalc(\"*\", 2, 3, 4)", "填空计算器分发。", "def calc(op, *nums):\n    if op == \"+\":\n        print(sum(nums))\n    elif op == \"*\":\n        result = 1\n        for n in nums:\n            result *= n\n        print(result)\n\ncalc(\"+\", 1, 2, 3)\ncalc(\"*\", 2, 3, 4)"),
]

HARD = [
    (1, "函数实现参数校验并处理。", "def divide(a, b):\n    if b == 0:\n        print(\"Error: division by zero\")\n    else:\n        print(a / b)\n\ndivide(10, 2)\ndivide(5, 0)", "填空除零处理。", "def divide(a, b):\n    if b == 0:\n        print(\"Error: division by zero\")\n    else:\n        print(a / b)\n\ndivide(10, 2)\ndivide(5, 0)"),
    (2, "函数用 *args 求最小公倍数。", "def lcm_all(*nums):\n    m = max(nums)\n    while not all(m % n == 0 for n in nums):\n        m += 1\n    return m\n\nprint('LCM:', lcm_all(2, 3, 4))", "填空 lcm。", "def lcm_all(*nums):\n    m = max(nums)\n    while not all(m % n == 0 for n in nums):\n        m += 1\n    return m\n\nprint('LCM:', lcm_all(2, 3, 4))"),
    (3, "函数参数实现最大公约数（多参数）。", "def gcd_all(*nums):\n    def gcd(a, b):\n        while b:\n            a, b = b, a % b\n        return a\n    result = nums[0]\n    for n in nums[1:]:\n        result = gcd(result, n)\n    return result\n\nprint('GCD:', gcd_all(12, 18, 24))", "填空 gcd 链。", "def gcd_all(*nums):\n    def gcd(a, b):\n        while b:\n            a, b = b, a % b\n        return a\n    result = nums[0]\n    for n in nums[1:]:\n        result = gcd(result, n)\n    return result\n\nprint('GCD:', gcd_all(12, 18, 24))"),
    (4, "kwargs 构建配置并输出。", "def build_config(**options):\n    defaults = {\"theme\": \"light\", \"lang\": \"en\"}\n    defaults.update(options)\n    for k in sorted(defaults):\n        print(f\"{k} = {defaults[k]}\")\n\nbuild_config(theme=\"dark\")", "填空配置合并。", "def build_config(**options):\n    defaults = {\"theme\": \"light\", \"lang\": \"en\"}\n    defaults.update(options)\n    for k in sorted(defaults):\n        print(f\"{k} = {defaults[k]}\")\n\nbuild_config(theme=\"dark\")"),
    (5, "函数参数实现简化版 argparse。", "def parse(*args, **kwargs):\n    for a in args:\n        print(f\"arg: {a}\")\n    for k, v in kwargs.items():\n        print(f\"opt: {k}={v}\")\n\nparse(\"input.txt\", verbose=True, out=\"out.txt\")", "填空参数解析。", "def parse(*args, **kwargs):\n    for a in args:\n        print(f\"arg: {a}\")\n    for k, v in kwargs.items():\n        print(f\"opt: {k}={v}\")\n\nparse(\"input.txt\", verbose=True, out=\"out.txt\")"),
    (6, "参数默认值可变对象陷阱（正确写法）。", "def add_to(items=None):\n    if items is None:\n        items = []\n    items.append(\"x\")\n    return items\n\nprint(add_to())\nprint(add_to())", "填空 None 陷阱。", "def add_to(items=None):\n    if items is None:\n        items = []\n    items.append(\"x\")\n    return items\n\nprint(add_to())\nprint(add_to())"),
    (7, "函数参数做矩阵转置。", "def transpose(matrix):\n    rows = len(matrix)\n    cols = len(matrix[0])\n    result = [[matrix[j][i] for j in range(rows)] for i in range(cols)]\n    return result\n\nfor row in transpose([[1, 2], [3, 4], [5, 6]]):\n    print(row)", "填空转置参数。", "def transpose(matrix):\n    rows = len(matrix)\n    cols = len(matrix[0])\n    result = [[matrix[j][i] for j in range(rows)] for i in range(cols)]\n    return result\n\nfor row in transpose([[1, 2], [3, 4], [5, 6]]):\n    print(row)"),
    (8, "可变参数计算加权平均。", "def weighted_avg(weights, *scores):\n    total = sum(w * s for w, s in zip(weights, scores))\n    return total / sum(weights)\n\nprint(weighted_avg([1, 2], 80, 90))", "填空加权平均。", "def weighted_avg(weights, *scores):\n    total = sum(w * s for w, s in zip(weights, scores))\n    return total / sum(weights)\n\nprint(weighted_avg([1, 2], 80, 90))"),
    (9, "kwargs 实现事件分发。", "def dispatch(event, **data):\n    print(f\"Event: {event}\")\n    for k, v in data.items():\n        print(f\"  {k}: {v}\")\n\ndispatch(\"login\", user=\"alice\", ip=\"10.0.0.1\")", "填空事件分发。", "def dispatch(event, **data):\n    print(f\"Event: {event}\")\n    for k, v in data.items():\n        print(f\"  {k}: {v}\")\n\ndispatch(\"login\", user=\"alice\", ip=\"10.0.0.1\")"),
    (10, "函数参数做二分查找。", "def binary_search(nums, target, low=0, high=None):\n    if high is None:\n        high = len(nums) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n\nprint('Found at:', binary_search([1, 3, 5, 7, 9], 7))", "填空二分参数。", "def binary_search(nums, target, low=0, high=None):\n    if high is None:\n        high = len(nums) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n\nprint('Found at:', binary_search([1, 3, 5, 7, 9], 7))"),
    (11, "函数参数做快速幂。", "def fast_pow(base, exp, mod=None):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n            if mod:\n                result %= mod\n        base *= base\n        if mod:\n            base %= mod\n        exp //= 2\n    return result\n\nprint(fast_pow(2, 10), fast_pow(2, 10, 1000))", "填空快速幂参数。", "def fast_pow(base, exp, mod=None):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n            if mod:\n                result %= mod\n        base *= base\n        if mod:\n            base %= mod\n        exp //= 2\n    return result\n\nprint(fast_pow(2, 10), fast_pow(2, 10, 1000))"),
    (12, "参数传递并统计词频。", "def word_freq(*texts):\n    counts = {}\n    for t in texts:\n        for w in t.split():\n            counts[w] = counts.get(w, 0) + 1\n    return counts\n\nprint(word_freq(\"a b\", \"b c\", \"a\"))", "填空词频参数。", "def word_freq(*texts):\n    counts = {}\n    for t in texts:\n        for w in t.split():\n            counts[w] = counts.get(w, 0) + 1\n    return counts\n\nprint(word_freq(\"a b\", \"b c\", \"a\"))"),
    (13, "参数做组合数学（C(n,k)）。", "def comb(n, k):\n    if k > n:\n        return 0\n    result = 1\n    for i in range(k):\n        result = result * (n - i) // (i + 1)\n    return result\n\nprint(comb(5, 2), comb(10, 3))", "填空组合数。", "def comb(n, k):\n    if k > n:\n        return 0\n    result = 1\n    for i in range(k):\n        result = result * (n - i) // (i + 1)\n    return result\n\nprint(comb(5, 2), comb(10, 3))"),
    (14, "参数驱动多策略排序。", "def custom_sort(items, key=None, reverse=False):\n    if key:\n        items.sort(key=key, reverse=reverse)\n    else:\n        items.sort(reverse=reverse)\n    return items\n\nprint(custom_sort([\"bbb\", \"a\", \"cc\"], key=len))\nprint(custom_sort([3, 1, 2], reverse=True))", "填空排序策略。", "def custom_sort(items, key=None, reverse=False):\n    if key:\n        items.sort(key=key, reverse=reverse)\n    else:\n        items.sort(reverse=reverse)\n    return items\n\nprint(custom_sort([\"bbb\", \"a\", \"cc\"], key=len))\nprint(custom_sort([3, 1, 2], reverse=True))"),
    (15, "函数参数实现日历计算。", "def days_in_month(month, leap=False):\n    if month in (1, 3, 5, 7, 8, 10, 12):\n        return 31\n    elif month in (4, 6, 9, 11):\n        return 30\n    elif leap:\n        return 29\n    return 28\n\nprint(days_in_month(2, leap=True), days_in_month(2))", "填空日期参数。", "def days_in_month(month, leap=False):\n    if month in (1, 3, 5, 7, 8, 10, 12):\n        return 31\n    elif month in (4, 6, 9, 11):\n        return 30\n    elif leap:\n        return 29\n    return 28\n\nprint(days_in_month(2, leap=True), days_in_month(2))"),
    (16, "kwargs 批量设置对象属性。", "class Config:\n    pass\n\ncfg = Config()\nfor k, v in {\"host\": \"localhost\", \"port\": 8080}.items():\n    setattr(cfg, k, v)\nprint(cfg.host, cfg.port)", "填空属性设置。", "class Config:\n    pass\n\ncfg = Config()\nfor k, v in {\"host\": \"localhost\", \"port\": 8080}.items():\n    setattr(cfg, k, v)\nprint(cfg.host, cfg.port)"),
    (17, "参数实现简化版柯里化。", "def adder(x):\n    def inner(y):\n        return x + y\n    return inner\n\nadd5 = adder(5)\nprint(add5(3), add5(10))", "填空闭包参数。", "def adder(x):\n    def inner(y):\n        return x + y\n    return inner\n\nadd5 = adder(5)\nprint(add5(3), add5(10))"),
    (18, "参数验证并输出错误。", "def safe_int(s, default=0):\n    try:\n        return int(s)\n    except ValueError:\n        return default\n\nprint(safe_int(\"42\"), safe_int(\"abc\"))", "填空安全转换。", "def safe_int(s, default=0):\n    try:\n        return int(s)\n    except ValueError:\n        return default\n\nprint(safe_int(\"42\"), safe_int(\"abc\"))"),
    (19, "参数做矩阵乘法。", "def mat_mul(a, b):\n    result = [[0, 0], [0, 0]]\n    for i in range(2):\n        for j in range(2):\n            for k in range(2):\n                result[i][j] += a[i][k] * b[k][j]\n    return result\n\nprint(mat_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]]))", "填空矩阵乘法。", "def mat_mul(a, b):\n    result = [[0, 0], [0, 0]]\n    for i in range(2):\n        for j in range(2):\n            for k in range(2):\n                result[i][j] += a[i][k] * b[k][j]\n    return result\n\nprint(mat_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]]))"),
    (20, "参数实现字符串压缩。", "def compress(s, max_run=None):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1] and (max_run is None or count < max_run):\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aaabbb\", max_run=2))", "填空压缩参数。", "def compress(s, max_run=None):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1] and (max_run is None or count < max_run):\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aaabbb\", max_run=2))"),
    (21, "参数驱动筛选（多条件）。", "def filter_nums(nums, *, even=None, positive=None):\n    result = nums\n    if even is not None:\n        result = [n for n in result if (n % 2 == 0) == even]\n    if positive is not None:\n        result = [n for n in result if (n > 0) == positive]\n    return result\n\nprint(filter_nums([-2, -1, 0, 1, 2], even=True, positive=True))", "填空多条件筛选。", "def filter_nums(nums, *, even=None, positive=None):\n    result = nums\n    if even is not None:\n        result = [n for n in result if (n % 2 == 0) == even]\n    if positive is not None:\n        result = [n for n in result if (n > 0) == positive]\n    return result\n\nprint(filter_nums([-2, -1, 0, 1, 2], even=True, positive=True))"),
    (22, "参数做动态规划（简化）。", "def min_steps(n, memo=None):\n    if memo is None:\n        memo = {}\n    if n <= 1:\n        return 0\n    if n in memo:\n        return memo[n]\n    memo[n] = 1 + min_steps(n - 1, memo)\n    return memo[n]\n\nprint('Steps:', min_steps(6))", "填空 DP 参数。", "def min_steps(n, memo=None):\n    if memo is None:\n        memo = {}\n    if n <= 1:\n        return 0\n    if n in memo:\n        return memo[n]\n    memo[n] = 1 + min_steps(n - 1, memo)\n    return memo[n]\n\nprint('Steps:', min_steps(6))"),
    (23, "参数实现二分查找演示过程。", "def search_steps(nums, target):\n    low, high = 0, len(nums) - 1\n    steps = []\n    while low <= high:\n        mid = (low + high) // 2\n        steps.append(nums[mid])\n        if nums[mid] == target:\n            return steps\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return steps\n\nprint(search_steps([1, 3, 5, 7, 9, 11], 9))", "填空二分步骤。", "def search_steps(nums, target):\n    low, high = 0, len(nums) - 1\n    steps = []\n    while low <= high:\n        mid = (low + high) // 2\n        steps.append(nums[mid])\n        if nums[mid] == target:\n            return steps\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return steps\n\nprint(search_steps([1, 3, 5, 7, 9, 11], 9))"),
    (24, "参数做区间合并。", "def merge_intervals(intervals):\n    intervals.sort()\n    result = []\n    for start, end in intervals:\n        if result and start <= result[-1][1]:\n            result[-1][1] = max(result[-1][1], end)\n        else:\n            result.append([start, end])\n    return result\n\nprint(merge_intervals([[1, 3], [2, 6], [8, 10]]))", "填空区间合并。", "def merge_intervals(intervals):\n    intervals.sort()\n    result = []\n    for start, end in intervals:\n        if result and start <= result[-1][1]:\n            result[-1][1] = max(result[-1][1], end)\n        else:\n            result.append([start, end])\n    return result\n\nprint(merge_intervals([[1, 3], [2, 6], [8, 10]]))"),
    (25, "kwargs 实现报表聚合。", "def aggregate(operation, **data):\n    values = list(data.values())\n    if operation == \"sum\":\n        return sum(values)\n    elif operation == \"avg\":\n        return sum(values) / len(values)\n    return max(values)\n\nprint(aggregate(\"avg\", a=10, b=20, c=30))", "填空聚合参数。", "def aggregate(operation, **data):\n    values = list(data.values())\n    if operation == \"sum\":\n        return sum(values)\n    elif operation == \"avg\":\n        return sum(values) / len(values)\n    return max(values)\n\nprint(aggregate(\"avg\", a=10, b=20, c=30))"),
    (26, "参数做最长递增子序列（简化）。", "def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(len(nums)):\n        for j in range(i):\n            if nums[j] < nums[i]:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp)\n\nprint('LIS:', lis([3, 10, 2, 1, 20]))", "填空 LIS。", "def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(len(nums)):\n        for j in range(i):\n            if nums[j] < nums[i]:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp)\n\nprint('LIS:', lis([3, 10, 2, 1, 20]))"),
    (27, "参数实现数字转罗马（简化）。", "def to_roman(n):\n    pairs = [(10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\")]\n    result = \"\"\n    for value, symbol in pairs:\n        while n >= value:\n            result += symbol\n            n -= value\n    return result\n\nfor n in [1, 4, 9, 14]:\n    print(f\"{n} -> {to_roman(n)}\")", "填空罗马数字。", "def to_roman(n):\n    pairs = [(10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\")]\n    result = \"\"\n    for value, symbol in pairs:\n        while n >= value:\n            result += symbol\n            n -= value\n    return result\n\nfor n in [1, 4, 9, 14]:\n    print(f\"{n} -> {to_roman(n)}\")"),
    (28, "参数驱动排序稳定性演示。", "def stable_by(data, key):\n    return sorted(data, key=key)\n\npeople = [(\"A\", 25), (\"B\", 20), (\"C\", 25)]\nfor name, age in stable_by(people, lambda x: x[1]):\n    print(name, age)", "填空稳定排序。", "def stable_by(data, key):\n    return sorted(data, key=key)\n\npeople = [(\"A\", 25), (\"B\", 20), (\"C\", 25)]\nfor name, age in stable_by(people, lambda x: x[1]):\n    print(name, age)"),
    (29, "参数做多结果统计。", "def stats(nums):\n    return sum(nums), max(nums), min(nums)\n\ntotal, maximum, minimum = stats([3, 7, 2, 9])\nprint(total, maximum, minimum)", "填空多返回。", "def stats(nums):\n    return sum(nums), max(nums), min(nums)\n\ntotal, maximum, minimum = stats([3, 7, 2, 9])\nprint(total, maximum, minimum)"),
    (30, "综合：参数实现通用表格打印。", "def print_table(rows, headers=None, width=8):\n    if headers:\n        print(\" \".join(h.center(width) for h in headers))\n    for row in rows:\n        print(\" \".join(str(c).center(width) for c in row))\n\nprint_table([[1, 2], [3, 4]], headers=[\"A\", \"B\"], width=4)", "填空表格打印。", "def print_table(rows, headers=None, width=8):\n    if headers:\n        print(\" \".join(h.center(width) for h in headers))\n    for row in rows:\n        print(\" \".join(str(c).center(width) for c in row))\n\nprint_table([[1, 2], [3, 4]], headers=[\"A\", \"B\"], width=4)"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
