# -*- coding: utf-8 -*-
"""生成 CH08 循环 (while) 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH08"
TITLE = "循环 (while)"
OUT_DIR = "CH08_While_Loops"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "用 while 输出 1 到 3。", "i = 1\nwhile i <= 3:\n    print(___)\n    i += 1", "输出变量 i，并让 i 递增。", "i = 1\nwhile i <= 3:\n    print(i)\n    i += 1"),
    (2, "用 while 倒计时输出 3 到 1。", "i = 3\nwhile i >= 1:\n    print(___)\n    i -= 1", "输出变量 i，并让 i 递减。", "i = 3\nwhile i >= 1:\n    print(i)\n    i -= 1"),
    (3, "用 while 计数器从 0 加到 3。", "i = 0\nwhile i < 3:\n    print(___)\n    i += 1", "输出变量 i，并让 i 递增。", "i = 0\nwhile i < 3:\n    print(i)\n    i += 1"),
    (4, "用 while 累加 1 到 5。", "total = 0\ni = 1\nwhile i <= 5:\n    total += i\n    i += 1\nprint(___)\n", "输出 total。", "total = 0\ni = 1\nwhile i <= 5:\n    total += i\n    i += 1\nprint(total)"),
    (5, "用 while 累乘 1 到 4。", "product = 1\ni = 1\nwhile i <= 4:\n    product *= i\n    i += 1\nprint(___)\n", "输出 product。", "product = 1\ni = 1\nwhile i <= 4:\n    product *= i\n    i += 1\nprint(product)"),
    (6, "用 while 输出 1 到 10 的偶数。", "i = 2\nwhile i <= 10:\n    print(i)\n    i += 2", "填空步长。", "i = 2\nwhile i <= 10:\n    print(i)\n    i += 2"),
    (7, "循环中用 break 提前退出。", "i = 1\nwhile i <= 5:\n    if i == 3:\n        break\n    print(i)\n    i += 1", "填空 break。", "i = 1\nwhile i <= 5:\n    if i == 3:\n        break\n    print(i)\n    i += 1"),
    (8, "循环中用 continue 跳过 3。", "i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        continue\n    print(i)", "填空 continue。", "i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        continue\n    print(i)"),
    (9, "while 正常结束执行 else。", "i = 1\nwhile i <= 3:\n    print(i)\n    i += 1\nelse:\n    print(\"done\")", "填空 else 输出。", "i = 1\nwhile i <= 3:\n    print(i)\n    i += 1\nelse:\n    print(\"done\")"),
    (10, "用条件变量控制循环。", "flag = True\ni = 0\nwhile flag:\n    i += 1\n    print(i)\n    if i == 4:\n        flag = False", "填空 flag 终止。", "flag = True\ni = 0\nwhile flag:\n    i += 1\n    print(i)\n    if i == 4:\n        flag = False"),
    (11, "while 步长递增输出。", "i = 1\nwhile i < 10:\n    print(i)\n    i += 3", "填空步长 3。", "i = 1\nwhile i < 10:\n    print(i)\n    i += 3"),
    (12, "while 输出 1 到 3 的平方。", "i = 1\nwhile i <= 3:\n    print(i * i)\n    i += 1", "填空平方。", "i = 1\nwhile i <= 3:\n    print(i * i)\n    i += 1"),
    (13, "while 累加 1 到 10 的奇数。", "total = 0\ni = 1\nwhile i <= 10:\n    if i % 2 == 1:\n        total += i\n    i += 1\nprint(___)\n", "输出 total。", "total = 0\ni = 1\nwhile i <= 10:\n    if i % 2 == 1:\n        total += i\n    i += 1\nprint(total)"),
    (14, "用 while 求数字 123 的各位和。", "n = 123\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(___)\n", "输出 total。", "n = 123\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(total)"),
    (15, "用 while 求数字 123 的位数。", "n = 123\ncount = 0\nwhile n > 0:\n    count += 1\n    n //= 10\nprint(___)\n", "输出 count。", "n = 123\ncount = 0\nwhile n > 0:\n    count += 1\n    n //= 10\nprint(count)"),
    (16, "用 while 遍历列表索引。", "fruits = [\"a\", \"b\", \"c\"]\ni = 0\nwhile i < len(fruits):\n    print(fruits[i])\n    i += 1", "填空索引访问。", "fruits = [\"a\", \"b\", \"c\"]\ni = 0\nwhile i < len(fruits):\n    print(fruits[i])\n    i += 1"),
    (17, "while 打印星号递增。", "i = 1\nwhile i <= 3:\n    print(\"*\" * i)\n    i += 1", "填空重复。", "i = 1\nwhile i <= 3:\n    print(\"*\" * i)\n    i += 1"),
    (18, "while 循环固定次数。", "count = 0\nwhile count < 2:\n    print(\"Hi\")\n    count += 1", "填空计数。", "count = 0\nwhile count < 2:\n    print(\"Hi\")\n    count += 1"),
    (19, "while 中判断并输出。", "i = 1\nwhile i <= 4:\n    if i % 2 == 0:\n        print(\"even\", i)\n    i += 1", "填空判断。", "i = 1\nwhile i <= 4:\n    if i % 2 == 0:\n        print(\"even\", i)\n    i += 1"),
    (20, "while 计算 2 的幂。", "i = 1\nwhile i <= 3:\n    print(2 ** i)\n    i += 1", "填空幂运算。", "i = 1\nwhile i <= 3:\n    print(2 ** i)\n    i += 1"),
    (21, "while 取余循环判断。", "n = 10\nwhile n > 0:\n    print(n % 3)\n    n -= 3", "填空取余。", "n = 10\nwhile n > 0:\n    print(n % 3)\n    n -= 3"),
    (22, "while 整除循环。", "n = 100\nwhile n > 1:\n    n //= 2\n    print(n)", "填空整除。", "n = 100\nwhile n > 1:\n    n //= 2\n    print(n)"),
    (23, "while 索引访问字符串。", "s = \"ab\"\ni = 0\nwhile i < len(s):\n    print(s[i])\n    i += 1", "填空字符索引。", "s = \"ab\"\ni = 0\nwhile i < len(s):\n    print(s[i])\n    i += 1"),
    (24, "while 计数 1 到 8 中 2 的倍数。", "i = 1\ncount = 0\nwhile i <= 8:\n    if i % 2 == 0:\n        count += 1\n    i += 1\nprint(___)\n", "输出 count。", "i = 1\ncount = 0\nwhile i <= 8:\n    if i % 2 == 0:\n        count += 1\n    i += 1\nprint(count)"),
    (25, "while 累加不超过 10 的数。", "total = 0\ni = 1\nwhile total + i <= 10:\n    total += i\n    i += 1\nprint(___)\n", "输出 total。", "total = 0\ni = 1\nwhile total + i <= 10:\n    total += i\n    i += 1\nprint(total)"),
    (26, "while 递减输出。", "i = 5\nwhile i > 0:\n    print(i)\n    i -= 2", "填空递减 2。", "i = 5\nwhile i > 0:\n    print(i)\n    i -= 2"),
    (27, "while 累加偶数。", "total = 0\ni = 2\nwhile i <= 6:\n    total += i\n    i += 2\nprint(___)\n", "输出 total。", "total = 0\ni = 2\nwhile i <= 6:\n    total += i\n    i += 2\nprint(total)"),
    (28, "while 判断数字大小。", "i = 1\nwhile i <= 5:\n    if i > 3:\n        print(i, \"big\")\n    i += 1", "填空判断。", "i = 1\nwhile i <= 5:\n    if i > 3:\n        print(i, \"big\")\n    i += 1"),
    (29, "while 求和直到 0。", "nums = [5, 2, 1, 0, 3]\ntotal = 0\ni = 0\nwhile nums[i] != 0:\n    total += nums[i]\n    i += 1\nprint(___)\n", "输出 total。", "nums = [5, 2, 1, 0, 3]\ntotal = 0\ni = 0\nwhile nums[i] != 0:\n    total += nums[i]\n    i += 1\nprint(total)"),
    (30, "while 输出平方数直到超限。", "i = 1\nwhile i * i < 20:\n    print(i * i)\n    i += 1", "填空平方条件。", "i = 1\nwhile i * i < 20:\n    print(i * i)\n    i += 1"),
]

SIMPLE = [
    (1, "用 while 求 1 到 100 的和。", "total = 0\ni = 1\nwhile i <= 100:\n    total += i\n    i += 1\nprint(f\"Sum: {total}\")", "填空累加。", "total = 0\ni = 1\nwhile i <= 100:\n    total += i\n    i += 1\nprint(f\"Sum: {total}\")"),
    (2, "用 while 求 1 到 10 的平方和。", "total = 0\ni = 1\nwhile i <= 10:\n    total += i * i\n    i += 1\nprint(f\"Sum of squares: {total}\")", "填空平方累加。", "total = 0\ni = 1\nwhile i <= 10:\n    total += i * i\n    i += 1\nprint(f\"Sum of squares: {total}\")"),
    (3, "用 while 实现猜数字（固定答案）。", "secret = 7\nguess = 5\nwhile guess != secret:\n    if guess < secret:\n        print(\"too low\")\n    guess += 1\nprint(\"found:\", guess)", "填空循环条件。", "secret = 7\nguess = 5\nwhile guess != secret:\n    if guess < secret:\n        print(\"too low\")\n    guess += 1\nprint(\"found:\", guess)"),
    (4, "用 while 输出 1 到 9 的乘法表行。", "i = 1\nwhile i <= 9:\n    print(f\"3 x {i} = {3 * i}\")\n    i += 1", "填空乘法行。", "i = 1\nwhile i <= 9:\n    print(f\"3 x {i} = {3 * i}\")\n    i += 1"),
    (5, "用 while 统计字符串中元音个数。", "text = \"hello\"\ni = 0\ncount = 0\nwhile i < len(text):\n    if text[i] in \"aeiou\":\n        count += 1\n    i += 1\nprint(f\"Vowels: {count}\")", "填空索引计数。", "text = \"hello\"\ni = 0\ncount = 0\nwhile i < len(text):\n    if text[i] in \"aeiou\":\n        count += 1\n    i += 1\nprint(f\"Vowels: {count}\")"),
    (6, "用 while 求数字 1234 的反转。", "n = 1234\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(f\"Reversed: {rev}\")", "填空反转算法。", "n = 1234\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(f\"Reversed: {rev}\")"),
    (7, "用 while 求最大公约数（递减试探）。", "a, b = 12, 18\ng = min(a, b)\nwhile a % g != 0 or b % g != 0:\n    g -= 1\nprint(f\"GCD: {g}\")", "填空试探递减。", "a, b = 12, 18\ng = min(a, b)\nwhile a % g != 0 or b % g != 0:\n    g -= 1\nprint(f\"GCD: {g}\")"),
    (8, "用 while 生成斐波那契前 8 项。", "a, b = 0, 1\ncount = 0\nwhile count < 8:\n    print(a, end=\" \")\n    a, b = b, a + b\n    count += 1", "填空递推。", "a, b = 0, 1\ncount = 0\nwhile count < 8:\n    print(a, end=\" \")\n    a, b = b, a + b\n    count += 1"),
    (9, "用 while 判断 17 是否为质数。", "n = 17\nis_prime = True\nd = 2\nwhile d * d <= n:\n    if n % d == 0:\n        is_prime = False\n        break\n    d += 1\nprint(f\"{n} prime: {is_prime}\")", "填空试除。", "n = 17\nis_prime = True\nd = 2\nwhile d * d <= n:\n    if n % d == 0:\n        is_prime = False\n        break\n    d += 1\nprint(f\"{n} prime: {is_prime}\")"),
    (10, "用 while 统计列表中大于 3 的个数。", "nums = [2, 5, 4, 1, 6]\ni = 0\ncount = 0\nwhile i < len(nums):\n    if nums[i] > 3:\n        count += 1\n    i += 1\nprint(f\"Count: {count}\")", "填空索引遍历。", "nums = [2, 5, 4, 1, 6]\ni = 0\ncount = 0\nwhile i < len(nums):\n    if nums[i] > 3:\n        count += 1\n    i += 1\nprint(f\"Count: {count}\")"),
    (11, "用 while 计算平均分。", "scores = [88, 92, 76]\ntotal = 0\ni = 0\nwhile i < len(scores):\n    total += scores[i]\n    i += 1\nprint(f\"Average: {total / len(scores)}\")", "填空累加与平均。", "scores = [88, 92, 76]\ntotal = 0\ni = 0\nwhile i < len(scores):\n    total += scores[i]\n    i += 1\nprint(f\"Average: {total / len(scores)}\")"),
    (12, "用 while 输出 1 到 20 的偶数列表。", "i = 1\nevens = []\nwhile i <= 20:\n    if i % 2 == 0:\n        evens.append(i)\n    i += 1\nprint(evens)", "填空筛选添加。", "i = 1\nevens = []\nwhile i <= 20:\n    if i % 2 == 0:\n        evens.append(i)\n    i += 1\nprint(evens)"),
    (13, "用 while 求 n 的阶乘。", "n = 6\nfact = 1\ni = 1\nwhile i <= n:\n    fact *= i\n    i += 1\nprint(f\"6! = {fact}\")", "填空累乘。", "n = 6\nfact = 1\ni = 1\nwhile i <= n:\n    fact *= i\n    i += 1\nprint(f\"6! = {fact}\")"),
    (14, "用 while 求 2 的 1 到 5 次幂。", "i = 1\nwhile i <= 5:\n    print(f\"2^{i} = {2 ** i}\")\n    i += 1", "填空幂表。", "i = 1\nwhile i <= 5:\n    print(f\"2^{i} = {2 ** i}\")\n    i += 1"),
    (15, "用 while 找到列表中第一个偶数。", "nums = [1, 3, 4, 5]\ni = 0\nwhile i < len(nums):\n    if nums[i] % 2 == 0:\n        print(f\"Found: {nums[i]}\")\n        break\n    i += 1", "填空查找。", "nums = [1, 3, 4, 5]\ni = 0\nwhile i < len(nums):\n    if nums[i] % 2 == 0:\n        print(f\"Found: {nums[i]}\")\n        break\n    i += 1"),
    (16, "用 while 求字符串长度（不用 len）。", "s = \"hello\"\ncount = 0\nwhile count < len(s):\n    count += 1\nprint(f\"Length: {count}\")", "填空计数。", "s = \"hello\"\ncount = 0\nwhile count < len(s):\n    count += 1\nprint(f\"Length: {count}\")"),
    (17, "用 while 判断回文数。", "n = 121\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif rev == n:\n    print(\"palindrome\")\nelse:\n    print(\"not palindrome\")", "填空反转比较。", "n = 121\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif rev == n:\n    print(\"palindrome\")\nelse:\n    print(\"not palindrome\")"),
    (18, "用 while 输出乘法表。", "i = 1\nwhile i <= 3:\n    j = 1\n    while j <= 3:\n        print(i * j, end=\" \")\n        j += 1\n    print()\n    i += 1", "填空嵌套 while。", "i = 1\nwhile i <= 3:\n    j = 1\n    while j <= 3:\n        print(i * j, end=\" \")\n        j += 1\n    print()\n    i += 1"),
    (19, "用 while 累加直到和大于 20。", "total = 0\ni = 1\nwhile total <= 20:\n    total += i\n    i += 1\nprint(f\"Total: {total}\")", "填空累加条件。", "total = 0\ni = 1\nwhile total <= 20:\n    total += i\n    i += 1\nprint(f\"Total: {total}\")"),
    (20, "用 while 求 1 到 50 的奇数之和。", "total = 0\ni = 1\nwhile i <= 50:\n    if i % 2 == 1:\n        total += i\n    i += 1\nprint(f\"Odd sum: {total}\")", "填空奇数累加。", "total = 0\ni = 1\nwhile i <= 50:\n    if i % 2 == 1:\n        total += i\n    i += 1\nprint(f\"Odd sum: {total}\")"),
    (21, "用 while 逐字符反转字符串。", "s = \"abc\"\nreversed_s = \"\"\ni = len(s) - 1\nwhile i >= 0:\n    reversed_s += s[i]\n    i -= 1\nprint(reversed_s)", "填空倒序拼接。", "s = \"abc\"\nreversed_s = \"\"\ni = len(s) - 1\nwhile i >= 0:\n    reversed_s += s[i]\n    i -= 1\nprint(reversed_s)"),
    (22, "用 while 求列表最大值。", "nums = [3, 9, 5, 7]\nmaximum = nums[0]\ni = 1\nwhile i < len(nums):\n    if nums[i] > maximum:\n        maximum = nums[i]\n    i += 1\nprint(f\"Max: {maximum}\")", "填空比较更新。", "nums = [3, 9, 5, 7]\nmaximum = nums[0]\ni = 1\nwhile i < len(nums):\n    if nums[i] > maximum:\n        maximum = nums[i]\n    i += 1\nprint(f\"Max: {maximum}\")"),
    (23, "用 while 统计单词个数。", "text = \"hello world python\"\nwords = text.split()\ni = 0\ncount = 0\nwhile i < len(words):\n    count += 1\n    i += 1\nprint(f\"Words: {count}\")", "填空遍历计数。", "text = \"hello world python\"\nwords = text.split()\ni = 0\ncount = 0\nwhile i < len(words):\n    count += 1\n    i += 1\nprint(f\"Words: {count}\")"),
    (24, "用 while 求数字各位乘积。", "n = 234\ndigits = [int(d) for d in str(n)]\nproduct = 1\ni = 0\nwhile i < len(digits):\n    product *= digits[i]\n    i += 1\nprint(f\"Product: {product}\")", "填空累乘。", "n = 234\ndigits = [int(d) for d in str(n)]\nproduct = 1\ni = 0\nwhile i < len(digits):\n    product *= digits[i]\n    i += 1\nprint(f\"Product: {product}\")"),
    (25, "用 while 输出右对齐三角形。", "i = 1\nwhile i <= 4:\n    print(\" \" * (4 - i) + \"*\" * i)\n    i += 1", "填空对齐。", "i = 1\nwhile i <= 4:\n    print(\" \" * (4 - i) + \"*\" * i)\n    i += 1"),
    (26, "用 while 模拟 7 的倍数表。", "i = 7\nwhile i <= 35:\n    print(i)\n    i += 7", "填空步长 7。", "i = 7\nwhile i <= 35:\n    print(i)\n    i += 7"),
    (27, "用 while 求两个数的最大公约数（辗转相除）。", "a, b = 48, 36\nwhile b:\n    a, b = b, a % b\nprint(f\"GCD: {a}\")", "填空辗转相除。", "a, b = 48, 36\nwhile b:\n    a, b = b, a % b\nprint(f\"GCD: {a}\")"),
    (28, "用 while 输出数字三角形。", "i = 1\nwhile i <= 4:\n    print(str(i) * i)\n    i += 1", "填空重复。", "i = 1\nwhile i <= 4:\n    print(str(i) * i)\n    i += 1"),
    (29, "用 while 判断完全平方数。", "n = 81\nroot = 1\nwhile root * root < n:\n    root += 1\nif root * root == n:\n    print(\"perfect square\")\nelse:\n    print(\"not\")", "填空递增试探。", "n = 81\nroot = 1\nwhile root * root < n:\n    root += 1\nif root * root == n:\n    print(\"perfect square\")\nelse:\n    print(\"not\")"),
    (30, "用 while 综合：求 1 到 10 偶数个数与和。", "i = 1\ncount = 0\ntotal = 0\nwhile i <= 10:\n    if i % 2 == 0:\n        count += 1\n        total += i\n    i += 1\nprint(f\"Evens: {count}, Sum: {total}\")", "填空双统计。", "i = 1\ncount = 0\ntotal = 0\nwhile i <= 10:\n    if i % 2 == 0:\n        count += 1\n        total += i\n    i += 1\nprint(f\"Evens: {count}, Sum: {total}\")"),
]

MEDIUM = [
    (1, "用 while 实现猜数字游戏（多次尝试）。", "secret = 7\nguesses = [3, 5, 7]\ni = 0\nwhile i < len(guesses):\n    g = guesses[i]\n    if g == secret:\n        print(\"Correct!\")\n        break\n    elif g < secret:\n        print(\"Too low\")\n    else:\n        print(\"Too high\")\n    i += 1", "填空猜数字。", "secret = 7\nguesses = [3, 5, 7]\ni = 0\nwhile i < len(guesses):\n    g = guesses[i]\n    if g == secret:\n        print(\"Correct!\")\n        break\n    elif g < secret:\n        print(\"Too low\")\n    else:\n        print(\"Too high\")\n    i += 1"),
    (2, "用 while 求 100 以内的素数个数。", "n = 2\ncount = 0\nwhile n <= 100:\n    is_prime = True\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            is_prime = False\n            break\n        d += 1\n    if is_prime:\n        count += 1\n    n += 1\nprint(f\"Primes: {count}\")", "填空素数计数。", "n = 2\ncount = 0\nwhile n <= 100:\n    is_prime = True\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            is_prime = False\n            break\n        d += 1\n    if is_prime:\n        count += 1\n    n += 1\nprint(f\"Primes: {count}\")"),
    (3, "用 while 输出斐波那契序列（对）。", "a, b = 0, 1\ncount = 0\nwhile count < 10:\n    print(f\"fib({count}) = {a}\")\n    a, b = b, a + b\n    count += 1", "填空递推输出。", "a, b = 0, 1\ncount = 0\nwhile count < 10:\n    print(f\"fib({count}) = {a}\")\n    a, b = b, a + b\n    count += 1"),
    (4, "用 while 求两个数的最小公倍数。", "a, b = 4, 6\nm = max(a, b)\nwhile m % a != 0 or m % b != 0:\n    m += 1\nprint(f\"LCM: {m}\")", "填空递增求 lcm。", "a, b = 4, 6\nm = max(a, b)\nwhile m % a != 0 or m % b != 0:\n    m += 1\nprint(f\"LCM: {m}\")"),
    (5, "用 while 实现数字进制转换（十进制转二进制）。", "n = 10\nbits = []\nwhile n > 0:\n    bits.append(str(n % 2))\n    n //= 2\nprint(\"\".join(reversed(bits)))", "填空除 2 取余。", "n = 10\nbits = []\nwhile n > 0:\n    bits.append(str(n % 2))\n    n //= 2\nprint(\"\".join(reversed(bits)))"),
    (6, "用 while 统计字符串中单词长度分布。", "text = \"a bb ccc\"\nwords = text.split()\ni = 0\nlengths = []\nwhile i < len(words):\n    lengths.append(len(words[i]))\n    i += 1\nprint(lengths)", "填空长度收集。", "text = \"a bb ccc\"\nwords = text.split()\ni = 0\nlengths = []\nwhile i < len(words):\n    lengths.append(len(words[i]))\n    i += 1\nprint(lengths)"),
    (7, "用 while 求数字各位之和（多数字）。", "nums = [123, 45, 6]\ni = 0\nwhile i < len(nums):\n    n = nums[i]\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    print(f\"{nums[i]}: {total}\")\n    i += 1", "填空嵌套位和。", "nums = [123, 45, 6]\ni = 0\nwhile i < len(nums):\n    n = nums[i]\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    print(f\"{nums[i]}: {total}\")\n    i += 1"),
    (8, "用 while 求 1 到 100 中 7 的倍数和。", "total = 0\ni = 7\nwhile i <= 100:\n    total += i\n    i += 7\nprint(f\"Sum: {total}\")", "填空倍数累加。", "total = 0\ni = 7\nwhile i <= 100:\n    total += i\n    i += 7\nprint(f\"Sum: {total}\")"),
    (9, "用 while 生成乘法口诀表。", "i = 1\nwhile i <= 5:\n    j = 1\n    row = []\n    while j <= i:\n        row.append(f\"{j}x{i}={i * j}\")\n        j += 1\n    print(\" \".join(row))\n    i += 1", "填空口诀表。", "i = 1\nwhile i <= 5:\n    j = 1\n    row = []\n    while j <= i:\n        row.append(f\"{j}x{i}={i * j}\")\n        j += 1\n    print(\" \".join(row))\n    i += 1"),
    (10, "用 while 判断回文数并输出过程。", "n = 1221\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif n == rev:\n    print(f\"{n} is palindrome\")\nelse:\n    print(f\"{n} is not\")", "填空回文判断。", "n = 1221\ntemp = n\nrev = 0\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nif n == rev:\n    print(f\"{n} is palindrome\")\nelse:\n    print(f\"{n} is not\")"),
    (11, "用 while 模拟用户输入直到正确（固定值）。", "correct = \"python\"\nattempts = [\"java\", \"python\"]\ni = 0\nwhile attempts[i] != correct:\n    print(f\"{attempts[i]} is wrong\")\n    i += 1\nprint(\"login ok\")", "填空验证循环。", "correct = \"python\"\nattempts = [\"java\", \"python\"]\ni = 0\nwhile attempts[i] != correct:\n    print(f\"{attempts[i]} is wrong\")\n    i += 1\nprint(\"login ok\")"),
    (12, "用 while 统计矩阵中正数个数。", "matrix = [[1, -2], [3, -4], [5, 6]]\ni = 0\ncount = 0\nwhile i < len(matrix):\n    j = 0\n    while j < len(matrix[i]):\n        if matrix[i][j] > 0:\n            count += 1\n        j += 1\n    i += 1\nprint(f\"Positive: {count}\")", "填空矩阵遍历。", "matrix = [[1, -2], [3, -4], [5, 6]]\ni = 0\ncount = 0\nwhile i < len(matrix):\n    j = 0\n    while j < len(matrix[i]):\n        if matrix[i][j] > 0:\n            count += 1\n        j += 1\n    i += 1\nprint(f\"Positive: {count}\")"),
    (13, "用 while 求数字反转并比较。", "nums = [123, 321]\ni = 0\nwhile i < len(nums):\n    n = nums[i]\n    rev = 0\n    while n > 0:\n        rev = rev * 10 + n % 10\n        n //= 10\n    print(f\"{nums[i]} -> {rev}\")\n    i += 1", "填空多数字反转。", "nums = [123, 321]\ni = 0\nwhile i < len(nums):\n    n = nums[i]\n    rev = 0\n    while n > 0:\n        rev = rev * 10 + n % 10\n        n //= 10\n    print(f\"{nums[i]} -> {rev}\")\n    i += 1"),
    (14, "用 while 输出 1 到 20 的完全平方数。", "n = 1\nsquares = []\nwhile n <= 20:\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares.append(n)\n    n += 1\nprint(squares)", "填空平方判断。", "n = 1\nsquares = []\nwhile n <= 20:\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares.append(n)\n    n += 1\nprint(squares)"),
    (15, "用 while 模拟存款利息增长。", "balance = 1000\nrate = 0.05\nyears = 0\nwhile balance < 1200:\n    balance *= 1 + rate\n    years += 1\nprint(f\"Years: {years}, Balance: {balance:.2f}\")", "填空复利循环。", "balance = 1000\nrate = 0.05\nyears = 0\nwhile balance < 1200:\n    balance *= 1 + rate\n    years += 1\nprint(f\"Years: {years}, Balance: {balance:.2f}\")"),
    (16, "用 while 求字符串中最长单词。", "text = \"the quick brown fox\"\nwords = text.split()\nlongest = \"\"\ni = 0\nwhile i < len(words):\n    if len(words[i]) > len(longest):\n        longest = words[i]\n    i += 1\nprint(f\"Longest: {longest}\")", "填空最长查找。", "text = \"the quick brown fox\"\nwords = text.split()\nlongest = \"\"\ni = 0\nwhile i < len(words):\n    if len(words[i]) > len(longest):\n        longest = words[i]\n    i += 1\nprint(f\"Longest: {longest}\")"),
    (17, "用 while 计算平均温度。", "temps = [20, 25, 30, 35]\ntotal = 0\ni = 0\nwhile i < len(temps):\n    total += temps[i]\n    i += 1\navg = total / len(temps)\nprint(f\"Average: {avg}\")", "填空温度平均。", "temps = [20, 25, 30, 35]\ntotal = 0\ni = 0\nwhile i < len(temps):\n    total += temps[i]\n    i += 1\navg = total / len(temps)\nprint(f\"Average: {avg}\")"),
    (18, "用 while 求数组的最大子段和（简化）。", "nums = [1, -2, 3, 4, -1]\nmax_sum = nums[0]\ni = 0\nwhile i < len(nums):\n    cur = 0\n    j = i\n    while j < len(nums):\n        cur += nums[j]\n        if cur > max_sum:\n            max_sum = cur\n        j += 1\n    i += 1\nprint(max_sum)", "填空子段扫描。", "nums = [1, -2, 3, 4, -1]\nmax_sum = nums[0]\ni = 0\nwhile i < len(nums):\n    cur = 0\n    j = i\n    while j < len(nums):\n        cur += nums[j]\n        if cur > max_sum:\n            max_sum = cur\n        j += 1\n    i += 1\nprint(max_sum)"),
    (19, "用 while 生成 4x4 棋盘。", "i = 0\nwhile i < 4:\n    row = \"\"\n    j = 0\n    while j < 4:\n        row += \"#\" if (i + j) % 2 == 0 else \".\"\n        j += 1\n    print(row)\n    i += 1", "填空棋盘生成。", "i = 0\nwhile i < 4:\n    row = \"\"\n    j = 0\n    while j < 4:\n        row += \"#\" if (i + j) % 2 == 0 else \".\"\n        j += 1\n    print(row)\n    i += 1"),
    (20, "用 while 求 1 到 100 的偶数和与奇数和。", "i = 1\neven_sum = 0\nodd_sum = 0\nwhile i <= 100:\n    if i % 2 == 0:\n        even_sum += i\n    else:\n        odd_sum += i\n    i += 1\nprint(f\"Even: {even_sum}, Odd: {odd_sum}\")", "填空双累加。", "i = 1\neven_sum = 0\nodd_sum = 0\nwhile i <= 100:\n    if i % 2 == 0:\n        even_sum += i\n    else:\n        odd_sum += i\n    i += 1\nprint(f\"Even: {even_sum}, Odd: {odd_sum}\")"),
    (21, "用 while 判断 2 的幂。", "n = 64\nis_power = True\nwhile n > 1:\n    if n % 2 != 0:\n        is_power = False\n        break\n    n //= 2\nprint(f\"Is power of 2: {is_power}\")", "填空幂判断。", "n = 64\nis_power = True\nwhile n > 1:\n    if n % 2 != 0:\n        is_power = False\n        break\n    n //= 2\nprint(f\"Is power of 2: {is_power}\")"),
    (22, "用 while 统计成绩分档。", "scores = [55, 72, 88, 91, 63]\ni = 0\ngrades = [\"A\", \"B\", \"C\", \"D\", \"F\"]\ncounts = [0, 0, 0, 0, 0]\nwhile i < len(scores):\n    s = scores[i]\n    if s >= 90:\n        counts[0] += 1\n    elif s >= 80:\n        counts[1] += 1\n    elif s >= 70:\n        counts[2] += 1\n    elif s >= 60:\n        counts[3] += 1\n    else:\n        counts[4] += 1\n    i += 1\nfor g, c in zip(grades, counts):\n    print(f\"{g}: {c}\")", "填空分档统计。", "scores = [55, 72, 88, 91, 63]\ni = 0\ngrades = [\"A\", \"B\", \"C\", \"D\", \"F\"]\ncounts = [0, 0, 0, 0, 0]\nwhile i < len(scores):\n    s = scores[i]\n    if s >= 90:\n        counts[0] += 1\n    elif s >= 80:\n        counts[1] += 1\n    elif s >= 70:\n        counts[2] += 1\n    elif s >= 60:\n        counts[3] += 1\n    else:\n        counts[4] += 1\n    i += 1\nfor g, c in zip(grades, counts):\n    print(f\"{g}: {c}\")"),
    (23, "用 while 求最小公倍数（多组）。", "pairs = [(3, 4), (6, 8), (5, 7)]\ni = 0\nwhile i < len(pairs):\n    a, b = pairs[i]\n    m = max(a, b)\n    while m % a != 0 or m % b != 0:\n        m += 1\n    print(f\"lcm({a}, {b}) = {m}\")\n    i += 1", "填空多组 lcm。", "pairs = [(3, 4), (6, 8), (5, 7)]\ni = 0\nwhile i < len(pairs):\n    a, b = pairs[i]\n    m = max(a, b)\n    while m % a != 0 or m % b != 0:\n        m += 1\n    print(f\"lcm({a}, {b}) = {m}\")\n    i += 1"),
    (24, "用 while 求数字的二进制中 1 的个数。", "n = 29\ncount = 0\nwhile n:\n    count += n & 1\n    n >>= 1\nprint(f\"Bits: {count}\")", "填空位计数。", "n = 29\ncount = 0\nwhile n:\n    count += n & 1\n    n >>= 1\nprint(f\"Bits: {count}\")"),
    (25, "用 while 输出数字塔。", "i = 1\nwhile i <= 4:\n    line = \"\"\n    j = 1\n    while j <= i:\n        line += str(j)\n        j += 1\n    print(line)\n    i += 1", "填空数字塔。", "i = 1\nwhile i <= 4:\n    line = \"\"\n    j = 1\n    while j <= i:\n        line += str(j)\n        j += 1\n    print(line)\n    i += 1"),
    (26, "用 while 模拟进度（百分比）。", "i = 0\nwhile i <= 100:\n    if i % 25 == 0:\n        print(f\"{i}%\")\n    i += 25", "填空进度输出。", "i = 0\nwhile i <= 100:\n    if i % 25 == 0:\n        print(f\"{i}%\")\n    i += 25"),
    (27, "用 while 求两数之差最小配对。", "nums = [1, 5, 3, 9]\nnums.sort()\nmin_diff = nums[1] - nums[0]\ni = 1\nwhile i < len(nums) - 1:\n    diff = nums[i + 1] - nums[i]\n    if diff < min_diff:\n        min_diff = diff\n    i += 1\nprint(f\"Min diff: {min_diff}\")", "填空最小差。", "nums = [1, 5, 3, 9]\nnums.sort()\nmin_diff = nums[1] - nums[0]\ni = 1\nwhile i < len(nums) - 1:\n    diff = nums[i + 1] - nums[i]\n    if diff < min_diff:\n        min_diff = diff\n    i += 1\nprint(f\"Min diff: {min_diff}\")"),
    (28, "用 while 统计字母出现次数。", "text = \"banana\"\ntarget = \"a\"\ni = 0\ncount = 0\nwhile i < len(text):\n    if text[i] == target:\n        count += 1\n    i += 1\nprint(f\"'{target}' appears {count} times\")", "填空字母计数。", "text = \"banana\"\ntarget = \"a\"\ni = 0\ncount = 0\nwhile i < len(text):\n    if text[i] == target:\n        count += 1\n    i += 1\nprint(f\"'{target}' appears {count} times\")"),
    (29, "用 while 求 3n+1 序列长度。", "n = 6\nsteps = 0\nwhile n != 1:\n    if n % 2 == 0:\n        n //= 2\n    else:\n        n = n * 3 + 1\n    steps += 1\nprint(f\"Steps: {steps}\")", "填空 3n+1。", "n = 6\nsteps = 0\nwhile n != 1:\n    if n % 2 == 0:\n        n //= 2\n    else:\n        n = n * 3 + 1\n    steps += 1\nprint(f\"Steps: {steps}\")"),
    (30, "用 while 综合：验证角谷猜想（1 到 10）。", "for start in range(1, 11):\n    n = start\n    steps = 0\n    while n != 1:\n        if n % 2 == 0:\n            n //= 2\n        else:\n            n = n * 3 + 1\n        steps += 1\n    print(f\"{start}: {steps} steps\")", "填空猜想验证。", "for start in range(1, 11):\n    n = start\n    steps = 0\n    while n != 1:\n        if n % 2 == 0:\n            n //= 2\n        else:\n            n = n * 3 + 1\n        steps += 1\n    print(f\"{start}: {steps} steps\")"),
]

HARD = [
    (1, "用 while 实现十进制转任意进制。", "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\nprint(to_base(255, 16), to_base(100, 2))", "填空取余拼接。", "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\nprint(to_base(255, 16), to_base(100, 2))"),
    (2, "用 while 实现快速幂。", "def fast_pow(base, exp):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n        base *= base\n        exp //= 2\n    return result\nprint(fast_pow(2, 10), fast_pow(3, 4))", "填空快速幂。", "def fast_pow(base, exp):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n        base *= base\n        exp //= 2\n    return result\nprint(fast_pow(2, 10), fast_pow(3, 4))"),
    (3, "用 while 求最大公约数（多组）。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\npairs = [(12, 18), (35, 10), (17, 5)]\ni = 0\nwhile i < len(pairs):\n    a, b = pairs[i]\n    print(f\"gcd({a}, {b}) = {gcd(a, b)}\")\n    i += 1", "填空多组 gcd。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\npairs = [(12, 18), (35, 10), (17, 5)]\ni = 0\nwhile i < len(pairs):\n    a, b = pairs[i]\n    print(f\"gcd({a}, {b}) = {gcd(a, b)}\")\n    i += 1"),
    (4, "用 while 求平方根近似（牛顿法）。", "n = 50\nx = n / 2\nwhile abs(x * x - n) > 1e-6:\n    x = (x + n / x) / 2\nprint(f\"sqrt({n}) ≈ {x:.4f}\")", "填空牛顿迭代。", "n = 50\nx = n / 2\nwhile abs(x * x - n) > 1e-6:\n    x = (x + n / x) / 2\nprint(f\"sqrt({n}) ≈ {x:.4f}\")"),
    (5, "用 while 输出 100 以内的质数。", "n = 2\nprimes = []\nwhile n <= 100:\n    is_prime = True\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            is_prime = False\n            break\n        d += 1\n    if is_prime:\n        primes.append(n)\n    n += 1\nprint(primes)", "填空质数收集。", "n = 2\nprimes = []\nwhile n <= 100:\n    is_prime = True\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            is_prime = False\n            break\n        d += 1\n    if is_prime:\n        primes.append(n)\n    n += 1\nprint(primes)"),
    (6, "用 while 求第 n 个斐波那契数。", "def fib(n):\n    a, b = 0, 1\n    count = 0\n    while count < n:\n        a, b = b, a + b\n        count += 1\n    return a\nfor n in [5, 10]:\n    print(f\"fib({n}) = {fib(n)}\")", "填空斐波那契函数。", "def fib(n):\n    a, b = 0, 1\n    count = 0\n    while count < n:\n        a, b = b, a + b\n        count += 1\n    return a\nfor n in [5, 10]:\n    print(f\"fib({n}) = {fib(n)}\")"),
    (7, "用 while 模拟猜数字统计次数。", "secret = 7\nattempts = [2, 4, 6, 7]\ni = 0\nwhile i < len(attempts):\n    g = attempts[i]\n    if g == secret:\n        print(f\"Correct in {i + 1} tries\")\n        break\n    elif g < secret:\n        print(f\"Try {i + 1}: too low\")\n    else:\n        print(f\"Try {i + 1}: too high\")\n    i += 1", "填空猜数字统计。", "secret = 7\nattempts = [2, 4, 6, 7]\ni = 0\nwhile i < len(attempts):\n    g = attempts[i]\n    if g == secret:\n        print(f\"Correct in {i + 1} tries\")\n        break\n    elif g < secret:\n        print(f\"Try {i + 1}: too low\")\n    else:\n        print(f\"Try {i + 1}: too high\")\n    i += 1"),
    (8, "用 while 实现大数乘法（字符串）。", "def str_multiply(s, n):\n    result = \"\"\n    carry = 0\n    i = len(s) - 1\n    while i >= 0:\n        prod = int(s[i]) * n + carry\n        result = str(prod % 10) + result\n        carry = prod // 10\n        i -= 1\n    if carry:\n        result = str(carry) + result\n    return result\nprint(str_multiply(\"123\", 3))", "填空逐位乘法。", "def str_multiply(s, n):\n    result = \"\"\n    carry = 0\n    i = len(s) - 1\n    while i >= 0:\n        prod = int(s[i]) * n + carry\n        result = str(prod % 10) + result\n        carry = prod // 10\n        i -= 1\n    if carry:\n        result = str(carry) + result\n    return result\nprint(str_multiply(\"123\", 3))"),
    (9, "用 while 输出杨辉三角。", "rows = 5\ntriangle = []\ni = 0\nwhile i < rows:\n    row = [1] * (i + 1)\n    j = 1\n    while j < i:\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n        j += 1\n    triangle.append(row)\n    i += 1\nfor row in triangle:\n    print(row)", "填空杨辉三角。", "rows = 5\ntriangle = []\ni = 0\nwhile i < rows:\n    row = [1] * (i + 1)\n    j = 1\n    while j < i:\n        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n        j += 1\n    triangle.append(row)\n    i += 1\nfor row in triangle:\n    print(row)"),
    (10, "用 while 求水仙花数。", "n = 100\nwhile n < 500:\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)\n    n += 1", "填空水仙花。", "n = 100\nwhile n < 500:\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)\n    n += 1"),
    (11, "用 while 模拟银行取款（面额组合）。", "amount = 78\nbills = [50, 20, 10, 5, 1]\ni = 0\nwhile i < len(bills):\n    count = amount // bills[i]\n    if count:\n        print(f\"{bills[i]} x {count}\")\n    amount %= bills[i]\n    i += 1", "填空找零。", "amount = 78\nbills = [50, 20, 10, 5, 1]\ni = 0\nwhile i < len(bills):\n    count = amount // bills[i]\n    if count:\n        print(f\"{bills[i]} x {count}\")\n    amount %= bills[i]\n    i += 1"),
    (12, "用 while 求最大回文乘积（简化）。", "max_pal = 0\nfor i in range(10, 100):\n    for j in range(10, 100):\n        prod = i * j\n        if str(prod) == str(prod)[::-1] and prod > max_pal:\n            max_pal = prod\nprint(max_pal)", "填空回文乘积。", "max_pal = 0\nfor i in range(10, 100):\n    for j in range(10, 100):\n        prod = i * j\n        if str(prod) == str(prod)[::-1] and prod > max_pal:\n            max_pal = prod\nprint(max_pal)"),
    (13, "用 while 统计每个字符出现次数。", "text = \"hello world\"\ncounts = {}\ni = 0\nwhile i < len(text):\n    ch = text[i]\n    counts[ch] = counts.get(ch, 0) + 1\n    i += 1\nfor ch in sorted(counts):\n    print(f\"{repr(ch)}: {counts[ch]}\")", "填空字符统计。", "text = \"hello world\"\ncounts = {}\ni = 0\nwhile i < len(text):\n    ch = text[i]\n    counts[ch] = counts.get(ch, 0) + 1\n    i += 1\nfor ch in sorted(counts):\n    print(f\"{repr(ch)}: {counts[ch]}\")"),
    (14, "用 while 求两个有序列表的合并。", "a = [1, 3, 5]\nb = [2, 4, 6]\nmerged = []\ni = j = 0\nwhile i < len(a) and j < len(b):\n    if a[i] < b[j]:\n        merged.append(a[i])\n        i += 1\n    else:\n        merged.append(b[j])\n        j += 1\nmerged.extend(a[i:])\nmerged.extend(b[j:])\nprint(merged)", "填空双指针合并。", "a = [1, 3, 5]\nb = [2, 4, 6]\nmerged = []\ni = j = 0\nwhile i < len(a) and j < len(b):\n    if a[i] < b[j]:\n        merged.append(a[i])\n        i += 1\n    else:\n        merged.append(b[j])\n        j += 1\nmerged.extend(a[i:])\nmerged.extend(b[j:])\nprint(merged)"),
    (15, "用 while 判断并输出素数对。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\nn = 2\nwhile n < 20:\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)\n    n += 1", "填空孪生素数。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\nn = 2\nwhile n < 20:\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)\n    n += 1"),
    (16, "用 while 求最长连续递增段。", "nums = [1, 2, 3, 1, 2, 3, 4]\nmax_len = 1\ncur_len = 1\ni = 1\nwhile i < len(nums):\n    if nums[i] > nums[i - 1]:\n        cur_len += 1\n        max_len = max(max_len, cur_len)\n    else:\n        cur_len = 1\n    i += 1\nprint(f\"Longest: {max_len}\")", "填空递增段。", "nums = [1, 2, 3, 1, 2, 3, 4]\nmax_len = 1\ncur_len = 1\ni = 1\nwhile i < len(nums):\n    if nums[i] > nums[i - 1]:\n        cur_len += 1\n        max_len = max(max_len, cur_len)\n    else:\n        cur_len = 1\n    i += 1\nprint(f\"Longest: {max_len}\")"),
    (17, "用 while 模拟除法（整除与余数）。", "a, b = 17, 5\nquotient = 0\nwhile a >= b:\n    a -= b\n    quotient += 1\nprint(f\"Quotient: {quotient}, Remainder: {a}\")", "填空减法除法。", "a, b = 17, 5\nquotient = 0\nwhile a >= b:\n    a -= b\n    quotient += 1\nprint(f\"Quotient: {quotient}, Remainder: {a}\")"),
    (18, "用 while 生成螺旋矩阵。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\nnum = 1\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nwhile top <= bottom and left <= right:\n    j = left\n    while j <= right:\n        matrix[top][j] = num\n        num += 1\n        j += 1\n    top += 1\n    i = top\n    while i <= bottom:\n        matrix[i][right] = num\n        num += 1\n        i += 1\n    right -= 1\n    j = right\n    while j >= left:\n        matrix[bottom][j] = num\n        num += 1\n        j -= 1\n    bottom -= 1\n    i = bottom\n    while i >= top:\n        matrix[i][left] = num\n        num += 1\n        i -= 1\n    left += 1\nfor row in matrix:\n    print(row)", "填空螺旋矩阵。", "n = 3\nmatrix = [[0] * n for _ in range(n)]\nnum = 1\ntop, bottom, left, right = 0, n - 1, 0, n - 1\nwhile top <= bottom and left <= right:\n    j = left\n    while j <= right:\n        matrix[top][j] = num\n        num += 1\n        j += 1\n    top += 1\n    i = top\n    while i <= bottom:\n        matrix[i][right] = num\n        num += 1\n        i += 1\n    right -= 1\n    j = right\n    while j >= left:\n        matrix[bottom][j] = num\n        num += 1\n        j -= 1\n    bottom -= 1\n    i = bottom\n    while i >= top:\n        matrix[i][left] = num\n        num += 1\n        i -= 1\n    left += 1\nfor row in matrix:\n    print(row)"),
    (19, "用 while 求字符串中最长单词长度。", "text = \"the quick brown fox jumps\"\nwords = text.split()\nmax_len = 0\ni = 0\nwhile i < len(words):\n    if len(words[i]) > max_len:\n        max_len = len(words[i])\n    i += 1\nprint(f\"Longest word length: {max_len}\")", "填空最长长度。", "text = \"the quick brown fox jumps\"\nwords = text.split()\nmax_len = 0\ni = 0\nwhile i < len(words):\n    if len(words[i]) > max_len:\n        max_len = len(words[i])\n    i += 1\nprint(f\"Longest word length: {max_len}\")"),
    (20, "用 while 模拟二进制加法。", "def bin_add(a, b):\n    result = \"\"\n    carry = 0\n    i = len(a) - 1\n    j = len(b) - 1\n    while i >= 0 or j >= 0 or carry:\n        x = int(a[i]) if i >= 0 else 0\n        y = int(b[j]) if j >= 0 else 0\n        total = x + y + carry\n        result = str(total % 2) + result\n        carry = total // 2\n        i -= 1\n        j -= 1\n    return result\nprint(bin_add(\"101\", \"11\"))", "填空二进制加法。", "def bin_add(a, b):\n    result = \"\"\n    carry = 0\n    i = len(a) - 1\n    j = len(b) - 1\n    while i >= 0 or j >= 0 or carry:\n        x = int(a[i]) if i >= 0 else 0\n        y = int(b[j]) if j >= 0 else 0\n        total = x + y + carry\n        result = str(total % 2) + result\n        carry = total // 2\n        i -= 1\n        j -= 1\n    return result\nprint(bin_add(\"101\", \"11\"))"),
    (21, "用 while 求数组的众数。", "nums = [1, 3, 3, 2, 3, 1]\ncounts = {}\ni = 0\nwhile i < len(nums):\n    counts[nums[i]] = counts.get(nums[i], 0) + 1\n    i += 1\nmode = max(counts, key=counts.get)\nprint(f\"Mode: {mode} ({counts[mode]} times)\")", "填空众数。", "nums = [1, 3, 3, 2, 3, 1]\ncounts = {}\ni = 0\nwhile i < len(nums):\n    counts[nums[i]] = counts.get(nums[i], 0) + 1\n    i += 1\nmode = max(counts, key=counts.get)\nprint(f\"Mode: {mode} ({counts[mode]} times)\")"),
    (22, "用 while 求矩阵转置。", "matrix = [[1, 2, 3], [4, 5, 6]]\nrows = len(matrix)\ncols = len(matrix[0])\ntransposed = [[0] * rows for _ in range(cols)]\ni = 0\nwhile i < rows:\n    j = 0\n    while j < cols:\n        transposed[j][i] = matrix[i][j]\n        j += 1\n    i += 1\nprint(transposed)", "填空转置。", "matrix = [[1, 2, 3], [4, 5, 6]]\nrows = len(matrix)\ncols = len(matrix[0])\ntransposed = [[0] * rows for _ in range(cols)]\ni = 0\nwhile i < rows:\n    j = 0\n    while j < cols:\n        transposed[j][i] = matrix[i][j]\n        j += 1\n    i += 1\nprint(transposed)"),
    (23, "用 while 求 1 到 100 的完数。", "n = 2\nperfect = []\nwhile n <= 100:\n    total = 0\n    d = 1\n    while d < n:\n        if n % d == 0:\n            total += d\n        d += 1\n    if total == n:\n        perfect.append(n)\n    n += 1\nprint(perfect)", "填空完数。", "n = 2\nperfect = []\nwhile n <= 100:\n    total = 0\n    d = 1\n    while d < n:\n        if n % d == 0:\n            total += d\n        d += 1\n    if total == n:\n        perfect.append(n)\n    n += 1\nprint(perfect)"),
    (24, "用 while 统计单词频次前 2。", "text = \"the cat and the dog\"\nwords = text.split()\ncounts = {}\ni = 0\nwhile i < len(words):\n    counts[words[i]] = counts.get(words[i], 0) + 1\n    i += 1\nfor w, c in sorted(counts.items(), key=lambda x: x[1], reverse=True)[:2]:\n    print(f\"{w}: {c}\")", "填空词频前 2。", "text = \"the cat and the dog\"\nwords = text.split()\ncounts = {}\ni = 0\nwhile i < len(words):\n    counts[words[i]] = counts.get(words[i], 0) + 1\n    i += 1\nfor w, c in sorted(counts.items(), key=lambda x: x[1], reverse=True)[:2]:\n    print(f\"{w}: {c}\")"),
    (25, "用 while 判断回文素数（前几个）。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\nn = 2\nresult = []\nwhile len(result) < 5:\n    if is_prime(n) and str(n) == str(n)[::-1]:\n        result.append(n)\n    n += 1\nprint(result)", "填空回文素数。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\nn = 2\nresult = []\nwhile len(result) < 5:\n    if is_prime(n) and str(n) == str(n)[::-1]:\n        result.append(n)\n    n += 1\nprint(result)"),
    (26, "用 while 求数列的第 n 项（递推）。", "n = 10\na, b = 1, 1\ncount = 2\nwhile count < n:\n    a, b = b, a + b\n    count += 1\nprint(f\"Term {n}: {b}\")", "填空递推。", "n = 10\na, b = 1, 1\ncount = 2\nwhile count < n:\n    a, b = b, a + b\n    count += 1\nprint(f\"Term {n}: {b}\")"),
    (27, "用 while 求最大连续 1 的个数。", "bits = [1, 1, 0, 1, 1, 1]\nmax_count = 0\ncur = 0\ni = 0\nwhile i < len(bits):\n    if bits[i] == 1:\n        cur += 1\n        max_count = max(max_count, cur)\n    else:\n        cur = 0\n    i += 1\nprint(f\"Max ones: {max_count}\")", "填空连续计数。", "bits = [1, 1, 0, 1, 1, 1]\nmax_count = 0\ncur = 0\ni = 0\nwhile i < len(bits):\n    if bits[i] == 1:\n        cur += 1\n        max_count = max(max_count, cur)\n    else:\n        cur = 0\n    i += 1\nprint(f\"Max ones: {max_count}\")"),
    (28, "用 while 验证哥德巴赫猜想。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\neven = 4\nwhile even <= 20:\n    p = 2\n    while p < even:\n        if is_prime(p) and is_prime(even - p):\n            print(f\"{even} = {p} + {even - p}\")\n            break\n        p += 1\n    even += 2", "填空哥德巴赫。", "def is_prime(n):\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return n > 1\neven = 4\nwhile even <= 20:\n    p = 2\n    while p < even:\n        if is_prime(p) and is_prime(even - p):\n            print(f\"{even} = {p} + {even - p}\")\n            break\n        p += 1\n    even += 2"),
    (29, "用 while 模拟环形队列出队。", "queue = [1, 2, 3, 4, 5]\nresult = []\ni = 0\nwhile queue:\n    i = (i + 1) % len(queue)\n    result.append(queue.pop(i))\nprint(result)", "填空环形出队。", "queue = [1, 2, 3, 4, 5]\nresult = []\ni = 0\nwhile queue:\n    i = (i + 1) % len(queue)\n    result.append(queue.pop(i))\nprint(result)"),
    (30, "用 while 综合：统计 1 到 50 的数字特性。", "n = 1\nsquares = 0\ncubes = 0\nwhile n <= 50:\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares += 1\n    cr = round(n ** (1 / 3))\n    if cr ** 3 == n:\n        cubes += 1\n    n += 1\nprint(f\"Squares: {squares}, Cubes: {cubes}\")", "填空特性统计。", "n = 1\nsquares = 0\ncubes = 0\nwhile n <= 50:\n    root = int(n ** 0.5)\n    if root * root == n:\n        squares += 1\n    cr = round(n ** (1 / 3))\n    if cr ** 3 == n:\n        cubes += 1\n    n += 1\nprint(f\"Squares: {squares}, Cubes: {cubes}\")"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
