# -*- coding: utf-8 -*-
"""生成 CH09 函数 (基础) 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH09"
TITLE = "函数 (基础)"
OUT_DIR = "CH09_Functions"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "定义函数 greet 并调用输出。", "def greet():\n    print(\"Hello\")\n\ngreet()", "填空函数调用。", "def greet():\n    print(\"Hello\")\n\ngreet()"),
    (2, "定义函数输出两次问候。", "def greet():\n    print(\"Hi\")\n\ngreet()\ngreet()", "填空两次调用。", "def greet():\n    print(\"Hi\")\n\ngreet()\ngreet()"),
    (3, "定义函数返回数字 42。", "def get_number():\n    return 42\n\nprint(get_number())", "填空 return。", "def get_number():\n    return 42\n\nprint(get_number())"),
    (4, "定义函数输出参数值。", "def show(x):\n    print(x)\n\nshow(5)", "填空参数调用。", "def show(x):\n    print(x)\n\nshow(5)"),
    (5, "定义两参数函数求差。", "def diff(a, b):\n    return a - b\n\nprint(diff(10, 3))", "填空返回表达式。", "def diff(a, b):\n    return a - b\n\nprint(diff(10, 3))"),
    (6, "函数返回两数之和并输出。", "def add(a, b):\n    return a + b\n\nresult = add(3, 8)\nprint(result)", "填空调用赋值。", "def add(a, b):\n    return a + b\n\nresult = add(3, 8)\nprint(result)"),
    (7, "函数体内输出固定文本。", "def say():\n    print(\"Python\")\n\nsay()", "填空函数体。", "def say():\n    print(\"Python\")\n\nsay()"),
    (8, "无 return 的函数输出 None。", "def no_return():\n    x = 1\n\nprint(no_return())", "填空调用。", "def no_return():\n    x = 1\n\nprint(no_return())"),
    (9, "函数接收字符串参数并输出。", "def echo(text):\n    print(text)\n\necho(\"hi\")", "填空参数调用。", "def echo(text):\n    print(text)\n\necho(\"hi\")"),
    (10, "同一函数调用两次。", "def square(x):\n    return x * x\n\nprint(square(2))\nprint(square(3))", "填空两次调用。", "def square(x):\n    return x * x\n\nprint(square(2))\nprint(square(3))"),
    (11, "函数内做参数运算。", "def double(x):\n    return x * 2\n\nprint(double(7))", "填空运算返回。", "def double(x):\n    return x * 2\n\nprint(double(7))"),
    (12, "函数返回拼接字符串。", "def combine(a, b):\n    return a + b\n\nprint(combine(\"Py\", \"Quest\"))", "填空拼接返回。", "def combine(a, b):\n    return a + b\n\nprint(combine(\"Py\", \"Quest\"))"),
    (13, "使用默认参数。", "def greet(name=\"World\"):\n    print(\"Hello\", name)\n\ngreet()", "填空默认参数。", "def greet(name=\"World\"):\n    print(\"Hello\", name)\n\ngreet()"),
    (14, "函数内定义局部变量。", "def calc():\n    x = 10\n    return x + 5\n\nprint(calc())", "填空局部变量。", "def calc():\n    x = 10\n    return x + 5\n\nprint(calc())"),
    (15, "用函数返回值做判断。", "def is_even(n):\n    return n % 2 == 0\n\nprint(is_even(4))", "填空布尔返回。", "def is_even(n):\n    return n % 2 == 0\n\nprint(is_even(4))"),
    (16, "函数返回字符串并输出。", "def make_msg():\n    return 'Hi there!'\n\nprint(make_msg())", "填空返回。", "def make_msg():\n    return 'Hi there!'\n\nprint(make_msg())"),
    (17, "数字参数传入函数。", "def add_ten(n):\n    return n + 10\n\nprint(add_ten(3))", "填空函数调用。", "def add_ten(n):\n    return n + 10\n\nprint(add_ten(3))"),
    (18, "函数返回比较结果。", "def is_larger(a, b):\n    return a > b\n\nprint(is_larger(3, 5))", "填空比较返回。", "def is_larger(a, b):\n    return a > b\n\nprint(is_larger(3, 5))"),
    (19, "复用函数计算多个值。", "def triple(x):\n    return x * 3\n\nprint(triple(2), triple(3))", "填空复用调用。", "def triple(x):\n    return x * 3\n\nprint(triple(2), triple(3))"),
    (20, "用关键字参数调用。", "def greet(name, msg):\n    print(msg, name)\n\ngreet(msg=\"Hi\", name=\"Bob\")", "填空关键字调用。", "def greet(name, msg):\n    print(msg, name)\n\ngreet(msg=\"Hi\", name=\"Bob\")"),
    (21, "函数内条件返回。", "def sign(n):\n    if n > 0:\n        return \"positive\"\n    return \"non-positive\"\n\nprint(sign(5))", "填空条件返回。", "def sign(n):\n    if n > 0:\n        return \"positive\"\n    return \"non-positive\"\n\nprint(sign(5))"),
    (22, "循环内调用函数。", "def square(x):\n    return x * x\n\nfor i in range(1, 4):\n    print(square(i))", "填空循环调用。", "def square(x):\n    return x * x\n\nfor i in range(1, 4):\n    print(square(i))"),
    (23, "函数返回平方数。", "def square(x):\n    return ___ * x\n\nprint(square(6))", "填 x。", "def square(x):\n    return x * x\n\nprint(square(6))"),
    (24, "定义并调用打招呼函数。", "def hello():\n    return \"Hello\"\n\nprint(hello() + \"!\")", "填空返回拼接。", "def hello():\n    return \"Hello\"\n\nprint(hello() + \"!\")"),
    (25, "默认参数与传入参数。", "def repeat(text, times=2):\n    return text * times\n\nprint(repeat(\"ab\"))", "填空默认参数。", "def repeat(text, times=2):\n    return text * times\n\nprint(repeat(\"ab\"))"),
    (26, "递归求阶乘（雏形）。", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5))", "填空递归式。", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5))"),
    (27, "函数返回多个值。", "def get_stats():\n    return 1, 2\n\na, b = get_stats()\nprint(a, b)", "填空多返回值。", "def get_stats():\n    return 1, 2\n\na, b = get_stats()\nprint(a, b)"),
    (28, "空函数用 pass。", "def placeholder():\n    pass\n\nprint(\"done\")", "填空 pass。", "def placeholder():\n    pass\n\nprint(\"done\")"),
    (29, "带文档说明的函数。", "def greet():\n    \"\"\"Say hello\"\"\"\n    print(\"Hi!\")\n\ngreet()", "填空调用。", "def greet():\n    \"\"\"Say hello\"\"\"\n    print(\"Hi!\")\n\ngreet()"),
    (30, "综合：函数求和并输出。", "def total(a, b, c):\n    return a + b + c\n\nprint(total(1, 2, 3))", "填空三参数求和。", "def total(a, b, c):\n    return a + b + c\n\nprint(total(1, 2, 3))"),
]

SIMPLE = [
    (1, "定义函数计算平均分。", "def average(a, b):\n    return (a + b) / 2\n\nprint(average(8, 10))", "填空平均返回。", "def average(a, b):\n    return (a + b) / 2\n\nprint(average(8, 10))"),
    (2, "函数判断是否为质数。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, n):\n        if n % d == 0:\n            return False\n    return True\n\nprint(f\"Prime: {is_prime(7)}\")", "填空质数判断。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, n):\n        if n % d == 0:\n            return False\n    return True\n\nprint(f\"Prime: {is_prime(7)}\")"),
    (3, "函数返回最大值。", "def maximum(a, b):\n    if a > b:\n        return a\n    return b\n\nprint(maximum(4, 9))", "填空取最大。", "def maximum(a, b):\n    if a > b:\n        return a\n    return b\n\nprint(maximum(4, 9))"),
    (4, "函数格式化输出学生信息。", "def describe(name, score):\n    print(f\"{name} scored {score}\")\n\ndescribe(\"Alice\", 90)", "填空格式化输出。", "def describe(name, score):\n    print(f\"{name} scored {score}\")\n\ndescribe(\"Alice\", 90)"),
    (5, "函数返回列表求和。", "def list_sum(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total\n\nprint(list_sum([1, 2, 3, 4]))", "填空列表求和。", "def list_sum(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total\n\nprint(list_sum([1, 2, 3, 4]))"),
    (6, "函数计算字符串长度。", "def my_len(s):\n    count = 0\n    for _ in s:\n        count += 1\n    return count\n\nprint('Length:', my_len('hello'))", "填空长度统计。", "def my_len(s):\n    count = 0\n    for _ in s:\n        count += 1\n    return count\n\nprint('Length:', my_len('hello'))"),
    (7, "函数返回阶乘。", "def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n\nprint(f\"Factorial: {factorial(5)}\")", "填空累乘。", "def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n\nprint(f\"Factorial: {factorial(5)}\")"),
    (8, "函数判断回文字符串。", "def is_palindrome(s):\n    return s == s[::-1]\n\nprint('Palindrome:', is_palindrome('radar'))", "填空回文判断。", "def is_palindrome(s):\n    return s == s[::-1]\n\nprint('Palindrome:', is_palindrome('radar'))"),
    (9, "函数返回多个计算结果。", "def circle(r):\n    area = 3.14159 * r * r\n    circumference = 2 * 3.14159 * r\n    return area, circumference\n\na, c = circle(1)\nprint(round(a, 2), round(c, 2))", "填空多返回。", "def circle(r):\n    area = 3.14159 * r * r\n    circumference = 2 * 3.14159 * r\n    return area, circumference\n\na, c = circle(1)\nprint(round(a, 2), round(c, 2))"),
    (10, "函数过滤偶数并返回。", "def get_evens(nums):\n    return [n for n in nums if n % 2 == 0]\n\nprint(get_evens([1, 2, 3, 4, 5]))", "填空推导式返回。", "def get_evens(nums):\n    return [n for n in nums if n % 2 == 0]\n\nprint(get_evens([1, 2, 3, 4, 5]))"),
    (11, "函数计算单词个数。", "def word_count(text):\n    return len(text.split())\n\nprint('Words:', word_count('hello world python'))", "填空分词计数。", "def word_count(text):\n    return len(text.split())\n\nprint('Words:', word_count('hello world python'))"),
    (12, "函数求幂并输出表。", "def power(base, exp):\n    return base ** exp\n\nfor i in range(1, 4):\n    print(power(2, i))", "填空幂函数。", "def power(base, exp):\n    return base ** exp\n\nfor i in range(1, 4):\n    print(power(2, i))"),
    (13, "函数将摄氏转华氏。", "def c_to_f(c):\n    return c * 9 / 5 + 32\n\nprint(c_to_f(100))", "填空转换公式。", "def c_to_f(c):\n    return c * 9 / 5 + 32\n\nprint(c_to_f(100))"),
    (14, "函数判断数字位数。", "def digit_count(n):\n    return len(str(n))\n\nprint(f\"Digits: {digit_count(12345)}\")", "填空位数统计。", "def digit_count(n):\n    return len(str(n))\n\nprint(f\"Digits: {digit_count(12345)}\")"),
    (15, "函数返回大写字符串。", "def shout(text):\n    return text.upper() + \"!\"\n\nprint(shout(\"hi\"))", "填空大写拼接。", "def shout(text):\n    return text.upper() + \"!\"\n\nprint(shout(\"hi\"))"),
    (16, "函数统计元音个数。", "def count_vowels(text):\n    return sum(1 for ch in text if ch in \"aeiou\")\n\nprint('Vowels:', count_vowels('hello'))", "填空元音统计。", "def count_vowels(text):\n    return sum(1 for ch in text if ch in \"aeiou\")\n\nprint('Vowels:', count_vowels('hello'))"),
    (17, "函数求两数较大者（三元）。", "def bigger(a, b):\n    return a if a > b else b\n\nprint(bigger(3, 8))", "填空三元返回。", "def bigger(a, b):\n    return a if a > b else b\n\nprint(bigger(3, 8))"),
    (18, "函数计算 BMI。", "def bmi(weight, height):\n    return weight / height ** 2\n\nprint(round(bmi(65, 1.75), 1))", "填空 BMI 公式。", "def bmi(weight, height):\n    return weight / height ** 2\n\nprint(round(bmi(65, 1.75), 1))"),
    (19, "函数生成重复字符串。", "def line(char, n):\n    return char * n\n\nprint(line(\"=\", 10))", "填空重复返回。", "def line(char, n):\n    return char * n\n\nprint(line(\"=\", 10))"),
    (20, "函数计算列表平均。", "def avg(nums):\n    return sum(nums) / len(nums)\n\nprint(avg([10, 20, 30]))", "填空平均返回。", "def avg(nums):\n    return sum(nums) / len(nums)\n\nprint(avg([10, 20, 30]))"),
    (21, "函数判断是否成年。", "def is_adult(age):\n    return age >= 18\n\nprint(is_adult(20), is_adult(15))", "填空比较返回。", "def is_adult(age):\n    return age >= 18\n\nprint(is_adult(20), is_adult(15))"),
    (22, "函数返回数字反转。", "def reverse_number(n):\n    return int(str(n)[::-1])\n\nprint(reverse_number(123))", "填空反转。", "def reverse_number(n):\n    return int(str(n)[::-1])\n\nprint(reverse_number(123))"),
    (23, "函数按长度截断。", "def truncate(s, n):\n    return s[:n]\n\nprint(truncate(\"Python\", 3))", "填空切片。", "def truncate(s, n):\n    return s[:n]\n\nprint(truncate(\"Python\", 3))"),
    (24, "函数求最大最小值对。", "def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([3, 1, 4])\nprint(lo, hi)", "填空极值返回。", "def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([3, 1, 4])\nprint(lo, hi)"),
    (25, "函数判断闰年。", "def is_leap(year):\n    return (year % 4 == 0 and year % 100 != 0) or year % 400 == 0\n\nprint(f\"Leap: {is_leap(2024)}\")", "填空闰年判断。", "def is_leap(year):\n    return (year % 4 == 0 and year % 100 != 0) or year % 400 == 0\n\nprint(f\"Leap: {is_leap(2024)}\")"),
    (26, "函数累加 1 到 n。", "def sum_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total\n\nprint(f\"Sum: {sum_to(10)}\")", "填空循环累加。", "def sum_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total\n\nprint(f\"Sum: {sum_to(10)}\")"),
    (27, "函数检查子串存在。", "def contains(text, sub):\n    return sub in text\n\nprint('Contains:', contains('hello', 'ell'))", "填空 in 判断。", "def contains(text, sub):\n    return sub in text\n\nprint('Contains:', contains('hello', 'ell'))"),
    (28, "函数输出表格行。", "def row(name, score):\n    print(f\"| {name:<6} | {score:>5} |\")\n\nrow(\"Alice\", 90)", "填空表格行。", "def row(name, score):\n    print(f\"| {name:<6} | {score:>5} |\")\n\nrow(\"Alice\", 90)"),
    (29, "函数返回字符重复次数。", "def count_char(text, ch):\n    return text.count(ch)\n\nprint('Count:', count_char('banana', 'a'))", "填空计数。", "def count_char(text, ch):\n    return text.count(ch)\n\nprint('Count:', count_char('banana', 'a'))"),
    (30, "综合：函数统计成绩。", "def stats(scores):\n    total = sum(scores)\n    avg = total / len(scores)\n    return total, avg\n\nt, a = stats([80, 90, 70])\nprint(f\"Total: {t}, Avg: {a}\")", "填空统计返回。", "def stats(scores):\n    total = sum(scores)\n    avg = total / len(scores)\n    return total, avg\n\nt, a = stats([80, 90, 70])\nprint(f\"Total: {t}, Avg: {a}\")"),
]

MEDIUM = [
    (1, "函数实现选择排序。", "def selection_sort(nums):\n    for i in range(len(nums)):\n        m = i\n        for j in range(i + 1, len(nums)):\n            if nums[j] < nums[m]:\n                m = j\n        nums[i], nums[m] = nums[m], nums[i]\n    return nums\n\nprint(selection_sort([5, 3, 8, 1]))", "填空选择排序。", "def selection_sort(nums):\n    for i in range(len(nums)):\n        m = i\n        for j in range(i + 1, len(nums)):\n            if nums[j] < nums[m]:\n                m = j\n        nums[i], nums[m] = nums[m], nums[i]\n    return nums\n\nprint(selection_sort([5, 3, 8, 1]))"),
    (2, "函数递归求斐波那契。", "def fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nfor i in range(8):\n    print(fib(i), end=\" \")", "填空递归斐波那契。", "def fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nfor i in range(8):\n    print(fib(i), end=\" \")"),
    (3, "函数实现二分查找。", "def binary_search(nums, target):\n    low, high = 0, len(nums) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n\nprint(f\"Found at: {binary_search([1, 3, 5, 7, 9], 7)}\")", "填空二分查找。", "def binary_search(nums, target):\n    low, high = 0, len(nums) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n\nprint(f\"Found at: {binary_search([1, 3, 5, 7, 9], 7)}\")"),
    (4, "函数统计字符频率。", "def char_freq(text):\n    freq = {}\n    for ch in text:\n        freq[ch] = freq.get(ch, 0) + 1\n    return freq\n\nprint(char_freq(\"abca\"))", "填空频率统计。", "def char_freq(text):\n    freq = {}\n    for ch in text:\n        freq[ch] = freq.get(ch, 0) + 1\n    return freq\n\nprint(char_freq(\"abca\"))"),
    (5, "函数求最大公约数（递归）。", "def gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a % b)\n\nprint(f\"GCD: {gcd(48, 36)}\")", "填空递归 gcd。", "def gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a % b)\n\nprint(f\"GCD: {gcd(48, 36)}\")"),
    (6, "函数生成乘法表行。", "def table_row(n, size):\n    return \" \".join(f\"{n}x{i}={n * i}\" for i in range(1, size + 1))\n\nprint(table_row(3, 4))", "填空表行生成。", "def table_row(n, size):\n    return \" \".join(f\"{n}x{i}={n * i}\" for i in range(1, size + 1))\n\nprint(table_row(3, 4))"),
    (7, "函数判断快乐数。", "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nprint(f\"Happy: {is_happy(19)}\")", "填空快乐数。", "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nprint(f\"Happy: {is_happy(19)}\")"),
    (8, "函数计算多项式值。", "def poly(x):\n    return 2 * x ** 2 + 3 * x + 1\n\nfor x in [0, 1, 2]:\n    print(poly(x))", "填空多项式。", "def poly(x):\n    return 2 * x ** 2 + 3 * x + 1\n\nfor x in [0, 1, 2]:\n    print(poly(x))"),
    (9, "函数合并两有序列表。", "def merge(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] < b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result\n\nprint(merge([1, 3], [2, 4]))", "填空双指针合并。", "def merge(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] < b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result\n\nprint(merge([1, 3], [2, 4]))"),
    (10, "函数求矩阵转置。", "def transpose(matrix):\n    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]\n\nprint(transpose([[1, 2], [3, 4]]))", "填空转置推导。", "def transpose(matrix):\n    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]\n\nprint(transpose([[1, 2], [3, 4]]))"),
    (11, "函数求数字各位和。", "def digit_sum(n):\n    return sum(int(d) for d in str(n))\n\nprint(f\"Sum: {digit_sum(12345)}\")", "填空位和。", "def digit_sum(n):\n    return sum(int(d) for d in str(n))\n\nprint(f\"Sum: {digit_sum(12345)}\")"),
    (12, "函数检查完全平方。", "def is_square(n):\n    root = int(n ** 0.5)\n    return root * root == n\n\nprint(f\"Square: {is_square(81)}, {is_square(82)}\")", "填空平方判断。", "def is_square(n):\n    root = int(n ** 0.5)\n    return root * root == n\n\nprint(f\"Square: {is_square(81)}, {is_square(82)}\")"),
    (13, "函数格式化成绩报告。", "def report(name, score):\n    grade = \"A\" if score >= 90 else \"B\" if score >= 80 else \"C\"\n    return f\"{name}: {score} ({grade})\"\n\nprint(report(\"Alice\", 92))", "填空报告格式。", "def report(name, score):\n    grade = \"A\" if score >= 90 else \"B\" if score >= 80 else \"C\"\n    return f\"{name}: {score} ({grade})\"\n\nprint(report(\"Alice\", 92))"),
    (14, "函数求列表去重。", "def unique(nums):\n    seen = []\n    for n in nums:\n        if n not in seen:\n            seen.append(n)\n    return seen\n\nprint(unique([1, 2, 1, 3, 2]))", "填空去重。", "def unique(nums):\n    seen = []\n    for n in nums:\n        if n not in seen:\n            seen.append(n)\n    return seen\n\nprint(unique([1, 2, 1, 3, 2]))"),
    (15, "函数求两数最小公倍数。", "def lcm(a, b):\n    m = max(a, b)\n    while m % a != 0 or m % b != 0:\n        m += 1\n    return m\n\nprint(f\"LCM: {lcm(4, 6)}\")", "填空 lcm。", "def lcm(a, b):\n    m = max(a, b)\n    while m % a != 0 or m % b != 0:\n        m += 1\n    return m\n\nprint(f\"LCM: {lcm(4, 6)}\")"),
    (16, "函数实现幂次表输出。", "def power_table(base, n):\n    for i in range(1, n + 1):\n        print(f\"{base}^{i} = {base ** i}\")\n\npower_table(3, 4)", "填空幂表。", "def power_table(base, n):\n    for i in range(1, n + 1):\n        print(f\"{base}^{i} = {base ** i}\")\n\npower_table(3, 4)"),
    (17, "函数求字符串中最长单词。", "def longest_word(text):\n    words = text.split()\n    return max(words, key=len)\n\nprint(longest_word(\"the quick brown fox\"))", "填空最长单词。", "def longest_word(text):\n    words = text.split()\n    return max(words, key=len)\n\nprint(longest_word(\"the quick brown fox\"))"),
    (18, "函数计算存款复利。", "def compound(principal, rate, years):\n    for _ in range(years):\n        principal *= 1 + rate\n    return principal\n\nprint(round(compound(1000, 0.05, 3), 2))", "填空复利。", "def compound(principal, rate, years):\n    for _ in range(years):\n        principal *= 1 + rate\n    return principal\n\nprint(round(compound(1000, 0.05, 3), 2))"),
    (19, "函数判断回文数。", "def is_pal_num(n):\n    s = str(n)\n    return s == s[::-1]\n\nfor n in [121, 123]:\n    print(n, is_pal_num(n))", "填空回文数。", "def is_pal_num(n):\n    s = str(n)\n    return s == s[::-1]\n\nfor n in [121, 123]:\n    print(n, is_pal_num(n))"),
    (20, "函数统计单词频率 top。", "def top_words(text, k):\n    words = text.split()\n    counts = {}\n    for w in words:\n        counts[w] = counts.get(w, 0) + 1\n    return sorted(counts.items(), key=lambda x: x[1], reverse=True)[:k]\n\nprint(top_words(\"a b a c a b\", 2))", "填空词频。", "def top_words(text, k):\n    words = text.split()\n    counts = {}\n    for w in words:\n        counts[w] = counts.get(w, 0) + 1\n    return sorted(counts.items(), key=lambda x: x[1], reverse=True)[:k]\n\nprint(top_words(\"a b a c a b\", 2))"),
    (21, "函数实现简化凯撒加密。", "def caesar(text, shift):\n    result = \"\"\n    for ch in text:\n        result += chr((ord(ch) - 97 + shift) % 26 + 97)\n    return result\n\nprint(caesar(\"abc\", 1))", "填空位移。", "def caesar(text, shift):\n    result = \"\"\n    for ch in text:\n        result += chr((ord(ch) - 97 + shift) % 26 + 97)\n    return result\n\nprint(caesar(\"abc\", 1))"),
    (22, "函数求数组最大子段和。", "def max_subarray(nums):\n    max_sum = nums[0]\n    cur = 0\n    for n in nums:\n        cur = max(n, cur + n)\n        max_sum = max(max_sum, cur)\n    return max_sum\n\nprint(f\"Max subarray: {max_subarray([-2, 1, -3, 4, -1, 2])}\")", "填空 Kadane。", "def max_subarray(nums):\n    max_sum = nums[0]\n    cur = 0\n    for n in nums:\n        cur = max(n, cur + n)\n        max_sum = max(max_sum, cur)\n    return max_sum\n\nprint(f\"Max subarray: {max_subarray([-2, 1, -3, 4, -1, 2])}\")"),
    (23, "函数输出菱形。", "def diamond(n):\n    for i in range(1, n + 1):\n        print(\" \" * (n - i) + \"*\" * (2 * i - 1))\n    for i in range(n - 1, 0, -1):\n        print(\" \" * (n - i) + \"*\" * (2 * i - 1))\n\ndiamond(2)", "填空菱形输出。", "def diamond(n):\n    for i in range(1, n + 1):\n        print(\" \" * (n - i) + \"*\" * (2 * i - 1))\n    for i in range(n - 1, 0, -1):\n        print(\" \" * (n - i) + \"*\" * (2 * i - 1))\n\ndiamond(2)"),
    (24, "函数求数列第 n 项。", "def fib_n(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint(fib_n(8))", "填空递推。", "def fib_n(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint(fib_n(8))"),
    (25, "函数检查是否有序。", "def is_sorted(nums):\n    return all(nums[i] <= nums[i + 1] for i in range(len(nums) - 1))\n\nprint(f\"Sorted: {is_sorted([1, 2, 3])}, {is_sorted([3, 1, 2])}\")", "填空有序检查。", "def is_sorted(nums):\n    return all(nums[i] <= nums[i + 1] for i in range(len(nums) - 1))\n\nprint(f\"Sorted: {is_sorted([1, 2, 3])}, {is_sorted([3, 1, 2])}\")"),
    (26, "函数计算折扣价。", "def discount(price, percent):\n    return price * (1 - percent / 100)\n\nprint(discount(200, 20))", "填空折扣。", "def discount(price, percent):\n    return price * (1 - percent / 100)\n\nprint(discount(200, 20))"),
    (27, "函数求众数。", "def mode(nums):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    return max(counts, key=counts.get)\n\nprint(f\"Mode: {mode([1, 2, 2, 3])}\")", "填空众数。", "def mode(nums):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    return max(counts, key=counts.get)\n\nprint(f\"Mode: {mode([1, 2, 2, 3])}\")"),
    (28, "函数输出九九乘法表。", "def mul_table(n):\n    for i in range(1, n + 1):\n        row = \" \".join(f\"{i}x{j}={i * j}\" for j in range(1, n + 1))\n        print(row)\n\nmul_table(3)", "填空乘法表。", "def mul_table(n):\n    for i in range(1, n + 1):\n        row = \" \".join(f\"{i}x{j}={i * j}\" for j in range(1, n + 1))\n        print(row)\n\nmul_table(3)"),
    (29, "函数判断是否互质。", "def coprime(a, b):\n    while b:\n        a, b = b, a % b\n    return a == 1\n\nprint(f\"Coprime: {coprime(8, 9)}, {coprime(8, 12)}\")", "填空互质判断。", "def coprime(a, b):\n    while b:\n        a, b = b, a % b\n    return a == 1\n\nprint(f\"Coprime: {coprime(8, 9)}, {coprime(8, 12)}\")"),
    (30, "综合：函数库（多个函数调用）。", "def square(x):\n    return x * x\n\ndef cube(x):\n    return x ** 3\n\nfor n in [2, 3]:\n    print(f\"{n}: sq={square(n)}, cube={cube(n)}\")", "填空多函数调用。", "def square(x):\n    return x * x\n\ndef cube(x):\n    return x ** 3\n\nfor n in [2, 3]:\n    print(f\"{n}: sq={square(n)}, cube={cube(n)}\")"),
]

HARD = [
    (1, "函数递归求 1 到 n 的和。", "def sum_rec(n):\n    if n <= 1:\n        return n\n    return n + sum_rec(n - 1)\n\nprint(f\"Recursive sum: {sum_rec(10)}\")", "填空递归求和。", "def sum_rec(n):\n    if n <= 1:\n        return n\n    return n + sum_rec(n - 1)\n\nprint(f\"Recursive sum: {sum_rec(10)}\")"),
    (2, "函数实现快速排序。", "def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[0]\n    left = [x for x in arr[1:] if x <= pivot]\n    right = [x for x in arr[1:] if x > pivot]\n    return quicksort(left) + [pivot] + quicksort(right)\n\nprint(quicksort([5, 3, 8, 1, 2]))", "填空快排。", "def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[0]\n    left = [x for x in arr[1:] if x <= pivot]\n    right = [x for x in arr[1:] if x > pivot]\n    return quicksort(left) + [pivot] + quicksort(right)\n\nprint(quicksort([5, 3, 8, 1, 2]))"),
    (3, "函数实现归并排序。", "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] < right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n\nprint(merge_sort([8, 3, 6, 1, 7]))", "填空归并排序。", "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] < right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n\nprint(merge_sort([8, 3, 6, 1, 7]))"),
    (4, "函数求 1 到 n 的阶乘和。", "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nfor n in [5, 10]:\n    total = sum(factorial(i) for i in range(1, n + 1))\n    print(f\"Sum of 1!..{n}! = {total}\")", "填空阶乘和。", "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nfor n in [5, 10]:\n    total = sum(factorial(i) for i in range(1, n + 1))\n    print(f\"Sum of 1!..{n}! = {total}\")"),
    (5, "函数求第 n 个质数。", "def nth_prime(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if all(num % p for p in primes if p * p <= num):\n            primes.append(num)\n        num += 1\n    return primes[-1]\n\nprint(nth_prime(5), nth_prime(10))", "填空第 n 质数。", "def nth_prime(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if all(num % p for p in primes if p * p <= num):\n            primes.append(num)\n        num += 1\n    return primes[-1]\n\nprint(nth_prime(5), nth_prime(10))"),
    (6, "函数实现字符串乘法（大数）。", "def str_multiply(s, n):\n    result = \"\"\n    carry = 0\n    for i in range(len(s) - 1, -1, -1):\n        prod = int(s[i]) * n + carry\n        result = str(prod % 10) + result\n        carry = prod // 10\n    if carry:\n        result = str(carry) + result\n    return result\n\nprint(str_multiply(\"999\", 9))", "填空大数乘法。", "def str_multiply(s, n):\n    result = \"\"\n    carry = 0\n    for i in range(len(s) - 1, -1, -1):\n        prod = int(s[i]) * n + carry\n        result = str(prod % 10) + result\n        carry = prod // 10\n    if carry:\n        result = str(carry) + result\n    return result\n\nprint(str_multiply(\"999\", 9))"),
    (7, "函数判断完全数。", "def is_perfect(n):\n    return sum(d for d in range(1, n) if n % d == 0) == n\n\nfor n in [6, 12, 28]:\n    print(n, is_perfect(n))", "填空完全数。", "def is_perfect(n):\n    return sum(d for d in range(1, n) if n % d == 0) == n\n\nfor n in [6, 12, 28]:\n    print(n, is_perfect(n))"),
    (8, "函数实现进制转换（任意进制）。", "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    if n == 0:\n        return \"0\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\n\nprint(to_base(255, 16), to_base(10, 2))", "填空进制转换。", "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    if n == 0:\n        return \"0\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\n\nprint(to_base(255, 16), to_base(10, 2))"),
    (9, "函数求最大子序列乘积。", "def max_product(nums):\n    max_prod = nums[0]\n    for i in range(len(nums)):\n        prod = 1\n        for j in range(i, len(nums)):\n            prod *= nums[j]\n            max_prod = max(max_prod, prod)\n    return max_prod\n\nprint(f\"Max product: {max_product([2, 3, -2, 4])}\")", "填空最大乘积。", "def max_product(nums):\n    max_prod = nums[0]\n    for i in range(len(nums)):\n        prod = 1\n        for j in range(i, len(nums)):\n            prod *= nums[j]\n            max_prod = max(max_prod, prod)\n    return max_prod\n\nprint(f\"Max product: {max_product([2, 3, -2, 4])}\")"),
    (10, "函数实现杨辉三角。", "def pascal(rows):\n    triangle = []\n    for i in range(rows):\n        row = [1] * (i + 1)\n        for j in range(1, i):\n            row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n        triangle.append(row)\n    return triangle\n\nfor row in pascal(5):\n    print(row)", "填空杨辉三角。", "def pascal(rows):\n    triangle = []\n    for i in range(rows):\n        row = [1] * (i + 1)\n        for j in range(1, i):\n            row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]\n        triangle.append(row)\n    return triangle\n\nfor row in pascal(5):\n    print(row)"),
    (11, "函数求水仙花数列表。", "def armstrong(limit):\n    result = []\n    for n in range(100, limit):\n        digits = [int(d) for d in str(n)]\n        if sum(d ** len(digits) for d in digits) == n:\n            result.append(n)\n    return result\n\nprint(armstrong(500))", "填空水仙花。", "def armstrong(limit):\n    result = []\n    for n in range(100, limit):\n        digits = [int(d) for d in str(n)]\n        if sum(d ** len(digits) for d in digits) == n:\n            result.append(n)\n    return result\n\nprint(armstrong(500))"),
    (12, "函数统计字符串中每个单词出现次数。", "def word_freq(text):\n    words = text.lower().split()\n    freq = {}\n    for w in words:\n        freq[w] = freq.get(w, 0) + 1\n    return freq\n\nprint(word_freq(\"The cat and the dog\"))", "填空词频。", "def word_freq(text):\n    words = text.lower().split()\n    freq = {}\n    for w in words:\n        freq[w] = freq.get(w, 0) + 1\n    return freq\n\nprint(word_freq(\"The cat and the dog\"))"),
    (13, "函数求矩阵乘法。", "def mat_mult(a, b):\n    result = [[0, 0], [0, 0]]\n    for i in range(2):\n        for j in range(2):\n            for k in range(2):\n                result[i][j] += a[i][k] * b[k][j]\n    return result\n\nprint(mat_mult([[1, 2], [3, 4]], [[5, 6], [7, 8]]))", "填空矩阵乘法。", "def mat_mult(a, b):\n    result = [[0, 0], [0, 0]]\n    for i in range(2):\n        for j in range(2):\n            for k in range(2):\n                result[i][j] += a[i][k] * b[k][j]\n    return result\n\nprint(mat_mult([[1, 2], [3, 4]], [[5, 6], [7, 8]]))"),
    (14, "函数求最长连续递增长度。", "def longest_increasing(nums):\n    max_len = 1\n    cur = 1\n    for i in range(1, len(nums)):\n        if nums[i] > nums[i - 1]:\n            cur += 1\n            max_len = max(max_len, cur)\n        else:\n            cur = 1\n    return max_len\n\nprint(f\"Longest: {longest_increasing([1, 2, 3, 1, 2])}\")", "填空递增长度。", "def longest_increasing(nums):\n    max_len = 1\n    cur = 1\n    for i in range(1, len(nums)):\n        if nums[i] > nums[i - 1]:\n            cur += 1\n            max_len = max(max_len, cur)\n        else:\n            cur = 1\n    return max_len\n\nprint(f\"Longest: {longest_increasing([1, 2, 3, 1, 2])}\")"),
    (15, "函数判断两个字符串是否变位词。", "def anagram(a, b):\n    return sorted(a) == sorted(b)\n\nprint('Anagram:', anagram('listen', 'silent'), anagram('abc', 'abd'))", "填空变位词。", "def anagram(a, b):\n    return sorted(a) == sorted(b)\n\nprint('Anagram:', anagram('listen', 'silent'), anagram('abc', 'abd'))"),
    (16, "函数实现二分查找演示。", "def binary_search(nums, target):\n    low, high = 0, len(nums) - 1\n    steps = []\n    while low <= high:\n        mid = (low + high) // 2\n        steps.append(nums[mid])\n        if nums[mid] == target:\n            return steps\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return steps\n\nprint(binary_search([1, 3, 5, 7, 9, 11], 9))", "填空二分演示。", "def binary_search(nums, target):\n    low, high = 0, len(nums) - 1\n    steps = []\n    while low <= high:\n        mid = (low + high) // 2\n        steps.append(nums[mid])\n        if nums[mid] == target:\n            return steps\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return steps\n\nprint(binary_search([1, 3, 5, 7, 9, 11], 9))"),
    (17, "函数求 100 内素数列表。", "def primes_up_to(limit):\n    result = []\n    for n in range(2, limit + 1):\n        if all(n % d for d in range(2, int(n ** 0.5) + 1)):\n            result.append(n)\n    return result\n\nprint(primes_up_to(30))", "填空素数列表。", "def primes_up_to(limit):\n    result = []\n    for n in range(2, limit + 1):\n        if all(n % d for d in range(2, int(n ** 0.5) + 1)):\n            result.append(n)\n    return result\n\nprint(primes_up_to(30))"),
    (18, "函数求最大公约数与最小公倍数。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\ndef lcm(a, b):\n    return a * b // gcd(a, b)\n\nprint(gcd(12, 18), lcm(12, 18))", "填空 gcd/lcm。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\ndef lcm(a, b):\n    return a * b // gcd(a, b)\n\nprint(gcd(12, 18), lcm(12, 18))"),
    (19, "函数实现简易加密（移位）。", "def encrypt(text, shift):\n    result = \"\"\n    for ch in text:\n        if ch.isalpha():\n            base = ord('a') if ch.islower() else ord('A')\n            result += chr((ord(ch) - base + shift) % 26 + base)\n        else:\n            result += ch\n    return result\n\nprint(encrypt(\"Hello World\", 3))", "填空加密。", "def encrypt(text, shift):\n    result = \"\"\n    for ch in text:\n        if ch.isalpha():\n            base = ord('a') if ch.islower() else ord('A')\n            result += chr((ord(ch) - base + shift) % 26 + base)\n        else:\n            result += ch\n    return result\n\nprint(encrypt(\"Hello World\", 3))"),
    (20, "函数求列表第二大的数。", "def second_largest(nums):\n    unique = sorted(set(nums))\n    return unique[-2] if len(unique) >= 2 else None\n\nprint(f\"Second: {second_largest([4, 9, 7, 9, 2])}\")", "填空第二大。", "def second_largest(nums):\n    unique = sorted(set(nums))\n    return unique[-2] if len(unique) >= 2 else None\n\nprint(f\"Second: {second_largest([4, 9, 7, 9, 2])}\")"),
    (21, "函数验证哥德巴赫猜想。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\ndef goldbach(n):\n    for p in range(2, n):\n        if is_prime(p) and is_prime(n - p):\n            return p, n - p\n    return None\n\nprint(goldbach(28))", "填空哥德巴赫。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\ndef goldbach(n):\n    for p in range(2, n):\n        if is_prime(p) and is_prime(n - p):\n            return p, n - p\n    return None\n\nprint(goldbach(28))"),
    (22, "函数实现字符串压缩。", "def compress(s):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aaabbc\"))", "填空压缩。", "def compress(s):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aaabbc\"))"),
    (23, "函数求数组中只出现一次的数。", "def single_number(nums):\n    result = 0\n    for n in nums:\n        result ^= n\n    return result\n\nprint(f\"Single: {single_number([4, 1, 2, 1, 2])}\")", "填空异或。", "def single_number(nums):\n    result = 0\n    for n in nums:\n        result ^= n\n    return result\n\nprint(f\"Single: {single_number([4, 1, 2, 1, 2])}\")"),
    (24, "函数求 3n+1 序列。", "def collatz(n):\n    seq = [n]\n    while n != 1:\n        if n % 2 == 0:\n            n //= 2\n        else:\n            n = n * 3 + 1\n        seq.append(n)\n    return seq\n\nprint(collatz(6))", "填空 3n+1。", "def collatz(n):\n    seq = [n]\n    while n != 1:\n        if n % 2 == 0:\n            n //= 2\n        else:\n            n = n * 3 + 1\n        seq.append(n)\n    return seq\n\nprint(collatz(6))"),
    (25, "函数求最小差配对。", "def min_difference(nums):\n    nums.sort()\n    return min(nums[i + 1] - nums[i] for i in range(len(nums) - 1))\n\nprint(f\"Min diff: {min_difference([3, 9, 1, 6])}\")", "填空最小差。", "def min_difference(nums):\n    nums.sort()\n    return min(nums[i + 1] - nums[i] for i in range(len(nums) - 1))\n\nprint(f\"Min diff: {min_difference([3, 9, 1, 6])}\")"),
    (26, "函数实现斐波那契（迭代优化）。", "def fib_iter(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nfor n in [0, 5, 10]:\n    print(f\"fib({n}) = {fib_iter(n)}\")", "填空迭代斐波那契。", "def fib_iter(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nfor n in [0, 5, 10]:\n    print(f\"fib({n}) = {fib_iter(n)}\")"),
    (27, "函数求最长回文子串长度（简化）。", "def longest_pal(s):\n    max_len = 1\n    for i in range(len(s)):\n        for j in range(i + 1, len(s) + 1):\n            sub = s[i:j]\n            if sub == sub[::-1]:\n                max_len = max(max_len, len(sub))\n    return max_len\n\nprint('Longest pal:', longest_pal('babad'))", "填空回文子串。", "def longest_pal(s):\n    max_len = 1\n    for i in range(len(s)):\n        for j in range(i + 1, len(s) + 1):\n            sub = s[i:j]\n            if sub == sub[::-1]:\n                max_len = max(max_len, len(sub))\n    return max_len\n\nprint('Longest pal:', longest_pal('babad'))"),
    (28, "函数求约瑟夫环幸存者。", "def josephus(n, k):\n    people = list(range(1, n + 1))\n    idx = 0\n    while len(people) > 1:\n        idx = (idx + k - 1) % len(people)\n        people.pop(idx)\n    return people[0]\n\nprint(f\"Survivor: {josephus(7, 3)}\")", "填空约瑟夫环。", "def josephus(n, k):\n    people = list(range(1, n + 1))\n    idx = 0\n    while len(people) > 1:\n        idx = (idx + k - 1) % len(people)\n        people.pop(idx)\n    return people[0]\n\nprint(f\"Survivor: {josephus(7, 3)}\")"),
    (29, "函数求螺旋矩阵。", "def spiral(n):\n    matrix = [[0] * n for _ in range(n)]\n    num = 1\n    top, bottom, left, right = 0, n - 1, 0, n - 1\n    while top <= bottom and left <= right:\n        for j in range(left, right + 1):\n            matrix[top][j] = num\n            num += 1\n        top += 1\n        for i in range(top, bottom + 1):\n            matrix[i][right] = num\n            num += 1\n        right -= 1\n        for j in range(right, left - 1, -1):\n            matrix[bottom][j] = num\n            num += 1\n        bottom -= 1\n        for i in range(bottom, top - 1, -1):\n            matrix[i][left] = num\n            num += 1\n        left += 1\n    return matrix\n\nfor row in spiral(3):\n    print(row)", "填空螺旋矩阵。", "def spiral(n):\n    matrix = [[0] * n for _ in range(n)]\n    num = 1\n    top, bottom, left, right = 0, n - 1, 0, n - 1\n    while top <= bottom and left <= right:\n        for j in range(left, right + 1):\n            matrix[top][j] = num\n            num += 1\n        top += 1\n        for i in range(top, bottom + 1):\n            matrix[i][right] = num\n            num += 1\n        right -= 1\n        for j in range(right, left - 1, -1):\n            matrix[bottom][j] = num\n            num += 1\n        bottom -= 1\n        for i in range(bottom, top - 1, -1):\n            matrix[i][left] = num\n            num += 1\n        left += 1\n    return matrix\n\nfor row in spiral(3):\n    print(row)"),
    (30, "综合：函数库演示（多函数协同）。", "def add(a, b):\n    return a + b\n\ndef mul(a, b):\n    return a * b\n\nx, y = 3, 4\nprint(f\"{x} + {y} = {add(x, y)}\")\nprint(f\"{x} * {y} = {mul(x, y)}\")\nprint(f\"(a+b)*2 = {mul(add(x, y), 2)}\")", "填空多函数协同。", "def add(a, b):\n    return a + b\n\ndef mul(a, b):\n    return a * b\n\nx, y = 3, 4\nprint(f\"{x} + {y} = {add(x, y)}\")\nprint(f\"{x} * {y} = {mul(x, y)}\")\nprint(f\"(a+b)*2 = {mul(add(x, y), 2)}\")"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
