# -*- coding: utf-8 -*-
"""生成 CH11 函数 (返回值) 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH11"
TITLE = "函数 (返回值)"
OUT_DIR = "CH11_Function_Returns"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "函数返回固定数字并输出。", "def get_num():\n    return 7\n\nprint(get_num())", "填空 return。", "def get_num():\n    return 7\n\nprint(get_num())"),
    (2, "函数返回表达式结果。", "def calc():\n    return 3 + 5\n\nprint(calc())", "填空返回表达式。", "def calc():\n    return 3 + 5\n\nprint(calc())"),
    (3, "函数返回两个值并解包。", "def pair():\n    return 1, 2\n\na, b = pair()\nprint(a, b)", "填空多返回值。", "def pair():\n    return 1, 2\n\na, b = pair()\nprint(a, b)"),
    (4, "无 return 的函数输出 None。", "def nothing():\n    x = 1\n\nprint(nothing())", "填空调用。", "def nothing():\n    x = 1\n\nprint(nothing())"),
    (5, "函数返回字符串。", "def msg():\n    return \"Hello\"\n\nprint(msg())", "填空返回字符串。", "def msg():\n    return \"Hello\"\n\nprint(msg())"),
    (6, "函数返回列表。", "def get_list():\n    return [1, 2, 3]\n\nprint(get_list())", "填空返回列表。", "def get_list():\n    return [1, 2, 3]\n\nprint(get_list())"),
    (7, "函数返回字典。", "def get_dict():\n    return {\"a\": 1}\n\nprint(get_dict())", "填空返回字典。", "def get_dict():\n    return {\"a\": 1}\n\nprint(get_dict())"),
    (8, "条件 return 不同值。", "def check(n):\n    if n > 0:\n        return \"positive\"\n    return \"negative\"\n\nprint(check(5))", "填空条件返回。", "def check(n):\n    if n > 0:\n        return \"positive\"\n    return \"negative\"\n\nprint(check(5))"),
    (9, "函数返回循环结果。", "def total():\n    result = 0\n    for i in range(1, 4):\n        result += i\n    return result\n\nprint(total())", "填空循环累加。", "def total():\n    result = 0\n    for i in range(1, 4):\n        result += i\n    return result\n\nprint(total())"),
    (10, "用 type() 查看返回值类型。", "def get():\n    return 42\n\nprint(type(get()))", "填空 type。", "def get():\n    return 42\n\nprint(type(get()))"),
    (11, "提前 return 退出函数。", "def find():\n    for i in range(5):\n        if i == 2:\n            return i\n    return -1\n\nprint(find())", "填空提前返回。", "def find():\n    for i in range(5):\n        if i == 2:\n            return i\n    return -1\n\nprint(find())"),
    (12, "多返回值用于运算。", "def get():\n    return 3, 4\n\na, b = get()\nprint(a * b)", "填空解包运算。", "def get():\n    return 3, 4\n\na, b = get()\nprint(a * b)"),
    (13, "返回值参与外部运算。", "def square(x):\n    return x * x\n\nprint(square(5) + 1)", "填空返回参与运算。", "def square(x):\n    return x * x\n\nprint(square(5) + 1)"),
    (14, "函数返回布尔值。", "def is_big(n):\n    return n > 10\n\nprint(is_big(15))", "填空布尔返回。", "def is_big(n):\n    return n > 10\n\nprint(is_big(15))"),
    (15, "函数返回拼接字符串。", "def full(first, last):\n    return first + \" \" + last\n\nprint(full(\"Tom\", \"Lee\"))", "填空拼接返回。", "def full(first, last):\n    return first + \" \" + last\n\nprint(full(\"Tom\", \"Lee\"))"),
    (16, "函数返回参数平方。", "def sq(n):\n    return n * n\n\nprint(sq(6))", "填空平方返回。", "def sq(n):\n    return n * n\n\nprint(sq(6))"),
    (17, "函数返回累加结果。", "def accumulate():\n    total = 0\n    for i in range(1, 5):\n        total += i\n    return total\n\nprint(accumulate())", "填空返回总和。", "def accumulate():\n    total = 0\n    for i in range(1, 5):\n        total += i\n    return total\n\nprint(accumulate())"),
    (18, "对比 return 与 print。", "def f():\n    print(\"inside\")\n    return 10\n\nresult = f()\nprint(result)", "填空调用与输出。", "def f():\n    print(\"inside\")\n    return 10\n\nresult = f()\nprint(result)"),
    (19, "返回值用于条件判断。", "def is_even(n):\n    return n % 2 == 0\n\nif is_even(8):\n    print(\"even\")\nelse:\n    print(\"odd\")", "填空返回值判断。", "def is_even(n):\n    return n % 2 == 0\n\nif is_even(8):\n    print(\"even\")\nelse:\n    print(\"odd\")"),
    (20, "多个函数返回值组合。", "def one():\n    return 1\n\ndef two():\n    return 2\n\nprint(one() + two())", "填空多函数返回。", "def one():\n    return 1\n\ndef two():\n    return 2\n\nprint(one() + two())"),
    (21, "函数返回元组。", "def point():\n    return (3, 4)\n\nprint(point())", "填空返回元组。", "def point():\n    return (3, 4)\n\nprint(point())"),
    (22, "函数返回格式化字符串。", "def greet(name):\n    return f\"Hello, {name}!\"\n\nprint(greet(\"Bob\"))", "填空格式化返回。", "def greet(name):\n    return f\"Hello, {name}!\"\n\nprint(greet(\"Bob\"))"),
    (23, "函数返回转换结果。", "def to_str(n):\n    return str(n)\n\nprint(to_str(42) * 2)", "填空转换返回。", "def to_str(n):\n    return str(n)\n\nprint(to_str(42) * 2)"),
    (24, "递归返回阶乘。", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5))", "填空递归返回。", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5))"),
    (25, "显式返回 None。", "def empty():\n    return None\n\nprint(\"explicit:\", empty())", "填空返回 None。", "def empty():\n    return None\n\nprint(\"explicit:\", empty())"),
    (26, "函数返回值链式调用。", "def add(x):\n    return x + 10\n\nprint(add(add(5)))", "填空链式调用。", "def add(x):\n    return x + 10\n\nprint(add(add(5)))"),
    (27, "函数返回参数处理结果。", "def reverse(s):\n    return s[::-1]\n\nprint(reverse(\"abc\"))", "填空反转返回。", "def reverse(s):\n    return s[::-1]\n\nprint(reverse(\"abc\"))"),
    (28, "函数返回最大值。", "def maximum(a, b):\n    if a > b:\n        return a\n    return b\n\nprint(maximum(7, 9))", "填空取最大返回。", "def maximum(a, b):\n    if a > b:\n        return a\n    return b\n\nprint(maximum(7, 9))"),
    (29, "函数返回最小值。", "def minimum(a, b):\n    return a if a < b else b\n\nprint(minimum(7, 5))", "填空取最小返回。", "def minimum(a, b):\n    return a if a < b else b\n\nprint(minimum(7, 5))"),
    (30, "综合：返回并输出多个结果。", "def stats(a, b):\n    return a + b, a * b\n\ns, p = stats(3, 4)\nprint(s, p)", "填空多返回输出。", "def stats(a, b):\n    return a + b, a * b\n\ns, p = stats(3, 4)\nprint(s, p)"),
]

SIMPLE = [
    (1, "函数返回平均值。", "def average(nums):\n    return sum(nums) / len(nums)\n\nprint(f\"Average: {average([10, 20, 30])}\")", "填空平均返回。", "def average(nums):\n    return sum(nums) / len(nums)\n\nprint(f\"Average: {average([10, 20, 30])}\")"),
    (2, "函数返回列表去重。", "def unique(nums):\n    return list(set(nums))\n\nprint(sorted(unique([3, 1, 2, 1, 3, 5])))", "填空去重返回。", "def unique(nums):\n    return list(set(nums))\n\nprint(sorted(unique([3, 1, 2, 1, 3, 5])))"),
    (3, "函数返回字典频率。", "def freq(text):\n    counts = {}\n    for ch in text:\n        counts[ch] = counts.get(ch, 0) + 1\n    return counts\n\nprint(freq(\"abca\"))", "填空频率返回。", "def freq(text):\n    counts = {}\n    for ch in text:\n        counts[ch] = counts.get(ch, 0) + 1\n    return counts\n\nprint(freq(\"abca\"))"),
    (4, "函数返回列表反转。", "def rev(nums):\n    return nums[::-1]\n\nprint(rev([1, 2, 3, 4, 5]))", "填空反转返回。", "def rev(nums):\n    return nums[::-1]\n\nprint(rev([1, 2, 3, 4, 5]))"),
    (5, "函数返回最值与位置。", "def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([4, 9, 2])\nprint(lo, hi)", "填空极值返回。", "def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([4, 9, 2])\nprint(lo, hi)"),
    (6, "函数返回布尔判断。", "def is_pal(s):\n    return s == s[::-1]\n\nprint(is_pal(\"radar\"), is_pal(\"hello\"))", "填空回文返回。", "def is_pal(s):\n    return s == s[::-1]\n\nprint(is_pal(\"radar\"), is_pal(\"hello\"))"),
    (7, "函数返回累积结果。", "def total_upto(n):\n    return sum(range(1, n + 1))\n\nprint(f\"Sum: {total_upto(10)}\")", "填空求和返回。", "def total_upto(n):\n    return sum(range(1, n + 1))\n\nprint(f\"Sum: {total_upto(10)}\")"),
    (8, "函数返回转换后字符串。", "def to_percent(ratio):\n    return f\"{ratio:.1%}\"\n\nprint(to_percent(0.25))", "填空百分比返回。", "def to_percent(ratio):\n    return f\"{ratio:.1%}\"\n\nprint(to_percent(0.25))"),
    (9, "函数返回偶数列表。", "def evens(nums):\n    return [n for n in nums if n % 2 == 0]\n\nprint(evens([1, 2, 3, 4, 5, 6]))", "填空筛选返回。", "def evens(nums):\n    return [n for n in nums if n % 2 == 0]\n\nprint(evens([1, 2, 3, 4, 5, 6]))"),
    (10, "函数返回格式化信息。", "def describe(name, age):\n    return f\"{name} is {age}\"\n\nprint(describe(\"Alice\", 20))", "填空描述返回。", "def describe(name, age):\n    return f\"{name} is {age}\"\n\nprint(describe(\"Alice\", 20))"),
    (11, "函数返回首个偶数。", "def first_even(nums):\n    for n in nums:\n        if n % 2 == 0:\n            return n\n    return None\n\nprint('First:', first_even([1, 3, 4, 5]))", "填空提前返回。", "def first_even(nums):\n    for n in nums:\n        if n % 2 == 0:\n            return n\n    return None\n\nprint('First:', first_even([1, 3, 4, 5]))"),
    (12, "函数返回字符统计对。", "def counts(s):\n    return len(s), s.count(\"a\")\n\ntotal, a_count = counts(\"banana\")\nprint(total, a_count)", "填空多返回。", "def counts(s):\n    return len(s), s.count(\"a\")\n\ntotal, a_count = counts(\"banana\")\nprint(total, a_count)"),
    (13, "函数返回排序列表。", "def sorted_list(nums):\n    return sorted(nums, reverse=True)\n\nprint(sorted_list([3, 1, 4, 2]))", "填空排序返回。", "def sorted_list(nums):\n    return sorted(nums, reverse=True)\n\nprint(sorted_list([3, 1, 4, 2]))"),
    (14, "函数返回字符串标题。", "def title(text):\n    return text.title()\n\nprint(title(\"hello world\"))", "填空标题返回。", "def title(text):\n    return text.title()\n\nprint(title(\"hello world\"))"),
    (15, "函数返回最大值索引。", "def max_index(nums):\n    return nums.index(max(nums))\n\nprint(max_index([4, 9, 2]))", "填空索引返回。", "def max_index(nums):\n    return nums.index(max(nums))\n\nprint(max_index([4, 9, 2]))"),
    (16, "函数返回组合结果。", "def combine(a, b):\n    return a + b, a - b\n\nadd_result, sub_result = combine(10, 3)\nprint(add_result, sub_result)", "填空组合返回。", "def combine(a, b):\n    return a + b, a - b\n\nadd_result, sub_result = combine(10, 3)\nprint(add_result, sub_result)"),
    (17, "函数返回中间值。", "def middle(nums):\n    nums.sort()\n    return nums[len(nums) // 2]\n\nprint('Middle:', middle([5, 1, 3]))", "填空中位数返回。", "def middle(nums):\n    nums.sort()\n    return nums[len(nums) // 2]\n\nprint('Middle:', middle([5, 1, 3]))"),
    (18, "函数返回重复次数。", "def repeat_count(s, ch):\n    return s.count(ch)\n\nprint('Count:', repeat_count('banana', 'n'))", "填空计数返回。", "def repeat_count(s, ch):\n    return s.count(ch)\n\nprint('Count:', repeat_count('banana', 'n'))"),
    (19, "函数返回单词数量。", "def word_count(text):\n    return len(text.split())\n\nprint('Words:', word_count('a quick brown fox'))", "填空分词返回。", "def word_count(text):\n    return len(text.split())\n\nprint('Words:', word_count('a quick brown fox'))"),
    (20, "函数返回类型对比。", "def get_value():\n    return 3.5\n\nprint(type(get_value()))", "填空类型返回。", "def get_value():\n    return 3.5\n\nprint(type(get_value()))"),
    (21, "函数返回默认与传入。", "def config(key, default=\"N/A\"):\n    return default\n\nprint(config(\"missing\"))", "填空默认返回。", "def config(key, default=\"N/A\"):\n    return default\n\nprint(config(\"missing\"))"),
    (22, "函数返回最大差值。", "def diff(nums):\n    return max(nums) - min(nums)\n\nprint('Diff:', diff([3, 9, 1, 6]))", "填空差值返回。", "def diff(nums):\n    return max(nums) - min(nums)\n\nprint('Diff:', diff([3, 9, 1, 6]))"),
    (23, "函数返回拼接标题。", "def heading(text, level=1):\n    return \"#\" * level + \" \" + text\n\nprint(heading(\"Welcome\"))", "填空标题返回。", "def heading(text, level=1):\n    return \"#\" * level + \" \" + text\n\nprint(heading(\"Welcome\"))"),
    (24, "函数返回列表求和。", "def sum_list(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total\n\nprint(f\"Total: {sum_list([5, 10, 15])}\")", "填空求和返回。", "def sum_list(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total\n\nprint(f\"Total: {sum_list([5, 10, 15])}\")"),
    (25, "函数返回是否包含。", "def contains(s, sub):\n    return sub in s\n\nprint('Contains:', contains('hello', 'lo'))", "填空包含返回。", "def contains(s, sub):\n    return sub in s\n\nprint('Contains:', contains('hello', 'lo'))"),
    (26, "函数返回翻转字符串。", "def flip(s):\n    return \"\".join(reversed(s))\n\nprint(flip(\"hello\"))", "填空翻转返回。", "def flip(s):\n    return \"\".join(reversed(s))\n\nprint(flip(\"hello\"))"),
    (27, "函数返回整除与余数。", "def divmod_result(a, b):\n    return a // b, a % b\n\nq, r = divmod_result(17, 5)\nprint(q, r)", "填空商余返回。", "def divmod_result(a, b):\n    return a // b, a % b\n\nq, r = divmod_result(17, 5)\nprint(q, r)"),
    (28, "函数返回大写形式。", "def shout(text):\n    return text.upper()\n\nprint(shout(\"good\"))", "填空大写返回。", "def shout(text):\n    return text.upper()\n\nprint(shout(\"good\"))"),
    (29, "函数返回默认值兜底。", "def safe_get(d, key, default=None):\n    return d.get(key, default)\n\nprint(safe_get({\"a\": 1}, \"b\", 0))", "填空兜底返回。", "def safe_get(d, key, default=None):\n    return d.get(key, default)\n\nprint(safe_get({\"a\": 1}, \"b\", 0))"),
    (30, "综合：多个函数返回值协作。", "def add(a, b):\n    return a + b\n\ndef mul(a, b):\n    return a * b\n\nprint(add(2, 3), mul(2, 3))", "填空函数协作。", "def add(a, b):\n    return a + b\n\ndef mul(a, b):\n    return a * b\n\nprint(add(2, 3), mul(2, 3))"),
]

MEDIUM = [
    (1, "函数返回计算表达式结果。", "def poly(x):\n    return 2 * x ** 2 + 3 * x + 1\n\nprint(f\"Poly: {poly(2)}\")", "填空多项式返回。", "def poly(x):\n    return 2 * x ** 2 + 3 * x + 1\n\nprint(f\"Poly: {poly(2)}\")"),
    (2, "函数返回质数判断。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nprint('Prime:', is_prime(13), is_prime(14))", "填空质数返回。", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nprint('Prime:', is_prime(13), is_prime(14))"),
    (3, "函数返回回文数判断。", "def is_pal_num(n):\n    return str(n) == str(n)[::-1]\n\nprint('Pal:', is_pal_num(121), is_pal_num(123))", "填空回文数返回。", "def is_pal_num(n):\n    return str(n) == str(n)[::-1]\n\nprint('Pal:', is_pal_num(121), is_pal_num(123))"),
    (4, "函数返回数字反转。", "def reverse_num(n):\n    return int(str(n)[::-1])\n\nprint(f\"Reversed: {reverse_num(123)}\")", "填空反转返回。", "def reverse_num(n):\n    return int(str(n)[::-1])\n\nprint(f\"Reversed: {reverse_num(123)}\")"),
    (5, "函数返回快乐数状态。", "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nprint('Happy:', is_happy(19))", "填空快乐数返回。", "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nprint('Happy:', is_happy(19))"),
    (6, "函数返回最大公约数。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\nprint(f\"GCD: {gcd(48, 36)}\")", "填空 gcd 返回。", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\nprint(f\"GCD: {gcd(48, 36)}\")"),
    (7, "函数返回多返回值并格式化。", "def circle(r):\n    return 2 * 3.14 * r, 3.14 * r * r\n\nc, a = circle(1)\nprint(round(c, 2), round(a, 2))", "填空圆参数返回。", "def circle(r):\n    return 2 * 3.14 * r, 3.14 * r * r\n\nc, a = circle(1)\nprint(round(c, 2), round(a, 2))"),
    (8, "函数返回字典统计。", "def char_counts(s):\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    return counts\n\nprint(char_counts(\"hello\"))", "填空字符统计返回。", "def char_counts(s):\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    return counts\n\nprint(char_counts(\"hello\"))"),
    (9, "函数返回第 n 个斐波那契。", "def fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint(f\"fib(7) = {fib(7)}\")", "填空斐波那契返回。", "def fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint(f\"fib(7) = {fib(7)}\")"),
    (10, "函数返回列表操作结果。", "def append_double(nums, n):\n    return nums + [n * 2]\n\nprint(append_double([1, 2], 5))", "填空列表返回。", "def append_double(nums, n):\n    return nums + [n * 2]\n\nprint(append_double([1, 2], 5))"),
    (11, "函数返回条件筛选。", "def filter_positive(nums):\n    return [n for n in nums if n > 0]\n\nprint(filter_positive([-1, 2, -3, 4]))", "填空筛选返回。", "def filter_positive(nums):\n    return [n for n in nums if n > 0]\n\nprint(filter_positive([-1, 2, -3, 4]))"),
    (12, "函数返回键值对数量。", "def size(d):\n    return len(d)\n\nprint('Size:', size({'a': 1, 'b': 2, 'c': 3}))", "填空字典大小。", "def size(d):\n    return len(d)\n\nprint('Size:', size({'a': 1, 'b': 2, 'c': 3}))"),
    (13, "函数返回字符串压缩长度。", "def unique_chars(s):\n    return len(set(s))\n\nprint('Unique:', unique_chars('banana'))", "填空唯一字符。", "def unique_chars(s):\n    return len(set(s))\n\nprint('Unique:', unique_chars('banana'))"),
    (14, "函数返回最大乘积对。", "def max_pair_product(nums):\n    sorted_nums = sorted(nums)\n    return sorted_nums[-1] * sorted_nums[-2]\n\nprint(max_pair_product([3, 5, 2, 7, 4]))", "填空乘积返回。", "def max_pair_product(nums):\n    sorted_nums = sorted(nums)\n    return sorted_nums[-1] * sorted_nums[-2]\n\nprint(max_pair_product([3, 5, 2, 7, 4]))"),
    (15, "函数返回出现次数最多字符。", "def most_common(s):\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    return max(counts, key=counts.get)\n\nprint(most_common(\"banana\"))", "填空众数字符。", "def most_common(s):\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    return max(counts, key=counts.get)\n\nprint(most_common(\"banana\"))"),
    (16, "函数返回列表合并去重。", "def merge_unique(a, b):\n    return sorted(set(a + b))\n\nprint(merge_unique([1, 2, 3], [2, 3, 4]))", "填空合并返回。", "def merge_unique(a, b):\n    return sorted(set(a + b))\n\nprint(merge_unique([1, 2, 3], [2, 3, 4]))"),
    (17, "函数返回数字位数和。", "def digit_sum(n):\n    return sum(int(d) for d in str(n))\n\nprint(f\"Digit sum: {digit_sum(1234)}\")", "填空位和返回。", "def digit_sum(n):\n    return sum(int(d) for d in str(n))\n\nprint(f\"Digit sum: {digit_sum(1234)}\")"),
    (18, "函数返回矩阵列和。", "def column_sums(matrix):\n    return [sum(row[i] for row in matrix) for i in range(len(matrix[0]))]\n\nprint(column_sums([[1, 2], [3, 4]]))", "填空列和返回。", "def column_sums(matrix):\n    return [sum(row[i] for row in matrix) for i in range(len(matrix[0]))]\n\nprint(column_sums([[1, 2], [3, 4]]))"),
    (19, "函数返回回文子串数。", "def count_palindromic(s):\n    count = 0\n    for i in range(len(s)):\n        for j in range(i, len(s)):\n            sub = s[i:j + 1]\n            if sub == sub[::-1]:\n                count += 1\n    return count\n\nprint('Count:', count_palindromic('aba'))", "填空回文计数。", "def count_palindromic(s):\n    count = 0\n    for i in range(len(s)):\n        for j in range(i, len(s)):\n            sub = s[i:j + 1]\n            if sub == sub[::-1]:\n                count += 1\n    return count\n\nprint('Count:', count_palindromic('aba'))"),
    (20, "函数返回成绩等级。", "def grade(score):\n    if score >= 90:\n        return \"A\"\n    elif score >= 80:\n        return \"B\"\n    else:\n        return \"C\"\n\nfor s in [92, 85, 70]:\n    print(f\"{s} -> {grade(s)}\")", "填空等级返回。", "def grade(score):\n    if score >= 90:\n        return \"A\"\n    elif score >= 80:\n        return \"B\"\n    else:\n        return \"C\"\n\nfor s in [92, 85, 70]:\n    print(f\"{s} -> {grade(s)}\")"),
    (21, "函数返回幂运算结果。", "def power(base, exp):\n    return base ** exp\n\nprint(f\"Power: {power(3, 4)}\")", "填空幂返回。", "def power(base, exp):\n    return base ** exp\n\nprint(f\"Power: {power(3, 4)}\")"),
    (22, "函数返回组合数。", "def comb(n, k):\n    if k == 0 or k == n:\n        return 1\n    return comb(n - 1, k - 1) + comb(n - 1, k)\n\nprint('Comb:', comb(5, 2))", "填空组合返回。", "def comb(n, k):\n    if k == 0 or k == n:\n        return 1\n    return comb(n - 1, k - 1) + comb(n - 1, k)\n\nprint('Comb:', comb(5, 2))"),
    (23, "函数返回数字进制形式。", "def to_binary(n):\n    return bin(n)[2:]\n\nprint(to_binary(10))", "填空二进制返回。", "def to_binary(n):\n    return bin(n)[2:]\n\nprint(to_binary(10))"),
    (24, "函数返回元组解包结果。", "def unpack(pairs):\n    return [a + b for a, b in pairs]\n\nprint(unpack([(1, 2), (3, 4), (5, 6)]))", "填空解包返回。", "def unpack(pairs):\n    return [a + b for a, b in pairs]\n\nprint(unpack([(1, 2), (3, 4), (5, 6)]))"),
    (25, "函数返回条件默认值。", "def validate(n, minimum=0):\n    if n < minimum:\n        return minimum\n    return n\n\nprint(validate(5), validate(-3, 0))", "填空校验返回。", "def validate(n, minimum=0):\n    if n < minimum:\n        return minimum\n    return n\n\nprint(validate(5), validate(-3, 0))"),
    (26, "函数返回列表平均值与中位数。", "def stats(nums):\n    avg = sum(nums) / len(nums)\n    sorted_nums = sorted(nums)\n    mid = len(sorted_nums) // 2\n    median = sorted_nums[mid]\n    return avg, median\n\na, m = stats([3, 1, 2])\nprint(round(a, 1), m)", "填空统计返回。", "def stats(nums):\n    avg = sum(nums) / len(nums)\n    sorted_nums = sorted(nums)\n    mid = len(sorted_nums) // 2\n    median = sorted_nums[mid]\n    return avg, median\n\na, m = stats([3, 1, 2])\nprint(round(a, 1), m)"),
    (27, "函数返回字符串中数字和。", "def digit_total(s):\n    return sum(int(c) for c in s if c.isdigit())\n\nprint('Sum:', digit_total('a1b2c3'))", "填空数字和返回。", "def digit_total(s):\n    return sum(int(c) for c in s if c.isdigit())\n\nprint('Sum:', digit_total('a1b2c3'))"),
    (28, "函数返回去重排序单词。", "def unique_words(text):\n    return sorted(set(text.lower().split()))\n\nprint(unique_words(\"Apple apple Banana\"))", "填空单词去重。", "def unique_words(text):\n    return sorted(set(text.lower().split()))\n\nprint(unique_words(\"Apple apple Banana\"))"),
    (29, "函数返回最大递增差。", "def max_gain(prices):\n    min_price = prices[0]\n    max_profit = 0\n    for p in prices:\n        min_price = min(min_price, p)\n        max_profit = max(max_profit, p - min_price)\n    return max_profit\n\nprint('Gain:', max_gain([7, 1, 5, 3, 6, 4]))", "填空最大收益。", "def max_gain(prices):\n    min_price = prices[0]\n    max_profit = 0\n    for p in prices:\n        min_price = min(min_price, p)\n        max_profit = max(max_profit, p - min_price)\n    return max_profit\n\nprint('Gain:', max_gain([7, 1, 5, 3, 6, 4]))"),
    (30, "综合：返回并汇总多个统计。", "def analyze(nums):\n    return len(nums), sum(nums), max(nums)\n\nn, s, m = analyze([2, 4, 6, 8])\nprint(f\"Count: {n}, Sum: {s}, Max: {m}\")", "填空分析返回。", "def analyze(nums):\n    return len(nums), sum(nums), max(nums)\n\nn, s, m = analyze([2, 4, 6, 8])\nprint(f\"Count: {n}, Sum: {s}, Max: {m}\")"),
]

HARD = [
    (1, "函数返回最小步数（DP 记忆化）。", "def min_steps(n, memo=None):\n    if memo is None:\n        memo = {}\n    if n <= 1:\n        return 0\n    if n in memo:\n        return memo[n]\n    memo[n] = 1 + min_steps(n - 1, memo)\n    return memo[n]\n\nprint(f\"Steps: {min_steps(6)}\")", "填空 DP 返回。", "def min_steps(n, memo=None):\n    if memo is None:\n        memo = {}\n    if n <= 1:\n        return 0\n    if n in memo:\n        return memo[n]\n    memo[n] = 1 + min_steps(n - 1, memo)\n    return memo[n]\n\nprint(f\"Steps: {min_steps(6)}\")"),
    (2, "函数返回最长公共前缀。", "def common_prefix(words):\n    if not words:\n        return \"\"\n    prefix = words[0]\n    for w in words[1:]:\n        while not w.startswith(prefix):\n            prefix = prefix[:-1]\n            if not prefix:\n                return \"\"\n    return prefix\n\nprint(common_prefix([\"flower\", \"flow\", \"flight\"]))", "填空公共前缀。", "def common_prefix(words):\n    if not words:\n        return \"\"\n    prefix = words[0]\n    for w in words[1:]:\n        while not w.startswith(prefix):\n            prefix = prefix[:-1]\n            if not prefix:\n                return \"\"\n    return prefix\n\nprint(common_prefix([\"flower\", \"flow\", \"flight\"]))"),
    (3, "函数返回合并区间。", "def merge(intervals):\n    intervals.sort()\n    result = []\n    for start, end in intervals:\n        if result and start <= result[-1][1]:\n            result[-1][1] = max(result[-1][1], end)\n        else:\n            result.append([start, end])\n    return result\n\nprint(merge([[1, 3], [2, 6], [8, 10], [15, 18]]))", "填空区间合并返回。", "def merge(intervals):\n    intervals.sort()\n    result = []\n    for start, end in intervals:\n        if result and start <= result[-1][1]:\n            result[-1][1] = max(result[-1][1], end)\n        else:\n            result.append([start, end])\n    return result\n\nprint(merge([[1, 3], [2, 6], [8, 10], [15, 18]]))"),
    (4, "函数返回两数之和索引。", "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target - n], i]\n        seen[n] = i\n    return []\n\nprint(two_sum([2, 7, 11, 15], 9))", "填空两数之和。", "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target - n], i]\n        seen[n] = i\n    return []\n\nprint(two_sum([2, 7, 11, 15], 9))"),
    (5, "函数返回矩阵螺旋。", "def spiral(matrix):\n    result = []\n    while matrix:\n        result += matrix.pop(0)\n        if matrix and matrix[0]:\n            for row in matrix:\n                result.append(row.pop())\n        if matrix:\n            result += matrix.pop()[::-1]\n        if matrix and matrix[0]:\n            for row in matrix[::-1]:\n                result.append(row.pop(0))\n    return result\n\nprint(spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))", "填空螺旋返回。", "def spiral(matrix):\n    result = []\n    while matrix:\n        result += matrix.pop(0)\n        if matrix and matrix[0]:\n            for row in matrix:\n                result.append(row.pop())\n        if matrix:\n            result += matrix.pop()[::-1]\n        if matrix and matrix[0]:\n            for row in matrix[::-1]:\n                result.append(row.pop(0))\n    return result\n\nprint(spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))"),
    (6, "函数返回最大子数组和。", "def max_sub(nums):\n    best = nums[0]\n    cur = 0\n    for n in nums:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best\n\nprint(f\"Max: {max_sub([-2, 1, -3, 4, -1, 2, 1])}\")", "填空 Kadane 返回。", "def max_sub(nums):\n    best = nums[0]\n    cur = 0\n    for n in nums:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best\n\nprint(f\"Max: {max_sub([-2, 1, -3, 4, -1, 2, 1])}\")"),
    (7, "函数返回字符串压缩。", "def compress(s):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aabcccccaaa\"))", "填空压缩返回。", "def compress(s):\n    result = \"\"\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            count += 1\n        else:\n            result += s[i - 1] + str(count)\n            count = 1\n    result += s[-1] + str(count)\n    return result\n\nprint(compress(\"aabcccccaaa\"))"),
    (8, "函数返回第 n 个质数。", "def nth_prime(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if all(num % p for p in primes if p * p <= num):\n            primes.append(num)\n        num += 1\n    return primes[-1]\n\nprint(f\"Prime: {nth_prime(7)}\")", "填空第 n 质数。", "def nth_prime(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if all(num % p for p in primes if p * p <= num):\n            primes.append(num)\n        num += 1\n    return primes[-1]\n\nprint(f\"Prime: {nth_prime(7)}\")"),
    (9, "函数返回最大回文子串长度。", "def longest_pal(s):\n    best = 1\n    for i in range(len(s)):\n        for j in range(i, len(s)):\n            sub = s[i:j + 1]\n            if sub == sub[::-1]:\n                best = max(best, len(sub))\n    return best\n\nprint(f\"Length: {longest_pal('babad')}\")", "填空回文长度。", "def longest_pal(s):\n    best = 1\n    for i in range(len(s)):\n        for j in range(i, len(s)):\n            sub = s[i:j + 1]\n            if sub == sub[::-1]:\n                best = max(best, len(sub))\n    return best\n\nprint(f\"Length: {longest_pal('babad')}\")"),
    (10, "函数返回约瑟夫幸存者。", "def josephus(n, k):\n    people = list(range(1, n + 1))\n    idx = 0\n    while len(people) > 1:\n        idx = (idx + k - 1) % len(people)\n        people.pop(idx)\n    return people[0]\n\nprint(f\"Survivor: {josephus(6, 3)}\")", "填空约瑟夫返回。", "def josephus(n, k):\n    people = list(range(1, n + 1))\n    idx = 0\n    while len(people) > 1:\n        idx = (idx + k - 1) % len(people)\n        people.pop(idx)\n    return people[0]\n\nprint(f\"Survivor: {josephus(6, 3)}\")"),
    (11, "函数返回罗马数字。", "def to_roman(n):\n    pairs = [(10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\")]\n    result = \"\"\n    for value, symbol in pairs:\n        while n >= value:\n            result += symbol\n            n -= value\n    return result\n\nprint(to_roman(14))", "填空罗马返回。", "def to_roman(n):\n    pairs = [(10, \"X\"), (9, \"IX\"), (5, \"V\"), (4, \"IV\"), (1, \"I\")]\n    result = \"\"\n    for value, symbol in pairs:\n        while n >= value:\n            result += symbol\n            n -= value\n    return result\n\nprint(to_roman(14))"),
    (12, "函数返回最接近目标的和。", "def closest(nums, target):\n    closest_sum = sum(nums[:3])\n    for i in range(len(nums)):\n        for j in range(i + 1, len(nums)):\n            for k in range(j + 1, len(nums)):\n                total = nums[i] + nums[j] + nums[k]\n                if abs(total - target) < abs(closest_sum - target):\n                    closest_sum = total\n    return closest_sum\n\nprint(f\"Closest: {closest([-1, 2, 1, -4], 1)}\")", "填空最近和。", "def closest(nums, target):\n    closest_sum = sum(nums[:3])\n    for i in range(len(nums)):\n        for j in range(i + 1, len(nums)):\n            for k in range(j + 1, len(nums)):\n                total = nums[i] + nums[j] + nums[k]\n                if abs(total - target) < abs(closest_sum - target):\n                    closest_sum = total\n    return closest_sum\n\nprint(f\"Closest: {closest([-1, 2, 1, -4], 1)}\")"),
    (13, "函数返回括号是否有效。", "def valid_brackets(s):\n    stack = []\n    pairs = {\")\": \"(\", \"]\": \"[\", \"}\": \"{\"}\n    for ch in s:\n        if ch in \"([{\":\n            stack.append(ch)\n        elif not stack or stack.pop() != pairs[ch]:\n            return False\n    return not stack\n\nprint('Valid:', valid_brackets('{[]}'), valid_brackets('([)]'))", "填空括号校验。", "def valid_brackets(s):\n    stack = []\n    pairs = {\")\": \"(\", \"]\": \"[\", \"}\": \"{\"}\n    for ch in s:\n        if ch in \"([{\":\n            stack.append(ch)\n        elif not stack or stack.pop() != pairs[ch]:\n            return False\n    return not stack\n\nprint('Valid:', valid_brackets('{[]}'), valid_brackets('([)]'))"),
    (14, "函数返回下一个更大元素。", "def next_greater(nums):\n    result = [-1] * len(nums)\n    stack = []\n    for i in range(len(nums)):\n        while stack and nums[stack[-1]] < nums[i]:\n            result[stack.pop()] = nums[i]\n        stack.append(i)\n    return result\n\nprint(next_greater([2, 1, 4, 3]))", "填空单调栈。", "def next_greater(nums):\n    result = [-1] * len(nums)\n    stack = []\n    for i in range(len(nums)):\n        while stack and nums[stack[-1]] < nums[i]:\n            result[stack.pop()] = nums[i]\n        stack.append(i)\n    return result\n\nprint(next_greater([2, 1, 4, 3]))"),
    (15, "函数返回乘法表。", "def mul_table(n):\n    return [[i * j for j in range(1, n + 1)] for i in range(1, n + 1)]\n\nfor row in mul_table(3):\n    print(row)", "填空乘法表返回。", "def mul_table(n):\n    return [[i * j for j in range(1, n + 1)] for i in range(1, n + 1)]\n\nfor row in mul_table(3):\n    print(row)"),
    (16, "函数返回最大水位差。", "def max_water(heights):\n    max_area = 0\n    for i in range(len(heights)):\n        for j in range(i + 1, len(heights)):\n            area = min(heights[i], heights[j]) * (j - i)\n            max_area = max(max_area, area)\n    return max_area\n\nprint(f\"Area: {max_water([1, 8, 6, 2, 5, 4, 8, 3, 7])}\")", "填空最大面积。", "def max_water(heights):\n    max_area = 0\n    for i in range(len(heights)):\n        for j in range(i + 1, len(heights)):\n            area = min(heights[i], heights[j]) * (j - i)\n            max_area = max(max_area, area)\n    return max_area\n\nprint(f\"Area: {max_water([1, 8, 6, 2, 5, 4, 8, 3, 7])}\")"),
    (17, "函数返回移动后数组。", "def rotate(nums, k):\n    k = k % len(nums)\n    return nums[-k:] + nums[:-k]\n\nprint(rotate([1, 2, 3, 4, 5], 2))", "填空旋转返回。", "def rotate(nums, k):\n    k = k % len(nums)\n    return nums[-k:] + nums[:-k]\n\nprint(rotate([1, 2, 3, 4, 5], 2))"),
    (18, "函数返回第一个缺失正数。", "def first_missing(nums):\n    present = set(nums)\n    n = 1\n    while n in present:\n        n += 1\n    return n\n\nprint(f\"Missing: {first_missing([1, 2, 0])}\")", "填空缺失数。", "def first_missing(nums):\n    present = set(nums)\n    n = 1\n    while n in present:\n        n += 1\n    return n\n\nprint(f\"Missing: {first_missing([1, 2, 0])}\")"),
    (19, "函数返回分组异或结果。", "def xor_groups(nums, size):\n    result = []\n    for i in range(0, len(nums), size):\n        group = nums[i:i + size]\n        total = 0\n        for n in group:\n            total ^= n\n        result.append(total)\n    return result\n\nprint(xor_groups([1, 2, 3, 4], 2))", "填空异或分组。", "def xor_groups(nums, size):\n    result = []\n    for i in range(0, len(nums), size):\n        group = nums[i:i + size]\n        total = 0\n        for n in group:\n            total ^= n\n        result.append(total)\n    return result\n\nprint(xor_groups([1, 2, 3, 4], 2))"),
    (20, "函数返回可形成最大数。", "def largest_number(nums):\n    strs = [str(n) for n in nums]\n    strs.sort(key=lambda a, b: -1, reverse=False)\n    from functools import cmp_to_key\n    strs.sort(key=cmp_to_key(lambda a, b: -1 if a + b > b + a else 1))\n    result = \"\".join(strs)\n    return \"0\" if result[0] == \"0\" else result\n\nprint(largest_number([3, 30, 34, 5, 9]))", "填空最大数。", "def largest_number(nums):\n    from functools import cmp_to_key\n    strs = [str(n) for n in nums]\n    strs.sort(key=cmp_to_key(lambda a, b: -1 if a + b > b + a else 1))\n    result = \"\".join(strs)\n    return \"0\" if result[0] == \"0\" else result\n\nprint(largest_number([3, 30, 34, 5, 9]))"),
    (21, "函数返回加一后的列表。", "def plus_one(digits):\n    n = len(digits)\n    for i in range(n - 1, -1, -1):\n        if digits[i] < 9:\n            digits[i] += 1\n            return digits\n        digits[i] = 0\n    return [1] + digits\n\nprint(plus_one([1, 2, 3]), plus_one([9, 9]))", "填空加一返回。", "def plus_one(digits):\n    n = len(digits)\n    for i in range(n - 1, -1, -1):\n        if digits[i] < 9:\n            digits[i] += 1\n            return digits\n        digits[i] = 0\n    return [1] + digits\n\nprint(plus_one([1, 2, 3]), plus_one([9, 9]))"),
    (22, "函数返回去重后的长度。", "def remove_duplicates(nums):\n    nums.sort()\n    unique = []\n    for n in nums:\n        if not unique or unique[-1] != n:\n            unique.append(n)\n    return len(unique)\n\nprint(f\"Length: {remove_duplicates([1, 1, 2])}\")", "填空去重长度。", "def remove_duplicates(nums):\n    nums.sort()\n    unique = []\n    for n in nums:\n        if not unique or unique[-1] != n:\n            unique.append(n)\n    return len(unique)\n\nprint(f\"Length: {remove_duplicates([1, 1, 2])}\")"),
    (23, "函数返回最大子序列乘积。", "def max_prod(nums):\n    best = nums[0]\n    for i in range(len(nums)):\n        prod = 1\n        for j in range(i, len(nums)):\n            prod *= nums[j]\n            best = max(best, prod)\n    return best\n\nprint(f\"Product: {max_prod([2, 3, -2, 4])}\")", "填空乘积返回。", "def max_prod(nums):\n    best = nums[0]\n    for i in range(len(nums)):\n        prod = 1\n        for j in range(i, len(nums)):\n            prod *= nums[j]\n            best = max(best, prod)\n    return best\n\nprint(f\"Product: {max_prod([2, 3, -2, 4])}\")"),
    (24, "函数返回分块结果。", "def chunk(nums, size):\n    return [nums[i:i + size] for i in range(0, len(nums), size)]\n\nprint(chunk([1, 2, 3, 4, 5], 2))", "填空分块返回。", "def chunk(nums, size):\n    return [nums[i:i + size] for i in range(0, len(nums), size)]\n\nprint(chunk([1, 2, 3, 4, 5], 2))"),
    (25, "函数返回最长连续序列长度。", "def longest_consecutive(nums):\n    num_set = set(nums)\n    longest = 0\n    for n in num_set:\n        if n - 1 not in num_set:\n            length = 1\n            while n + length in num_set:\n                length += 1\n            longest = max(longest, length)\n    return longest\n\nprint(f\"Longest: {longest_consecutive([100, 4, 200, 1, 3, 2])}\")", "填空连续长度。", "def longest_consecutive(nums):\n    num_set = set(nums)\n    longest = 0\n    for n in num_set:\n        if n - 1 not in num_set:\n            length = 1\n            while n + length in num_set:\n                length += 1\n            longest = max(longest, length)\n    return longest\n\nprint(f\"Longest: {longest_consecutive([100, 4, 200, 1, 3, 2])}\")"),
    (26, "函数返回矩阵副对角线和。", "def anti_diag(matrix):\n    n = len(matrix)\n    return sum(matrix[i][n - 1 - i] for i in range(n))\n\nprint(f\"Sum: {anti_diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]])}\")", "填空副对角线。", "def anti_diag(matrix):\n    n = len(matrix)\n    return sum(matrix[i][n - 1 - i] for i in range(n))\n\nprint(f\"Sum: {anti_diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]])}\")"),
    (27, "函数返回表达式结果表。", "def evaluate(a, b):\n    return [a + b, a - b, a * b, a / b]\n\nprint(evaluate(10, 2))", "填空表达式返回。", "def evaluate(a, b):\n    return [a + b, a - b, a * b, a / b]\n\nprint(evaluate(10, 2))"),
    (28, "函数返回第 k 大元素。", "def kth_largest(nums, k):\n    return sorted(nums, reverse=True)[k - 1]\n\nprint(f\"Kth: {kth_largest([3, 2, 1, 5, 6, 4], 2)}\")", "填空第 k 大。", "def kth_largest(nums, k):\n    return sorted(nums, reverse=True)[k - 1]\n\nprint(f\"Kth: {kth_largest([3, 2, 1, 5, 6, 4], 2)}\")"),
    (29, "函数返回列表中的峰元素。", "def peak(nums):\n    for i in range(1, len(nums) - 1):\n        if nums[i] > nums[i - 1] and nums[i] > nums[i + 1]:\n            return nums[i]\n    return None\n\nprint('Peak:', peak([1, 3, 2, 4, 1]))", "填空峰元素。", "def peak(nums):\n    for i in range(1, len(nums) - 1):\n        if nums[i] > nums[i - 1] and nums[i] > nums[i + 1]:\n            return nums[i]\n    return None\n\nprint('Peak:', peak([1, 3, 2, 4, 1]))"),
    (30, "综合：函数返回多维度统计。", "def full_stats(nums):\n    return len(nums), sum(nums), sum(nums) / len(nums), max(nums), min(nums)\n\ncount, total, avg, mx, mn = full_stats([4, 8, 6])\nprint(count, total, round(avg, 1), mx, mn)", "填空综合统计返回。", "def full_stats(nums):\n    return len(nums), sum(nums), sum(nums) / len(nums), max(nums), min(nums)\n\ncount, total, avg, mx, mn = full_stats([4, 8, 6])\nprint(count, total, round(avg, 1), mx, mn)"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
