# -*- coding: utf-8 -*-
"""生成 CH04 基础运算符 题库（4 档 × 30 = 120 道）。

id 后缀沿用递进命名：E=超简单 / M=简单 / H=中等 / X=较难。
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from framework import gen_chapter  # noqa: E402

CHAPTER = "CH04"
TITLE = "基础运算符"
OUT_DIR = "CH04_Operators"
DIFF = {"E": ("超简单", "⭐"), "M": ("简单", "⭐⭐"),
        "H": ("中等", "⭐⭐⭐"), "X": ("较难", "⭐⭐⭐⭐")}
TOPIC = {"E": TITLE, "M": TITLE, "H": TITLE, "X": TITLE}

EASY = [
    (1, "用 + 计算两个数相加。", "print(3 + ___)", "填 5。", "print(3 + 5)"),
    (2, "用 - 计算两个数相减。", "print(___ - 4)", "填 10。", "print(10 - 4)"),
    (3, "用 * 计算两个数相乘。", "print(6 * ___)", "填 7。", "print(6 * 7)"),
    (4, "用 / 计算两个数相除。", "print(9 / ___)", "填 2。", "print(9 / 2)"),
    (5, "用 // 计算整除结果。", "print(9 // ___)", "填 2。", "print(9 // 2)"),
    (6, "用 % 计算取余结果。", "print(9 % ___)", "填 2。", "print(9 % 2)"),
    (7, "用 ** 计算幂运算。", "print(2 ** ___)", "填 5。", "print(2 ** 5)"),
    (8, "比较三个结果并输出。", "a = 5\nb = 3\nprint(___ > b, a == ___, a < b)", "依次填 a、b。", "a = 5\nb = 3\nprint(a > b, a == b, a < b)"),
    (9, "比较 >= 和 == 的结果。", "a = 5\nb = 5\nprint(a >= ___, a == b)", "填 b。", "a = 5\nb = 5\nprint(a >= b, a == b)"),
    (10, "比较 != 和 == 的结果。", "a = 3\nb = 4\nprint(a != ___, a == b)", "填 b。", "a = 3\nb = 4\nprint(a != b, a == b)"),
    (11, "输出 and 与 or 的结果。", "print(True and ___, True or False)", "填 False。", "print(True and False, True or False)"),
    (12, "用 not 取反布尔值。", "print(___ True)", "填 not。", "print(not True)"),
    (13, "用 and 连接两个比较。", "print(5 > 3 ___ 5 < 10)", "填 and。", "print(5 > 3 and 5 < 10)"),
    (14, "用 += 复合赋值后输出。", "x = 5\nx += ___\nprint(x)", "填 10。", "x = 5\nx += 10\nprint(x)"),
    (15, "输出负数。", "print(___)", "填 -7。", "print(-7)"),
    (16, "观察乘法的优先级。", "print(1 + ___ * 3)", "填 2。", "print(1 + 2 * 3)"),
    (17, "用括号改变运算顺序。", "print((___ + 2) * 3)", "填 1。", "print((1 + 2) * 3)"),
    (18, "用 * 重复字符串。", "print(___ * 3)", "填 \"ab\"。", "print(\"ab\" * 3)"),
    (19, "用 + 拼接字符串。", "print(\"a\" + ___)", "填 \"b\"。", "print(\"a\" + \"b\")"),
    (20, "浮点数相乘。", "print(2.5 * ___)", "填 2。", "print(2.5 * 2)"),
    (21, "整数与浮点数相加。", "print(10 + ___)", "填 5.5。", "print(10 + 5.5)"),
    (22, "计算 10 除以 4 的余数。", "print(10 % ___)", "填 4。", "print(10 % 4)"),
    (23, "计算 17 整除 5。", "print(17 // ___)", "填 5。", "print(17 // 5)"),
    (24, "输出链式比较的结果。", "print(\"chain:\", ___ < 2 < 3)", "填 1。", "print(\"chain:\", 1 < 2 < 3)"),
    (25, "计算 2 的负一次方。", "print(2 ** ___)", "填 -1。", "print(2 ** -1)"),
    (26, "用 not 和 and 组合判断。", "print(\"result:\", not (___ and False))", "填 True。", "print(\"result:\", not (True and False))"),
    (27, "变量相乘后输出。", "x = 4\ny = 3\nprint(___ * y)", "填 x。", "x = 4\ny = 3\nprint(x * y)"),
    (28, "输出比较结果和差值。", "a = 3\nb = 4\nprint(a < b, ___ - a)", "填 b。", "a = 3\nb = 4\nprint(a < b, b - a)"),
    (29, "计算 5*5-5 的结果。", "print(5 * 5 - ___)", "填 5。", "print(5 * 5 - 5)"),
    (30, "计算 100 整除 7。", "print(100 // ___)", "填 7。", "print(100 // 7)"),
]

SIMPLE = [
    (1, "用复合赋值链更新变量。", "x = 5\nx += 4\nx *= 2\nprint(x)", "填空复合赋值。", "x = 5\nx += 4\nx *= 2\nprint(x)"),
    (2, "同时输出整除商和余数。", "print(20 // 3, 20 % 3)", "填空 // 与 %。", "print(20 // 3, 20 % 3)"),
    (3, "输出三个值的布尔转换。", "print(bool(0), bool(1), bool(-1))", "填空 bool()。", "print(bool(0), bool(1), bool(-1))"),
    (4, "用取余判断奇偶余数。", "print(15 % 2, 16 % 2)", "填空两处取余。", "print(15 % 2, 16 % 2)"),
    (5, "判断数字是否在区间内。", "x = 7\nprint(\"in range:\", 3 < x <= 10)", "填空链式比较。", "x = 7\nprint(\"in range:\", 3 < x <= 10)"),
    (6, "对比括号前后的运算结果。", "print(2 + 3 * 4, (2 + 3) * 4)", "填空两个表达式。", "print(2 + 3 * 4, (2 + 3) * 4)"),
    (7, "用 //= 复合赋值。", "a = 17\na //= 3\nprint(a)", "填空 //=。", "a = 17\na //= 3\nprint(a)"),
    (8, "用取余判断输出奇数提示。", "n = 9\nprint(\"odd\" if n % 2 else \"even\")", "填空条件表达式。", "n = 9\nprint(\"odd\" if n % 2 else \"even\")"),
    (9, "同时输出幂和开方结果。", "print(3 ** 2, 9 ** 0.5)", "填空两处运算。", "print(3 ** 2, 9 ** 0.5)"),
    (10, "比较年龄是否成年。", "age = 17\nprint(age >= 18, age == 18)", "填空两个比较。", "age = 17\nprint(age >= 18, age == 18)"),
    (11, "用 and/or 组合判断并输出。", "a = 5\nb = 3\nprint(\"both:\", a > b and b > 0, \"either:\", a < b or a > 0)", "填空逻辑组合。", "a = 5\nb = 3\nprint(\"both:\", a > b and b > 0, \"either:\", a < b or a > 0)"),
    (12, "字符串乘法与加法组合。", "print(\"ab\" * 2 + \"cd\")", "填空组合运算。", "print(\"ab\" * 2 + \"cd\")"),
    (13, "用 round 处理浮点误差。", "print(round(0.1 + 0.2, 2))", "填空 round。", "print(round(0.1 + 0.2, 2))"),
    (14, "用 += 依次累加。", "count = 0\ncount += 1\ncount += 2\ncount += 3\ncount += 4\nprint(count)", "填空累加链。", "count = 0\ncount += 1\ncount += 2\ncount += 3\ncount += 4\nprint(count)"),
    (15, "把布尔结果转成数字。", "print(\"bool to int:\", int(True), int(False))", "填空 int()。", "print(\"bool to int:\", int(True), int(False))"),
    (16, "用取模模拟时钟。", "print(23 % 12)", "填空取模。", "print(23 % 12)"),
    (17, "用 divmod 同时得商和余。", "print(divmod(17, 5))", "填空 divmod。", "print(divmod(17, 5))"),
    (18, "负号与减法组合。", "print(-5 - 3)", "填空表达式。", "print(-5 - 3)"),
    (19, "观察逻辑运算符优先级。", "print(\"precedence:\", True or False and False)", "填空 or/and。", "print(\"precedence:\", True or False and False)"),
    (20, "一个变量参与多个比较。", "a = 10\nprint(a > 5, a == 10, a < 5)", "填空三个比较。", "a = 10\nprint(a > 5, a == 10, a < 5)"),
    (21, "输出运算结果的类型。", "print(type(3 + 4), type(3 / 4))", "填空两个 type。", "print(type(3 + 4), type(3 / 4))"),
    (22, "比较两个字符串的大小。", "print(\"compare:\", \"apple\" < \"banana\")", "填空字符串比较。", "print(\"compare:\", \"apple\" < \"banana\")"),
    (23, "把比较结果赋给变量。", "x = 5 == 5\nprint(\"x =\", x)", "填空比较赋值。", "x = 5 == 5\nprint(\"x =\", x)"),
    (24, "计算 5 的三次方。", "print(5 ** 3)", "填空幂运算。", "print(5 ** 3)"),
    (25, "负数整除的向下取整。", "print(-7 // 2)", "填空整除。", "print(-7 // 2)"),
    (26, "负数取余的结果。", "print(7 % -3)", "填空取余。", "print(7 % -3)"),
    (27, "多种运算符混合运算。", "print(10 + 4 * 3 // 2)", "填空混合表达式。", "print(10 + 4 * 3 // 2)"),
    (28, "浮点数取余。", "print(7.5 % 2)", "填空浮点取余。", "print(7.5 % 2)"),
    (29, "比较不同类型是否相等。", "print(\"equal:\", 3 == 3.0)", "填空 ==。", "print(\"equal:\", 3 == 3.0)"),
    (30, "输出求和结果。", "print(\"sum:\", 3 + 4)", "填空求和。", "print(\"sum:\", 3 + 4)"),
]

MEDIUM = [
    (1, "输出两个数七种运算的结果。",
     "a = 15\nb = 4\nprint(a + b, a - b, a * b, a / b, a // b, a % b, a ** 2)",
     "填空七种运算符。",
     "a = 15\nb = 4\nprint(a + b, a - b, a * b, a / b, a // b, a % b, a ** 2)"),
    (2, "统计 1 到 10 的奇偶个数。",
     "odd = even = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        even += 1\n    else:\n        odd += 1\nprint(\"Odd:\", odd, \"Even:\", even)",
     "填空取余判断。",
     "odd = even = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        even += 1\n    else:\n        odd += 1\nprint(\"Odd:\", odd, \"Even:\", even)"),
    (3, "判断 17 是否为素数。",
     "n = 17\nis_prime = True\nfor d in range(2, n):\n    if n % d == 0:\n        is_prime = False\n        break\nprint(n, \"is prime:\", is_prime)",
     "填空取余判断。",
     "n = 17\nis_prime = True\nfor d in range(2, n):\n    if n % d == 0:\n        is_prime = False\n        break\nprint(n, \"is prime:\", is_prime)"),
    (4, "输出 1 到 50 中同时被 3 和 5 整除的数。",
     "for i in range(1, 51):\n    if i % 3 == 0 and i % 5 == 0:\n        print(i, end=\" \")",
     "填空 and 条件。",
     "for i in range(1, 51):\n    if i % 3 == 0 and i % 5 == 0:\n        print(i, end=\" \")"),
    (5, "用算术运算反转三位数。",
     "n = 123\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev)",
     "填空取余与整除。",
     "n = 123\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev)"),
    (6, "判断 121 是否为回文数。",
     "n = 121\nrev = 0\ntemp = n\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nprint(n, \"palindrome:\", n == rev)",
     "填空反转比较。",
     "n = 121\nrev = 0\ntemp = n\nwhile temp > 0:\n    rev = rev * 10 + temp % 10\n    temp //= 10\nprint(n, \"palindrome:\", n == rev)"),
    (7, "统计数字的位数与各位和。",
     "n = 12345\ncount = 0\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    count += 1\n    n //= 10\nprint(\"Digits:\", count, \"Sum:\", total)",
     "填空取位累加。",
     "n = 12345\ncount = 0\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    count += 1\n    n //= 10\nprint(\"Digits:\", count, \"Sum:\", total)"),
    (8, "输出 2 的 1 到 6 次幂。",
     "for i in range(1, 7):\n    print(f\"2^{i} = {2 ** i}\")",
     "填空幂运算。",
     "for i in range(1, 7):\n    print(f\"2^{i} = {2 ** i}\")"),
    (9, "计算 6 的阶乘。",
     "n = 6\nfact = 1\nfor i in range(2, n + 1):\n    fact *= i\nprint(f\"{n}! = {fact}\")",
     "填空累乘。",
     "n = 6\nfact = 1\nfor i in range(2, n + 1):\n    fact *= i\nprint(f\"{n}! = {fact}\")"),
    (10, "求 12 和 18 的最大公约数。",
     "a, b = 12, 18\nwhile b:\n    a, b = b, a % b\nprint(\"gcd =\", a)",
     "填空辗转相除。",
     "a, b = 12, 18\nwhile b:\n    a, b = b, a % b\nprint(\"gcd =\", a)"),
    (11, "求 4 和 6 的最小公倍数。",
     "a, b = 4, 6\nm, n = a, b\nwhile n:\n    m, n = n, m % n\nprint(\"lcm =\", a * b // m)",
     "填空 gcd 后求 lcm。",
     "a, b = 4, 6\nm, n = a, b\nwhile n:\n    m, n = n, m % n\nprint(\"lcm =\", a * b // m)"),
    (12, "输出摄氏到华氏的温度表。",
     "print(\"C   F\")\nc = 0\nwhile c <= 100:\n    f = c * 9 / 5 + 32\n    print(f\"{c:3d} {f:6.1f}\")\n    c += 20",
     "填空转换公式。",
     "print(\"C   F\")\nc = 0\nwhile c <= 100:\n    f = c * 9 / 5 + 32\n    print(f\"{c:3d} {f:6.1f}\")\n    c += 20"),
    (13, "用百分制分数输出等级。",
     "score = 85\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelse:\n    grade = \"D\"\nprint(f\"Grade: {grade}\")",
     "填空条件判断。",
     "score = 85\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelif score >= 70:\n    grade = \"C\"\nelse:\n    grade = \"D\"\nprint(f\"Grade: {grade}\")"),
    (14, "猜数字并给出提示。",
     "answer = 7\nguess = 5\nif guess == answer:\n    print(\"Correct!\")\nelif guess > answer:\n    print(\"Too high\")\nelse:\n    print(\"Too low\")",
     "填空比较判断。",
     "answer = 7\nguess = 5\nif guess == answer:\n    print(\"Correct!\")\nelif guess > answer:\n    print(\"Too high\")\nelse:\n    print(\"Too low\")"),
    (15, "用 100 元找零计算最少张数。",
     "price = 37\nchange = 100 - price\nprint(\"Change:\", change)\nfor denom in [50, 20, 10, 5, 1]:\n    count = change // denom\n    change %= denom\n    if count:\n        print(denom, \"x\", count)",
     "填空整除与取余。",
     "price = 37\nchange = 100 - price\nprint(\"Change:\", change)\nfor denom in [50, 20, 10, 5, 1]:\n    count = change // denom\n    change %= denom\n    if count:\n        print(denom, \"x\", count)"),
    (16, "判断 2024 是否为闰年。",
     "year = 2024\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print(year, \"leap\")\nelse:\n    print(year, \"common\")",
     "填空闰年条件。",
     "year = 2024\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print(year, \"leap\")\nelse:\n    print(year, \"common\")"),
    (17, "输出 100 以内的完数。",
     "for n in range(2, 101):\n    total = 0\n    for d in range(1, n):\n        if n % d == 0:\n            total += d\n    if total == n:\n        print(n)",
     "填空约数累加。",
     "for n in range(2, 101):\n    total = 0\n    for d in range(1, n):\n        if n % d == 0:\n            total += d\n    if total == n:\n        print(n)"),
    (18, "输出所有三位水仙花数。",
     "for n in range(100, 1000):\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)",
     "填空位分解与立方和。",
     "for n in range(100, 1000):\n    a = n // 100\n    b = (n // 10) % 10\n    c = n % 10\n    if a ** 3 + b ** 3 + c ** 3 == n:\n        print(n)"),
    (19, "输出逻辑运算真值表。",
     "for a in [True, False]:\n    for b in [True, False]:\n        print(a, b, \"and:\", a and b, \"or:\", a or b)",
     "填空双层循环。",
     "for a in [True, False]:\n    for b in [True, False]:\n        print(a, b, \"and:\", a and b, \"or:\", a or b)"),
    (20, "验证运算符优先级的三行输出。",
     "print(2 + 3 * 4)\nprint((2 + 3) * 4)\nprint(2 * 3 ** 2)",
     "填空三个表达式。",
     "print(2 + 3 * 4)\nprint((2 + 3) * 4)\nprint(2 * 3 ** 2)"),
    (21, "输出斐波那契数列前 8 项。",
     "a, b = 0, 1\nfor _ in range(8):\n    print(a, end=\" \")\n    a, b = b, a + b",
     "填空递推加法。",
     "a, b = 0, 1\nfor _ in range(8):\n    print(a, end=\" \")\n    a, b = b, a + b"),
    (22, "统计数字中 7 出现的次数。",
     "n = 7771237\ncount = 0\nwhile n > 0:\n    if n % 10 == 7:\n        count += 1\n    n //= 10\nprint(\"Sevens:\", count)",
     "填空取位判断。",
     "n = 7771237\ncount = 0\nwhile n > 0:\n    if n % 10 == 7:\n        count += 1\n    n //= 10\nprint(\"Sevens:\", count)"),
    (23, "逐步输出复合赋值过程。",
     "x = 2\nprint(x)\nx += 3\nprint(x)\nx *= 4\nprint(x)\nx -= 5\nprint(x)",
     "填空复合赋值链。",
     "x = 2\nprint(x)\nx += 3\nprint(x)\nx *= 4\nprint(x)\nx -= 5\nprint(x)"),
    (24, "统计比较结果为真的个数。",
     "nums = [1, 2, 3, 4, 5]\ncount = 0\nfor n in nums:\n    if n > 3:\n        count += 1\nprint(\"Greater than 3:\", count)",
     "填空比较计数。",
     "nums = [1, 2, 3, 4, 5]\ncount = 0\nfor n in nums:\n    if n > 3:\n        count += 1\nprint(\"Greater than 3:\", count)"),
    (25, "用条件表达式求两数较大者。",
     "a, b = 7, 9\nlarger = a if a > b else b\nprint(\"Larger:\", larger)",
     "填空三元表达式。",
     "a, b = 7, 9\nlarger = a if a > b else b\nprint(\"Larger:\", larger)"),
    (26, "用位运算输出与、或、异或。",
     "a, b = 6, 3\nprint(a & b, a | b, a ^ b)",
     "填空三种位运算。",
     "a, b = 6, 3\nprint(a & b, a | b, a ^ b)"),
    (27, "用成员运算符判断元素存在。",
     "nums = [1, 2, 3]\nprint(\"2 in:\", 2 in nums, \"5 in:\", 5 in nums)",
     "填空 in 判断。",
     "nums = [1, 2, 3]\nprint(\"2 in:\", 2 in nums, \"5 in:\", 5 in nums)"),
    (28, "计算平均分并四舍五入。",
     "scores = [88, 92, 76]\navg = sum(scores) / len(scores)\nprint(\"Avg:\", round(avg, 1))",
     "填空平均与 round。",
     "scores = [88, 92, 76]\navg = sum(scores) / len(scores)\nprint(\"Avg:\", round(avg, 1))"),
    (29, "判断完全平方数。",
     "n = 81\nroot = int(n ** 0.5)\nprint(n, \"perfect square:\", root * root == n)",
     "填空开方判断。",
     "n = 81\nroot = int(n ** 0.5)\nprint(n, \"perfect square:\", root * root == n)"),
    (30, "综合：统计 1 到 100 中被 7 整除的个数。",
     "count = 0\nfor i in range(1, 101):\n    if i % 7 == 0:\n        count += 1\nprint(\"Multiples of 7:\", count)",
     "填空取余计数。",
     "count = 0\nfor i in range(1, 101):\n    if i % 7 == 0:\n        count += 1\nprint(\"Multiples of 7:\", count)"),
]

HARD = [
    (1, "用迭代实现快速幂。",
     "def fast_pow(base, exp):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n        base *= base\n        exp //= 2\n    return result\n\nprint(fast_pow(2, 10), fast_pow(3, 5))",
     "填空分治幂运算。",
     "def fast_pow(base, exp):\n    result = 1\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n        base *= base\n        exp //= 2\n    return result\n\nprint(fast_pow(2, 10), fast_pow(3, 5))"),
    (2, "统计二进制中 1 的个数。",
     "def popcount(n):\n    count = 0\n    while n:\n        count += n & 1\n        n >>= 1\n    return count\n\nfor n in [0, 5, 7, 15]:\n    print(n, \"->\", popcount(n))",
     "填空位运算。",
     "def popcount(n):\n    count = 0\n    while n:\n        count += n & 1\n        n >>= 1\n    return count\n\nfor n in [0, 5, 7, 15]:\n    print(n, \"->\", popcount(n))"),
    (3, "用位运算实现两数相加。",
     "def add(a, b):\n    while b:\n        carry = a & b\n        a = a ^ b\n        b = carry << 1\n    return a\n\nfor x, y in [(3, 5), (7, 9), (10, 20)]:\n    print(f\"{x} + {y} = {add(x, y)}\")",
     "填空位运算加法。",
     "def add(a, b):\n    while b:\n        carry = a & b\n        a = a ^ b\n        b = carry << 1\n    return a\n\nfor x, y in [(3, 5), (7, 9), (10, 20)]:\n    print(f\"{x} + {y} = {add(x, y)}\")"),
    (4, "计算两个数的汉明距离。",
     "def popcount(n):\n    c = 0\n    while n:\n        c += n & 1\n        n >>= 1\n    return c\n\ndef hamming(a, b):\n    return popcount(a ^ b)\n\nprint(hamming(1, 4), hamming(3, 1))",
     "填空异或与计数。",
     "def popcount(n):\n    c = 0\n    while n:\n        c += n & 1\n        n >>= 1\n    return c\n\ndef hamming(a, b):\n    return popcount(a ^ b)\n\nprint(hamming(1, 4), hamming(3, 1))"),
    (5, "对 84 做质因数分解。",
     "n = 84\nfactors = []\nd = 2\nwhile d * d <= n:\n    while n % d == 0:\n        factors.append(d)\n        n //= d\n    d += 1\nif n > 1:\n    factors.append(n)\nprint(factors)",
     "填空试除分解。",
     "n = 84\nfactors = []\nd = 2\nwhile d * d <= n:\n    while n % d == 0:\n        factors.append(d)\n        n //= d\n    d += 1\nif n > 1:\n    factors.append(n)\nprint(factors)"),
    (6, "用埃氏筛输出 30 以内素数。",
     "limit = 30\nis_prime = [True] * (limit + 1)\nis_prime[0] = is_prime[1] = False\nfor i in range(2, int(limit ** 0.5) + 1):\n    if is_prime[i]:\n        for j in range(i * i, limit + 1, i):\n            is_prime[j] = False\nprimes = [n for n in range(2, limit + 1) if is_prime[n]]\nprint(primes)",
     "填空筛法标记。",
     "limit = 30\nis_prime = [True] * (limit + 1)\nis_prime[0] = is_prime[1] = False\nfor i in range(2, int(limit ** 0.5) + 1):\n    if is_prime[i]:\n        for j in range(i * i, limit + 1, i):\n            is_prime[j] = False\nprimes = [n for n in range(2, limit + 1) if is_prime[n]]\nprint(primes)"),
    (7, "用列表实现高精度加法。",
     "def big_add(a, b):\n    a, b = list(str(a)), list(str(b))\n    carry = 0\n    result = []\n    while a or b or carry:\n        x = int(a.pop()) if a else 0\n        y = int(b.pop()) if b else 0\n        total = x + y + carry\n        result.append(total % 10)\n        carry = total // 10\n    return int(\"\".join(map(str, reversed(result))))\n\nprint(big_add(999, 1))\nprint(big_add(123456789, 987654321))",
     "填空逐位加法。",
     "def big_add(a, b):\n    a, b = list(str(a)), list(str(b))\n    carry = 0\n    result = []\n    while a or b or carry:\n        x = int(a.pop()) if a else 0\n        y = int(b.pop()) if b else 0\n        total = x + y + carry\n        result.append(total % 10)\n        carry = total // 10\n    return int(\"\".join(map(str, reversed(result))))\n\nprint(big_add(999, 1))\nprint(big_add(123456789, 987654321))"),
    (8, "用位运算把二进制转十进制。",
     "def bin_to_dec(b):\n    dec = 0\n    for ch in b:\n        dec = (dec << 1) + int(ch)\n    return dec\n\nfor b in [\"101\", \"1101\", \"10000\"]:\n    print(b, \"->\", bin_to_dec(b))",
     "填空移位累加。",
     "def bin_to_dec(b):\n    dec = 0\n    for ch in b:\n        dec = (dec << 1) + int(ch)\n    return dec\n\nfor b in [\"101\", \"1101\", \"10000\"]:\n    print(b, \"->\", bin_to_dec(b))"),
    (9, "求 7 的 100 次方的末位数字。",
     "base = 7\nexp = 100\nresult = 1\nfor _ in range(exp):\n    result = (result * base) % 10\nprint(\"Last digit:\", result)",
     "填空取模循环。",
     "base = 7\nexp = 100\nresult = 1\nfor _ in range(exp):\n    result = (result * base) % 10\nprint(\"Last digit:\", result)"),
    (10, "用牛顿法求 16 的平方根近似。",
     "n = 16\nx = n / 2\nfor _ in range(5):\n    x = (x + n / x) / 2\nprint(round(x, 4))",
     "填空牛顿迭代。",
     "n = 16\nx = n / 2\nfor _ in range(5):\n    x = (x + n / x) / 2\nprint(round(x, 4))"),
    (11, "递归实现最大公约数。",
     "def gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a % b)\n\nprint(gcd(48, 36), gcd(17, 5))",
     "填空递归取余。",
     "def gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a % b)\n\nprint(gcd(48, 36), gcd(17, 5))"),
    (12, "验证取模运算性质。",
     "a, b, m = 17, 23, 5\nprint((a * b) % m)\nprint(((a % m) * (b % m)) % m)",
     "填空取模性质验证。",
     "a, b, m = 17, 23, 5\nprint((a * b) % m)\nprint(((a % m) * (b % m)) % m)"),
    (13, "演示浮点数累加误差。",
     "total = 0.0\nfor _ in range(10):\n    total += 0.1\nprint(repr(total))\nprint(round(total, 2))",
     "填空累加与舍入。",
     "total = 0.0\nfor _ in range(10):\n    total += 0.1\nprint(repr(total))\nprint(round(total, 2))"),
    (14, "用位掩码表示集合并运算。",
     "a = 0b10110\nb = 0b01101\nprint(\"and:\", bin(a & b))\nprint(\"or:\", bin(a | b))\nprint(\"xor:\", bin(a ^ b))",
     "填空集合位运算。",
     "a = 0b10110\nb = 0b01101\nprint(\"and:\", bin(a & b))\nprint(\"or:\", bin(a | b))\nprint(\"xor:\", bin(a ^ b))"),
    (15, "用异或交换两个变量。",
     "a, b = 5, 9\nprint(a, b)\na = a ^ b\nb = a ^ b\na = a ^ b\nprint(a, b)",
     "填空三步异或交换。",
     "a, b = 5, 9\nprint(a, b)\na = a ^ b\nb = a ^ b\na = a ^ b\nprint(a, b)"),
    (16, "输出 1000 以内的自守数。",
     "for n in range(1, 1001):\n    square = n * n\n    if str(square).endswith(str(n)):\n        print(n, end=\" \")",
     "填空平方尾数判断。",
     "for n in range(1, 1001):\n    square = n * n\n    if str(square).endswith(str(n)):\n        print(n, end=\" \")"),
    (17, "判断 45 是否为卡普雷卡数。",
     "def is_kaprekar(n):\n    square = n * n\n    s = str(square)\n    for i in range(1, len(s)):\n        left = int(s[:i])\n        right = int(s[i:])\n        if left + right == n:\n            return True\n    return False\n\nfor n in [9, 45, 55, 99]:\n    print(n, is_kaprekar(n))",
     "填空拆分判断。",
     "def is_kaprekar(n):\n    square = n * n\n    s = str(square)\n    for i in range(1, len(s)):\n        left = int(s[:i])\n        right = int(s[i:])\n        if left + right == n:\n            return True\n    return False\n\nfor n in [9, 45, 55, 99]:\n    print(n, is_kaprekar(n))"),
    (18, "判断 19 是否为快乐数。",
     "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nfor n in [19, 4]:\n    print(n, \"happy:\", is_happy(n))",
     "填空平方和迭代。",
     "def is_happy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d) ** 2 for d in str(n))\n    return n == 1\n\nfor n in [19, 4]:\n    print(n, \"happy:\", is_happy(n))"),
    (19, "模拟猜数字游戏并统计次数。",
     "secret = 7\nguesses = [3, 5, 7]\nfor g in guesses:\n    if g == secret:\n        print(g, \"correct!\")\n        break\n    elif g < secret:\n        print(g, \"too low\")\n    else:\n        print(g, \"too high\")",
     "填空比较与分支。",
     "secret = 7\nguesses = [3, 5, 7]\nfor g in guesses:\n    if g == secret:\n        print(g, \"correct!\")\n        break\n    elif g < secret:\n        print(g, \"too low\")\n    else:\n        print(g, \"too high\")"),
    (20, "用 while 实现简易四则计算器。",
     "ops = [(\"+\", 6, 3), (\"-\", 6, 3), (\"*\", 6, 3), (\"/\", 6, 3)]\nfor op, a, b in ops:\n    if op == \"+\":\n        print(a + b)\n    elif op == \"-\":\n        print(a - b)\n    elif op == \"*\":\n        print(a * b)\n    else:\n        print(a / b)",
     "填空四则分发。",
     "ops = [(\"+\", 6, 3), (\"-\", 6, 3), (\"*\", 6, 3), (\"/\", 6, 3)]\nfor op, a, b in ops:\n    if op == \"+\":\n        print(a + b)\n    elif op == \"-\":\n        print(a - b)\n    elif op == \"*\":\n        print(a * b)\n    else:\n        print(a / b)"),
    (21, "把十进制转成任意进制。",
     "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    if n == 0:\n        return \"0\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\n\nprint(to_base(255, 16), to_base(100, 2), to_base(100, 8))",
     "填空取余拼接。",
     "def to_base(n, base):\n    digits = \"0123456789ABCDEF\"\n    if n == 0:\n        return \"0\"\n    result = \"\"\n    while n > 0:\n        result = digits[n % base] + result\n        n //= base\n    return result\n\nprint(to_base(255, 16), to_base(100, 2), to_base(100, 8))"),
    (22, "用列表逐位计算大数阶乘。",
     "def big_fact(n):\n    digits = [1]\n    for i in range(2, n + 1):\n        carry = 0\n        for j in range(len(digits)):\n            prod = digits[j] * i + carry\n            digits[j] = prod % 10\n            carry = prod // 10\n        while carry:\n            digits.append(carry % 10)\n            carry //= 10\n    return \"\".join(map(str, reversed(digits)))\n\nprint(big_fact(5))\nprint(big_fact(20))",
     "填空逐位乘法。",
     "def big_fact(n):\n    digits = [1]\n    for i in range(2, n + 1):\n        carry = 0\n        for j in range(len(digits)):\n            prod = digits[j] * i + carry\n            digits[j] = prod % 10\n            carry = prod // 10\n        while carry:\n            digits.append(carry % 10)\n            carry //= 10\n    return \"\".join(map(str, reversed(digits)))\n\nprint(big_fact(5))\nprint(big_fact(20))"),
    (23, "计算 2x2 矩阵乘法。",
     "a = [[1, 2], [3, 4]]\nb = [[5, 6], [7, 8]]\nresult = [[0, 0], [0, 0]]\nfor i in range(2):\n    for j in range(2):\n        for k in range(2):\n            result[i][j] += a[i][k] * b[k][j]\nfor row in result:\n    print(row)",
     "填空三重循环乘法。",
     "a = [[1, 2], [3, 4]]\nb = [[5, 6], [7, 8]]\nresult = [[0, 0], [0, 0]]\nfor i in range(2):\n    for j in range(2):\n        for k in range(2):\n            result[i][j] += a[i][k] * b[k][j]\nfor row in result:\n    print(row)"),
    (24, "输出 100 以内的孪生素数对。",
     "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nfor n in range(2, 98):\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)",
     "填空素数判断与相邻检查。",
     "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nfor n in range(2, 98):\n    if is_prime(n) and is_prime(n + 2):\n        print(n, n + 2)"),
    (25, "验证哥德巴赫猜想（100 内偶数）。",
     "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nfor even in range(4, 21, 2):\n    for p in range(2, even):\n        if is_prime(p) and is_prime(even - p):\n            print(even, \"=\", p, \"+\", even - p)\n            break",
     "填空素数拆分。",
     "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nfor even in range(4, 21, 2):\n    for p in range(2, even):\n        if is_prime(p) and is_prime(even - p):\n            print(even, \"=\", p, \"+\", even - p)\n            break"),
    (26, "用运算验证三个数的最大值。",
     "a, b, c = 3, 9, 5\nmaximum = a\nif b > maximum:\n    maximum = b\nif c > maximum:\n    maximum = c\nprint(\"Max:\", maximum)",
     "填空比较更新。",
     "a, b, c = 3, 9, 5\nmaximum = a\nif b > maximum:\n    maximum = b\nif c > maximum:\n    maximum = c\nprint(\"Max:\", maximum)"),
    (27, "计算表达式的综合结果。",
     "x = 5\ny = 2\nprint(x ** 2 + y * 3)\nprint((x + y) ** 2 // 3)\nprint(x * (y + 3) % 4)",
     "填空三个综合表达式。",
     "x = 5\ny = 2\nprint(x ** 2 + y * 3)\nprint((x + y) ** 2 // 3)\nprint(x * (y + 3) % 4)"),
    (28, "用运算符判断平年闰年个数。",
     "leap = 0\nfor year in range(2000, 2051):\n    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n        leap += 1\nprint(\"Leap years:\", leap)",
     "填空闰年统计。",
     "leap = 0\nfor year in range(2000, 2051):\n    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n        leap += 1\nprint(\"Leap years:\", leap)"),
    (29, "求三个数的最小公倍数。",
     "a, b, c = 3, 4, 6\nm = max(a, b, c)\nwhile True:\n    if m % a == 0 and m % b == 0 and m % c == 0:\n        break\n    m += 1\nprint(\"LCM:\", m)",
     "填空逐增判断。",
     "a, b, c = 3, 4, 6\nm = max(a, b, c)\nwhile True:\n    if m % a == 0 and m % b == 0 and m % c == 0:\n        break\n    m += 1\nprint(\"LCM:\", m)"),
    (30, "输出 1 到 50 的数字分类统计。",
     "perfect = abundant = 0\nfor n in range(2, 51):\n    total = sum(d for d in range(1, n) if n % d == 0)\n    if total == n:\n        perfect += 1\n    elif total > n:\n        abundant += 1\nprint(\"Perfect:\", perfect, \"Abundant:\", abundant)",
     "填空约数分类。",
     "perfect = abundant = 0\nfor n in range(2, 51):\n    total = sum(d for d in range(1, n) if n % d == 0)\n    if total == n:\n        perfect += 1\n    elif total > n:\n        abundant += 1\nprint(\"Perfect:\", perfect, \"Abundant:\", abundant)"),
]

BATCHES = {
    "easy_30.json": ("E", EASY),
    "medium_30.json": ("M", SIMPLE),
    "hard_30.json": ("H", MEDIUM),
    "expert_30.json": ("X", HARD),
}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_chapter(root, CHAPTER, TITLE, OUT_DIR, DIFF, TOPIC, BATCHES)


if __name__ == "__main__":
    main()
